### ISSUE TITLE
Inferring typeclass constraints in multi-parameter typeclasses

### ISSUE THREAD

**Issue by mkaemmerer** [purescript/purescript#1004]
I've noticed a number of cases where typeclass constraints *could* be inferred from "superclasses", but which don't compile without writing the extra constraints:
- https://github.com/mkaemmerer/purescript-vector-space/blob/affine-space/src/Data/VectorSpace.purs#L48
- https://github.com/mkaemmerer/purescript-vector-space/blob/affine-space/src/Data/VectorSpace.purs#L82

I have also encountered a case which fails to compile even after explicitly writing the redundant constraints.
- https://github.com/mkaemmerer/purescript-vector-space/blob/affine-space/src/Data/AffineSpace.purs#L28

Apologies if this is a duplicate issue (I looked but didn't find it), or if I'm just completely abusing multi parameter typeclasses.

**Comment by paf31** [comment]
Yes, we don't infer constraints right now, and the last issue is related to the lack of functional dependencies. Right now, we don't have enough information to infer certain type equalities.

I'll mark this as a duplicate, since there are various bug reports which report this in various forms that aren't obviously connected. The solution will be to implement something like fundeps.
