### ISSUE TITLE
IDE support for info

### ISSUE THREAD

**Issue by rikvdkleij** [purescript/purescript#1053]
Add `info` command to psci. Similar like `info` in `ghc-mod`.

`info <file> <identifier>`

This command would make it easier to get nice IDE support for Purescript. 

Most important information would be definition and module where identifier is defined. Nice to have is for example list of instances in case identifier is type class.

**Comment by hdgarrood** [comment]
Is this related to #529? Can you post example output?

If this is for IDE support, I'm not sure that `psci` is the right place to put it. Maybe a separate command line tool would be better.

**Comment by rikvdkleij** [comment]
@hdgarrood hdgarrood
> Is this related to #529? Can you post example output?

Yeah, it's the same. I did not see that issue.

> If this is for IDE support, I'm not sure that psci is the right place to put it. Maybe a separate command line tool would be better.

Well, `info` in both would be great.  You are right, for IDE support a separate tool (like ghc-modi) would be even nicer because output would be easier to parse (also for checking code, getting type information, browse module etc.).

**Comment by rikvdkleij** [comment]
@hdgarrood 
IDE support is also related to https://github.com/purescript/purescript/issues/555

So maybe create separate issue for IDE support which includes all commands?

**Comment by hdgarrood** [comment]
Thanks for clarifying :) I'm not sure it's worth making a separate issue, maybe just retitle this one?

**Comment by rikvdkleij** [comment]
Retitle to "IDE support for `info`"?

**Comment by paf31** [comment]
Does `psc-ide` provide this functionality?

**Comment by kRITZCREEK** [comment]
Not yet :( But we could move this issue to the psc-ide repo and track it from here.

**Comment by hdgarrood** [comment]
Just for the sake of clarity: is it correct that what we're aiming for here is a way of asking "tell me everything you know about this identifier (which might refer to a value, type, or type class)"?

We all seem to agree that this would be useful both inside `psci` and for IDE support. Presumably, then, we want to start off by implementing the version for `psci`, since this would need to be inside the compiler? (In this case, the original title for this issue would perhaps be more appropriate?)

**Comment by paf31** [comment]
#1136
