### ISSUE TITLE
Parser error in the expression "(== foo.x)": unexpected .

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript#1090]
Suppose I have a simple record type `Foo` and an instance `foo`:
```purescript
type Foo = { x :: Number }

foo :: Foo
foo = { x: 42 }
```
Then, the following expression does not compile:
```
(== foo.x) 42
```
psc is failing with: `unexpected .; expecting )`. A workaround for now is to add parenthesis. Both of the following expressions compile:
```purescript
((==) foo.x) 42
(== (foo.x)) 42
```

**Comment by paf31** [comment]
This isn't limited to accessors. The type in an operator section is parsed using `parseValueAtom`. We have a couple of options:

- Defer this parse until during operator desugaring and allow any expression
- Allow accessors only, which happen to be a special case in the parser anyway
- Document this as expected behavior.

**Comment by garyb** [comment]
Option 1 sounds good if it's not too troublesome - being able to do things like `(== f x)` would be quite nice. Option 2 sounds like a good compromise. Option 3 is ok too, but the accessor case does seem like a reasonable exception to make at a minimum as it "looks" like an atom at least.
