### ISSUE TITLE
Question: remove effect types with no type content

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1124]
I brought this up a while ago, but I don't remember the outcome, and now seems to be a good time to bring it up again.

Most of our effect types are the equivalent of `Unit` at the effect kind, in that they don't carry any type content (`ST` and `History` seem to be the two exceptions). Effect types in different libraries don't unify with each other (think of `DOM` for example).

It doesn't have to be this way. If we used polymorphic effects instead, then the presence of the label itself would represent the use of an effect:

```purescript
trace :: forall console eff. String -> Eff (console :: console | eff) Unit
```

This can be read as "`trace` uses the console, but in no way that the type system should care about, and can be used in the context of other effects".

**Comment by paf31** [comment]
The downside is that we can create any label we like. Alternatively, labels should not convey special behavior, types should.

**Comment by starper** [comment]
Maybe it's because of lack of experience (I've been an OOP guy for a long time and started to learn FP only two months ago), but I don't see how it will help. The problem, as I see it, is tight coupling between my own code and a library. Library's internal types and effects leak into domain specific code and there is no way to hide this library behind some kind of abstraction (I understand that trying to hide everything is OOP way of thinking, but I don't know any other way to fight dependencies).

For example let's imagine some MyDOM library with MyDOM effect, MyNode type and some functions:

    ...
    foreign import data MyDOM :: !
    foreign import data MyNode :: *
    
    type NodeType = String
    type AttrName = String
    type Selector = String
    
    createNode :: NodeType -> Node
    setAttribute :: AttrName -> Node -> Node
    appendNode :: forall e. Selector -> Node -> Eff (mydom :: MyDOM | e) Unit
    ...

Then we could have Components and Controller modules. Components adapts this library to an API that our Controller expects to see:

    ...
    fooComponent :: SomeData -> Node -- this one and next two functions build components using MyDOM functions
    barComponent :: SomeData -> Node
    bazComponent :: SomeData -> Node
    addToBody :: forall e. Node -> Eff (mydom :: MyDOM | e) Unit -- adds node to body using appendNode
    ...

And Controller looks something like this:

    ...
    firstView :: SomeData -> Node -- uses some combination of components to build first view
    secondView :: SomeData -> Node -- uses some combination of components to build second view
    controller :: ViewToSelect -> SomeData -> Eff (mydom :: MyDOM | e) Unit
    constroller First d = addToBody $ firstView d
    constroller Second d = addToBody $ secondView d
    ...

As you can see controller module depends on MyDOM library's type and effect even though we have some kind of adapter module in between. And what if I would need to change MyDOM lib to, for example, JQuery?
But what does MyDOM effect mean? It means that this function is a computation with side-effects, which can be run in any environment which supports MyDOM.js library, right? Components module relies on MyDOM lib so it is true for it, but is it true for Controller module as well? Or maybe controller function is a computation with side-effects, which can be run in any environment which supports some way to render data?
It would be great if we could describe our domain in terms of types and effects, describe some kind of ports in which third party libraries then could be plugged. And when we would need to change one library to another, domain logic would stay untouched. (And different libraries could be unified this way too)
Our controller then could look something like this:

    ...
    firstView :: SomeData -> View
    secondView :: SomeData -> View
    controller :: ViewToSelect -> SomeData -> Eff (render :: Render | e) Unit
    ...

I don't know if any of this make sense or is it even possible, but I think that without a way to decouple libraries from actual code, creating a complex long-living projects in Purescript would be incredibly hard.
PS: sorry for my English, I'm not a native speaker :)

**Comment by joneshf** [comment]
I think the point isn't to remove all effects, but just that some shouldn't be specified.

One of the main reasons libraries like `purescript-dom` began existing was to help mitigate the problem of multiple other libraries like `purescript-jquery` defining their `DOM` effect and a library like `purescript-virtual-dom` defining their `DOM` effect, then using the same label name of `dom`. This caused incompatibilities between the functions. However, for most effects like `DOM` there's no reason they shouldn't be compatible.

As I understand the suggestion, it's to allow the case where you don't care what other functions use the `dom` label, you want to unify with them all because you're performing general dom side effects.

If you want to express that your `dom` label means you can only add `<a>` tags to the dom, then you can represent this with a concrete effect. And if anyone uses the label with a function that specifies some other concrete dom side effect, then it wont unify.

I think having polymorphic effects is a good idea, so I think removing most unit effects in exchange for "The one true unit effect" is a good way to represent things.

I also think there's room for more granular effects.
