### ISSUE TITLE
Clean up purescript-contrib

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1156]
Dear @purescript-contrib,

With Pursuit 2 around the corner, `purescript-contrib` is no longer needed as a database of contributor libraries (which I don't think it really lived up to anyway), so we've decided to close it.

If you would like to stay on as or become the maintainer of a contrib library (some libraries have fairly clearly defined owners already, others not so much), please make a note below, and we'll figure out a way to transfer the repo to the right person. If you are the current maintainer, and would prefer to just close a library, also let us know below.

Thanks.

**Comment by jdegoes** [comment]
I think this is a bad idea.

People create these libraries, register them with bower, and then abandon them. Or even if they don't abandon them, they can take weeks to respond to PRs. All of which happens in practice. I want a place where community libraries can live. That is, you may create a library, but not have the time to maintain it, so you can create it on contrib, give it a bower name, and it can live there forever, whether or not you are the one maintaining it. A huge number of libraries belong there.

Now, it doesn't have to be purescript-contrib, but please, if you're going to abandon that, just make me the admin and I will approve others and allow unlimited purescript libraries on that repo.

**Comment by garyb** [comment]
Those are some good points actually. I was all for closing contrib too, but if we change the focus from "projects that are supposed to be maintained to a decent level and in sync with the latest core" to just "projects maintained by the community, and maybe not all that maintained even" then it definitely has more of a use. It could be a place people can send their projects when they're useful to "the community" but they no longer want to mantain them too.

On the other hand, a graveyard of variable quality dead projects is probably not ideal either...

**Comment by joneshf** [comment]
I agree with @jdegoes. 

It's nice to have a community helping out with this stuff. I know I appreciated it when @mankykitty created a couple of repos to help out, and I definitely appreciate others coming in to help with pr's and whatnot when I can't respond quickly.

Can we change the requirements for contrib so that we don't get a whole mess of abandoned repos? I'm sure I've got a fair share in there that should be moved out.

**Comment by garyb** [comment]
@joneshf you're an "Owner" in contrib so you can move stuff in and out at will. I'm not sure there's anything of yours abandoned in there, and there's the excellent `lens` of course.

**Comment by paf31** [comment]
>  I want a place where community libraries can live.

I see the value in that. Maybe we just need to identify what contrib is for, set down some guidelines and try to transition it from "graveyard" to "community organization" again.

How's this for a first draft?

- Projects should be **maintained**. Each library should have a clearly identified owner who is responsible for responding to PRs and issues on the repo. To yield maintainership, simply say so in the README and we'll find a new maintainer.
- Projects should be **up to date**. Specifically they should build against the current core library set (up to a reasonable time window), or be identified as deprecated or seeking a new maintainer.
- Projects should be **documented**.

The alternative is that we just find a way to identify libraries as "seeking contributors". This could be as simple as a tag in Pursuit 2 with a page to list such libraries. I prefer this, since we could even use Pursuit to document things like whether a library is up to date with its dependencies one day (a la Stackage).

**Comment by paf31** [comment]
Further thoughts: I generally like things which are community-driven but decentralized, like the wiki. I think that's why I'm not a fan of contrib right now, because it's centralized and requires curation. To a certain extent, I feel like what we're describing above is just GitHub itself. There are already mechanisms in place to make sure things can be maintained by others - just _forking a repository_ and permissive licensing.

**Comment by chexxor** [comment]
Note: Seems appropriate to note that the bower registry is a mapping from package name to package location (no?), like

    purescript-lens => person-a/purescript-lens

If "person-a" stops responding to PRs, "person-b" can update the bower registry to have everyone use his fork of the package, like

    purescript-lens => person-b/purescript-lens

The effectively ensures the package creator won't be the maintainer-forever of that package. The only difficult part is deciding when to update the bower registry and whose should be the new master repo.

**Comment by jdegoes** [comment]
>  To a certain extent, I feel like what we're describing above is just GitHub itself. 

Due to the heavy dependency on Bower (which is not a bad thing), that's not exactly true; there's only ever one `purescript-lens` or `purescript-markdown`, for example.

If I stop maintaining `jdegoes/purescript-foo`, then every library anywhere that directly or indirectly references `purescript-foo` will ultimately be broken, and even if `purescript-foo` is a really popular library with lots of users (e.g. `simple-dom`), it doesn't matter — no number of community members nor helpful PRs can fix the situation. 

The only thing that can fix it is going through ALL libraries that directly or transitively reference the abandoned library, and updating them, which in turn will be good for a time until *that* Github user abandons the library (which WILL happen: people do not maintain libraries for their entire lifetime, so libraries will continuously transition from user to user causing much community pain all the while).

The system used by Hackage works well enough, where people can turn over the name / library / maintenance to someone else, which is what I'd like to see for `purescript-contrib` or something like it.

**Comment by paf31** [comment]
Isn't that what `bower unregister` is for?

**Comment by chexxor** [comment]
A case I'm worried about: "person-a" stops maintaining his fork of "purescript-foo". Within a few weeks, "person-b", "person-c", and "person-d" all create forks of "purescript-foo" to fix a bug and add a feature. Which one should become the new master repo? :-/

To alleviate this, having and managing (implies a committee/government? :dizzy_face:) a list of highly-referenced packages and their official latest git trees seems like a good idea. We could have that list as a purescript-contrib organization or as a bower registry. What's the difference? In the former, maintainers change while repo locations stay the same, while in the latter, maintainer changes force a repo location change.

How do we choose? Note that **active package maintainers is essential to PureScript**, as we have decided to use Bower for now. See the [Diamond Dependency Management Discussion](https://github.com/purescript/purescript/wiki/Dependency-Management-Discussion) notes to see why. Here's the summary: What do we do when we depend on a package which breaks due to dependency "bit-rot"? We **have someone update the bit-rotted package** to fix its dependency issues. (NPM packages don't suffer from such bit-rot, as each referenced package uses its own declared versions of dependencies when run. That ability relies on Node's run-time module-discovery process, `require`, which PureScript does not have.)

For this reason, I'm inclined to support the idea of fixing up purescript-contrib. We need active maintainers. Even if a package temporarily breaks due to a less-than-perfect maintainer, the pain of merging a subsequent patch is lower than having no maintainer at all.

**Comment by jdegoes** [comment]
> Isn't that what bower unregister is for?

Unregister cannot be used by just anyone — it has to be called by a contributor to the original package, which in my `purescript-foo` example, is just me, and I've abandoned the library (and, quite possibly, PureScript as well). Even if I am willing to go through the trouble of unregistering `purescript-foo` (and however many other packages I've abandoned), the name will be doled out first-come, first-serve — i.e. potentially anyone has control over arbitrary code imported into who knows how many projects.

> Within a few weeks, "person-b", "person-c", and "person-d" all create forks of "purescript-foo" to fix a bug and add a feature. Which one should become the new master repo? :-/

This is, in fact, what happens, as you can see by numerous abandoned purescript and other language projects. In some cases, they fix the same bugs or add similar functionality in conflicting ways. I've seen out it plays out and it leaves a lot to be desired, IMO.

**Comment by jdegoes** [comment]
By the way, if the final decision is to shut down `purescript-contrib`, I'm fine with that (although it's not my first choice), as I have created a `purescript-user` org. I can open up `purescript-user` to all community-maintained (as opposed to: individual-maintained) packages. In either case, would still need to decide the process by which one becomes an owner on `purescript-user` (i.e. someone who can create and fork repos there and add contributors), and the process by which one acquires (or loses) status as the "maintainer" for a package in charge of PRs, issues, docs, and the like.

**Comment by paf31** [comment]
Closing. This is being tracked in #1038.
