### ISSUE TITLE
Performance regression?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1171]
/cc @puffnfresh 

Do you have any details for this?

**Comment by puffnfresh** [comment]
I took purescript-aff master, installed the deps and timed it with 0.6.9.5 (with my recent performance patches applied) then compared it with @anttih's recent upgrade to 0.7 with the new deps and got the roughly the same timings. For some reason @garyb gets very different results.

I decided to do a profile anyway, and saw that ~25% of the time (a bit over a second for me) is spent in liftUnifyWarnings, which seems strange since I only saw 2 warnings printed. Warnings are also a new feature in 0.7, right?

**Comment by garyb** [comment]
Yep, `0.6.9.5` with the perf patches applied builds `purescript-aff` in about 2.5s for me, `0.6.9.5` without perf patches takes about 5s, `0.7-rc.1` takes 8s.

This is on a MacBook Pro. I'll try it on my desktop too actually.

**Comment by puffnfresh** [comment]
@garyb interesting, you're comparing numbers of pre-patching and I'm comparing post-patching. Maybe the performance changes mostly disappear with the patches, could you check that?

**Comment by garyb** [comment]
Sorry, I'm pretty sure I ran it on `master` actually when I said `0.7-rc.1` above. I'll double check and run everything again.

**Comment by garyb** [comment]
MacBook
- `master`: 7.9s
- `0.7-rc.1`: 13s
- `0.6.9.5`: 3.5s
- `0.6.9.5` + perf: 2.1s

**Comment by garyb** [comment]
Desktop (Win7 i7-4770k / 16gb RAM)
- `master`: 11s
- `0.7-rc.1`: 8.9s
- `0.6.9.5`: 3s
- `0.6.9.5` + perf: 1.8s

I'm 100% sure that `master` and `0.7-rc.1` is the right way around here too. What on earth? :sob:

**Comment by puffnfresh** [comment]
@garyb you fixed the problem with some strictness right?

**Comment by jdegoes** [comment]
`psc 0.7.x` was using 100x as much memory; now it's down to 10x (so better but not yet fixed).

**Comment by paf31** [comment]
I'll close this as a duplicate of #1297 now - build time has been reduced by parallel builds, so memory is the only major performance issue at the moment. Not that we can't improve build times more, of course.
