### ISSUE TITLE
Suggested `const` rewrite

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1188]
When the right hand side of const is not a literal or variable, rewrite as `const x` as `\_ -> x`.

**Comment by rightfold** [comment]
Why only when it is not a literal or variable?

**Comment by garyb** [comment]
I'm not so sure about whether we should do this one at all now. The idea was to avoid paying for evaluating `x` at the time `const x` is used, but maybe sometimes you do actually want that, instead of paying for it multiple times by evaluating a thunked value.

**Comment by spicydonuts** [comment]
This seems more like a strict -> lazy change rather than a perf change.  I know `const x` and `\_ -> x` are the same in Haskell, but the first way people are told that PS differs from Haskell is that it's strict.  It seems confusing to have that sometimes not be the case for special functions the compiler knows about.

If a PS dev cares about making a particular `const x` lazy they should probably make it a lambda.  To compare with JS, these are not at all the same:

```js
const constant = (x) => () => x
const buildAFive = () => Number(5)

// 'const'
doStuff().then(constant(buildAFive()))

// 'lambda'
doStuff().then(() => buildAFive())
```

This distinction is pretty clear in JS, but it's a bit fuzzy in PS.

**Comment by rightfold** [comment]
@spicydonuts it already is the case for `(&&)` and `(||)`. The compiler sometimes optimizes them to be lazy in its second argument.

**Comment by spicydonuts** [comment]
Right, but they become `&&` and `||` in JS, which are lazy.  They should _always_ behave that way.

**Comment by spicydonuts** [comment]
(*disclaimer*: by 'should' I mean I would expect them to, as a JS developer learning PS as a better way to write JS, and mostly going off of my intuition for JS)

**Comment by AppShipIt** [comment]
I'm familiar with JavaScript's behavior but that one surprises me. Is that sound concerning strictness?

**Comment by garyb** [comment]
@rightfold I think that's a little different, as you can't "pass around" an if expression in the same way a `const` might be. @spicydonuts sums up my concerns perfectly.

I know I've actually used a `const` wanting it to evaluate `x` immediately. Using a thunk explicitly to make it lazy does seem to be the appropriate way to deal with this, as although both things do mean `const` you can explicitly determine how it should be evaluated based on choice of construction, with this optimisation the choice is taken from you.

So I vote :-1: on my own suggestion :wink:.

**Comment by rightfold** [comment]
Compiler flag `--non-strict-strictness`.

**Comment by garyb** [comment]
@AppShipIt it's sound in that you can't do anything effectful in an expression involving `&&` and `||` without lifting them into `Eff`, so it doesn't change the semantics, it's just that when booleans are involved we use native `&&` and `||`, hence delayed evaluation.

**Comment by AppShipIt** [comment]
> it's sound in that you can't do anything effectful in an expression

That makes perfect sense 🙏

**Comment by rightfold** [comment]
The only semantic difference between laziness and strictness here is in nontermination. `const loopforever 42` never returns (= terminates) in PS, but it does in Haskell. Since observing nontermination is effectful, and PS lacks effects, this optimisation wouldn't break code. Throwing an exception is also considered nontermination.

**Comment by AppShipIt** [comment]
> maybe sometimes you do actually want that, instead of paying for it multiple times by evaluating a thunked value.

@garyb's concern sounded like performance characteristics unless it could be memorized?

**Comment by garyb** [comment]
Yeah exactly, I'm concerned that sometimes `const` is already used as a choice to ensure evaluation of `x` only occurs once, so turning it into a thunk would actually de-optimise it, unless we add memoization too, but then it's way more complicated than what was seemed like a simple change! And possibly even worse behaving sometimes...

**Comment by paf31** [comment]
Agreed, this is a performance issue not a semantic one. 👎 from me for the same reason as @garyb.

**Comment by rightfold** [comment]
I think this optimization does make sense when the *left* argument *is* a variable or a literal.
