### ISSUE TITLE
Wildcards with Tagged Unions and Fuctions

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1225]
test f = f 1 

    data Foo = Foo Int
    x  = test $ Foo _ --unexpected Underscore

    bar x y = x - y
    y = test $ bar _ 2 --unexpected Underscore

Is there a reason you cannot use wildcards in the same way as with the records or it is just not implemented?

**Comment by paf31** [comment]
The record syntax you're referring to is not the same as wildcards, which are a type-system feature. The underscore feature on the value level is restricted to three cases:

- record construction
- record updates
- record accessors

The reason is that it's not obvious how to desugar these underscores in the general case. What type do you claim the first example has? I assume the type is `Foo` because you want the function argument to be introduced inside the `$`, but how would the compiler know that?

**Comment by user471** [comment]
Foo _ should have type Int -> Foo
Why can't it just be syntax sugar?
something _ 
just transform to 
\x -> something x

**Comment by paf31** [comment]
Why does `test $ Foo _` not become `\x -> test $ Foo x` then?

**Comment by user471** [comment]
I guess for the same reason
test $ {x:_} not become \x -> test $ {x: x}

The simplest solution would be
something _ => x -> something x
so even if there is other stuff around it doesn't matter
foo (something _) bar => foo (\x -> something x) bar

**Comment by paf31** [comment]
I worry that this would be hard to document. The nice thing about the record restriction is that each case we currently handle is easily understood.

**Comment by user471** [comment]
Scala have this feature so I don't thing it's really so difficult. Honestly it is harder to understand why you cannot use _ everywhere but only records.

**Comment by user471** [comment]
I think it can be even easier to document because instead of this explanations from
https://github.com/purescript/purescript/wiki/Language-Guide:-Syntax
{ foo: _, bar: _ }
_.propertyName
rec { foo = _ }
_ { foo = 1 }
You can just write one line
something _ transform to \x -> something x everywhere it make sense.

**Comment by paf31** [comment]
But that doesn't suffice to document every case. You need to explain how it interacts with operators, records, constructors...

**Comment by user471** [comment]
But you already need to explain it with records.
And most important it doesn't interact with anything, it just syntax sugar.
foo something _ bar => foo (\x -> something x) bar
There isn't any interaction.

**Comment by robotlolita** [comment]
It's not that trivial to figure out what the boundaries of the transformation when you have this kind of partial application in expressions. In Clojure it works because the boundaries are clearly defined:

```clj
(map #(+ (identity %) 1) [1 2 3])
```

In PureScript it's more complicated, what should the following compile to:

```hs
map (1 + (identity _)) [1, 2, 3]
```

If we consider the `identity` application, that's not going to do the same the Clojure code does. If we consider the entire `map` expression, that's going to be bad as well. Worse cases happen with things like:

```hs
foldr (_ + (2 * _)) 1 xs
```

Is that a single function with two arguments? Or two functions? In the first case, it doesn't generalise (because of the problem demonstrated previously), in the second case it doesn't do what you expect it to do.

Purr considers only the application expression that directly has the wildcard, but that's still kinda awkward in some cases (the foldr example). It works for records because the delimiters of where the transformation happen are clearly defined.

**Comment by user471** [comment]
If we use the simplest solution there isn't any problem.
map (1 + (identity _)) [1, 2, 3]
map (1 + (\x -> identity x)) [1, 2, 3]

foldr (_ + (2 * _)) 1 xs
foldr (\y -> y + (\x -> 2 * x)) 1 xs

**Comment by robotlolita** [comment]
It's simpler, but in both of those cases those transformations don't make any sense, from an intention PoV, since they result in a type error.

**Comment by paf31** [comment]
Also, please define "simplest", ideally by structural induction on the term language. It's not so obvious how to formalize the intuition.

**Comment by natefaubion** [comment]
```
map (1 + (identity _)) [1, 2, 3] 
```
Is just
```
map (1 + identity) [1, 2, 3]
```
due to currying

```
foldr (_ + (2 * _)) 1 xs
```
Can be done as
```
foldr (+ (2 *)) 1 xs
```
Due to operator sections.

**Comment by user471** [comment]
> transformations don't make any sense
Yes you just cannot use it in such way and you need to use lambdas instead
map (\x -> 1 + (identity x)) [1, 2, 3]

**Comment by robotlolita** [comment]
My point here was most that, if you consider:

```hs
partialise (App f Hole) = (Lambda (Id x) f (Id x))
partialise n = n
```

That will only cover a minimal amount of cases. Those cases already happen to be covered by other syntactical features in PureScript (sectioning, almost clutter-free lambda syntax).

If you want to cover more cases, you'd need to find a way to figure out what the intended delimiter of the partial application is, and in PureScript the simplest way would be to introduce a new syntactical form similar to Clojure's #(...).

**Comment by user471** [comment]
>Also, please define "simplest", ideally by structural induction on the term language

foo (something _) bar => foo (\x -> something x) bar
I don't really know how to define it. You just take fist application of underscore and transform it to lambda.

**Comment by robotlolita** [comment]
Oh, by the way, if you introduce holes on expression application, then:

```hs
f { x: _ }
```

Would compile to:

```hs
f { x: \x -> x }
```

So, you'd need to differentiate the cases where you're inside records and the cases you're not, which complicates things quite a bit.

**Comment by paf31** [comment]
And our attempt to document this already spans several comments, hence my reluctance to go this route .. :smile:

**Comment by user471** [comment]
>That will only cover a minimal amount of cases. 
Why do you need it for {x: _} but not for Foo _? What is the big difference between Union and Records?

**Comment by user471** [comment]
>f { x: _ }

Where isn't application so it should be x -> f {x: x}

**Comment by garyb** [comment]
This is the problem Scala has also, it's not that clear what `_` does in any particular circumstance when you start nesting applications, etc. Or not to me anyway, I perhaps haven't written enough Scala (although, that's still not an insignificant amount).

**Comment by paf31** [comment]
> This is the problem Scala has also

Agreed. If I use this feature in Scala, and I rarely do, it's in very simple cases where it's very obvious where the abstraction happens.

**Comment by robotlolita** [comment]
@garyb it really isn't :)

In particular, I've tried to go the "figure out the correct delimitation of the partially applied expression with deeply nested holes" route in Mermaid. It didn't go well because you basically couldn't reason about the resulting code, so I removed that and went with the simpler semantics outlined above, which makes it rather limited in where it can be used, and the only reason for keeping it in is that Mermaid doesn't have either currying or sectioning.

I don't think this kind of partial application makes sense in the presence of currying, as far as function application goes.

**Comment by user471** [comment]
>it's in very simple cases where it's very obvious where the abstraction happens.

That is why I suggested simplest solution. It's just the same records feature but in two new scenarios.

**Comment by paf31** [comment]
If you want to put together a PR so that we can try out your suggestion on real examples, then go ahead, but I think most people are against this generally (this is not the first time this has been suggested), so you're going to have to make a pretty convincing case.

**Comment by jdegoes** [comment]
> Agreed. If I use this feature in Scala, and I rarely do, it's in very simple cases where it's very obvious where the abstraction happens.

I have no opinion on this feature at all.

That said, I think one could do a better job than Scala. The rule could be something like "go outside the nearest parens, curly braces, or brackets".

In which case you can use it in contexts like:

```purescript
{ x : _ }
```

```purescript
(foo _ bar baz)
```

and,

```purescript
[0, 3, 1, _]
```

but no where else. Which is at least simple and predictable.

After a while you can predict Scala's, but it's not so easy. :grimacing:

**Comment by paf31** [comment]
> The rule could be something like "go outside the nearest parens, curly braces, or brackets".

But parens should have no effect on program meaning.

**Comment by paf31** [comment]
Sorry, to be clear, I should be able to replace something like `$` with parens freely.

**Comment by paf31** [comment]
Also, can someone give me a rule which generalizes the current behavior for `_ { foo = _}`?

**Comment by jdegoes** [comment]
> But parens should have no effect on program meaning.

Yeah, and `_` should not alter the meaning of code outside of it.... yet it does. :wink: 

Because it's syntax, it's non-composable and magical by definition. It's still that way with records, you cannot ascribe an expression-oriented meaning to `_`. Which is why I have no opinion on it. Even the existing record syntax magic can be done simply through lenses (although it's nice not to have to pull in that dependency and define lenses for simple cases).

**Comment by garyb** [comment]
I guess if you ignore structure and only use the left-to-right position of `_`s, but then it's how you delimit that still.

**Comment by robotlolita** [comment]
Does PureScript support things like:

```hs
a { b = _ + c }
```

Because in that case the feature would always be ambiguous, and resolution would have to use arbitrary rules which can be difficult to reason about. (Not that `a { b = _ }` isn't already ambiguous with this addition)

**Comment by garyb** [comment]
No it doesn't, the `_` replaces the full value (or object).

**Comment by paf31** [comment]
> Because it's syntax, it's non-composable and magical by definition ...  It's still that way with records, you cannot ascribe an expression-oriented meaning to _.

Except that a standalone `_` doesn't even parse. It doesn't make sense to talk about it in isolation. It only makes sense in one of three very locally-scoped contexts. And I can give a very simple meaning for each of those three, and I only have to look as far as the immediately surrounding `{}` to do so.

**Comment by paf31** [comment]
> _ should not alter the meaning of code outside of it.... yet it does.

`{ x: _}` and `{ x: anything else }` are different terms in the language.

**Comment by jdegoes** [comment]
> And I can give a very simple meaning for each of those three, and I only have to look as far as the immediately surrounding {} to do so.

Yes, that's why I think the "evilness" of the present rules is fairly low, but it is syntax and that comes with all the usual caveats... I do *understand* the desire of people to avoid "flip hell" or local lambdas with common cases like "foo _ bar baz", but until someone proposes / implements a rule that's simpler and more predictable than Scala, this may be one of those cases where the solution is worse than the problem.

**Comment by garyb** [comment]
I think that perfectly sums up my feelings on it too :+1:

**Comment by robotlolita** [comment]
So, rules covering this could be given as:

```hs
partialise (Record xs) = let ns = collectNames xs in Lambda ns (Record (replaceNames xs ns)) 
partialise (Project Hole y) = let n = free in Lambda x (Project n y)
partialise (Update x y) = let ns = (collectNames x + collectNames y) in Lambda ns (Update (replaceNames x ns) (replaceNames y ns))
partialise (App f Hole) = let n = free in Lambda n (App f n)
partialise n = n
```

But again, I don't see the reason for adding (App ...) there when `f` can be curried, since application rules already generalise partial application.

**Comment by jdegoes** [comment]
> { x: _ } and { x: anything else } are different terms in the language.

That's just semantics, though. The point is, that single magical character, which has no standalone meaning and which does not compose, alters the meaning of its surrounding context, in much the same way that a hypothetical `(foo _ bar baz)` would. Which is why all syntax is evil. :smile:

**Comment by paf31** [comment]
Closing this. See this and previous discussions for reasons why we want to avoid overusing `_`.

**Comment by AppShipIt** [comment]
For documentation purposes: wildcards have since been applied to operator sections within parens, soon to be lambda `case`, and potentially ternary expressions. As a group we seem comfortable with wildcard in syntactic constructs and binary operations but not general function application. The reason is a combination of both visual and parsing ambiguity of complex expressions as well as potential obfuscation. I know one desirable use case but doesn't outweigh the cost of adopting wholesale.

**Comment by user471** [comment]
>visual 
Personally I don't see any difference between
```
(x <#> _)
```
and
```
(foo _ x)
```

> parsing ambiguity 

Could you show some example?
