### ISSUE TITLE
Conflicting imports when module doesn't use conflicting name

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1240]
module A where
	import Prelude
	foo :: Int -> Int
	foo x = x + 1

	module B where
	import Prelude
	foo :: Int -> Int
	foo x = x + 10

	module C where
	import A
	import B

error: Conflicting imports for "foo" from modules A and B

Is this error really necessary? Cannot compiler just ignore this conflict because foo is not used?

Also 

	module C where
	import A
	foo :: Int -> Int
	foo x = x + 100

instead of error "Cannot declare "foo" since another declaration of that name was imported from C"
Why not just auto hide foo from A?

**Comment by user471** [comment]
Why do you close issues without explanation? What is wrong with this suggestion?

**Comment by paf31** [comment]
Because I was working through a lot of issues and didn't have time to comment on each one. The suggestion is fine, but it's probably not something we're going to do, because we generally prefer to be explicit about imports, and inferring them from the content of the module is even less explicit than what we allow now. I also think it would lead to more confusing error messages. Also, doing a search for every imported thing to see if it is imported twice and used sounds costly, and code generation becomes ambiguous.

**Comment by user471** [comment]
But it's annoying. You cannot just

```
import Data.Array
import Data.List
```

Also in most languages you can just write 
```
namespace A {
	class X {}
}

namespace B {
	class X {}
}
using A;
using B;
```
Without any problem. And it makes perfect sense, because you shouldn't care about what imported module contains if you don't use it.

>Also, doing a search for every imported thing to see if it is imported twice and used sounds costly

But compiler already search for it, otherwise how can it write error like Conflicting imports for "foo" 
Also I would prefer if compiler works instead of manually import management.

**Comment by paf31** [comment]
I suggest you fork the compiler and demonstrate how this should work then.
