### ISSUE TITLE
Use psci when parts of your code fail to compile

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1279]
If I am using psci with a bunch of modules, and one fails to compile, it would be nice to be able to import and play with the ones that did compile successfully. Currently you can't do anything until all of the loaded files can be compiled successfully.

**Comment by libscott** [comment]
This is an issue for me too. I find myself opening psci and just entering `1` to see if my code compiles. Because when the build is broken, all you can get from it is a binary result. I'd like to be able to "import MyProject.Types" to see if that module checks out, even if others dont. Also, it seems to slow the repl considerably that it tries to compile whole whole project on every command - completions are lightning fast.

**Comment by kRITZCREEK** [comment]
This could be (partially) solved by using "rebuild" as it only looks at modules downstream from the rebuilt module.

**Comment by kRITZCREEK** [comment]
I say partial because if you didn't manage to compile a downstream module and now try to build a module higher in the hierarchy you might end up rebuilding against a stale externs file which could get very frustrating...

**Comment by paf31** [comment]
I could potentially fix this with in current branch. The new code uses `rebuild`, and when it's done, will hopefully work like GHCi's `:load` mode, always running in the context of a single module and its dependencies.

**Comment by kika** [comment]
I'm much more painful now with 0.9 psci, On 0.8.5 I just edited `.psci` file and removed problematic modules, but `.psci` file is no longer with us, unfortunately.

**Comment by hdgarrood** [comment]
Can't believe this didn't occur to me before &mdash; if we had deferred type errors (#1868) wouldn't that more or less solve this?

**Comment by paf31** [comment]
> On 0.8.5 I just edited .psci file and removed problematic modules, but .psci file is no longer with us, unfortunately.

This is true, but I think we're better set up to solve this problem properly now, along with some other nice enhancements.

For now, it should be possible to invoke `psci` with a custom list of files on the command line, which you could put into a script if need be.

**Comment by kika** [comment]
> For now, it should be possible to invoke psci with a custom list of files on the command line, which you could put into a script if need be.

Well, it was easier to `mkdir test.purs && cd test.purs && pulp init && cp ../bower.json . && bower install`

I thought that maybe it would be even better to have a "scratch" mode for psci to ignore everything in `src/` and `test/` and whatnot and only load from `bower_dependencies`.

**Comment by paf31** [comment]
> only load from bower_dependencies.

`pulp 'bower_components/purescript-*/src/**/*.purs'`

Does this do what you want?

**Comment by kika** [comment]
@paf31 if you meant `pulp psci 'bower_components/purescript-*/src/**/*.purs'` then no, it complains about `Control.Alt` being defined multiple times. I have absolutely no idea how that might happen even in theory, because I had an impression that bower dependencies are flat. But `pulp psci` works as expected, except that it doesn't because I introduced a deliberate error in `Main.purs` for testing :-)

**Comment by kika** [comment]
If I remove the error from `Main.purs` then `pulp psci` works perfectly well.

**Comment by paf31** [comment]
Sorry, I've corrected what I wrote. It should have said `psci`, not `pulp`.

**Comment by kika** [comment]
Yep, that works! I abandoned using `psci` by itself, because it doesn't even pick up the `purescript-psci-support` module and always use it through pulp. But this usage pattern totally makes sense, great.

**Comment by hdgarrood** [comment]
I wonder if that "module being defined multiple times" error is happening as a result of modules being listed twice on the command line. Does the same thing happen if you try running this?

```
psci 'bower_components/purescript-*/src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs'
```

**Comment by paf31** [comment]
Since we can do

```
purs repl 'bower_components/purescript-*/src/**/*.purs'
```

```
purs repl `psc-package sources`
```

to drop into the repl with only dependencies loaded, I think this can be closed now.

**Comment by hdgarrood** [comment]
I would like to consider keeping this open for two reasons:

* it would be nice not to have to use that command, and I think it could be somewhat awkward for people with non-standard setups.
* it's true that in many cases, you only want to play with code from your dependencies and therefore your proposed workaround is sufficient, but I imagine it's not that uncommon to want to play with a local module A even if some other local module B doesn't compile.

**Comment by kRITZCREEK** [comment]
`purs ide` does this in a sense. It doesn't see errors in any modules the to-be-rebuilt module doesn't depend on transitively. I'd imagine it working like this for `purs repl`:

1. Parse all the passed in modules, ignore modules that cause parse errors. 
2. Build the toposorted dependency graph, remove every module for which a dependency cannot be found.
3. Compile like we usually do, but instead of erroring the whole computation on failure, collect all the successful compiles and discard the failing ones.

**Comment by paf31** [comment]
The problem is that I don't see a nicer way to solve this. I don't want to ignore modules with errors, because the user _asked_ us to load those files. It's a fine default for `pscide`, but not for PSCi in my opinion.

The only alternative I can think of is something like `purs repl <files> --exclude <module>`, where we exclude the specified module and its dependents. But that seems awfully redundant to me: "please load these modules - oh, except these ones".

Especially since the usual use cases are

1. load everything
2. load only dependencies
3. load only dependencies plus some (hopefully small) subset of `src/`

So if there's a good proposal that addresses these things, I'm happy to reopen this.

**Comment by chexxor** [comment]
After discussing a bit in chat, I think we can reframe the requested change a bit. I think the current request is "allow psci to load broken modules", perhaps a better request is "have psci lazy-load modules".

I imagine psci would work as follows to obtain the behavior requested in this issue. I haven't worked with psci much, so this will need to become more specific:

```
$ purs psci $FILES # Creates index of all modules in $FILES
Found 150 modules.
> import Prelude -- Loads/parses Prelude and its dependencies (and transitive deps).
Compiling PreludeDep1
Compiling PreludeDep2
Compiling Prelude
> 1 + 1
2
> import App.MyModule -- Loads/parses App.MyModule, as with Prelude.
Compiling App.MyModuleDep1
Compiling App.MyModuleDep2
Compiling App.MyModule
> :type myFunction
String -> String
> import App.MyModule2 -- This one has a type-error, so nothing is added to context.
Compiling App.MyModule2
Compilation failed.
Error 1 of 5: ...
Error 2 of 5: ...
...
> :type App.MyModule2.myFunction2 -- Nothing new here, because that module doesn't compile.
  Unknown value myFunction2
```
