### ISSUE TITLE
Optimizer rules broken after BooleanAlgebra change

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1312]
https://github.com/purescript/purescript/blob/master/src/Language/PureScript/CodeGen/JS/Optimizer/Inliner.hs#L159

**Comment by natefaubion** [comment]
It seems like this stems from the test Prelude getting out of sync with the published Prelude.

For example, if you add a test like

```purescript
module Main where
import Prelude
import Assert
import Debug.Trace
main = print (true || error "Fail")
```

It will pass because its getting correctly inlined for the tests.

https://github.com/purescript/purescript/blob/0644a4c7ae236daf05c75004062d72ded4e8a497/tests/prelude/Prelude.purs#L401-L405
https://github.com/purescript/purescript-prelude/blob/8d6cd04f322d15480d0c583a385f18ec1342933c/src/Prelude.purs#L809-L814
