### ISSUE TITLE
Linter runs every time on unmodified modules

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1328]
Should this be the case? We don't get warnings about partial matches every time the compiler runs, only shadowed name warnings - but also, this is probably not helping incremental performance... not that it will have any impact on the overall memory usage explosion unfortunately.

**Comment by hdgarrood** [comment]
I think that when you build a Haskell project with cabal, if a module compiles successfully but produces warnings, it won't print those warnings the next time you run `cabal build`. This can be a little annoying; more than once I've accidentally checked in code that produces warnings because I forgot to run `cabal clean; cabal build`. I don't feel particularly strongly either way, but it might be worth keeping this in mind, at least.
