### ISSUE TITLE
Capitalized key names in records?

### ISSUE THREAD

**Issue by ethul** [purescript/purescript#1360]
Should it be permitted to use capitalized key names in records?

For example:
```purescript
type Test = { "Foo" :: Int }
```
Produces the following externs:
```purescript
type Test = { Foo :: Prim.Int }
```

And the compiler fails with:

```bash
unexpected "Foo"
expecting type
```

**Comment by garyb** [comment]
Yeah, I think this should be allowed - any valid identifier or quote-escaped string should be acceptable if we're following the same rules as javascript for what's allowable in a record... I guess whatever we do here applies to rows as a whole, but again I don't see any issues with that, there are no namespace clashes that can result from allowing captialised row labels.

Looks like we're not pretty-printing the externs file here correctly, but @paf31 was talking about overhauling the externs format soon to just used something based on Show/Read s-exprs, so that will probably fix this.

**Comment by ethul** [comment]
Sounds good. Thanks for taking a look.

**Comment by rhurmala** [comment]
Probably related:
```purescript
type Record = { "label with whitespace" :: String }
```
produces externs
```purescript
type Record = { label with whitespace :: Prim.String }
```
which also fails to compile
```
  Unable to parse module:
    unexpected "with"
    expecting type
```
