### ISSUE TITLE
Question: Module System and Dependencies

### ISSUE THREAD

**Issue by seanstrom** [purescript/purescript#1447]
Hello everybody!
I have few questions around PureScript's module system.
* Why do dependencies (third party modules) need to be a flat list?
* Is it possible to implement a module system similar to Node's where it allows for nested dependencies for version conflicts?
* Or is it possible to something similar NixPkgs, where the dependencies are always a flat list, but module lookup is more fine grained. e.g. name + version + other build arguments.

I've seen @garyb mention in https://github.com/purescript/purescript/issues/631#issuecomment-77535163 that there are issues with using hierarchical dependencies. The comment sort of eludes to it being something with the way Type Classes are implemented, or needed to be implemented. I general I would appreciate some clarification, and possibly documentation on the subject if there is any.

Thanks in advance. :)

**Comment by robotlolita** [comment]
Those are more related to packaging and distribution than the module system per se. But from what I gather:

- Dependencies are a flat list because that's how Bower works. Bower places the burden of resolving dependencies on the user, because it doesn't know anything about the semantics of how each package interacts with each other;

- Probably not. But npm's model of dependencies is a bad idea in general: even if the package manager can install all of the dependencies, there is absolutely no way of knowing whether the resulting application works, because if things ever cross the boundaries you might either get a type error (if you're lucky), or things might just have a very confusing behaviour at runtime (because the types aren't sufficient to capture the differences):

```purs
reverse :: forall a. [a] -> [a]
reverse [] = []
reverse (x : xs) = (reverse xs) ++ [x]

reverse' :: forall a. [a] -> [a]
reverse' xs = xs

-- Both functions have the same types, but behave differently. This will cause surprises
-- when these functions are passed around from one context to another.
```

- These have the same problem above in naïve implementations.

Would a package manager that's specific for PureScript help? Certainly. A lot of the problems in Bower's usability for PureScript come from the fact that Bower does not know what PureScript is. Otherwise, it could, for example, run tests for different versions when a conflict happens, and tell you either the recommended version, or whether the versions are fundamentally incompatible (neither works across your whole application).

I did start planning a tool for that (https://github.com/robotlolita/puree/blob/master/notes.md), but haven't got the time to implement it yet.

While this is more about tooling, there are some semantics that make it harder to have a good tool for this:

- PureScript modules depend on implementations of modules, rather than their signatures. So, when you say `import Foo.Bar.Baz`, you're really saying that your module requires some concrete thing that `Foo.Bar.Baz` happens to be from the paths you've provided to the compiler. Interfaces/Signatures, like those in ML modules and Haskell's Backpack allow a more general view of this, and also separate compilation/linking (you don't need to have the modules in order to run the type checker, just the interfaces, and you can type check things separately. This would help a package manager verify if what you're installing is indeed what you need to install. It also allows replacing implementations in a type-safe manner, since the constraints are independent of their implementations).

- Many things are second-class in PS. I'm not sure if PureScript allows overlapping instances. If it does, then you get even more ambiguity if you use something like npm's dependency model. If it doesn't, you can't use npm's dependency model, because it won't compile if dependencies ever diverge. You might also get type errors if instances ever cross a boundary (if you pass M@1.x to some module that expected M@2.x, things are not going to look very good. Even if it type checks). Fortunately, a package manager could use PS's type system, and quickcheck tests (it would be nice if PS supported defining QC tests for type class laws, and then have some way of running those), to help you disambiguating. Unfortunately, PS's type system isn't on the level of dependent types, so the amount of constraints you can encode is limited.

**Comment by seanstrom** [comment]
@robotlolita thanks for the comprehensive response :). I'm still trying to internalize the information, but I have another question that if answered would help clarify things for me. This may be a very naive question, so please bear with me.

What I imagine is a system that would allow for an individual app/module to have its own context for defining modules and external dependencies. And those external dependencies would have their own context for defining their own modules and external dependencies. Is it possible to do that in a way where when you have a dependency conflict, each dependency gets the proper reference to the source?
How would that affect verifying if the program can run? I would note that this question assumes that the only way these context ever leak out to one another is by one exporting and another importing. I'm not sure if there are implicit ways for the "contexts" I talk about to leak. I'm not sure if this line of questioning makes sense. Thanks again for taking the time?

**Comment by garyb** [comment]
Great reply @robotlolita!

My point about typeclasses is covered in that, but I'll explain a bit more - instances are global in a PureScript program, so if you have two versions of `Data.Maybe`, how would we decide which version to use when something that has two different versions of `Data.Maybe` as transitive dependencies? We indeed do not allow overlapping instances*, so this means the compiler will reject the program entirely if this situation where ever to arise.

[*] This isn't strictly true, they are warned about at the moment, but only to allow the `Inject` typeclass to work until we implement a real fix for it (instance chains, something like that). They should be avoided at all costs currently, as they _will_ be totally disallowed again, and hopefully not too long from now.

On the other hand, if the compiler was version-aware, maybe these instances wouldn't be overlapping, as they would be for different incompatible types, `Data.Maybe@1.0.0` and `Data.Maybe@2.0.0`. In theory, if you wanted to depend on various modules using different incompatible versions of `Data.Maybe`, you could perhaps make this workable by having to write an explicit conversion between the two data types: `Maybe@1.0.0 -> Maybe@2.0.0` as this would definitely make it safe, however would not be much fun. This is perhaps as it should be though, as it gives you an escape hatch but certainly doesn't encourage relying on incompatible dependencies.

There may be other issues that I'm not thinking of here, but indexing modules/types by version this way might be possible. There are quite a few things that would need figuring out even still:

- Making the compiler aware of libraries
- Introducing version-indexing for every module, value, type
- Figuring out how to import multiple modules of differing versions and talk about their types
- How would that play with module re-exports?
- How would you avoid being required to specify the version for every import in every module? (Perhaps the default version imported is based on the current library's manifest file, referencing others would require version-indexing)

Regarding contexts leaking, without some version-indexed types and values, here's a very simple case that is could easily happen in:

- Module `A` imports `Data.Maybe@1.0.0` where `data Maybe a = Just a | Nothing` and has a function `getA :: Maybe String`.
- Module `B` imports `Data.Maybe@2.0.0` where `data Maybe a = Some a | None` and has a function `getB :: Maybe String`.
- Module `C` imports `B` and `A`, and tries to pattern match usages of both `getA` and `getB` - oops! Now what?
- Neither `A` or `B` export `Maybe` directly here, but their transient `Maybe` dependency leaks out and causes problems unless we have some way of talking about different versions of `Maybe`.

**Comment by seanstrom** [comment]
@robotlolita @garyb Ah! I see what you're saying now. Allow me to re-iterate so I'm clear.
Basically if a library exposes a return value like Maybe, it automatically makes it hard to reason about what Maybe we're talking about without having some type of version on them. Otherwise you won't know if the Maybe that's being returned is the Maybe you're expecting. Is that correct?

**Comment by seanstrom** [comment]
I did a tiny bit of digging and found some slides suggesting "Private Dependencies".
I'm not sure if this has already been brought up but here's what I digested.

From what I gather, any dependencies that go across library boundaries, would only have one instance of them. Any dependency that isn't leaked from the would be annotated as "Encapsulated", and then tests would be ran to validate that indeed that dependency hasn't been leaked out in any way.

So for example, Data.Maybe would most likely only have one instance in the system, since there is a good chance that it will travel across library borders. But a dependency like Data.Foo, which is a common dependency among projects, could be used in multiple libraries as long as Data.Foo wasn't exported in any way. You may be able to pull that off by having version indexes that are read in from the manifest, as you mentioned.

What are your thoughts on that?

**Comment by seanstrom** [comment]
Some further digging has lead me to an issue in the Elm repo.
https://github.com/elm-lang/elm-package/issues/89#issuecomment-69539587
Seems to answer my question, correct?

**Comment by seanstrom** [comment]
I've already received some great answers, but I have another question, forgive me :)

I started looking into how Rust crates handle dependencies.
The language allows for nested dependencies and has a language feature similar to TypeClasses (Traits). I've asked around on IRC and it seems that Rust will embed meta information into the exports of the packages. So that when you would import them there's an user friendly symbol like `Foo` and the computer version `Foo@1.0.0#CrateName. Does that make sense? Im still figuring it all out so It may not seem clear.

@robotlolita
Have you looked into how Rust handles its dependencies? If so what we're your thoughts on it.

**Comment by hdgarrood** [comment]
I was doing a bit of research on this topic recently and blogged about it: http://harry.garrood.me/blog/purescript-why-bower/

My current view is that trying to do this now would introduce a whole bunch of really thorny problems, which have no obvious good solutions, and maybe no good solutions at all! So I'm not keen. If we are going to even think about this, I think we should be very clear about what we expect to gain from doing it, and why it would be better than the current situation. Even thinking about this stuff makes my head hurt ;) Occasionally having to send a PR in order to loosen version bounds for some library I depend on seems much more agreeable in comparison.

I admit I haven't looked into how Rust handles dependencies yet.

**Comment by paf31** [comment]
Closing. I think @hdgarrood 's post answers the original question, and the Package Manager discussion item covers the rest.
