### ISSUE TITLE
First class modules

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1505]
Suggestion from this issue https://github.com/purescript/purescript/issues/1502#issuecomment-145322646
What if a module could be some sort of a first-class citizen. When you define a module, compiler create a record.
```
module Foo where
bar x = x + 1

Foo  = {bar: \x -> x + 1}
```
Then you could use this record
```
x = let f = Foo in f.bar 1
y = f.bar 1 where f = Foo
```
Maybe you could even open the record in a local scope
```
open Foo
x = bar 1
```

**Comment by garyb** [comment]
So, as I mentioned in the other issue, I had experimented with this idea a little, but classes/instances were the problem (as usual).

However, now we disallow orphan instances and perform a global lookup, there maybe is no problem anymore - there are no strange scoping rules to worry about anymore.

If we were to introduce something like the `open` syntax I would vote for it to be expression-oriented rather than a statement, as discuessed in #1492 and demonstrated with the `using`/`with` examples mentioned in there.

**Comment by robotlolita** [comment]
First-class modules are pretty great, but they're also impossible to optimise (we can't e.g. DCE a first-class module because we can't track which parts of it will be used afaict).

First-class modules and second-class classes seem kind of at odds to me, but maybe only if you allow embedding/creating modules in expressions? I know Purr has this problem because it's unclear how one should merge the instances when the module gets instantiated with different type/value arguments, though the problem doesn't exist if you don't allow dynamic/parametric modules.

**Comment by garyb** [comment]
I think "first class module" isn't quite the right terminology here, it's just about the ability to treat modules as if they are records (and vice versa for local imports) - so not true ML style functors/parametric modules. Following that, it doesn't really change anything in our ability to reason about them, so I think we can preserve DCE and the like.

**Comment by paf31** [comment]
I think this can be replaced by the Modular Type Classes proposal, yes?
