### ISSUE TITLE
Rows in instance heads

### ISSUE THREAD

**Issue by jbrownson** [purescript/purescript#1510]
```purescript
module Main where

import Prelude
import Control.Monad.Eff
import Control.Monad.ST

class Foo a b where
  asdf :: a
  qwerty :: b a

-- This doesn't build with the error:
-- Invalid type in class instance head:
--  (st :: Control.Monad.ST.ST s)
instance fooIntA :: Foo Int (Eff (st :: ST s)) where
  asdf = 42
  qwerty = pure 42

-- I can work around it w/ a newtype:
newtype X s a = X (Eff (st :: ST s) a)

instance fooIntB :: Foo Int (X s) where
  asdf = 42
  qwerty = X $ pure 42
```

Is there a reason we don't just support rows in the instance directly? It seems like if it works w/ the `newtype` it should work w/o it too.

**Comment by paf31** [comment]
Rows aren't allowed in instances because that effectively assigns behavior to different row labels, something we (I?) don't want to do. I think of it this way: labels are just opaque symbols, and all behavior should be invariant under arbitrary renaming of labels.

If you really want to assign behavior to a label, you might be able to use `purescript-reflection`.

**Comment by jbrownson** [comment]
This was a small example of a thing I hit when experimenting w/ using the finally tagless style and converting a data structure to use a bunch of multi parameter type classes (as it needed the main type as well as types that were a function of that main type, and I wasn't sure how to specify that w/ just one type).

It so happened that inside the type I wanted to create an instance for I had some Eff stuff happening, so I wasn't really interested in assigning behavior to labels, I just happened to have some labels in a bigger thing I wanted to assign behavior to.

The multi-parameter type classes absolutely ruined inference though so I abandoned that line of thinking,  but I don't know that it's completely unreasonable to want to make typeclass instances for things that have some Eff stuff going on inside them. I do agree that intentionally giving the labels meaning is a bad idea. One could of course solve 90% of cases by just relying on the shape of the types, and unless there are duplicates in the row you're good, you could give an ambiguity error otherwise, but that's pretty ugly.

I could understand not fixing this for the reason you gave, and I no longer have use for it myself.

**Comment by paf31** [comment]
Bear in mind, you can have class instances for things like `Eff`, but the effect row has to be unconstrained.

You can also have constrained rows in instance _contexts_, but not in instance _declarations_, so you can have 

```purescript
shout :: forall m. (MonadEff (console :: CONSOLE) m) => String -> m Unit
```

for example.

**Comment by jbrownson** [comment]
I was making an instance for a thing that contained w/in it an Eff w/ ST, I needed to specify the ST so I could use it w/in the functions in the typeclass.

The typeclass was for a graph. Some of the instances were pure, but one of them lived in ST.

It's interesting that one can work around this restriction using a newtype which effectively allows for defining behavior for labels with some added syntax to discourage it. Maybe the compiler isn't the best place to encourage/discourage this behavior, and it should just be style? I don't really have a strong opinion.

**Comment by paf31** [comment]
> It's interesting that one can work around this restriction using a newtype which effectively allows for defining behavior for labels with some added syntax to discourage it.

Well, if you define for example

```purescript
newtype WithST eff h a = WithST (Eff (st :: ST h | eff) a)
```

then `WithST` is a new type name, and behavior is tied to that name, not any particular label like `st`.

> Maybe the compiler isn't the best place to encourage/discourage this behavior, and it should just be style?

Potentially, but there are also type checking concerns, since type checking and type class lookup are separate right now. Maybe it's possible to use unification once they are brought together, but I'm not even sure that's a good idea. Should rows be instantiated with particular labels because a type class exists, for example? I'm not sure, really.

**Comment by paf31** [comment]
Moving this to "Discussion" since it's come up many times, and I think we should answer it once and for all.

Another option here is to wait for functional dependencies, and solve this with

```purescript
instance fooIntA :: (eff ~ (st :: ST s)) => Foo Int (Eff eff) where
```

Note, this is not the same thing as the original, since this instance will successfully match _any_ effect row, then its subgoal will try to force `eff ~ (st :: ST s)`. So you've still attached special behavior to a row, but you can't "row case" any more since overlapping instances would allow at most one instance with head `Foo Int (Eff eff)`.

**Comment by garyb** [comment]
I think the `~` usage is perhaps a bit harder to understand, but it definitely sounds like a better way of solving it than allowing the row directly.

Would open rows like `eff1 ~ (st :: ST s | eff2)` be workable here too?

**Comment by AppShipIt** [comment]
Same quandary as @garyb. It doesn't feel so much harder to me especially considering it already addresses a relatively advanced use case. I also like the generality of functional dependencies.

**Comment by paf31** [comment]
> Would open rows like eff1 ~ (st :: ST s | eff2) be workable here too?

I don't see why not.

It is harder to understand, but if you're trying to case on rows in instance heads, you're probably already advanced enough to understand the additional constraint, I think.

**Comment by garyb** [comment]
Cool. I assumed that was the case, but just wanted to check I wasn't missing some hidden assumption.

And yep, agreed.

**Comment by garyb** [comment]
Actually, do we have an issue for `~` constraints?

**Comment by paf31** [comment]
I think it's called functional dependencies, but it should probably be renamed, because that's not really what it is.

**Comment by AppShipIt** [comment]
Just for my learning do you have a link about its relationship to functional dependencies?

**Comment by paf31** [comment]
Nothing off the top of my head, but here's a sketch: with fundeps, you have classes like 

```haskell
class MonadState s m | m -> s
```

The arrow says "`m` determines `s`", so you can have at most one instance for a given `m`, and the `s` is determined based on that. During solving, if you know `m`, that means you can solve for `s` too, instead of the usual solver approach where you need both to match.

Alternatively, you can push the solving into the instances:

```haskell
class MonadState s m

instance monadStateStateT :: (s ~ s1) => MonadState s (StateT s1 m)
```

The instance head will match _any_ `s1`, but then the subgoal will force it to unify with `s`.

Compare this with the current approach:

```haskell
instance monadStateStateT :: MonadState s (StateT s m)
```

Here, you might find yourself wanting a `MonadState s (StateT Foo m)`, and you'll get "No instance for...".

But with the `~` constraint, `s` will unify and `s1` will unify with `Foo`, so the instance will be chosen. _Then_, the subgoal will unify `s ~ Foo`.

**Comment by AppShipIt** [comment]
[Equality constraints](https://wiki.haskell.org/GHC/Type_families#Equality_constraints) (I remember going there to compare type families to functional dependencies before).

**Comment by rvion** [comment]
here (https://github.com/purescript/purescript/issues/1580) is a related discussion about __fundeps__ vs __type families + equality constraints__. (I still prefer type families + equality constraints)

**Comment by cprussin** [comment]
Sorry to revisit a dead horse, but I keep seeing folks mention that `~` will solve this, but I can't seem to find any docs on what `~` is or how to use it. @paf31 can you point me in the right direction?  Has it landed in PS or is this still future speculation?

**Comment by paf31** [comment]
@cprussin `TypeEquals` is what you want. You can use `TypeEquals (RProxy r1) (RProxy r2)` to assert that rows `r1` and `r2` are equal, or something like `Record` in place of `RProxy` if you need to coerce records of those types, for example.

**Comment by cprussin** [comment]
Hmm not sure I follow, how does that enable rows in instance heads without the newtype wrapper?

**Comment by garyb** [comment]
`TypeEquals` is a constraint, so you'd use it a little like:

``` purescript
instance monadAskMyMonad ∷ TE.TypeEquals r MyRecordSynonym ⇒ MonadAsk r MyMonad where
  ask = ...
```

With this constraint, you can use the `to` and `from` functions in `TypeEquals` to coerce between `r` and `MyRecordSynonym`.

In the above, if `MyMonad` is a `ReaderT` over `Aff` or something, the `ask` implementation would be `ask = MyMonad (map TE.from ask)`

**Comment by cprussin** [comment]
I see--but that doesn't seem any more convenient than using a `newtypè to wrap the row. Is there something I'm missing that makes `TypeEquals` preferred over `newtypè?

**Comment by garyb** [comment]
You only have to use the extra machinery at the instance site, rather than everywhere that you use it - if you `newtype`d the record here, you'd have to unwrap it every time you `ask`ed.

**Comment by cprussin** [comment]
Ah I see--I misunderstood and thought with this, you'd have to use `to` at the call site. Makes sense, thanks a bunch for the explanation!

**Comment by cprussin** [comment]
Ok, one more question here--say I have a typeclass that is only defined over a single type.  How do I avoid overlapping type class instance errors?

For example:

```purescript
class Foo b where
  bar :: b -> String

instance fooString :: Foo String where
  bar = identity

instance fooRecord :: TE.TypeEquals r (Record (baz :: String)) => Foo r where
  bar = TE.to >>> _.baz
```

With the example you posted above, `MonadAsk` has a fundep between the types so the monad type is enough to ensure the instance is unique.  But with no other types, or no fundep between the types, is there still a way I can use `TypeEquals` to solve this?

**Comment by LiamGoodacre** [comment]
@cprussin in your specific example case you probably want to do
```
instance fooRecord :: TE.TypeEquals (Record w) (Record (baz :: String)) => Foo (Record w) where
```

The `Foo (Record w)` is necessarily apart from `Foo String` so they aren't overlapping.

**Comment by cprussin** [comment]
So then, I guess there'd be no way to disambiguate different `Record` structures in this example:

```purescript
instance fooRecordBaz :: TE.TypeEquals (Record w) (Record (baz :: String)) => Foo (Record w) where
instance fooRecordBar :: TE.TypeEquals (Record w) (Record (bar :: String)) => Foo (Record w) where
```

In any case, this got me exactly what I needed; thanks so much for all the help folks!
