### ISSUE TITLE
Functional Dependencies

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1580]

**Comment by jdegoes** [comment]
Do you mean this generically, or specifically fundeps versus type families?

**Comment by paf31** [comment]
I mean that I want to write e.g. `class MonadState s m | s <- m` and have any solution for `m` solve the type of `s`.

**Comment by LiamGoodacre** [comment]
:smile: :+1:

**Comment by tfausak** [comment]
:+1:

**Comment by paf31** [comment]
Another option, instead of using `->` to indicate dependencies, is something like

```purescript
class MonadState s m where
  state :: forall a. (s -> Tuple a s) -> m a

instance monadStateStateT :: (Monad m, s ~ s1) => MonadState s (StateT s1 m)
```

where `~` becomes a constraint.

**Comment by paf31** [comment]
Another option: get rid of MPTCs entirely, and add associated types:

```purescript
class MonadState m where
  type State m
  state :: forall a. (State m -> Tuple a (State m)) -> m a

instance monadStateStateT :: (Monad m) => MonadState (StateT s m) where
  type State (StateT s m) = s
  ...
```

I prefer the `~` constraints solution.

**Comment by jdegoes** [comment]
Are they exactly equivalent in terms of expressive power?

**Comment by paf31** [comment]
No, I don't think so, but I think fundeps could be equivalent to using `~`, since the purpose of a constraints like `MonadState s m | m -> s` is just to make the instance head match more eagerly, by requiring the `s`s to be equal as long as the `m`s are, which we can enforce with a `~` constraint.

**Comment by cdepillabout** [comment]
I wrote up a small Haskell program to show the differences between type families and functional dependencies.  It shows how functional dependencies and type families are similar, and how they can be used to make type checking easier for the end user:

```haskell
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}

module Main where

--------------------------------------------------------------------------
-- This is a typeclass for adding two types together.  It doesn't use
-- functional dependencies or type families.  You can see that things like
-- the 'test' function are a little hard to write.
--------------------------------------------------------------------------

class Adder a b c where
    myPlus :: a -> b -> c

instance Adder Int Int Int where  
    myPlus :: Int -> Int -> Int   
    myPlus a b = a + b

instance Adder Int Double Double where
    myPlus :: Int -> Double -> Double
    myPlus a b = fromIntegral a + b

test :: String
-- This does not work because ghc doesn't know what the return type of the
-- 'myPlus' function should be:
-- testNoFunDeps = show $ myPlus (3 :: Int) (4 :: Int)
--
-- This works:
test = show (myPlus (3 :: Int) (4 :: Int) :: Int)

---------------------------------------------------------------------
-- This is the same typeclass but using functional dependencies.  Its
-- 'testFunDeps' function is a little nicer.
---------------------------------------------------------------------

class AdderFunDeps a b c | a b -> c where
    myPlusFunDeps :: a -> b -> c  

instance AdderFunDeps Int Int Int where
    myPlusFunDeps :: Int -> Int -> Int
    myPlusFunDeps a b = a + b

instance AdderFunDeps Int Double Double where
    myPlusFunDeps :: Int -> Double -> Double
    myPlusFunDeps a b = fromIntegral a + b

testFunDeps :: String
-- This works because of the fundeps.
testFunDeps = show $ myPlusFunDeps (3 :: Int) (4 :: Int)

---------------------------------------------------------------------
-- This is the same typeclass but using type families.  Its
-- 'testTypeFam' function is nice like 'testFunDeps'.
---------------------------------------------------------------------

class AdderTypeFam a b where
    type ResultType a b

    myPlusTypeFam :: a -> b -> ResultType a b

instance AdderTypeFam Int Int where
    type ResultType Int Int = Int 

    myPlusTypeFam :: Int -> Int -> Int
    myPlusTypeFam a b = a + b

instance AdderTypeFam Int Double where
    type ResultType Int Double = Double

    myPlusTypeFam :: Int -> Double -> Double
    myPlusTypeFam a b = fromIntegral a + b

testTypeFam :: String
-- This works because of the type families.
testTypeFam = show $ myPlusTypeFam (3 :: Int) (4 :: Int)
```

However, I'm not sure how something like this could be written without multi-parameter typeclasses (or lots of newtypes)?  Also, while the `~` trick can definitely be used for things like `MonadState` and `StateT`, I'm not sure how it would apply to typeclasses like above?

Here is a nice write-up on functional dependencies vs. type families (although I think some of this stuff is Haskell-specific):
https://ghc.haskell.org/trac/ghc/wiki/TFvsFD

In my personal experience, functional dependencies and type families are both nice to have.  Functional dependencies are nice for purely just doing type resolution (like in the `MonadState` example above).  Having to use type families for this can lead to verbose code.  Imagine if you had to encode all of the functional dependencies of the [`Cons`](https://hackage.haskell.org/package/lens-4.13/docs/Control-Lens-Cons.html) class as type families!

However, type families are nice for doing more complicated things.  The Haskell library Servant makes [nice use of type families](http://www.arow.info/blog/posts/2015-07-10-servant-intro.html).

**Comment by cdepillabout** [comment]
Since this tripped me up in https://github.com/purescript/purescript-transformers/issues/64, I added a section about functional dependencies to the "Differences Between Haskell" wiki page: https://github.com/purescript/purescript/wiki/Differences-from-Haskell#functional-dependencies-and-type-families

Please edit as necessary.

**Comment by phadej** [comment]
My 5¢:

Between `FunctionalDependencies` and `TypeFamilies`, I'd pick `TypeFamilies` and type equality constraint `~`. Even the later is a slippery slope into dependent types like programming (or maybe because of that?)

I'll explain why.

Conceptually `TypeFamilies` are (open or closed) type level functions. We need equality constraint to make possible to postpone unification of function results. For example:

`F a ~ F b` may hold when `a` and `b` are instantiated, even `a` and `b` are different. Pick `type instance F a = ()`.

Taking the previous example by @cdepillabout (examples are Haskell, I tested them):

```hs
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FunctionalDependencies #-}

class AdderFunDeps a b c | a b -> c where
    myPlusFunDeps :: a -> b -> c  

class AdderTypeFam a b where
    type ResultType a b

    myPlusTypeFam :: a -> b -> ResultType a b
```

we can simulate `FunDeps` with `TypeFam`:

```hs
class (AdderTypeFam a b, c ~ ResultType a b) <= AdderFunDeps' a b c where
    myPlusFunDeps' :: a -> b -> c
    myPlusFunDeps' = myPlusTypeFam
```

Other way around is impossible (?), at least I don't know how to write `ResultType` without `TypeFamilies`.

---

Another (a bit more) complicated example:

```hs
class Strict strict lazy | strict -> lazy, lazy -> strict where
    -- In `lens` there's just strict :: Iso strict lazy
    strict :: lazy -> strict
    lazy :: strict -> lazy

class StrictTF strict where
    type Lazy strict

    strictTF :: Lazy strict -> strict
    lazyTF :: strict -> Lazy strict

class (StrictTF strict, lazy ~ Lazy strict) => Strict' strict lazy where
    strict' :: lazy -> strict
    strict' = strictTF

    lazy' :: strict -> lazy
    lazy' = lazyTF
```

---

Why this examples? To motivate that `FunctionalDependencies` could be desugared into `TypeFamilies`.

In `Strict` example inference is better with original *both ways* functional dependency. There other parameter could be inferred from other one. In `TypeFamilies` example that is not possible, as `Lazy strict` is ambigious. **Except** if we have [`InjectiveTypeFamilies`](https://ghc.haskell.org/trac/ghc/wiki/InjectiveTypeFamilies) which introduces the same `| -> ` syntax :)

OTOH as `TypeFamilies`, especially `InjectiveTypeFamilies` are very expressive, you will eventually (probably sooner than later) run into situations like in this [haskell cafe post](https://mail.haskell.org/pipermail/haskell-cafe/2015-November/122322.html). In other words, you'd like to be able to guide type checker, and it's not clear where actually.

**Comment by rvion** [comment]
I would also prefer to see type families than fundeps becasue they have proven simpler and more straight forward in most cases. I agree that fundeps are sometimes shorter to write and avoid some redundancy in constraints, but they seems harder to implement, and they bring a new construction to the language.

regarding type equality operator, I would prefer to see '='

**Comment by rvion** [comment]
also, if you go for type families, I think it would be great to add data kinds too

**Comment by paf31** [comment]
After more thought, it occurs to me that `~` constraints are not enough to support some of the things we want to be able to do. Specifically, we can define things like `MonadState` instances globally this way, and have `s` inferred when that instance is picked, but we can't abstract over those instances in type signatures (i.e. MTL style). So I think that's a non-option unfortunately.

So we're back to functional dependencies or something like type families (or associated types) as the available options.

**Comment by rvion** [comment]
here is an other excelent write-up about FD vs TF

https://typesandkinds.wordpress.com/2015/09/09/what-are-type-families/

it's from Richard Eisenberg (a.k.a. goldfire), prolific ghc contributor (and who recently merged types and kinds in ghc (type-in-type extension))

It includes some recommendation about what could be done to improve the haskell state of things if we didn't care about breaking changes (so that totally could apply to purescript) 

small citation from the post:

> ### A radical proposal:
>
>So, what should we do about all of this? I’m inspired by the non-problems with functional dependencies. I thus propose the following. (Actually, I don’t. This is too radical. But I’m trying to provoke discussion. So take this all with a heap of salt.)
>
>  1. Remove unassociated open type families. They’re quite awkward anyway – either they should be closed and define some sort of concrete function, or they will need a class constraint nearby to be useful.
>  2. Require class constraints to use associated type families. That is, if F a is associated with a class C a, writing F Int without a C Int constraint in scope is an error. This means that the use of an associated type family in the right-hand side of another associated type family will require the class constraint in the instance context.
>  3. Require closed type families to be total, with an improved termination checker. Naturally, closed type families would be unable to call partial type families.
>  4. Devise a mechanism to associate a closed type family with a class. This would allow for partial closed type families, which indeed are useful.

**Comment by phadej** [comment]
@paf31 what you mean, cannot abstract over?

```hs
class Monad m => MonadState s m | m -> s where
  get :: m s

class MonadState m where
  MonadStateS :: *

  get :: m (MonadStateS m)

-- lensy
foo' :: (MonadState m, HasFoo (MonadState m)) -> m Foo
foo' = ...
```

@rvion: nice find.

Yes, we have to be precise what we really want. Here I
- don't propose *unassociated open type*
- *use class constraints to use type family*
- (3) and (4), don't talk about closed type families.

So I agree with Richard :P

**Comment by rvion** [comment]
@paf31 I was also wondering

@phadej I'm fully in line with you :)
(to solve the problem with class associated TypeFamilies, with a type equality constraint `~`(or `=`) and some injectivity checking.

(📝  I'm wondering if in this setup, injectivity checking will be easier. Could purescript expand mappings on his own, and check if stuff is injective or not without annotations ?)

Having injective type families would solve another of those __huge__ problem haskell use to have (I know that ghc 8 has injective type families with some markup, but it has caused so much pain until now)

**Comment by goldfirere** [comment]
Ah -- the chance to do it all over again. :)

Here's a few thoughts:
* I'm glad you like my "radical proposal". My views have not evolved since writing that blog post, so I still recommend that course of action.
* Sometimes fundeps match the domain better than type families, and sometimes it's the opposite. For example, I like using fundeps for something like `MonadState`. They are much syntactically lighter than type families. You could always consider having one underlying mechanism (I think type families are conceptually simpler) with two different possibilities for surface syntax.
* Be better than GHC in giving the type families a deterministic operational semantics. Right now, GHC reduces type families in an impossible-to-predict manner. This means that it's impossible to write the `If` type family, because GHC might reduce the true/false cases before the condition. Of course, PureScript is strict, so you probably want a strict semantics to your type families anyway. How to do this? Just reduce type families using the same semantics as you do at the term level.
* Think carefully before you allow non-linear patterns in type families. (That is, ones with a repeated variable on the left-hand side.) I don't think they're all that common in practice. Indeed, when writing the "Closed type families" paper I did a search and was unable to find a single non-linear type family instance. With closed type families, non-linear patterns are more useful (and gave rise to the canonical closed type family `Equals`), but even there they're not great. In particular, I've found that code that requires non-linear type families is often trying to implement some rather intricate new type system on top of Haskell's. While this can work in many cases in the target domain, these approaches often fall short at a critical moment and then suddenly require a typechecker plugin. I'm not currently advocating typechecker plugins for PureScript (though they've proven popular in GHC), but I would say that non-linear type families without typechecker plugins is an awkward compromise... and once you have typechecker plugins, you don't really need the non-linear patterns either.
  - Bonus: Without non-linear patterns, termination checking is more straightforward.
* Do consider adding closed type families. They're very useful.
  - In a first version, you can require the patterns to be non-overlapping. Then you don't have to worry about apartness.
  - Regardless of other benefits, having a type family that is closed (that is, no more equations can be added) is useful documentation.
  - You can imagine implementing totality checking on a closed type family. Even if you don't implement this today, having closed type families around will encourage programmers to use them, and then you can introduce the totality checker tomorrow.
  - Without non-linear patterns, you can "compile" a closed type family into a normal pattern match; with your well-defined operational semantics, you can then just try patterns top-to-bottom. This also eliminates the need for apartness checking.
* When writing the injective type families paper, we had a hard time coming up with examples where you want an injective type family. It turns out most useful type families are not injective! I would not prioritize that feature.

I'm happy to debate these and other ideas -- I may keep looking in on this ticket. If I don't, just email me.

**Comment by rvion** [comment]
@goldfirere thanks you very 👍  !

__I have a few questions:__

> Sometimes fundeps match the domain better than type families, and sometimes it's the opposite. For example, I like using fundeps for something like MonadState. They are much syntactically lighter than type families. You could always consider having one underlying mechanism (I think type families are conceptually simpler) with two different possibilities for surface syntax.

 - Do you think it worth it to have both FD and TF in the language ?
 - Can you think of cases that only FD can solve nicely and other cases only TF can solve nicely ?
 - Would you be annoyed if there were only FD or only TF ?

I ask this because I think I mostly saw cases where either
  1.  using FD is shorter but TF is okay too, a bit more verbose but also easier to read.
  2. using TF is short, not quite sure how to write the FD counterpart without several FD annotations, and large multiparams-typeclasses hard to refactor and read.

__and a few comments__

> Do consider adding closed type families. They're very useful.

👍 Most type level stuff I do now in regular applications (eg. to enfore type sanity via phantom types, or extending the architecture of an app without changing all underlying types) end up using closed type families. I feel the need for them in most projects I do.

> When writing the injective type families paper, we had a hard time coming up with examples where you want an injective type family. It turns out most useful type families are not injective! I would not prioritize that feature.

I guess it's just me, so. I missed injective type families quite a few times while working on libraries (ORMs, game engines, etc.). Maybe was I just missing the obvious because of inexperience.

**Comment by goldfirere** [comment]
>    Do you think it worth it to have both FD and TF in the language ?
    Can you think of cases that only FD can solve nicely and other cases only TF can solve nicely ?
    Would you be annoyed if there were only FD or only TF ?

I like the fundeps in Haskell's mtl package. I think that's more succinct than using type families. On the other hand, any type-level computation is much cleaner with type families. If I were choosing between the two, I would favor type families over fundeps -- while keeping with my "radical proposal" to have the type families be more fundep-like in requiring a class constraint available to use them.

As for injective type families: now that GHC has them, see if you can go back and reimplement your old idea with injective type families. You might discover that your type family isn't injective after all. That's what happened in most every case when someone really wanted injective type families.

**Comment by paf31** [comment]
@goldfirere Thanks for the helpful information! Chances are, I'll end up implementing something like functional dependencies first, since it's a natural fit with what's already there (MPTCs etc.) and fixes an existing problem (`MonadState`). If/when I get to implementing type families though, this will all be very useful.

**Comment by srghma** [comment]
> I'll end up implementing something like functional dependencies first, since it's a natural fit with what's already there

((((

IMHO, TypeFamilies are easier to understand

e.g.

```
{-# LANGUAGE TypeFamilies #-}

class (Monad m) => MonadError m where
  type Err m
  throwError :: Err m -> m a
  catchError :: m a -> (Err m -> m a) -> m a

instance MonadError (Either e) where
  type Err (Either e) = e
  throwError = Left
  catchError (Left e) f  = f e
  catchError (Right a) _ = Right a
```

is easier to understand than

```
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE MultiParamTypeClasses #-}

class (Monad m) => MonadError e m | m -> e where
    throwError :: e -> m a
    catchError :: m a -> (e -> m a) -> m a

instance MonadError e (Either e) where
  thowError = Left
  catchError (Left e)  f = f e
  catchError (Right a) _ = Right a
```
