### ISSUE TITLE
Pattern Synonyms

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1667]

**Comment by natefaubion** [comment]
As a reference in this space, what about something like [F# active patterns](http://blogs.msdn.com/b/dsyme/archive/2007/04/07/draft-paper-on-f-active-patterns.aspx)?

**Comment by rgrempel** [comment]
In working on [purescript-elm](https://github.com/rgrempel/purescript-elm), I've come across two cases in which pattern synonyms would be nice (if I'm understanding correctly what pattern synonyms would be -- here's a reference to an older issue, called "Constructor alias" #1438).

One case is Elm's [`Result`](https://github.com/elm-lang/core/blob/master/src/Result.elm) type, which is basically equivalent to [`Data.Either`](https://github.com/purescript/purescript-either/blob/master/src/Data/Either.purs), but using [`Ok` and `Err`](https://github.com/elm-lang/core/blob/master/src/Result.elm#L31-L33) as the two constructors, rather than [`Left` and `Right`](https://github.com/purescript/purescript-either/blob/master/src/Data/Either.purs#L31).

Ordinarily, I'd want to implement `Result` as an alias for `Either`, and then write whatever functions are needed to wrap the API differences. However, it's not really possible to alias the *constructors*. (I know I can now have *operator* aliases for the constructors, and even use them in pattern matching (#1890), which is neat, but doesn't allow for `Ok` and `Err`). So, I end up [re-implementing the whole thing](https://github.com/rgrempel/purescript-elm-compat/blob/master/src/Elm/Result.purs) (basically copying the code for `Either` and renaming the constructors).

The other case is Elm's `Date` type. Like `Data.Date`, it has an type for enumerating the days of the week. Now, they are named differently --  [`Day`](https://github.com/elm-lang/core/blob/master/src/Date.elm#L51) in Elm vs. [`DayOfWeek`](https://github.com/purescript/purescript-datetime/blob/master/src/Data/Date.purs#L229-L236) in Purescript. Of course, I can alias `Day` to mean `DayOfWeek` easily enough. However, the Elm constructors are abbreviated ... i.e. `Mon`, `Tue`, `Wed` vs. `Monday`, `Tuesday`, `Wednesday` in `Data.Date`. Without pattern synonyms (or constructor aliases), I don't think there's anything I can do about that.

So, those are cases in which I would have found pattern synonyms (or constructor aliases) to be helpful.
