### ISSUE TITLE
Official (non-JS) backend(s)

### ISSUE THREAD

**Issue by andyarvanitis** [purescript/purescript#1692]
I'd like to have a discussion about where we'd like to go with non-javascript backends. To cut to the chase, I'm not sure a "non-embedded" backend can survive (beyond the "experimental" phase). There are of course some difficulties in keeping in sync with the baseline, e.g., introducing changes that break the backend without realizing it, or simply not taking its needs into account when redesiging/refactoring things bacause it's not "right there." But perhaps the bigger issue is the reliance on FFI code in the standard packages. Any non-official backend would have to maintain forks of the now many packages, which has its own set of logistics problems.

Although there's been interest by Phil and others to make the C++11 backend an official one at some point, I'm not lobbying for that here. It might not be a good idea to have more than, say, two official backends, and maybe that second one should be a JVM one (or LLVM, or BEAM, etc.). Thoughts?

**Comment by garyb** [comment]
As you know one of the major hurdles for alternative backends at the moment is the lack of the core imperative representation - I'll be working on that again soon though, as 0.8 is almost done now. I think that will definitely help with some of these issues as I imagine that AST will change much less frequently than the rest - I think I may have only changed the core functional representation once since coming up with it.

There was some suggestion on IRC that we could move the core of the compiler into an actual library and start semantically versioning it, that would help some with the compatibility issue, as at least you'd know whether something had changed in a breaking manner between versions. I'm not sure what Phil thinks about doing it this way though.

Regarding forks of packages, I'd always assumed we'd add multiple FFI implementations to the core libraries, so no forks would be required for those at least. Since it's the executable that determines what files get used there is no real obstacle to having the JS, C++, etc. FFI implementations included in the libraries. It's one of the reasons we've also tended to promote the idea of "FFI libraries" in contrib, which then have a more pleasant API constructed on top, to avoid the need for libraries to have random snippets of FFI in their midst (where possible, obviously not every FFI library will make sense across platforms, I imagine there's no problem with any of core's FFI usage however).

**Comment by andyarvanitis** [comment]
> Regarding forks of packages, I'd always assumed we'd add multiple FFI implementations to the core libraries, so no forks would be required for those at least. Since it's the executable that determines what files get used there is no real obstacle to having the JS, C++, etc. FFI implementations included in the libraries

Right, but that's a big part of what I'm wondering. Which backends would/should get FFI implementations in the standard libraries? Even if they're ignored by `psc`, `pcc`, etc., they still need to get there and be maintained. The current mechanism is very good and clean, IMO, but it's more of a logistics question for me.

**Comment by garyb** [comment]
I see what you mean. From my perspective I'd be happy for the core libraries to support any backend that is actively developed, I don't really expect there will be that many unfortunately :smile:

I think getting fairly comprehensive tests in every core library that uses the FFI will be important too, perhaps we could come up with some way of comparing the test output across backends to ensure compatability.

**Comment by andyarvanitis** [comment]
Thanks for the comments, @garyb.
> I think getting fairly comprehensive tests in every core library that uses the FFI will be important too, perhaps we could come up with some way of comparing the test output across backends to ensure compatibility.

Definitely. Even ones that don't use the FFI would be helpful. I've been comparing the test suite outputs (`examples/passing`) to make sure the C++ backend is producing the same runtime results as the js one.

**Comment by paf31** [comment]
I agree there is an issue of maintaining compatibility here, but I also would like to avoid having many backends implemented in this repo. I like the idea of splitting out the core AST stuff, and versioning that very carefully, especially since the pure11/14 backends are now much closer to interpreters for that core, if I understand the situation correctly, and it might make sense to implement other backends that way (JVM?)

I also like the idea of providing the ability to dump the core as a file, so maybe there is a middle ground where we version the core files using a tag inside the file, like we do with externs, and just be very careful to bump the version whenever a breaking change occurs. So the file versioning would be independent of the main compiler versions.

**Comment by hdgarrood** [comment]
Funnily enough, I was just thinking about this recently: http://harry.garrood.me/blog/when-to-use-the-purescript-ffi/. I hope we can address this issue reducing the amount of FFI usage, or perhaps rather the *spread* of FFI usage. I do think there are lots of places that use it where they don't really need to at the moment.

Re dumping core: we might be able to steal some code from truffled-purescript and put it into the compiler. I think it currently implements JSON serialization of an intermediate AST. Although I think it was CoreFn.

**Comment by andyarvanitis** [comment]
Re @paf31's:
> ..., especially since the pure11/14 backends are now much closer to interpreters for that core, if I understand the situation correctly, ...

Yes, the pure11 backend is very similar to the js codegen now, and effectively pushes a pseudo-dynamic-types (variant types) mechanism into the C++11 "runtime". For pure14, not so, but I haven't decided what its future is yet.

**Comment by andyarvanitis** [comment]
Also, to reiterate my original main point (which maybe I inadvertently buried), what to do about the standard packages is my main concern. But overall, it's a logistics issue/question more than any technical one. Keeping the backend(s) code out of the main compiler is probably the easy part.

**Comment by paf31** [comment]
Maybe we can make a distinction between "officially supported" (i.e. core libraries include support etc.) and "included in the main compiler repo". I see no problem with including C++11 backend files in the core library repos, but we'd probably want to avoid doing that if we have 10 backends :smile: Perhaps this is something that can be solved with a smart package manager.

**Comment by dagit** [comment]
I'd like to vote for a .NET/CLR backend.

**Comment by andyarvanitis** [comment]
That would be be interesting -- maybe someone will do it at some point.

The C++11 backend actually works quite well on Windows / VS 2015 -- or at least it did when I last tried it a couple of months ago. And I plan to try it again soon and continue to support it. So I think you can at least get PureScript native binaries on UWP (I believe that gets us there before F# 😉).

**Comment by dagit** [comment]
@andyarvanitis Thanks for mentioning the C++11 backend, I was unaware of that. I'm currently looking for ways to use PureScript with Unity. With enough boilerplate I could also make the C++11 work, so I may look into that as well.

First I should try PureScript -> js and loading that into Unity. It's just that I'm not sure if Unity's js implementation can accept standard js. I've heard it's non-standard and some of their examples hint towards that. I know that Unity accepts C# and F# just fine hence my interest in .NET as a target.

**Comment by andyarvanitis** [comment]
@dagit, Cool. Well let me know if you do end up trying the C++ backend at some point and need any help or support with it.

**Comment by paf31** [comment]
Note that `--dump-corefn` is now available as of 0.10. I think I'd like that to be the answer to "how should I implement a backend for language X?" going forward, especially once we have `--dump-imperative-core` too.

**Comment by freylax** [comment]
I would like to point out the ideas I had for the native cpp integration. First to the build/package management to be seen here: [purescript-native-build](github.com/freylax/purescript-native-build)
and more complex [purescript-native-cpp-so](github.com/freylax/purescript-native-cpp-so).
Second I managed to use the REPL for native code with the changes in [purescript](github.com/freylax/purescript)
and example [purescript-native-repl](github.com/freylax/purescript-native-repl).
best regards
Robert

**Comment by natefaubion** [comment]
I believe that it's possible now to maintain alternative backends without compiler forks (several exist and fairly well maintained). I believe we also document these alternative backends. I don't think the current org maintainers will have the bandwidth any time soon to officially support alternative backends. Should this be closed?
