### ISSUE TITLE
Set --require-path to ../

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#1698]
Previously in #1605, @stkb [posted](https://github.com/purescript/purescript/issues/1605#issuecomment-153451808):
> :+1: from me too. IMO `--require-path=../` should be the default anyway.

I just stumbled across this useful option value. Was `--require-path` meant to be added with a default value of `../`?

The current defaults generate files with no prefix, for example `require('Prelude')`. This default seems to be making the assumption that the resulting build output path should also be on the `$NODE_PATH`. Up until I found @stkb's comment, I hadn't personally gotten a build working outside of a single-file bundle with `--to someBuildTarget.js`, or `$NODE_PATH` hacks.

(I'm using Pulp, and the default may be more useful there, but I'm curious to hear your thoughts.)

**Comment by natefaubion** [comment]
An emphatic :+1: from me. The webpack `purs-loader` uses `--require-path=../`. The problem with the default now is that you can get conflicts between npm modules and purescript modules if you add the output directory to your $NODE_PATH. For example, if you install `react` via npm and then use `purescript-react` (which exports a `React` module, note the case difference) and try to bundle the two of them, you'll get warnings because this is actually a conflict in a case insensitive file system.

**Comment by garyb** [comment]
I'm not sure if @paf31 has changed his position here, but there's discussion about why it's not already the default in #938. I still prefer the idea of a `../`-default :wink:.

**Comment by stkb** [comment]
Was going to mention the contents of #938 too but gary beat me to it :)

I still think ```--require-path=../``` should be the default too; the reason being that the ```/output/``` folder becomes valid commonjs modules, rather than just temporary intermediate files. 

The argument against of course is that it might break existing projects, but since most use the psc / psc-bundle combination I don't know if it would be that many.

**Comment by stkb** [comment]
I should correct myself and say that the output folder becomes more useful as valid *Node* modules, rather than commonjs, since the commonjs spec is actually less specific than the Nodejs implementation on resolving top-level modules.

Also to @damncabbage not sure if you were asking but #1605 and the PR #1606 fixed the fact that ```psc-bundle``` wouldn't work at all if ```psc ... --require-path=../``` was used. Also you can add the ```--require-path``` option to a ```pulp``` command line and it will pass it through to ```psc```

**Comment by damncabbage** [comment]
@stkb Thanks; I do realise you _can_ do it, but it was only after @hdgarrood telling me that `--require-path` existed and then stumbling across your comment with the `--require-path '../'` example specifically that I was able to produce a build I could make use of.

**Comment by hdgarrood** [comment]
We should also note `psc-bundle` does allow you to avoid `NODE_PATH` hacks while using the default require-path, even in the presence of conflicting module names (eg, `React` and `react` on a case-insensitive FS). If you run `psc-bundle` first on the `output` directory, collecting all your compiled purescript code, and then run the result through `browserify` to pick up npm dependencies, you're good.

Unfortunately, since `psc-bundle` performs whole-program DCE, it's arguably not suitable for a normal development build, because it's too slow. It's also not always possible to switch `psc-bundle` for `browserify` either (eg: it's easy to use the output of `psc-bundle` with some additional JS code, but this is not really the case with `browserify`). This leads me to think that a `psc-bundle` mode which is optimised for speed would be useful. It could avoid performing DCE and maybe even parsing too.

**Comment by hdgarrood** [comment]
Also, this situation where half of us are using `--require-path=../` and the other half aren't is a bit silly, I think. It would make things a lot simpler if we could find a value that works for everyone and remove the configuration option. For example:

* #1836
* https://github.com/bodil/pulp/issues/151
* https://github.com/ethul/purs-loader/issues/15
* https://github.com/purescript-contrib/purescript-react/issues/58

**Comment by boris-marinov** [comment]
Hi,
I tried playing with purescript today and I encountered an issue with this.

Currently what do I have to do if I want to require a PureScript module from JS?

**Comment by hdgarrood** [comment]
@boris-marinov these sorts of questions are better suited to the mailing list, IRC, or stackoverflow, really. But since you're here I'll just say that one option is to use "pulp build --to purescript-bundle.js" and then add a line "module.exports = PS" at the end of purescript-bundle.js.

**Comment by paf31** [comment]
I think we've decided to implement this. Moving to 0.9.

**Comment by paf31** [comment]
Fixed in 0.8.3.
