### ISSUE TITLE
`psci` should be easier to use globally and/or when a project directory fails to build

### ISSUE THREAD

**Issue by chrisdotcode** [purescript/purescript#1756]
`pulp psci` is nice, but it isn't when you need to test something in a REPL, but can't because your build is broken (and it's probably broken because you were in the middle of needing to test something in a REPL...).

Furthermore, it's a giant detriment to adoption that `psci` ***doesn't*** immediately work out of the box without installing `purescript-console` (and it didn't even work for me when I *did* try doing `bower install -g purescript-console`).

I propose that 1. `pulp psci` first attempts to build, and if that fails, falls back to a global variant of `psci`, and that 2. `psci` works immediately globally, after a fresh purescript install by installing `purescript-console` with it, and creating a global `.psci` file that imports `Prelude` defaultly.

As a tangential request, `.psci` shouldn't pollute `$HOME`, but should be in `.config/purescript/psci` or wherever that OS stores configs. I - *ahem* - know a [great module](https://github.com/chrisdotcode/cone) that does that in a cross-platform way.

**Comment by paf31** [comment]
I think we already look for `.psci` in the home directory and the current directory.

And I'm fairly sure there is another issue to track the issue when code fails to compile.

**Comment by chrisdotcode** [comment]
I still think allowing `psci` to work globally at all times (even importing `Prelude`) provides a much better [OOBE](https://en.wikipedia.org/wiki/Out-of-box_experience).

**Comment by hdgarrood** [comment]
Just fyi: `bower install` has no `-g` option, and bower (regrettably) just ignores unrecognised flags.

There isn't really any purescript installation process at the moment, other than putting some executables on your PATH. Complex installation processes are usually a total nightmare, in my experience, so I really wouldn't want to create one unless there was a very good reason.

I agree that it's unfortunate that psci doesn't "just work" (although I'm unconvinced by your assertion that it's a giant detriment to adoption). I don't think this is a good enough reason to start making the installation process more complex, though, especially as we distribute purescript through a bunch of different channels already (hackage, github releases, npm...)

If you just want to play around, `mkdir purescript-scratch && cd purescript-scratch && pulp init && pulp psci` works. The [getting started](http://www.purescript.org/learn/getting-started/) page already instructs you to do essentially this.

I'm also :-1: for using different config locations for different OSes. There is no standard for where to put configuration files on any OS, really, it's just a total mess. The way I see it is, it's a mess at the moment, but if we started putting it in a different place in different OSes, it would remain a mess, *and* it would be harder to explain where the global `.psci` should go.

**Comment by chrisdotcode** [comment]
Well, out of the box experience *is* the user's experience. I don't necessarily mean adding more and more files - rather `psci` can check to see if the current directory is a purescript project, and if not (or said project doesn't build), it'll just run the "global" version of a psci compiler. Adding a singular additional dependency to `psci` to make it work in this case doesn't seem all that complex to me.

As for configuration, there *are* standards: two of them at least. `%appdata%` for Windows, and `XDG_CONFIG_HOME` for Linuxy. Macs have either have nothing, or a recommended directory specified in the Apple guides, I forget. But these are all OS-specified locations for where configuration information *should* go.

**Comment by hdgarrood** [comment]
> out of the box experience *is* the user's experience

Not really; you learn quickly that `psci` is meant to be run inside an existing project, and do that from then on, and then it's fine. I think it's a good thing that everything in purescript-land works locally. If we made `psci` work globally, then it would make sense for `psc` to work globally, too: i.e. for there to be a global purescript package database, and, well, there be dragons...

> As for configuration, there *are* standards ...

I'm on Ubuntu and `XDG_CONFIG_HOME` is not defined. Also, I have more stuff that I care about directly in `~` than I do in `~/.config`: git, bash, screen, vim, python, npm...

This is my point, really; there are "standards", but so few existing applications follow them, that they're pretty much worthless.

**Comment by hdgarrood** [comment]
Ah, apparently if `XDG_CONFIG_HOME` is not defined, then `~/.config` should be used. Still, we shouldn't be asking people to read the XDG Base Directory Specification to find where to put their `.psci` file, I think.

Does anyone even have a global `.psci` file? I can't imagine a use for them. My global `.ghci` fiddles with the prompt and enables some extensions, but `psci` doesn't have these things.

**Comment by chrisdotcode** [comment]
I definitely agree with small and local being king - but I feel the exception of a global REPL (and a local REPL that works when your project doesn't build) would be worth the trade-off.

> My global .ghci fiddles with the prompt and enables some extensions, but psci doesn't have these things.

Right, the global `.psci` would be used to just import Prelude and Control.Monad.Eff.Console for the global REPL to work.

**Comment by hdgarrood** [comment]
I definitely agree re making it work when something fails to compile &mdash; I already raised #1279 for that. That's a separate issue, though.

Let's suppose we start bundling a version of `purescript-console` with the compiler (this is the only way I can imagine we could get this to work, as I don't think we can assume `bower` is available). Suppose we're in a project directory, and we already have a bower.json, which depends on a future version of `purescript-prelude`. Suppose also that we forgot to `bower install`. In this case, I think it's best to error as soon as possible, rather than start using the bundled version of `purescript-console`. It might be very confusing when the user doesn't get the version of prelude they were expecting.

**Comment by chrisdotcode** [comment]
Right, but `psci` is different from building files with `psc`/`pulp build`. A REPL should be just that: a place to always test commands.

I think having your REPL unusable for it's primary purpose from first install isn't good. It's the same reason `ghci` had done work on removing `let` from the creating of new bindings.

**Comment by hdgarrood** [comment]
> Right, but psci is different from building files with psc/pulp build. A REPL should be just that: a place to always test commands.

I don't understand what you're getting at. Do you think, in the case I outlined, `psci` should use global versions of `purescript-console`, `purescript-prelude`, etc, even if it's being run inside a project that uses different versions of them?

**Comment by chrisdotcode** [comment]
There should be a two-step hierarchy: 1. local project psci. 2. if not-exist, or fails to build, use global psci with (potentially) different versions of console and the prelude.

1, I highly doubt many major revisions will happen to either purescript-console or purescript-prelude such that a differing global version will be all that different, and two, a slightly-out-of-date, or a slightly-ahead version of either of the two is better than no REPL at all when your project won't build, or when you're first getting your feet wet, or when you just need to test something quickly without a project at all.

**Comment by hdgarrood** [comment]
My impression is that the reason everything is still <1.0 is that we don't want to rule out major changes. I recently suggested getting rid of the `Show` type class, for instance. There's also a plan to rearrange things a lot fairly soon, I think, so that eg `Functor` will be defined in `Data.Functor`, and then re-exported from `Prelude`.

It should probably be noted that most of the time, in an existing project, any build failures will be a result of errors in your own code. So there's no reason to bundle special versions of `console` or `prelude` for this case. We should just load what we can and continue; if we do this, `prelude` and `console` will almost certainly be available anyway.

I disagree that a slightly out-of-date or slightly newer version is better than no REPL at all. I'd much rather it fail immediately and loudly, so that I can fix my project. I want things to work exactly as they would within my project. Doing anything else carries a large risk of taking hours of people's time as they try to understand weird behaviour, I think.

If you just want to test something quickly, for all but the most basic cases, you'll need extra libraries. I very regularly create a new directory and run `pulp init; bower install x y z; pulp psci` for this exact purpose. I don't think there's anything wrong with this workflow. So I don't think bundling `console` and `prelude` would even help very much in that situation, either.

**Comment by chrisdotcode** [comment]
The problem with the workflow is that it's time-consuming; not to mention cases in which access to the internet isn't available; requiring the internet to installing libraries to run the REPL you already have installed sounds more than a little odd to me.

As for "slight version differences", how about a big loud, "WARNING: YOUR CURRENT PROJECT AND GLOBAL VERSION REPL DIFFER" - or something to that effect?

**Comment by hdgarrood** [comment]
Merry Christmas!

If you're already in flow, surely that would mean that you're already working within a project that depends on those libraries, so fixing #1279 would be sufficient to allow you to test stuff?

Not having internet isn't a problem because bower caches everything. If you've ever installed a particular version of a particular package, you can `bower install` again even it without internet access by using the `--offline` flag.

Re your suggested warning, I don't think we can reliably detect that situation without building in a bunch of extra assumptions about how purescript projects are usually structured into psci itself. We'd have to start looking inside bower.json and bower_components and stuff.

**Comment by joneshf** [comment]
> This is my point, really; there are "standards", but so few existing applications follow them, that they're pretty much worthless.

Chicken and egg. If nobody follows a standard, how will it ever get used? FWIW, we used to follow that standard, until it started breaking for random people and became too much time to maintain.

Also, a random data point:

```
➜  ~  ls ~/.config | wc -l
60
```
So, some people care.
```
➜  ~  ls -d ~/.* | wc -l                            
200
```
But, obviously not enough :).

I tend to agree with @chrisdotcode though. ps makes it pretty complex to use the repl nowadays. Couldn't the act of choosing a prelude or console or whatever be the exception, and not the rule?

**Comment by hdgarrood** [comment]
Just in case I haven't made my position clear enough: I agree that the current situation is undesirable, and I would also like to see it solved. However, I think @chrisdotcode's suggestion would cause worse problems. I just don't (yet) see a way of solving it that doesn't introduce more/worse problems.

**Comment by paf31** [comment]
Moved to Discussion, since I also think this needs a resolution, but I also don't know what it should be.

**Comment by chrisdotcode** [comment]
Okay, so these are the issues that need to be solved:

- Good out of box experience (firing up a REPL in any location should work instantly, the first time, without question). Futhermore, the user should be able to do "common actions" (i.e. add two numbers (it's kind of silly that a new user can't even do this immediately in our current state)) immediately.
- User package consistency. If a user is using certain versions of a package in their package, the REPL should packages installed locally. (What happens when a user requires a package that is installed globally, but not locally? Does the REPL fail to import, or does it import that global module?)
- The REPL should not depend on project build status to work. That would defeat the point of a testing environment entirely (If you broke something trying to build something new, you should be able to use the REPL to graft out the rest of your functionality, not have it unavailable).
- Use a configuration directory for global configuration (if any). A standard exists: if we decide to have global config files, let's use said standard.

My solution is to use a global config directory like Haskell (but store it in `$CONFIGHOME`, not `~`), and put a Prelude export in that global config. If you are in a project dir, `psci` would *attempt* to load the modules in the project, but if it can't/if it doesn't build, it only loads the local modules it can, and imports the Prelude still.

**Comment by hdgarrood** [comment]
I don't understand your second point, could you explain that a bit more?

We are all agreed that psci should load what it can if there are compile errors in some of the modules. That's a separate issue, though. Can we please keep it out of this discussion?

**Comment by paf31** [comment]
Sorry but I don't want a global package database.

**Comment by hdgarrood** [comment]
Yeah, agreed. It really complicates things, I think. Cabal's global package database has caused so many headaches for Haskell users.

**Comment by chrisdotcode** [comment]
Revisions:

1. Good out of box experience (firing up a REPL in any location should work instantly, the first time, without question). Futhermore, the user should be able to do "common actions" (i.e. add two numbers (it's kind of silly that a new user can't even do this immediately in our current state)) immediately. We're against a global package database, but as @joneshf said, `purescript-console` and the prelude should be exceptions (in some way, shape or form, not necessarily even that they have to be global modules) such that `psci` always works.
2. User package consistency. If `purescript-console` and the prelude are exceptions to the "no global module rule", local modules would use a local version of both (falling back to global versions of both, if *those* modules fail to build in a package?)

**Comment by adamw** [comment]
I found this issue trying to achieve something a bit different with `psci`, but I think related. I have a project which is built using webpack instead of pulp (as it's mixed JS/Purescript, or rather, it *will* be :) ). How can I start psci then, so that all the installed bower modules & my sources are visible?

The only thing that I found on wiki & got pointed to at IRC is the `.psci` file, where I can load individual files. But I don't think I can include a whole directory as a search path. So maybe that's another thing to consider.

**Comment by adamw** [comment]
As to the "good out of the box experience", when starting plain `psci` and trying to reference a field of a record I get the error:

```
> let x = {y: 10}
> x.y
Error found:
in module $PSCI.Support
at  line 3, column 1 - line 4, column 1

  Unknown module Prelude
```

In my case, having the above mentioned search path would solve the problem (`Prelude` is in its usual place in `bower_components`), but probably having this work "anywhere" would be good as well. Or just checking at startup if prelude is available

**Comment by hdgarrood** [comment]
@adamw, using psci with webpack is not related to this issue. Perhaps ask on the purs-loader repo? I'm not quite sure how you would generate a .psci file with the webpack stuff.

**Comment by adamw** [comment]
@hdgarrood yes, what I hoped for is that I could use `psci` without a build tool and it would "just work" :) Or at least, provide it some basic configuration (like `PSCI_PATH=project/bower_components:project/src`) or in the `.psci` file.

However, I discovered that I can just run `pulp psci` even though I'm not using `pulp` for builds (and I never did `pulp init`), and it fires up `psci` with the correct setup.

**Comment by paf31** [comment]
Merge with #1279?

**Comment by hdgarrood** [comment]
Yeah, I think I we can close this as a duplicate. I'd add although we don't want a global package database, I'd still be interested to hear alternative proposals about improving the out-of-the-box experience for psci here.
