### ISSUE TITLE
Core library changes needed before 1.0

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1762]
Let's list some of the issues we're aware of in the core libraries, which should be fixed before they collectively get bumped to version 1.0.

I'm not worried about compiler compatibility or feature additions here, just "bugs" in the core abstractions.

- `Enum`/`Finite` (https://github.com/purescript/purescript-enums/issues/10)
- `MonadPlus`/`MonadZero`/`MonadOr` (https://github.com/purescript/purescript-control/issues/24)
- Remove `Arrow` (https://github.com/purescript/purescript-arrows/issues/9)
- `Inject` overlaps (https://github.com/purescript/purescript-inject/issues/2)
- Merge breaking PRs in `strings` etc.

Are there any more?

**Comment by hdgarrood** [comment]
What about feature removals? eg, #1675

**Comment by hdgarrood** [comment]
We should probably do something about https://github.com/purescript/purescript-maps/pull/45 too

**Comment by garyb** [comment]
I've been thinking about `BooleanAlgebra` again recently. I think perhaps we threw away too much stuff when we dropped the `Lattice` hierarchy, as the class we've ended up with is pretty much only useful for unit, booleans, or two-valued types that behave exactly the same as booleans... I wanted to make an instance for `Ordering` as a Kleene logic, which would give the ability to use `not` for reversing orders in comparisons, but this violates the "complemented" law we have for `BooleanAlgebra`. I think I'd need to define a bounded complemented non-distributive lattice for this to avoid breaking any rules (a boolean algebra and bounded complemented distributive lattice are the same thing).

I'm not really suggesting we bring back `Lattice`, `BoundedLattice`, `ComplementedLattice`, `DistributiveLattice` (apart from anything that would reintroduce the issue that `Lattice` should be a `Poset` not `Ord`) but thought since we're talking about libraries again it might be worth mentioning to see if anyone has any thoughts, as it seems not quite right to have classes that only have one useful instance...

**Comment by hdgarrood** [comment]
Could we also have the following `BooleanAlgebra` instances?

* `BooleanAlgebra a, BooleanAlgebra b => BooleanAlgebra (Tuple a b)`
* Any unsigned integral type with a fixed number of bits, where `conj` = bitwise and, `disj` = bitwise or, `not` = flip all the bits?

Admittedly there still aren't that many. And afaik we don't even have any unsigned integral types (yet).

Might it be feasible to trial any potential replacement as a separate library first? That might make things simpler.

**Comment by paf31** [comment]
I think a separate trial library for lattices and posets might be nice.

Also, `f b` is a Boolean algebra for any `Applicative f, BooleanAlgebra b`, isn't it?

**Comment by hdgarrood** [comment]
You'd need a `Bounded` instance first, and it's not obvious how to do that for lots of Applicatives, I don't think.

**Comment by paf31** [comment]
Ah ok. Still a few interesting examples whenever `f a` is `Bounded` though (`Maybe`, `a ->` for finite `a`, etc.)

**Comment by hdgarrood** [comment]
Also:

* `lists`: renaming `toList` & `fromList` to `fromFoldable` & `toUnfoldable` respectively: https://github.com/purescript/purescript-lists/issues/50

**Comment by garyb** [comment]
The above cases are good examples, I'm sure there are lots of functor-type-things like those examples that are `BooleanAlgebra` also, but they mostly are syntactic convenience in that they still need a `Boolean` at the bottom. Nothing wrong with that though, it definitely makes a better case for having the class than I could think of at the time.

I guess we can't really weaken any of the laws we have for boolean algebra, since to do what I wanted means giving up distributivity, but that's perhaps one of the most useful laws to rely on.

Even with the weaker lattice form(s) I'm not sure are a huge number of new and useful instances, so maybe this leads back to where we are, and anything weaker isn't worth pursuing as something that needs to happen in the Prelude at all anyway.

**Comment by Thimoteus** [comment]
I gave a shot at a lattice/poset library a while back, until I ran into the problem with `join :: a -> a -> a, meet :: a -> a -> a`  and parametricity (I think @hdgarrood brought it up in some issue a few months ago, too). I couldn't think of a suitable way to get around it.

**Comment by hdgarrood** [comment]
Also:
* `Data.Array.{take,drop}` do not follow Haskell semantics: https://github.com/purescript/purescript-arrays/issues/25

**Comment by garyb** [comment]
Perhaps we should deprecate `purescript-coproducts` and move `Coproduct` into `purescript-functors`?

Perhaps `Yoneda` and `Coyoneda` would probably fit better there too?

**Comment by paf31** [comment]
I'm not sure. It sounds like a fine option, but there are lots of functors which we could throw in there. Or we could just rename it to `functor-products` and `functor-coproducts`, for example, and keep things fine-grained.

**Comment by garyb** [comment]
Yeah, I guess it's the "functors" name that I find odd with its current contents. As you say, `Invariant`, `Contravariant`, etc. could also go in there in theory.

I'd suggest not renaming them though, and instead duplicating with the new name. Otherwise we'll end up with something like the `profunctor` vs `profunctors` situation we had a while back.

**Comment by paf31** [comment]
This can be closed now, correct?

**Comment by hdgarrood** [comment]
Yes, I think so.
