### ISSUE TITLE
Rename Prim.Object to Prim.Record

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#1768]
I think `Object` is a confusing name because its not what we use anywhere in our literature, and its ultimately the JS nomenclature leaking through. It's obviously a breaking change, but it would be nice to say "the record syntax { ... } is just sugar for `Record ( ... )`".

**Comment by SimonRichardson** [comment]
:+1: from me, this has always been confusing.

**Comment by michaelficarra** [comment]
:+1: I like it.

**Comment by paf31** [comment]
I think this makes sense, but we should do it as part of a breaking release. Move to 0.9?

**Comment by garyb** [comment]
:+1:

**Comment by LiamGoodacre** [comment]
:+1:

**Comment by zudov** [comment]
I am not sure if that would actually work, but how about we introduce it in a non-breaking way:

```haskell
foreign import data Record :: # * -> *
type Object = Record
```

And then in 0.9 we can remove `type Object = Record`

For almost any other type this would be a breaking change for following reasons:

1. Type synonyms can't appear in instance heads.
2. IIRC, there are some differences between imports of type synonyms and imports of data types.

However in this case neither of those two problems apply, (1) doesn't apply because you are not allowed to have an `Object` in an instance head, (2) doesn't apply because `Prim` is implicitly imported.

However the error messages would change since type synonyms get fully expanded in there, but I don't think this can be considered as a breaking change.

I won't be surprised if I missed something, so please correct me.

**Comment by LiamGoodacre** [comment]
@zudov you can have `Object` in an instance head:

~~~purescript
class Foo t
instance fooObject :: Foo (Object e)
~~~

**Comment by garyb** [comment]
Maybe we should do this for 0.9, since we're breaking stuff?

**Comment by kRITZCREEK** [comment]
ping I think this would be nice for 0.9

**Comment by paf31** [comment]
Agreed, I've moved this over.
