### ISSUE TITLE
Use newline instead of comma

### ISSUE THREAD

**Issue by user471** [purescript/purescript#1775]
F# has this nice syntax feature. 
>When each label is on a separate line, the semicolon is optional.

So, you can do this with records and lists
```
type Test = {foo : Int; bar : String}
type Test = { 
    foo : Int
    bar : String
}
let list = [
    "Foo"
    "Bar"
]
```
Could Purescript have this?
Or at least could last comma be optional in records?
```
type Test = { 
    foo :: Int,
    bar :: String,
}
```

**Comment by hdgarrood** [comment]
If you use the following style, I think it solves the same problem that this syntax feature would: diffs are clearer, and you (mostly) don't need to modify more than one line at a time.

```
type Test =
  { foo :: Int
  , bar :: String
  }

let list = [ "Foo"
           , "Bar"
           ]
```

**Comment by user471** [comment]
Personally I don't like commas before names, it's too noisy.

**Comment by zudov** [comment]
I don't think you can simply start treating the newline as a comma. E.g. how would you parse:

```haskell
foo = [ \x -> x
        \y -> y
      ]
```
as: `[ \x -> x \y -> y ]` or as `[\x -> x, \y -> y]`.

There are many ways in which these ambiguities could be resolved (by introducing even more syntactic nuances), but I think it would create more problems that it would solve.

**Comment by user471** [comment]
>as: [ \x -> x \y -> y ] or as [\x -> x, \y -> y].

```\x -> x, \y -> y```
I don't think 
```
\x -> x
\y -> y
```
is good formating for  ```\x -> x \y -> y```
An intent should be used.
```
foo = [ \x -> x 
            \y -> y ]
```

**Comment by garyb** [comment]
@zudov I could be wrong but I think indentation would save that case, as I'm pretty sure the `\y -> ...` would have to be indented past `\x -> ...` for it to be interpreted as a single expression.

I have no strong feelings about this. If it's possible to do unambiguously it might be nice (I don't want to be using another Coffeescript), but I'm also totally fine with prefix commas.

**Comment by natefaubion** [comment]
I think the only syntactic nuance you need is the same one we use to desugar do-blocks without using semicolons. I'm with @garyb though, as I don't find the commas much of a burden.

**Comment by natefaubion** [comment]
One area where this would be really nice is in HTML DSLs like Halogen.

**Comment by user471** [comment]
>do-blocks without using semicolons

Do block is good example. If you can use it without semicolons, why not use the similar approach in other places.

>One area where this would be really nice is in HTML DSLs like Halogen.

WebSharper uses similar DSL, and it looks nicer without commas

```
let myList =
    UL [
        LI [Text "First item"]
        LI [Text "Second item"]
    ]
```

**Comment by zudov** [comment]
@user471 @garyb A bit of misunderstanding here. I made an example assuming a
syntax which only is "treating the newline as a comma", if we also consider
indentation that ambiguity can be resolved. I didn't really realize that the
indentation-sensitive syntax was implied in the post.

I initially was sceptical but when I think more, I realize that it can be really
nice.

I'll try to outline how I see these parsing rules just to make sure that we are on the same page.

I think that it would be best if the rules were restrictive, allowing to use
only the clearly defined and simple syntax. I also think that it should require
to follow the common style which @hdgarrood demonstrated. In the essence the
rules say: "If you write you arrays/records like @hdgarrood, you are allowed to
omit the commas, otherwise please separate your elements explicitly using commas".

It shouldn't be possible to mix the newline-separators and comma-separators in a
single array/record like that:

    [ 1, 2, 3
      4, 5, 6
    ]

*{-# I'll further refer to "array/record" as "enumeration" #-}*

We would have comma-separated-enumeration (we already have them) and
newline-separated-enumeration.

Every element in newline-separated-enumeration should be indented from the
indentation-line (explained below) by exactly the same amount of spaces.

An imaginary indentation-line starts at the opening bracket and stretches
vertically to a closing bracket (brackets have to be on the same vertical line):

    |
    |
    [ 1
    | 2
    ]
    |
    |

we could also allow to put the closing bracket on the same line as the
expression (only using the opening bracket to find indentation-line):

    |
    |
    [ 1
    | 2 ]
    | 
    |

Additionally, we could require that all the parts of expressions are
indented further than indentation-line, so something like that is a parse error:

        [ 1
     2
        ]


Such rules would have minimal effect on existing code. Only the single-element arrays
are affected and they would be broken only in cases like:

    -- Three element array instead of (foo bar baz)
    [ onClick (\event -> somehow
      process $ that event
    ]

and if we employ the additional rule such monstrosity would also get broken:

            [ onClick (\event -> somehow
     process $ that event
            ]


Any additions?

**Comment by paf31** [comment]
Can't we use rebindable do notation for this?

```purescript
myList = ul do
  li [Text "First item"]
  li [Text "Second item"]
  []
  where bind x f = x : f unit
```

**Comment by paf31** [comment]
:-1: from me, this definitely needs changes to the current indentation rules.

**Comment by zudov** [comment]
@natefaubion @user471 That's what made me realize how useful that is.

Many haskellish HTML DSLs (purescript-smolder, blaze-html, lucid) are abusing do-notation mostly to just get a nicer syntax for their `<>`, while it's enough to just drop the commas.

**Comment by garyb** [comment]
@paf31 good point, I've used rebindable `do` for exactly this now you mention it.

**Comment by zudov** [comment]
Wait since `bind` and friends are just taken from the normal scope we have `RebindableSyntax`, whaaa. Never realized that.

**Comment by zudov** [comment]
@paf31 It would work syntactically and it's actually much broader and even nicer solution. You can use it for other things and overall it looks like a concise syntax. But unless we optimize it (super-compilation?) it has a disadvantage of cluttered js-output and maybe some performance implications.

**Comment by paf31** [comment]
Cluttered JS, definitely, but for performance, we could use a difference list or something using ST, perhaps.

And yes, you can do a few things with the rebindable syntax. I have a couple of examples in `examples/passing/RebindableDoNotation.purs`.

**Comment by user471** [comment]
Is it just overkill to use do notation for removing commas?
And is it possible to remove this part?
```
  []
  where bind x f = x : f unit
```
Also, how do notation could help with things like records and module exports?

**Comment by user471** [comment]
Why is not possible to use rules from do notation in lists and records?

```
example :: Int -> Int
example = do
  \x -> x
  \y -> y
  where
  bind x f = x >>> f unit
```

**Comment by natefaubion** [comment]
I personally don't really care for rebindable syntax as is because it applies over the entire scope, when what you usually want is for it to apply for a specific block. This makes it impractical to interleave different binds.

Somewhat half-baked, but it would be nice if you could overload a specific block, potentially with functions of different shapes. Like in the Array/DOM DSL case, it would be cool if you could provide a function that unifies with `[a] -> b` and have it disallow the `<-` syntax at compile time, and give you an efficient block-like DSL.

```purescript
-- `@some_identifier` starts an overloaded block
-- Using `id` to just give you the array back
foo :: Array Int
foo = @id
  1
  2
  3

-- But you could use something like `fold` for a monoid
bar :: Component
bar = @fold
  H.span_ "foo"
  H.div_ @fold
    H.foo 42
```

When I say different shapes, by providing something that matches the shape of `bind`, you then opt in to the variable binding syntax.

**Comment by user471** [comment]
>but it would be nice if you could overload a specific block, potentially with functions of different shapes

What benefits would it have over array syntax?
In this cases you can just create arrays 
```
foo = [
  1
  2
  3
]
bar = [
  H.span_ "foo"
  H.div_ [
    H.foo 42
  ]
]
```
And after that you can do with them anything you want.

**Comment by natefaubion** [comment]
Yeah, it's primarily me expressing a desire to have other ways of hooking into DSL syntax other than shadowing `bind`, especially for things where `bind` is "too big". Because we use rebindable syntax, there's no real connection between the `Bind` typeclass and the syntax sugar.

**Comment by user471** [comment]
>Yeah, it's primarily me expressing a desire to have other ways of hooking into DSL syntax other than shadowing bind, especially for things where bind is "too big"
Then PureScript would have some sort of syntax marcos. I believe right now do notation is defined in compiler code. If it would be possible to define it in PureScript, than everyone could create similar operator for their needs.

**Comment by AppShipIt** [comment]
I want to add my support for this. Not for DSLs but because 1) punctuation preceding elements contradicts grammatical intuition, 2) it's a “smell” coming from other (non-ML) language conventions (from my perspective writing curriculum), 3) regardless whether you liked CoffeeScript (I quite respect it) commas contradict intuition about whitespace sensitivity, 4) the newline proposal is proven in F#. I don't think @paf31 would feel comfortable with such a syntactic change without a new parser but I'd like to see it someday.

**Comment by ivan-kleshnin** [comment]
Relevant discussion in Elm
https://github.com/elm-lang/elm-plans/issues/2

**Significant whitespace criticism:**
> It is personally unpopular among a significant portion of Elm users. Sample comments: 1, 2, 3, 4, 5
> It is a breaking change that would take considerably more effort to implement, whereas this is a very minor compiler change that is entirely backwards-compatible.
> It requires additional breaking changes to function application in order to prevent parsing ambiguities.

**Interspersed leading comma criticism:**

Compared to the proposed Consistent Ending Commas styles, the Interspersed Leading Commas style has these drawbacks:

> It is harder to scan. Instead of your eye being able to jump to the first letter on the line, it must jump to the comma (or brace) and then parse past it.
> Any change that involves the first position (e.g. adding something at the top, or reordering it) is more time-consuming in a text editor because it has a different leading character than the other lines. This is an especially noticeable pain point when using multiline lists in elm-html DSLs, as much of building web app interfaces involves rearranging elements.
> It is unfamiliar to most programmers. 

I'm especially interested what do you guys think about the latter?

**Comment by zudov** [comment]
> it must jump to the comma (or brace) and then parse past it

For me, that's one of the most important advantages for leading commas. I first see the comma, I realize that it's a new element of the list and what follows is parsed as a next list element.

**Comment by garyb** [comment]
> It is harder to scan. Instead of your eye being able to jump to the first letter on the line, it must jump to the comma (or brace) and then parse past it.

I don't even notice the commas when things are formatted this way, so although I can't argue with someone else's experience, it's not one that I share. I find the "gutter" that `[`, `,` and `]` form is helpful in fact, as it makes it easier to see where the list is closed.

> Any change that involves the first position (e.g. adding something at the top, or reordering it) is more time-consuming in a text editor because it has a different leading character than the other lines. This is an especially noticeable pain point when using multiline lists in elm-html DSLs, as much of building web app interfaces involves rearranging elements.

Text manipulation/input has never been the bottleneck for me when it comes to time spent writing code (and I'm not a especially fast typer or anything). I think it's pretty easy to adjust prefixed text as well: I tend to rearrange the lines as needed, correct the first line, and then column-select and edit the remainder back to `,`. It probably takes 2 seconds tops.

> It is unfamiliar to most programmers.

Until they read it the first time, and then it's obvious what's going on :laughing:. I think there are other things in the language that are unfamiliar more so than a comma/indentation style. 

Although I'm arguing all against the points here, I'm not particularly for or against this change, I just don't care either way. It's an inoffensive change to syntax and not too magical, so I don't really see any downside apart from parse complexity, but I'll also probably not use it, and still insert leading commas manually out of habit even if we do implement it.

**Comment by ivan-kleshnin** [comment]
@zudov, @garyb thanks for sharing your experience!

**Comment by AppShipIt** [comment]
@ivan-kleshnin That proposal arose because Elm's designer felt strongly opposed to newlines. @garyb Each response (don't notice, not hard to change, only ugly once) sounds like necessarily evil Haskell-isms (like the operator sections you guys improved upon). If it were curly braces or semicolons it'd be called noise rather than defended. It was one of the strengths of CoffeeScript and looks beautiful in F# (n.b. `[]`/`{}` remain in the gutter) which leads me to suspect it can be unambiguous. Regardless whether it's hard to change it's certainly perturbing when I want to quickly jump to a line, shortcut move it,  and jump back (although arguably a tooling issue). Most of all the first time perception has as much to do with linguistic grammar as it does other code languages. The only features I'd like more (for aesthetics and evangelism) are improving error messages (working on a proposal myself) and API exposing types at every expression level (kinda like how source maps works) for tool integration. Optional commas just tastes like EcmaScript 💩

**Comment by phadej** [comment]
I wouldn't **ever** mention CoffeeScriot as an example of good and/or unambiguous syntax design. I'm sorry if I hurt someones feelings.

**Comment by paf31** [comment]
Big :-1: from me. I'd put this in the "DIY" category - if you want to implement it yourself, we can try it out, and see how it affects readability, parser errors and tooling, and then make an informed decision.

**Comment by AppShipIt** [comment]
Which was precisely Elm's designer's argument and one I strongly disagree with. It's a functional layer on top of JavaScript and very effective at it. It was likewise used very effectively as a replacement for JavaScript. It never aspired to be in league with Haskell but that doesn't make it inherently bad. It shares whitespace rules for arrays and records roughly with F# which I consider as respectable as Haskell as well as YAML for its readability as opposed to JSON. By comparison I've also written Python professionally and would pick CoffeeScript hands down by any measure except libraries. I just don't want to approach language decisions (likewise in my response to source maps) form an elitist standpoint or one isolated from the community PureScript is embedded in.

**Comment by paf31** [comment]
I'd be happier to see this implemented alongside curly braces and semicolons, since then a slight variant of the current records would just be a special case of that.

**Comment by garyb** [comment]
I'm afraid any argument that holds up CoffeeScript as a good example isn't going to go down too well with me, it's grammar is riddled with amiguities, and is one of the major reasons why I stopped using it after the second project I put into production with it.

**Comment by AppShipIt** [comment]
Aforementioned F#.

**Comment by AppShipIt** [comment]
Proposing `backlog` until someone (or myself) wants to champion implementation. F# is markedly more consistent than Haskell by unifying record and array parsing with every other construct (e.g. `let`) by universally interpreting newline as semantically equivalent to semicolon (as opposed to comma):

> When a token occurs directly on the offside line of a _SeqBlock_ on the second or subsequent lines of the block, the `$sep` token is inserted. This token plays the same role as `;` in the grammar rules.

For future reference:
* [The F# 3.0 Language Specification](http://fsharp.org/specs/language-spec/3.0/FSharpSpec-3.0-final.pdf)
* [F# examples](https://github.com/dungpa/fantomas/blob/master/docs/FormattingConventions.md#records)
* [F# record doc](https://msdn.microsoft.com/en-us/library/dd233184.aspx)
* [F# array doc](https://msdn.microsoft.com/en-us/library/dd233214.aspx)

**Comment by paf31** [comment]
`Backlog` means "we know we want to do this, but we haven't prioritized it".

`Ideas` means "someone wants to do this, we haven't been convinced it's a good idea yet".

Which is why I propose a new label `DIY` meaning "do it yourself, to collect evidence that it's worthwhile and won't introduce new issues". There have been a lot of proposals lately which I would put into that bucket.

**Comment by AppShipIt** [comment]
👍

**Comment by paf31** [comment]
Actually, I'm happy for anything in `Ideas` to be treated as `DIY`. It should be understood that we make no guarantee that such things will get merged though.

**Comment by AppShipIt** [comment]
True of any PR!

**Comment by garyb** [comment]
It's good to know there is at least one example of it being non-ambiguously-parseable, I assumed it probably was in F#, but it's been years since I dabbled with it so wasn't sure.

**Comment by garyb** [comment]
@AppShipIt I found your argument that it's like curly braces/semicolons but we're just more used to it a good one too, although I'm still not quite motivated enough to work on it myself :smile:

**Comment by AppShipIt** [comment]
I'm going to take a stab at in a couple weeks. It'll scratch a long time itch and provide an opportunity to poke around the parser. No hard feelings if it doesn't work out ✌️

**Comment by adius** [comment]
I think the comma first style of PureScript / Haskell / ... is awful.
Easily the worst thing of the whole language.
I brought it up for Dhall (https://github.com/dhall-lang/dhall-lang/issues/66).
It be really cool if you could read through the discussion and also reconsider it for PureScript!

**Comment by kRITZCREEK** [comment]
If a minor syntactic preference that isn't hindered/enforced by the compiler in any way is the "worst thing of the whole language" it seems we're doing a pretty good job.

On a side note, I've read through the thread on dhall-lang and there is no need to be rude and call people's projects "awful" or "sickening", so please tone it down a bit on this issue tracker.

**Comment by AlexMouton** [comment]
Hi adrian
Im new to PS myself so this isnt the opinion of any team but could you “give it five minutes” (https://signalvnoise.com/posts/3124-give-it-five-minutes)?

Theres lots to get to know here, and fighting syntax is only going to make it harder for you, in my opinion.

For other questions or griefing (i have one my share!) im on the purescript-beginners slack channel and id be happy to help you work out anything else you come up with!

Alex

**Comment by hdgarrood** [comment]
Thanks for this, Christoph; seconded.

**Comment by adius** [comment]
> seems we're doing a pretty good job

Haskell & PureScript are great, no question. And that's what makes me so distressed.
Of all language communities you guys should be the ones seeing reason :wink:.
If you can't get it right, who else should?

> people's projects "awful" or "sickening"

I called nobodies projects any of that. I said separator style listings are an awful design choice and I stand to that. I think the long list of cons in the other thread should confirms this.

> could you “give it five minutes”

I have been pondering over this many months already. I've also started to design my own programming & config languages. This was however before I really got into Haskell, and it's so close to perfect, otherwise I wouldn't even bother to discuss. Even JavaScript gets things like trailing commas right (even in function calls). Why can't we?

**Comment by adius** [comment]
@AlexMouton Oh cool, there is a slack? I'm always on the Gitter thread. Where can I find it? Do I need an invitation or something?

**Comment by Pauan** [comment]
@adius Some other functionalish languages which you might want to look into are F# and Rust. They don't have this syntax problem (though obviously they have *other* issues and limitations).

Also, both [Rust](https://github.com/koute/stdweb) and [F#](http://fable.io/) can compile to JavaScript. Rust in particular is *extremely* fast, because it compiles to WebAssembly, it doesn't have any overhead from a garbage collector, most things are stack allocated, and it heavily avoids boxing.

I have used PureScript, Rust, and F#. They all work well. I consider Rust and F# good alternatives to PureScript (they aren't as abstract as PureScript though).

**Comment by adius** [comment]
- Rust has this implicit return without a semicolon, which sounds really, really dangerous and awful.
- F# is multi-paradigm which sounds pretty dangerous as well (nowadays I can't think of many good reasons to code object oriented).
Granted I haven't used them yet, so maybe it's half bad...

Like I said I consider Haskell and PureScript pretty close to perfect.
If there was a Haskell 2 where the https://wiki.haskell.org/Nitpicks and https://wiki.haskell.org/Syntactic_sugar/Cons would be fixed (and if there was finally a trailing comma :wink:), I'd be extremely happy.

What I'd rather want to try out is to build some kind of graphical editor where the final syntax of the language doesn't matter anymore. I think Haskell would be extremely well suited for this.
Point in case: http://stefanj.me/funblocks/ - Only beginner level Haskell, but a start nonetheless

**Comment by Pauan** [comment]
@adius I don't want to derail this thread too much, but I'm happy to continue this conversation via e-mail (it's in my GitHub profile).

As my final comment here, you might also be interested in [Unison](http://unisonweb.org/), which implements some of the ideas that you want.
