### ISSUE TITLE
Add psc-ide-server as an executable

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1813]
After discussion with @kRITZCREEK on IRC:

`psc-ide` is the de-facto editor backend, and it needs to be kept in sync with the compiler code. It also makes sense to distribute it with the compiler so that the executable is available on the user's PATH.

**Comment by kRITZCREEK** [comment]
I've recently moved more and more of my code to use types and functions from the compiler library which makes versioning of `psc-ide` hard because it depends on the compiler. So having `psc-ide` versioned together with the compiler would improve my distribution story.
I'd also reach more users and get more feedback for the project, which would of course also help me.
 
The current `psc-ide` "architecture" contains a library and two executables:

The `psc-ide-server` executable is a TCP server that accepts commands as json and runs the accepted commands through the library code.

The `psc-ide` executable is a very shallow client that talks to `psc-ide-server`. It accepts json on stdin, passes it to the server and outputs the response to stdout.

I've recently written a [PureScript client](https://github.com/kRITZCREEK/purescript-psc-ide) that bypasses the `psc-ide` executable and so I think the Haskell client executable shouldn't be bundled as it's easier to just connect to the server via TCP.

**Comment by kRITZCREEK** [comment]
If this were to happen for 0.8.0, what changes would I need to make to psc-ide? I've got branches that compile and work with the current purescript master... For the "operational" part of splitting out psc-ide-server from the project I might need some help as my cabal knowledge is very limited.

**Comment by paf31** [comment]
> If this were to happen for 0.8.0, what changes would I need to make to psc-ide?

Do you want to try to get this done in 0.8.1? If so, why don't you open an initial PR, and we can take a look at the code there.

**Comment by kRITZCREEK** [comment]
I'll see how much time I have this week and what I can put together.
