### ISSUE TITLE
Allow using (- 1) for operator section?

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1846]
I would like to be able to use `(- 1)` as an operator section that subtracts one. Currently it is parsed as `negate 1`. I still want to be able to negate things with a prefix `-` operator. I think both could be allowed by using whitespace. If there is a space, use the `-` binary operator. If there's not a space, use `negate`. 

``` purescript
(-1)    -- negate 1
(- 1) x -- x - 1 -- (`sub` 1)
```

Obviously this behaves differently than all other operators. But I would prefer it to using `sub` as a makeshift section.

**Comment by rgrempel** [comment]
If you're looking for a function that will subtract 1 from an Int, then I think you're looking for:

```purescript
(flip (-)) 1
```

Because:

* To use any operator as if it were a function, you surround it with `()`
* Given the argument order for `-`, currying it will supply the number to be subtracted from, not the number to subtract. So, you'd need to flip it first.

Now, it's true that `-` is sometimes interpreted as `negate` ... i.e. as a unary operator. However, I don't think that's the issue behind what you're observing, since the syntax you're trying to use wouldn't work for  any operator. So, the reason it doesn't work is nothing special about `-`.

**Comment by tfausak** [comment]
The syntax I'm using works for other operators. It's called an [operator section](https://wiki.haskell.org/Section_of_an_infix_operator). For example:

``` purescript
(+ 1) 2
-- 3
```

I want to be able to use `-` in a (right) section like every other operator.

**Comment by rgrempel** [comment]
Ah, your right -- my apologies!

**Comment by hdgarrood** [comment]
Come to think of it, why do we have the rebindable syntax on unary negation? I'm not convinced of its usefulness, but I can imagine it causing lots of confusion ("unknown value negate" when you only use unary minuses, even if you never explicitly use `negate`, for example).

Could we define integer and number literals so that they can optionally start with `-`, in which case they get negated inside the compiler, i.e. not involving `negate` at all? Then treat any other occurrences of `-` the same as everything else while rebracketing? Disambiguating unary from binary `-` by using whitespace seems sensible to me too, although I am not particularly familiar with the parser.

We would lose the ability to negate any `Ring` instances other than `Int` and `Number` with unary minus if we ditched the rebindable syntax, but I don't think that's a huge loss. I think I'd rather use eg. `negate one :: forall a. (Ring a) => a` than `-one`.

**Comment by paf31** [comment]
@hdgarrood I think that's the right solution. If everyone agrees, I think we should throw this into 0.8 before this weekend's release.

**Comment by tfausak** [comment]
:+1: for making `-` not depend on `negate`. 

One thing to consider about making `-` sensitive to whitespace is expressions like this: `x-y`. I would expect that to mean `x - y`, not `x (-y)`.

**Comment by zudov** [comment]
@tfausak It probably won't hurt to disallow operators without spaces around, not sure how much code that would break though.

**Comment by garyb** [comment]
@hdgarrood @paf31 I think you're forgetting a common use-case there: the ability to negate non-literals like `-x`. I think it would be rather surprising if `-10 * y + z` worked but `-x * y + z` didn't...

**Comment by garyb** [comment]
Even if you still think it's worth it (I don't, personally) I'd be very much against making the change in 0.8: we should make it a warning for 0.9 like we have done with all the other breaking changes so far.

**Comment by hdgarrood** [comment]
@garyb Oh of course, that's a good point. And I guess we have to use the rebindable syntax approach if we want `-x * y + z` to work?

**Comment by garyb** [comment]
It doesn't necessarily need to take the rebindable syntax approach, but the alternative is to desugar it as a fully qualified reference to `Ring`'s `negate`, which I'm pretty sure is a worse behaviour :smile:

**Comment by hdgarrood** [comment]
Yeah, agreed. I still prefer `negate one` to `-one`, but at the same time I prefer `-x * y + z` to `(negate x) * y + z`. Perhaps this is because I'm used to unary minus in mathematics, where all variables have a single letter. :smile: 

In that case I'm in favour of @tfausak's original proposal.

**Comment by paf31** [comment]
Ah right. I really dislike it when whitespace changes a parse, so I would vote to deprecate unary minus in 0.8, and remove it completely before 0.9, since there is no way I can think of to unambiguously parse both operator sections and unary minus, modulo whitespace changes. The lexer will need to be changed to handle negative literals.

> I think it would be rather surprising if -10 * y + z worked but -x * y + z didn't...

Perhaps if you're coming from other languages, but I don't think this is a big issue. Given how symbols work generally in PureScript, it shouldn't be so surprising if a left hanging `-` is invalid syntax.

**Comment by tfausak** [comment]
Oh, I didn't think of `-x` when I responded earlier. I definitely want that to work. I think you'd run into that pretty quickly if you were trying to refactor an expression.

``` purescript
f y z = -10 * y + z
-- Maybe that 10 will change. Let's pull it out.
f x y z = -x * y + z
-- Parse error? Blergh.
```

**Comment by garyb** [comment]
It doesn't really change much, but just to be clear, currently the `-x` can appear in the middle of an expression too.

**Comment by hdgarrood** [comment]
I didn't realise deprecating unary minus was even an option - I think I'd really like that. :+1:

**Comment by LiamGoodacre** [comment]
:+1: for deprecating unary minus

**Comment by garyb** [comment]
I can see this will definitely be a source of confusion for people in the future if we do go ahead with it, and probably some annoyance, but if we're totally set on not doing the whitespace option (which seems more sensible to me) then I can't really argue with the reasoning.

**Comment by garyb** [comment]
Also, just to point out, deprecating the unary-minus-for-`negate` mapping wouldn't fix the issue that was originally raised here. `(- 1)` would still be the value `-1` rather than an operator section that subtracts 1.

**Comment by paf31** [comment]
It would solve that issue: the lexer would lex those two things differently.

**Comment by garyb** [comment]
The original issue was basically "`(- 1)` is not `(\x -> x - 1)`", and that's still the case without unary `negate` but with negative literals though, isn't it? Or if you're saying `(-1)` would be the negative literal and `(- 1)` would not, isn't that basically the same as accepting the whitespace fix?

**Comment by paf31** [comment]
Yes:

- `-1` is a negative literal, a single lexeme
- `(- 1)` is made up of four lexemes, and is a section of the _binary_ minus operator.
- `-x` fails to parse
- `(-x)` is a section

This way, whitespace continues to be handled in the lexer.

**Comment by garyb** [comment]
Ah, I was thinking more from a user's point of view, not the implementation of it. I'm not sure "it may be tricky to parse" is a great argument for not implementing something if the alternative increases overall confusion, which I think this will: surely the use of a subtraction operator section is less common than wanting to negate non-literals?

As you put it, the expectation that it will work is there "perhaps if you're coming from other languages", maybe it's just me, but that reads like "perhaps if you're using common sense" :laughing:, we're not talking about some js-vs-haskell expectation here, it's pretty pervasive.

**Comment by paf31** [comment]
How do we keep unary minus without letting whitespace creep into the parser though? I'd really rather that not happen.

**Comment by garyb** [comment]
Maybe we could introduce a `Minus Bool` token, the bool determined by peeking ahead one character to see whether whitespace is present.

**Comment by paf31** [comment]
I think we should be careful about making the jump from indentation-sensitive to whitespace-sensitive generally. I mean whitespace-sensitive in the sense where whitespace information leaks out of the lexer. There is value in having the parse be a function only of the lexemes and indentations amounts, I think.

**Comment by garyb** [comment]
Would it make a difference if we had two tokens: `Minus` and `Negate`? It can be purely determined in the lexer with no special casing required in the parser.

**Comment by paf31** [comment]
I guess that's no less magical than lots of stuff going on in GHC's lexer, and that might be the best solution. It pains me to add the whitespace sensitivity, but I suppose it is the most practical option.

**Comment by garyb** [comment]
Yeah, it just seems the least-bad option to me. My order of preference is:

1. Whitespace sensitive version
2. What we have now (it covers what I suspect is the more common use case, negation rather than subtract-section)
3. Negation only works for literals (would seem strange that `(-6)` and `(- 6)` are both handled but `(-x)` fails and `(- x)` does not)

**Comment by garyb** [comment]
For the record, what we have now is how it works with GHC, so maybe it's a little more magical :smile:

**Comment by LiamGoodacre** [comment]
Just to put it out there, changing section syntax from `(- 6)` to something like `(_ - 6)` could mean that `(- 6)`, `(-6)` are negative numbers, `(-x)`, `(- x)` are negation.

**Comment by paf31** [comment]
I like that idea a lot.

**Comment by hdgarrood** [comment]
What would `(+3)` mean if we changed the operator section syntax?

**Comment by LiamGoodacre** [comment]
@hdgarrood Parse error? With a suggestion of `Did you mean (_ + 3)`.

**Comment by paf31** [comment]
I figure it'd be handled in the lexer on literals, just like `-`.

**Comment by paf31** [comment]
@garyb Shall we just bump this and the other issue, figure them out in 0.8.1, and release today? Things are pretty stable, and 0.8 has been dragged out a little.

**Comment by garyb** [comment]
Yes please. Even with the `(_ - 1)` solution I expect we'll need to do a little tweaking to get everything right. I'm in favour, by the way; another nice property it has is makes the infix psuedo-flip trick much more obvious, as it'll be like:

``` purescript
what y = (_ `flipped` y)
```

**Comment by garyb** [comment]
I'd suggest we hold off releasing any of the v1 library updates until we get it resolved too, as that way we can ensure all the v1 libraries will be at least "0.9 safe".

**Comment by tfausak** [comment]
I think I like the idea of ditching operator sections for underscores. It mimics the existing use of underscores for accessing properties.

``` purescript
map (_.x)   [{ x: 1 }, { x: 2 }]
map (_ + 1) [1, 2]
```

**Comment by paf31** [comment]
I think if we implement this, we should make wildcards into a new data constructor for `Expr`, then remove them in all a single desugaring pass. This way, we can provide good errors in case they get misused, we can reduce some ambiguities in the parser, which should give better parse errors.

I'm happy to work on this this week, unless someone else wants to take it. 

I'm inclined to just remove the old syntax outright, since we're at a major release anyway.

**Comment by garyb** [comment]
I still think we should deprecate first; if we do remove it outright it means there's a good chance that `psc` 0.8 will be unable to compile much of what is out there currently (due to dependencies). It'd be a real shame to have a single breaking change in 0.8!

**Comment by hdgarrood** [comment]
One thing to consider: what does `{ x: _ * 2 }` mean? Presumably `{x: \y -> y * 2}`? And are we alright with it being a bit different to `{x: _}`?

**Comment by garyb** [comment]
That's an error I think, my understanding was the proposal is this for only to be valid in the same situation that it is for operator sections, which means it would have to be `{ x: (_ * 2) }`.

**Comment by LiamGoodacre** [comment]
Also should `(_ + _)` be valid?

**Comment by phadej** [comment]
@LiamGoodacre `(+)`

**Comment by LiamGoodacre** [comment]
@phadej I know, I mean should it be a parse error and suggest `(+)`, or should it mean the same thing?

**Comment by phadej** [comment]
I'd give my vote for parse error, without even trying too hard to recommend the fix (i.e. *multiple wildcards are forbidden* or so is good enough). Otherwise the snowball effect would have to support `(_ + _ * 1)`, followed by `(myfunction _ * _ + 3)` etc. That sounds cool, but practical value is quite low, as at that point it's good idea to give a name to the expression.

**Comment by phadej** [comment]
P.S. supporting `(-13)` as `negate 13` is bad idea. I'd rather drop support for unary operators; they are too confusing and not common enough to be worth the trouble.

**Comment by phadej** [comment]
i.e. I'd rather:
- drop unary `-`: `-10` 
-  make `(.prop)` syntax; not `(_.prop)`
- leave operator sections as is, i.e. `(+3)`, `(-3)` or `(1-)` would all mean that. With or without whitespace.

IMHO this is uniform and helps when one need to partially apply an operator.

E.g. in `slamdata/slamdata` I found [only single occurency of negative literal](https://github.com/slamdata/slamdata/blob/80c084a435eaab3147d375f858d416fb1018c156/src/View/Notebook/Cell/Viz.purs#L376).

**Comment by garyb** [comment]
@LiamGoodacre no, I don't think there's any benefit in parsing something like `(_ + _)`, since we're not going support scala-style underscore behaviours where they can be used all over the place - the behaviour of underscores should always be easy to understand and unambiguous (to a human), so that means only allowing them in restricted places.

@phadej use of underscores for sections is equally uniform, but far less "surprising" than having no unary negate IMO.

**Comment by phadej** [comment]
@garyb but unary negate is *very* special case. The problem I see, that user cannot define anything like that themselves. E.g. I might want to have unary prefix and postfix operators; but I cannot define ones.

Other direction is to do something like Agda, either all the way or just with operator characters:
```hs
(_!) :: Integer -> Integer
(_!) = factorial

(_|-_:_) :: Ctx -> Term -> Type
ctx |- term : ty = ...
```

**Comment by garyb** [comment]
Yeah, but it's such a common case that I think it warrants it. It may not be common in slamdata, but I mean in terms of "things that are the same in almost all programming languages". Even Scheme supports the use of `(- x)` as distinct from `(- x y)`! :wink:

There is an issue for mixfix too, #139, but I think that has its own set of issues.

**Comment by phadej** [comment]
@garyb, I'm not sure if negative literals are that common. They are just one thing which makes some people think they need to know math (i.e. arithmetics) to do programming. ;)

And scheme supports `(/ x)` too. How's about that. I'm half-serious here. In scheme you could define unary operators, if they are common to your problem domain. I don't feel that making *arithmetics* special is justified.

**Comment by garyb** [comment]
Good points, and unless you're doing something numeric we probably encourage the avoidance of the use of numbers as indexes are evil, etc. too.

I have other issues with `(.prop)` for sections though, as `(prop.)` would be meaningless, so it's not like a real section in that regard. We'd just be swapping one special case for another :wink: while also losing some existing functionality.

There are other benefits to using the `_` placeholder for sections too, as mentioned up there ^ somewhere I think:

``` purescript
what y = (_ `func` y)
```

Would be much clearer than:

``` purescript
what y = (`func` y)
```

Perhaps it's obvious what's going on when written as this example, but when you have a usage like that embedded in another expression it can be easy to miss the "hidden `flip`".

**Comment by phadej** [comment]
well, i'd rather write `flip func y`. It's more refactor-friendly, IMHO.

**Comment by natefaubion** [comment]
One thing that's nice about the underscore section syntax, is that it makes it much easier to parse sections that have further chains of operators (`(x <<< y <$> _)` and `_ <#> x <<< y`) which can't easily be done with the current parser. I do think it can be a bit confusing since `_.foo` does not require parens: `_.foo <$> _`.

**Comment by phadej** [comment]
what I said :P https://github.com/purescript/purescript/issues/1846#issuecomment-174513509

IMHO, at this point point-free is a bit pointless.

```hs
(\z -> x <<< y <$> z)  -- not much longer.
```

**Comment by natefaubion** [comment]
But its not multiple wildcards in the same expression (it just looks like it), its single wildcards in nested expressions, its just that the property section doesn't require parens like an operator section.

**Comment by natefaubion** [comment]
Also, the composition examples are just the easiest examples to come up with. I don't think we even allow function application in an operator section without another set of parens.

**Comment by garyb** [comment]
Yeah, it wouldn't work right now, but I think wildcards make it possible/easier to handle.

**Comment by paf31** [comment]
Bumping to 0.8.1.

**Comment by AppShipIt** [comment]
I dig @tfausak's operator section proposal! Much easier to read. Would it ambiguate ever having typed holes though??

**Comment by jdegoes** [comment]
> One thing that's nice about the underscore section syntax, is that it makes it much easier to parse sections that have further chains of operators ((x <<< y <$> _) and _ <#> x <<< y)

I agree with this, and in fact, I think this would eliminate `flip` and other symptoms of pointfree abuse (of which I am guilty myself). I'd argue for parsing any parenthesized list of terms separated by operators in the same consistent fashion (`(_ >>> foo _ 2.3 >>> bar 9)`), and requiring parens around record syntax (e.g. `(_.foo)`).

**Comment by AppShipIt** [comment]
> well, i'd rather write `flip func y`.

@garyb Any reason not to track `func _ y`?

**Comment by garyb** [comment]
There is a discussion about that on an issue elsewhere, we don't want to do it because it can be difficult to reason about what it means. Scala has something like it, and it almost never works the way that seems sensible.

**Comment by AppShipIt** [comment]
The difference in Scala's is only with respect to multiple parameters right? I searched <q>sections</q> and couldn't find the issue. It looks exactly like operators/`case`/`if` to me and as often as I `flip f` seems useful.

**Comment by garyb** [comment]
Yeah, I don't know, maybe we can reopen now that `_`s have become more prevalent in the syntax. As you've seen though, it was a pretty long discussion the first time.

The main issue is when people will try to write things like `map (foo (bar _ x) y)` thinking that it means `map (\z -> foo (bar z x) y)`, but actually it would be `map (foo (\z -> bar z x) y)`.

**Comment by AppShipIt** [comment]
> Yeah, I don't know, maybe we can reopen now that _s have become more prevalent in the syntax.

@garyb I intend to read it fully and talk offline before bringing it up formally. At the very least I now empathize with your Scala argument. Your example makes sense too whereas perhaps the it'd be less an expectation with nested operators and `case`s. Thanks!

**Comment by user471** [comment]
>The main issue is when people will try to write things like map (foo (bar _ x) y) thinking that it means map (\z -> foo (bar z x) y), but actually it would be map (foo (\z -> bar z x) y).

How is that different from
```
map (foo (x <#> _) y)
```
```
map (\z -> foo (bar <#> z) y)
map (foo (\z -> x <#> z) y)
```
?
