### ISSUE TITLE
Wiki Javascript Operator `==` is Purescript Function `==`

### ISSUE THREAD

**Issue by leohahn** [purescript/purescript#1885]
On this section on the wiki:
https://github.com/purescript/purescript/wiki/Language-Guide#binary-operators

It is stated that the JS Operator `==` is the same as the function `==` in Purescript
Wouldn't it be the JS `===` Operator?

**Comment by hdgarrood** [comment]
For the primitive types - Int, Boolean, String, Number - I believe that PureScript == could correspond equally to JS == and ===, because the type system already requires that the operands have the same type. For all other types, PS == is neither JS == nor ===, as you can choose how to implement Eq for every type you define.

Maybe we should just remove that, it sounds like it might be a bit misleading.

**Comment by hdgarrood** [comment]
Or rename the column to something like "roughly corresponds to in JS"

**Comment by leohahn** [comment]
Yeah that is true. The problem is that in JS `2 == "2"`, so people could interpret it wrongly.

**Comment by leohahn** [comment]
Maybe it helps just to write an observation.

**Comment by paf31** [comment]
The wiki definitely needs updating. I'm doing some tidying of issues, so I'll close this, but please feel free to update the wiki as you see fit.
