### ISSUE TITLE
0.8.1 hangs compiling SlamData

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1905]
I assume that's the case anyway, I cancelled the build after 10 minutes of near 100% CPU usage.

I'm not sure what the hold up is, as `output` has 779 subdirectories at that point, which is the same as when 0.7.6 succesfully completes.

**Comment by garyb** [comment]
Maybe this is the same thing @nwolverson mentioned... if I run the compiler again after cancelling it it's fine, probably as there are no warnings on recompile, so no pretty-printer hangups, if that's where it's spinning.

**Comment by nwolverson** [comment]
My issue only surfaced (for me) with a change which inserted an extra `PositionedValue` ast node around atoms, with this change I was seeing an infinite recursion when printing a warning (I think about operator sections) between `prettyPrintValue`/`prettyPrintValueAtom` involving `Parens`/`BinaryNoParens`. I didn't understand what the actual underlying problem was, so I wouldn't be surprised if this was related.

Adding an internal error there for the unexpected cases may make sense either way.

**Comment by garyb** [comment]
Yeah, I'm doing away with the infinite recursions in the pretty printer now, even though the new code is slightly less pleasant the current situation has blown up so many times it's probably worth being explicit.

**Comment by garyb** [comment]
I think this is my fault actually, I didn't add new cases for new constructors in pattern binders. I'm not sure why they'd be used in SD though, as no code uses the new binders yet. `ParensInBinder` perhaps.

**Comment by garyb** [comment]
Hmm ok, it's not just that. There's definitely a pretty printing problem though.
