### ISSUE TITLE
Configurable warnings

### ISSUE THREAD

**Issue by agrafix** [purescript/purescript#1923]
Are there any plans to make warnings configurable? I'd like to enable and/or disable warnings individually and also make some warnings an error (`-Werror`).

**Comment by kRITZCREEK** [comment]
https://github.com/natefaubion/purescript-psa allows you to silence certain warnings. Not sure about how to achieve -Werror

**Comment by natefaubion** [comment]
psa has a `--strict` flag that turns all warnings into errors. It doesn't allow one to configure individual warnings as errors atm though.

**Comment by paf31** [comment]
I'd really rather not make warnings configurable or implement `-Werror` for the same reason I don't want to add language pragmas - build behavior should be completely reproducible on all machines. If a user wants to change the presentation of the warnings/errors, that's another matter.

**Comment by paf31** [comment]
This seems like another one which could benefit from a decision and then freezing.

**Comment by agrafix** [comment]
"build behavior": does that also include emitted warnings from the compiler for you?

**Comment by garyb** [comment]
:-1: from me, I think `purescript-psa` solves the configurability of warnings, and there is a reason we emit them. I'd be slightly more in favour of having a flag that makes warnings into errors, but I don't think suppressing them is a great idea.

I guess some of the warnings we emit are lint-y, like shadowed names, missing type signatures, so we could introduce another severity tier in the output and have `--no-lint`. That I'd be okay with, but for the "real" warnings: imports, deprecated things, non-exhaustive patterns, etc. I definitely think suppression is a bad idea.

**Comment by jdegoes** [comment]
:-1: 

@garyb's idea of a "linting" level in the error / warning hierarchy is attractive, because I feel there is at least one warning, and in the future there will be more, which are unexpectedly opinionated, and fall properly in the domain of a linter. But the actual issue of configuring them should, as with anything that can, be pulled out into psa / build tools. (It's too easy for a compiler to become a gigantic monolith catering to all possible preferences, when in fact good composability allows non-compilation features to be pulled out into build tools.)

**Comment by agrafix** [comment]
In that case, I'd argue that it would be better to remove all lint-like warnings from the compiler and introduce a `ps-lint` tool.

**Comment by paf31** [comment]
That seems like a good idea, but it requires reimplementing the PureScript AST and parser in PureScript, and then keeping them up to date.

Lint warnings serve the same purpose as regular warnings - they inform you that something _may_ (or may not, if you're careful) break in future. You can choose to ignore them, but everything the compiler currently warns on is something that you probably should take note of, even if you decide not to take action.

**Comment by fsoikin** [comment]
There is this big inconvenience with using `psa --strict`:

```
> pulp build -- --strict
(a gazillion errors that are really warnings)
> pulp build -- --strict
Compiled successfully
> WTF?
WTF?: command not found
```

Running the build twice in a row results in successful compilation, even if there are warnings. To reveal the warnings again, I have to `rm -rf ./output`, then build again, which results in a very long build, because it will rebuild everything, including libraries. A very inefficient development process.

I'm not sure what exactly could be done about this (short of adding the support to the core compiler), but this works as expected in Haskell (and every other language I've tried so far).

**Comment by LiamGoodacre** [comment]
@fsoikin this is what purescript-psa's `--stash` flag is for.

**Comment by fsoikin** [comment]
Oh, indeed, that works. Thank you!
It was not obvious from the docs that this is what `--stash` does.

Never mind then :-)
