### ISSUE TITLE
Process for closing issues

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#1930]
There has been a proliferation of issues lately, and I find myself wanting to close a lot of them. Many are simply poorly thought out proposals, which need much more development in order to be practical. I'd like to suggest we come up with a way to filter these out, without being too undemocratic about the issue process.

What about if we had a threshold for the number of :-1: votes from _contributors_ before an issue was swiftly closed?

**Comment by hdgarrood** [comment]
I've seen quite a few projects which only use the issue tracker for stuff they are fairly sure they want to implement, so new proposals get trialled on the mailing list first. Maybe that could work?

**Comment by paf31** [comment]
I think that sounds great. Perhaps GitHub's new issue templates are a decent way to solve this, since we can try to force users to go through a checklist before opening something (did you provide an example? did you check the issue list already? etc.)

**Comment by hdgarrood** [comment]
I'm not sure we even need to force users to go through a checklist, it may well be enough just to add some information to contributing.md about whatever process we decide on. If people still don't follow it (and whatever we do, chances are there will be people who don't, I think), then we can just close it straight away, say "please follow the process", and link to contributing.md.

**Comment by paf31** [comment]
Sounds good. I'm usually reluctant to close issues too quickly, but recently, it's been hard to keep up. Perhaps it's better to just set down some rules and then be strict about them.

**Comment by paf31** [comment]
Another irritation is when the same issues and questions crop up again and again. I appreciate it's difficult to find previous discussions sometimes, but I would like a way to deal with these issues once, and then close them as soon as they come up the next time. Explicit `forall` is a good example here, but there are plenty of others. I think we should try to make decisions on these sorts of things and record the outcome in a visible place.

**Comment by hdgarrood** [comment]
:+1:

**Comment by AppShipIt** [comment]
> poorly thought out proposals, which need much more development in order to be practical.

Elm at one point moved these from the mailing list to [elm-plans](https://github.com/elm-lang/elm-plans) (arguably by my suggestion). I think it failed because of 1) lack of process, 2) lack of democracy, and 3) lack of delegation (increased burden on Elm's maintainer). EcmaScript and TypeScript both impose rigorous proposal processes. Democracy could be addressed by empowering a team within the GitHub organization responsible for guiding discussion through stages to a proof of concept or closing (@hdgarrood would be an obvious candidate). From my perspective the strength of PureScript is the diversity of ideas from exceptionally ingenuitive users (not just contributors). No matter where it happens @paf31 needs to be able to ignore them until needed.

> only use the issue tracker for stuff they are fairly sure they want to implement,

Agreed this repo should be for bugs and approved features.

> so new proposals get trialled on the mailing list first.

May I recommend a separate repo? I know it didn't go well for Elm but mailing lists are less suitable for code formatting, issue linking, user callouts, and arguably notifications (my inbox is full enough and there's no Google Groups app).

> GitHub's new issue templates are a decent way to solve this,

Agreed.

> it may well be enough just to add some information to contributing.md

No sense not to surface information up front even if it just reads "Please consult `CONTRIBUTING.md` before reporting an issue."

> the same issues and questions crop up again and again.

Perhaps we could add topics to an FAQ as they repeat? Another candidate is instance naming which I didn't know where to find.

**Comment by garyb** [comment]
> No reason not to surface information up front even if it just reads "Please review CONTRIBUTING.md before reporting an issue."

GitHub actually prompts something along those lines already when opening an issue. It apparently doesn't work very well!

**Comment by AppShipIt** [comment]
So I'd be keen to research various proposal processes and draft our own if the idea of a separate process driven repo sounds appealing?

**Comment by hdgarrood** [comment]
Re elm-plans, I did a bit of googling and found this:

> The elm-plans repo is not in use anymore. Folks wanted me to do a roadmap, but the repo ended up being a real quagmire of questionable feature requests and discussions that were not going to turn into results. Some cool ideas and perspectives came up that I filed away in my mind, but "taking requests" for language design is not a good process for me. I need to know the problem, not how people think it should be solved, and I get that from talking with folks and watching discussions!

Not sure if this applies to us, but maybe worth considering.

**Comment by hdgarrood** [comment]
the above is from https://groups.google.com/forum/m/#!searchin/elm-discuss/elm-plans/elm-discuss/Kh3dImV4Xkg

**Comment by AppShipIt** [comment]
For openness "folks" was primarily me in offline discussions when I visited Prezi. The experiment was a failure. But in my opinion the failure was autocratic (perhaps just OCD) leadership not the concept. That's why I recommended 1) establishing a process, 2) enabling a team, 3) and delegating to them. Besides programming I've done small business consulting. My consistent pitch has been "you'll be successful as you delegate success."  In my opinion the biggest strength of PureScript is its openness to both contributions and ideas (in contrast to Elm). And to scale effectively as more people's interest piques will necessitate Phil and Gary not having to feel burdened to follow every issue or tweet or whatever.

**Comment by hdgarrood** [comment]
I'm not sure autocracy is necessarily a bad thing in our context, or that democracy is necessarily good. Everyone refers to Guido van Rossum as Python's benevolent dictator, for example, and my impression is that Python is one of the healthier communities.

@AppShipIt thanks for sharing, this is very interesting. Just to be clear, which experiment are you referring to? Elm-plans?

Maybe the answer, at least partially, is to encourage people to share their difficulties in a specific place that is not the GitHub issue tracker (perhaps mailing list, perhaps a repo, idk) instead of making proposals to change the language; I think we have a bit of XY problem going on. It's probably more useful to hear "this is my code, this is what I'm struggling with" than "I think we should change the language like this", especially as, in my experience, most problems can be solved well enough by the language as it is today.

**Comment by hdgarrood** [comment]
Also, I'd be happy to moderate such a proposal forum, if we were to create it. I don't really mind whether it's the mailing list, a GitHub repository, or anything else.

**Comment by AppShipIt** [comment]
> I'm not sure autocracy is necessarily a bad thing in our context, or that democracy is necessarily good.

I feel confident that either, exclusively, is bad which is why I propose delegating to proven contributors. Likewise Evan called Python a <q>good</q> example and CoffeeScript a <q>bad</q> one. I don't know Guido but I've written a painful (e.g. broken multiple inheritance, nuanced decorators, crippled lambdas, explicit `self` without first class functions,…) amount of Python and don't want PS to reflect one single viewpoint. On the contrary I love the input of the likes of Brian M, Jon S, John D, ect.

More than aversion toward Python I can point at examples within each community. Most recently revised operator sections (ingenious to me) were proposed by Liam in an arguably wearisome ticket. In contrast the Elm architecture has conspicuous holes. A community member (who's now trying PS) proposed a simpler alternative with proof of concept that was effectively dismissed. By comparison our community has produced 3 independently viable app architectures. I consider our openness to evaluate fundamental change part of what cultivates such innovation.

> are you referring to? Elm-plans?

Yep.

> instead of making proposals to change the language; I think we have a bit of XY problem going on.

I agree at least in part. Addressing <q>XY</q> could be formalized (what's the problem, what's a solution, what are alternatives). But to quote Phil:

> I like to think of PureScript as a playground for new ideas, to a certain extent.

There are caveats. There's danger of <q>too many cooks in the kitchen</q>. But I imagine something inspired by TC39's process could walk the line.

**Comment by AppShipIt** [comment]
I'll draft a process document (inspired by TC39 and TS) in my fork for a tentative separate repo. It'll take me at least a weak because I want to finish my compiler PRs.

**Comment by AppShipIt** [comment]
Finally looked for inspiration and found it in [Ember](https://github.com/emberjs/rfcs). We don't seem to need it right now but could be valuable when we start getting too many suggestions again.
