### ISSUE TITLE
psc to stdout?

### ISSUE THREAD

**Issue by raould** [purescript/purescript#1940]
Would be nifty (maybe?) if output from psc could be piped to stdout? (Not that I have a giant use case for it, just that it is a useful thing for all command line tools to support, for unknown unknowns.)

**Comment by paf31** [comment]
`psc` creates multiple files on disk, how would it pipe them all to standard output?

If you want `Main`, why not create a wrapper script which Pulp can use instead of `psc`, and have it `cat output/Main/index.js` when `psc` is done.

In general, we try to avoid handling this sort of stuff in the compiler, and defer it to tools/scripts.

**Comment by raould** [comment]
Got it, thanks.

**Comment by zudov** [comment]
Which output are you referring to? Compiler basically produces two outputs errors/warnings (which I believe goes to stderr) and the actual compiled files (note the plural) which go to a separate directory for every module (two files per directory).

Warnings can be redirected from stderr to stdout using shell capabilities. Actual files however can't trivially be printed to a single stream since there is no canonical way to the files which would mean that no tool would be able to process whatever we come up with.

Note that `psc-bundle` (which outputs a single file) can output to `stdout` which is very useful for reason you mentioned, piping to other tools (e.g. minifiers).

**Comment by raould** [comment]
(psc-bundle sounds very helpful, thanks.)

**Comment by zudov** [comment]
IIRC `pulp build -O` and `pulp browserify` actually prints the output to stdout, providing a `--to file` option which allows to put it into a file.
