### ISSUE TITLE
Inline typeclass instances in specialized functions

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#1976]
[Given](http://www.purescript.org/learn/ffi/#handling-constrained-types):
```purs
inOrder :: forall a. (Ord a) => a -> a -> Tuple a a
inOrder a1 a2 | a1 < a2 = Tuple a1 a2
inOrder a1 a2 = Tuple a2 a1
```

Generate:
```js
var inOrder$ordInt = function (_1) {
  return function (_2) {
    if (Prelude.greaterThan(ordInt)(_1)(_2)) {
      return Data_Tuple.Tuple(_1)(_2);
    };
    return Data_Tuple.Tuple(_2)(_1);
  };
};
```

When: `let x = inOrder 1 2`

Why: One fewer closures.

**Comment by paf31** [comment]
What you're describing (I think) is _monomorphization_, which is a global program transformation for compiling type classes.

I think I misunderstood when we spoke about this on chat, but here are the optimizations I want to do instead:

- common subexpression elimination for reused dictionary expressions
- inlining dictionary members for _already monomorphic_ dictionary applications.

**Comment by AppShipIt** [comment]
> Being global, it doesn't always play nicely with separate compilation.

That's why I mentioned only non-exported functions which would be the common case for apps.

> here are the optimizations I want to do instead:

Cool.

**Comment by paf31** [comment]
Oh ok, I see now :smile: 

I don't know if this would be the common case for apps though.

One downside of this approach is that we need to come up with unique names for the instantiated versions of the function, which is a pain for code gen. I'm also not a fan of having two very different solutions to the same problem for the one-module and many-module cases.

**Comment by paf31** [comment]
I think this might also be a nice fit for `psc-bundle`, since we've recently [seen](http://symbolian.net/2016/04/07/513/) that global JS transformations can be handled nicely there, and I think this is a special case of a more general global program transformation.

**Comment by AppShipIt** [comment]
I had the same thought reading his writeup in the plane!

**Comment by rvion** [comment]
Some languages like C++ specialize all templates at compile time during type instantiation (from what I heard).
as @texastoland suggested, if we consistently use a syntax like `fn$class1$class2` and specialize all functions, I think we could make it so it plays nicely with separate compilation too.
Combined with the uncurryfication POC, and current TCO, it should yield very good perfs at the cost of larger generated code.
I took a (very) quick look at psc-bundle changes to support uncurrification, and I indeed also have the impression that extending the uncurrification logic to typeclasses would work.

@paf31 @texastoland Do you have any more thought on this since last time it was discussed ?
@jutaro any plan to rebase your work ? Make a PR ? Improve it to work on typeclasses ?

**Comment by texastoland** [comment]
No but I'd be happy to brainstorm on Zoom this week!

**Comment by rightfold** [comment]
C++ is different in that it type-checks parts of the template bodies again for each instantiation. It's a semantic, not a codegen, issue. For PS want something more like what Rust does.

**Comment by rvion** [comment]
@texastoland I'd be happy too. I just created a account on Zoom. 

@rightfold I'm not sure it's different.
Rust actually borrowed monomorphization from C++.
Monomorphisation is actually just the second part of the two phase lookup.  I said that "C++ specialize all templates at compile time during type instantiation", which still seems true to me. 
Purescript could works the same way as C++ and Rust, and that's how interpretated @texastoland proposal along paf31 comments: add monomorphisation during codegen instead of paying runtime cost.

Is that wrong ?
I'm by no means an expert, so any feedback welcome.

**Comment by rightfold** [comment]
Monomorphization in C++ is more than an optimization. You could have different output for different types, for example. This isn't desirable in PureScript. In Rust this isn't the case (except for `Drop` but that's tolerable).

**Comment by rightfold** [comment]
You also have to be careful about polymorphic recursion if you want the monomorphization algorithm to terminate.

**Comment by texastoland** [comment]
I've got to give this a think. But what I remember about C++ templates all that is true. I'm only vaguely familiar with Rust.

**Comment by rvion** [comment]
@rightfold thanks for the extra infos / precisions !

> Monomorphization in C++ is more than an optimization. 

I guess I agree. Since C++ only carries "function dictionaries (~instances)"  along "types", supports separate compilation with "low-level" object files, and doesn't have typeclasses (for now, c++17 has _concepts_), I indeed guess they have no choice but to do that. It's also much  easier to re-typecheck against concrete types, and to optimize small and concrete functions.

> You could have different output for different types, for example. This isn't desirable in PureScript. In Rust this isn't the case (except for Drop but that's tolerable).

__This is the part I sincerely don't realy understand. What exactly would not be desirable in PureScript ? To have concrete functions for each concrete types ?__
With monomorphisation and inlining, generated code could be faster, right ?

> You also have to be careful about polymorphic recursion if you want the monomorphization algorithm to terminate.

Oh, right ! I don't have a good enough mental model yet to visualise concretely the problem, but I imagine that there can be problems with higher kinded types, or infinite tower types where class instances are automatically building upon along recursion.

The good thing is that since monomorphisation in purescript would just be an optimisation, we could still fallback to paying the cost for class dictionary access at runtime in those cases, though.

**Comment by rightfold** [comment]
@rvion consider this program:

    #include <cstddef>
    #include <iostream>
    
    template<typename T>
    std::size_t f() {
        return sizeof(T);
    }
    
    int main() {
        std::cout << f<char>() << '\n';
        std::cout << f<double>() << '\n';
        return 0;
    }

Here the output of `f` depends on the type argument. This makes `f` not [parametric](https://en.wikipedia.org/wiki/Parametricity). All polymorphic function in PureScript are parametric and you want to keep it this way.

**Comment by rvion** [comment]
@rightfold thanks for the explanation and the link

I understand what you mean. Since there is no typeclasses in c++, you have to re-typecheck the function for each concrete type to ensure all methods used in the function body are available for each given types. (2nd phase of the two phase lookup) This is some __implicit contract__.

In haskell and purescript, the compiler ensure functions only use methods from declared class constraint, hence parametricity. That's the reason why we don't have to typecheck functions at each instanciation (no need for two phase lookup because we have parametricity, since we have explicit contracts).

when you say:

> For PS you want something more like what Rust does (monomorphization while retaining parametricity).

I completely agree with you :) Initially, I just wanted to say in this thread: "I also think that monomorphisation is a good optimization trick that would benefit purescript", nothing more

I understand that C++ monomorphization is needed for more reasons than just optimization.
regarding this point: I expressed myself badly, and my sentence "Monomorphisation is actually just the second part of the two phase lookup" was wrong. I mostly wanted to point out that parametricity is quite a week notion, since both haskell and c++ have the notion of contracts (or types). It's more about the language semantic, how those contracts are implicit or not, checked once or twice, easy to reason about or not, etc. In the end, you can write the same thing and there is not such a large conceptual difference IMO.

```
class Size a where size :: (Proxy a) -> Int

Instance Size Double where f _ = 8
Instance Size Char where f _ = 1

main = do
    print (f (Proxy Char))
    print (f (Proxy Char))
```

C++ needs to compile twice because it has different semantics regarding type contracts.

**Comment by rvion** [comment]
I was confused when you said 

> Monomorphization in C++ is more than an optimization. You could have different output for different types, for example. This isn't desirable in PureScript

because I read this as: "Monomorphization [...] isn't desirable in PureScript", which I was disagreeing with. I also didn't undestand exactly what you meant by "You could have different output for different types" because having different output for different types is normal, both in haskell, purescript, and c++.

----

as I said in my previous message: 

> For PS you want something more like what Rust does (monomorphization while retaining parametricity).

I agree with you :)

**Comment by jdegoes** [comment]
Specializing everything requires whole program compilation, but you can do it. It does enable substantially more performance optimizations, although it greatly expands the size of the generated code. It's something we might look at if we ever get around to super-compiler mode (-O3) for PureScript. 😄

**Comment by paf31** [comment]
> super-compiler mode (-O3)

Code name Ozone?

**Comment by jdegoes** [comment]
Hell yeah! 👍

**Comment by rightfold** [comment]
> although it greatly expands the size of the generated code

Depends on later optimisations such as constant folding and common subexpression elimination.

**Comment by paf31** [comment]
Closing, only because this is subsumed by more general optimizer issues, namely global inlining.
