### ISSUE TITLE
A proposal to reduce bureaucracy of re-exports

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#1983]
Given that:

1. We currently warn about re-exports since we want to ensure that additive changes in upsteam libraries will not cause breakages.
2. We don't want to make the compiler package aware (now at least).

I have a suggestion that may allow us to supress the warning in the more common cases at least:

If module A is re-exporting module B and they both share the same path prefix up to the directory that module A resides within, then we can supress the error.

Example: The module at `~/my-thing/src/Control/Monad/State.purs` re-exports a module defined in `~/my-thing/src/Control/Monad/State/Class.purs`. Since they're both under `~/my-thing/src/Control/Monad/` then I think it's more than reasonable to say that they're in the same package, without concerning ourselves with what packages really look like in the compiler.

This even works in the prelude, since all the modules re-exported from `src/Prelude.purs` are under `src/`.

The only assumption we're making here is that external packages will not be installed under some hierarchy where they're in a sub-tree of the current library/app's source folder. I think that's totally reasonable, and very much worth it given how annoying the current situation is to maintain.

**Comment by AppShipIt** [comment]
This sounds a lot like https://github.com/purescript/purescript/issues/1869#issuecomment-180807376 combined with https://github.com/purescript/purescript/issues/1869#issuecomment-187297577 CC @tfausak 👏

**Comment by tfausak** [comment]
:+1: I like this idea! 

The only problem I can think of is that the file path doesn't have to match the module path. The definition of `A.B` could be in `src/Y/Z.purs`, right?

**Comment by paf31** [comment]
> We don't want to make the compiler package aware (now at least).

I'd rather avoid making the compiler even filepath aware for now. What about using the module name?

I'm interested in the import warning "problem", and I think the single open import exception is a great step, but I'd be wary of adding new exceptions which can't definitely be known to be safe, since they will be tricky to remove.

**Comment by hdgarrood** [comment]
I don't think using the module name works, because it's common to define modules under hierarchies defined in other packages. Take `Control.Monad.Eff`, which is under `Control.Monad`, for instance, even though these modules are in different packages.

I am tentatively agreeing with @paf31, I think it would be a pity to lose the property that you get the same behaviour no matter how modules are laid out on the disk &mdash; not that I *use* this property at all, but this proposal does seem to me to be the kind of thing that's at risk of causing WTFs (sorry).

**Comment by jonsterling** [comment]
I don't have much to say other than I think we should be very serious about not depending on things like filenames or disk location for anything.

One of my favorite things about MLton + ML Basis System or SML/NJ + CM is that the file structure is totally irrelevant. Doesn't matter how you organize files, nor how you name thing. The package calculus allows you to "import files" into a package and export abstract entities (e.g. declarations).

**Comment by garyb** [comment]
Yeah, module names doesn't work (`Control.Monad.Eff.Exception` is "under" `Control.Monad.Eff` but in a totally different library), so we may as well close this if the filename option is objectional.

**Comment by garyb** [comment]
Just one last note:

> I'd rather avoid making the compiler even filepath aware for now. 

It already is, I was intending on reading this from `SourceSpan`s.

**Comment by paf31** [comment]
Yeah, I know the parser knows about filenames, but I think filenames for good error messages are a different sort of thing. I think we should be treating the source span data as abstract anyway.
