### ISSUE TITLE
Allow other license file names?

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1985]
I upgraded to PureScript 0.8.3 from 0.8.0 and was surprised to find that `psc-publish` failed. It complained about the lack of a `LICENSE` file. That was strange to me because I *do* have a license file, but it's called `LICENSE.md` instead. Can [this check](https://github.com/purescript/purescript/blob/e2864866692ba0837bbc6df8c8ebd3e627a38f0a/src/Language/PureScript/Publish.hs#L140) change to allow different license files?

**Comment by AppShipIt** [comment]
It theoretically also checks the `license` key in `bower.json`. Is that sufficient?

**Comment by hdgarrood** [comment]
I would like to keep the file check in, because I have seen code which listed the license in bower.json but did not have a license file. It would not take much to persuade me to allow LICENSE.md too, but is there a reason why you'd rather not rename it?

**Comment by AppShipIt** [comment]
> It would not take much to persuade me to allow LICENSE.md too

FYI that seems like a [slippery slope](http://daringfireball.net/linked/2014/01/08/markdown-extension).

**Comment by hdgarrood** [comment]
I've just realised one reason: the .md suffix means that GitHub will render it nicely. That's good enough for me, I think. I've also seen .markdown and .txt so I guess we should accept those too. I don't see this as a slippery slope; we can consider future suggestions as (if) they come.

**Comment by tfausak** [comment]
> is there a reason why you'd rather not rename it?

Because it's a Markdown file. As you noted, it gets rendered nicely. And for other projects (like [Octane](https://github.com/tfausak/octane/blob/0.4.12/LICENSE.md)), I actually use features of Markdown.

**Comment by paf31** [comment]
Does it make sense to just allow any file of the form `license(.*)?`

**Comment by hdgarrood** [comment]
Yeah, sounds good.

**Comment by bodil** [comment]
I'd be very happy if it would accept `COPYING` as well. I'm extremely reluctant to rename my standard GPL licence files.

Overall, though, I believe a valid [SPDX licence ID](http://spdx.org/licenses/) in the `license` key should be sufficient. These map 1 to 1 onto a licence document, and npm considers them legally sufficient.

**Comment by hdgarrood** [comment]
The only reason I wanted to require that a license file exists was that I wasn't sure if just writing eg. `"license": "MIT"` in bower.json is enough to clearly specify which license(s) you actually mean. Having browsed the [SPDX specification](http://spdx.org/SPDX-specifications/spdx-version-2.0), and given that [Bower's spec](https://github.com/bower/spec/blob/master/json.md#license) explicitly mentions SPDX, I'm happy that this is in fact that case.

Therefore, I think we should drop the requirement on any license files existing, and instead require that there is a valid SPDX license expression in bower.json. I don't think a SPDX license ID is sufficient, because eg. purescript-signal is LGPL 3 or newer, which you can't represent with just an ID (but you can with an expression: "LGPL-3.0+").

**Comment by bodil** [comment]
👍😁👍

**Comment by robotlolita** [comment]
:+1:
