### ISSUE TITLE
psc-ide and psc consistency finding FFI

### ISSUE THREAD

**Issue by AppShipIt** [purescript/purescript#2065]
I'm trying to set up our mixed project to keep `.purs` and `.js` files in the same directory tree. @ethul's PureScript WebPack plugin [requires](https://www.npmjs.com/package/purescript-webpack-plugin#ffi-string-array) a glob of FFI files as input. @spicydonuts suggested naming FFI `*.purs.js` for the WebPack plugin. But I remembered @kRITZCREEK mentioning in https://github.com/purescript/purescript/pull/2013#issuecomment-210560323 that `psc-ide` expects those to be named like `[ps-name].js` (which sounded like a reasonable assumption) for fast recompilation. @hdgarrood also [voiced](https://twitter.com/hdgarrood/status/725955514249568257) that `psc-ide` finding FFI differently than `psc` violates principle of least surprise. Just reporting a use case we're working around. I don't have a suggestion how it should work differently.

**Comment by kRITZCREEK** [comment]
One thing to add, is that you want your FFI files to be TypeScript/ES2015 transpiled before fed into the compiler by the webpack plugin.

**Comment by hdgarrood** [comment]
I think 'surprise' isn't quite the right word for what I'm worried about. My aim, generally, is to minimise unnecessary variations in how projects are set up. The more variation there is, the less likely any two random build tools are likely to work nicely (or even at all) together. This same idea, and particularly because we were getting reports of build tools breaking for lots of users, is what led me to advocate removing the `--require-path` option.

Given the following observations:
* Almost all PureScript code in the wild uses one module per file,
* Almost all PureScript code in the wild uses a predictable scheme for locating the path of FFI files (i.e. `moduleFileName.replace('.purs', '.js')`,
* `psc-ide-server` assumes that your code is arranged as above,
* this is different from how `psc` works (multiple modules per file, scan FFI modules for module comments to match them up),

I worry that we're setting ourselves up for unnecessary pain; at the moment, we have two separate ways of indicating to compiler tools how normal and FFI modules match up. Not only does this mean we're asking users to do extra unnecessary work to get things to work, I would also bet that this is going to come back and bite us sooner or later.

To get the two in sync, we will have to either make `psc` stricter in what it accepts, or `psc-ide-server` looser. I vote the former; not only does it seem very feasible, but also it's in line with the language's philosophy (of adding power by removing unnecessary flexibility, eg. forcing `Eff _ a` to be different from `a`).

I can't comment on Webpack specifically, since I've never used it in anger, but I will say that I'd like to discourage setups where FFI modules automatically get preprocessed somehow, because I want to avoid people accidentally releasing libraries that can't be built with Pulp's defaults (which, for now, means only ES5 in FFI files).

**Comment by hdgarrood** [comment]
Hm, perhaps this is somewhat orthogonal to what @AppShipIt is trying to do, though. Do you need 'normal' JavaScript source files mixed in with PureScript FFI modules in the same directory tree? I'd guess it will be less painful in the long run to separate them.

**Comment by AppShipIt** [comment]
> I'd like to discourage setups where FFI modules automatically get preprocessed somehow,

There you go we disagree again 😂 If it works in Bower it ought to be irrelevant.

> Do you need 'normal' JavaScript source files mixed in with PureScript FFI modules in the same directory tree?

Should I have separate directory trees for TypesScript, ES.next, cssnext modules, etc. as well? It's not necessary but I'd prefer to be agnostic to how React components are written. Regardless I can work around but I don't think is an unbearable use case.

> To get the two in sync, we will have to either make psc stricter in what it accepts, or psc-ide-server looser.

I don't understand what the compiler does with vanilla JS but @kRITZCREEK made an interesting point that FFI files reference their PS modules instead of vice versa presumably so `psc` doesn't need to be file path aware?

**Comment by hdgarrood** [comment]
What do you mean, 'if it works in Bower'? If Bower lets you register the package? Bower doesn't care about the contents at all, just that it's a git repository with semver tags and a bower.json file.

What point did @kRITZCREEK make? Can I read about it anywhere in more detail?

**Comment by garyb** [comment]
We're going to remove the ability to have multiple modules per file in 0.9, so there's that at least.

@AppShipIt: `psc` looks at files either with a `.js` extension or provided by `--ffi` and examines them for a comment `// module X.Y.Z` to determine the module they're associated with.

**Comment by AppShipIt** [comment]
> `psc` looks at files either with a `.js` extension or provided by `--ffi`

@garyb Does that mean `psc` works exactly like `psc-ide` except for the case (like WebPack) where `--ffi` gets passed in? If that's true it's inconvenient in this case but works as I'd expect and happy to close the issue.

**Comment by garyb** [comment]
@AppShipIt no, `psc-ide` only looks at the filename if I understand correctly. `psc` reads every js in the input sources and tries to parse a comment with that exact format, disregarding where the file is located or what it's called.

**Comment by AppShipIt** [comment]
That was my impression. Issue definitely isn't a complaint but raising a use case where the difference is inconvenient.

**Comment by kRITZCREEK** [comment]
@hdgarrood The point I made, was that currently we match a `.js` file and a `.purs` file by looking at a comment inside the `.js` file that references the `.purs` module by name. If it was the other way around
(ie. a relative filepath inside the `.purs` module) we could easily get at the FFI file when rebuilding. Of course this has lots of other problems, like making it really hard to move files around and forcing the compiler to deal with filesystems more than we'd like.

If you choose a fancy file layout, you can always just explicitly list your FFI modules instead of globbing them.
An option would be to create a format with metadata and persist it to disc during compilation. Other tools could then use that file to get at mappings like `FilePath -> ModuleName` or `Module -> FFIPath`.

**Comment by garyb** [comment]
We can't really put the `.js` file location in a `.purs` because that totally rules out any ability to be backend agnostic. Obviously a lot of FFI-using modules will be backend specific, but not all of them.

**Comment by garyb** [comment]
That's actually why we chose the current approach too, it's up to the backend to deal with the FFI files however is appropriate. The file locations that we use by convention in JS might not be viable for other backends.

**Comment by AppShipIt** [comment]
Thanks for the discussion. The only <q>fix</q> I can imagine is asking `psc-ide` to check `[ps-name].purs.js` in addition to `[ps-name].js` but that sounds quite specific to my use case. Close?

**Comment by garyb** [comment]
I don't think we should close just yet, this is still a worthwhile discussion to have. It would certainly be nice if we could somehow make `psc-ide` and `psc` consistent with each other... tool consistency is less important with other tools perhaps, but as we're distributing these together it would make sense that they follow the same rules.

I don't exactly know how to do that either :wink:

**Comment by AppShipIt** [comment]
> It would certainly be nice if we could somehow make psc-ide and psc consistent with each other

Title updated 👍

**Comment by hdgarrood** [comment]
> The file locations that we use by convention in JS might not be viable for other backends.

@garyb do you have any other backends in mind when you say this? Do you think we might be able to come up with a file location convention which should work for all backends?

**Comment by AppShipIt** [comment]
> Do you think we might be able to come up with a file location convention which should work for all backends?

@tfausak [pointed out](https://twitter.com/taylorfausak/status/726021499509833728) Neon uses a [different convention](https://github.com/tfausak/purescript-neon/tree/v0.1.1/src/Neon/Class/Native) and @kRITZCREEK also pointed out that JavaScript tools (like WebPack) prefer flexibility.

**Comment by hdgarrood** [comment]
Neon doesn't have any FFI modules any more, but even if it still did, and even if there are some other projects that don't follow the convention, I'd much rather break them now to fix this; I'm fairly certain that this is going to cause a lot of pain in the long run if we don't. Besides, we're breaking lots of stuff in 0.9 anyway.

**Comment by AppShipIt** [comment]
Then I'm back to asking for `.purs.js` instead so I can glob it.

**Comment by tfausak** [comment]
Neon used to do that. It doesn't have any FFI currently. 

I used a different schema because I didn't like polluting my source directories with a bunch of JavaScript files. So if you scanned `src/`, you'd only see `*.purs` files. If you wanted to peek under the covers, you could look in the `Native/` directory for FFI stuff. In my case that only included `*.js` files, but presumably you could put `*.cpp` and `*.java` and whatever else in there too.

That being said, I would support making FFI file names match PureScript file names, modulo extension. I would expect a project that uses the FFI to look like this:

```
src/Example.purs # regular PureScript file
src/Example.js # JavaScript FFI to support regular psc
src/Example.cpp # (or whatever extension) C++ FFI to support pcc from Pure11/14
src/Example.java # Java FFI to support truffled-purescript (I think)
```

I could also get behind `.purs.*` for FFI to make globbing easier. But why would you have a `*.js` file in the `src/` directory of a PureScript project if that file wasn't for FFI?

**Comment by AppShipIt** [comment]
> But why would you have a *.js file in the src/ directory of a PureScript project if that file wasn't for FFI?

https://github.com/purescript/purescript/issues/2065#issuecomment-215702494

**Comment by spicydonuts** [comment]
I still think `Example.purs.[ffi extension]` is best.  It will never conflict with any existing systems I can think of, and it's still `[purs file].[ffi extension]` in spirit.  It also keeps the PS file sorted to the top, which has been a minor annoyance with 'j' coming before 'p' (yes, _minor_):
```
src/Example.purs # regular PureScript file
src/Example.purs.js   # JavaScript FFI to support regular psc
src/Example.purs.cpp  # (or whatever extension) C++ FFI to support pcc from Pure11/14
src/Example.purs.java # Java FFI to support truffled-purescript (I think)
```

In general I lean towards configuration that all tools use (especially since the only tools external to the compiler right now are pulp and specific editor plugins, but those should use the compiler for getting their config.. separate issue probably) because it allows every use-case.

"PS projects in the wild don't mix FFI JS and regular JS" doesn't make sense because it's self-fulfilling.  Those projects won't exist until the tooling makes it straightforward.  This is precisely the reason the limited PS we use right now is in separate, simple projects and not in our main React project.

Basically, I see 3 options that don't break existing convention:

1. A common PureScript tooling config file.  Everything else has them; yes they're annoying but they solve a real problem (this one).
2. Defaults that don't conflict with existing practices, especially those in the language PS compiles to.. (the file extension changes referred to above).  The suggestion above is a safer default, but I still think #1 should be done and this should just be the default, not hard-coded into each tool.
3. Add something to each FFI file that _only_ makes sense in a PS module.  Turns out we already have this.. the `// module X.Y.Z` comment.  PS tooling could completely ignore any JS file without that module directive and everything would be solved.  This shouldn't break any compiler errors/warning either, since a PS file using `foreign import` that didn't have a backing JS file with the right module declaration could give the error, "No foreign module found.  It looks like `./Z.js` exists, though.  Are you missing a module declaration?".  Or when no file matching the convention exists, "No foreign module found.  I was looking for a file like `./Z.[ffi extension]`."

**Comment by spicydonuts** [comment]
> PS projects in the wild don't mix FFI JS and regular JS

That also implies all FFI code can only ever be in a single file.  What if you wanted to break out some reusable JS functions into a separate file?  _Usually_ that can and should be moved into PS, but it's silly for PS tooling to decide that you can't because it's PS convention or the highway (hyperbole, but if this is the first think you try using PS for -- a likely use case now that Pux exists -- you'd probably bail pretty fast).

> What do you mean, 'if it works in Bower'? If Bower lets you register the package? Bower doesn't care about the contents at all, just that it's a git repository with semver tags and a bower.json file.

Compiled code is the norm in Bower, not the exception.  JS projects use compilers (CoffeeScript, TypeScript, Babel, file concatination tools) and minifiers more often than not.  It's also pretty common to use the `bower.json` to exclude everything besides those compiled `dist/lib.js` and `dist/lib.min.js` files from downloading when the package is installed.  There's no reason PS can't do the same, besides the limitations with PS tooling configuration we're discussing right now.

**Comment by hdgarrood** [comment]
@spicydonuts Are you saying that you won't consider PureScript for your main React project until the tooling makes it easy to mix FFI and regular JS in the same directory tree?

> That also implies all FFI code can only ever be in a single file. What if you wanted to break out some reusable JS functions into a separate file?

No, it doesn't imply that. If you wanted reusable JS functions in a separate file, you'd go ahead and do it, and then `require()` that separate file from inside the FFI code. This is also how you should go about transpiling; if you want to write JS code as ES2015, or TypeScript, or anything, go ahead and do it, and just `require()` it from your FFI module.

> There's no reason PS can't do the same, besides the limitations with PS tooling configuration we're discussing right now.

I can think of a good reason: that the externs file format is not part of the compiler's public API, and is liable to breaking changes in patch releases of the compiler.

---

I could potentially be persuaded to keep the current approach (as in your option 3), as long as `psc` and `psc-ide-server` act in a consistent way.

The problem is, it's not clear to me that this extra configurability helps anyone, but it's very clear to me (as a build tool maintainer) that it's detrimental. It's most obvious to build tool implementors, of course, but when build tools have to work with unnecessarily complex specifications, they will make mistakes or fail to anticipate things, and so it indirectly causes pain for everyone using the language, too.

**Comment by spicydonuts** [comment]
> Are you saying that you won't consider PureScript for your main React project until the tooling makes it easy to mix FFI and regular JS in the same directory tree?

No, I really _want_ to use it but it's very difficult to add one file at a time to an existing project with existing tooling right now (per machine Atom settings for which flags to send the compiler aren't practical, and that's one of the settings that _is_ configurable even if it's a bit tedious to do so).

> If you wanted reusable JS functions in a separate file, you'd go ahead and do it, and then require() that separate file from inside the FFI code.

It's _possible_, but only if that JS isn't in `./src`.  This discussion is about making it practical in projects that don't match the ideal of a simple PS library.  It's very difficult to do it in a large, evolving project that uses more than just PS.  Requiring the code isn't the issue, keeping regular JS from being picked up by PS tooling is.

> I can think of a good reason: that the externs file format is not part of the compiler's public API, and is liable to breaking changes in patch releases of the compiler.

Sorry, I wasn't clear.  I meant you would compile the FFI JS with something like TypeScript or Babel and just copy the PS files, so you'd have `./src` with PS and ES6 and `./dist` with PS and ES5, exactly what the compiler uses today (besides the directory name, but you should be able to indicate your source directory).  This'll be especially nice when PS starts supporting ES6 internally, since you could just remove the build step in the future.

> it's not clear to me that this extra configurability helps anyone, but it's very clear to me (as a build tool maintainer) that it's detrimental

I strongly disagree.  You said earlier that you didn't want variation because it made it more likely for two tools to break when used together.  This is true if they hardcode conflicting configuration or make bad assumptions and don't have a common config to share, but this is only considering the context of PS.  In real end-user projects (not language-specific tools and libraries) a wide array of tools and dependencies are used.  Usually that's a result of changes over time and not an irrational, one-time spree of tool adding, and it will be different for every project.  If PS really takes off the most common use case won't be clean isolation.  It will be mixed in with React and Webpack, or Angular and TypeScript, or Ember and ember-cli, or custom Backbone projects, etc.  If every tool chooses arbitrary, non-configurable rules for how it should be used you'd end up with a pile of tools that can never be used together.

With configuration there will be a little more up front work in the tooling and more "this doesn't work for this specific edge case" issues.  With no configuration there will be issues like this one, where we debate either adding configuration or changing the conventions for everyone.  The latter of those choices will become impractical quickly as the user base grows.

**Comment by spicydonuts** [comment]
Sorry for the book.  You said, "I'm not sure how this extra configurability helps anyone", but it helps me and everyone I want to share the amazingness of PS with!

**Comment by paf31** [comment]
Could someone please summarize? Specifically, is there an argument against the `.purs.js` suggestion, and if so, what is it?

**Comment by hdgarrood** [comment]
I would be very happy if we decided to have both `psc` and `psc-ide-server` locate FFI modules just by appending `.js` to the `.purs` file name, i.e. `.purs.js` like @spicydonuts suggested, replacing the current mechanism of a comment in the FFI module saying which PureScript module it corresponds to. I'm not aware of any argument against this.

**Comment by hdgarrood** [comment]
Oh, sorry, except this one: https://github.com/purescript/purescript/issues/2065#issuecomment-215725665

**Comment by kRITZCREEK** [comment]
One argument is that we dictate the filestructure layout for projects with PureScript if we do this. I like the flexibility the current approach gives one when laying out his project.

**Comment by paf31** [comment]
Well, 0.9 is going to make things stricter generally there, e.g. the one-module-per-file restriction.

**Comment by kRITZCREEK** [comment]
On the other hand this would make a java backend impractical, because the package structure wants to dictate how to lay out files.

**Comment by paf31** [comment]
Why would it affect a Java backend? Presumably `javac` would run after compilation, and we'd copy the `.purs.java` files to the right place.

**Comment by kRITZCREEK** [comment]
That works great if you use a taskrunner (`ant`, `gulp`in js land) but it won't be pretty with declarative tools like `maven` or `webpack`

**Comment by paf31** [comment]
Well I don't want to get too caught up thinking about backends which don't exist right now. @andyarvanitis, do you have any thoughts on this?

**Comment by garyb** [comment]
Avoiding having to change everything again in the future would be nice though :wink:

I've been abstaining from this discussion so far, because I keep finding ways to argue with myself whenever I start to make a point. However, I think I've just come up with a viable answer.

I'm fine with going ahead with the `.purs.js` approach, although I'm also sympathetic to the fact that removes some options to do things like Neon used to. But my thinking is this: whatever these `.purs.<ffi>` files are, they don't actually need to be source files. For the Java case, they could just be some config glue file that dictates where the actual source/class files are that need linking up, etc. The same thing applies to any backend where a second compiler pass may not accept our chosen file structure.

We could even provide some mechanism for accommodating the same with JS, so if people do want a custom layout they don't actually have to put their JS in these files, they just need to specify where they are.

**Comment by hdgarrood** [comment]
@spicydonuts I'd be interested to hear more about your project. I have to admit I don't understand where you're coming from in everything you say, for instance, what's limiting you with reusable JS functions in FFI code, or what you would accomplish by defining per machine Atom settings. However I feel like this issue might not be the best place for discussing this. Mailing list maybe? Just a quick write-up of how your project is organised and what's painful right now could be really helpful, I think.

**Comment by andyarvanitis** [comment]
Currently, the C++ backend scans for header (`.hh`) or source (`.cc`) files in the `.purs` source tree -- looking for `{path}/foo.hh` or `{path}/foo.cc` for every `{path}/foo.purs`. These end up together with the generated code in the output source tree, with the FFI sources getting a small rename to `foo_ffi.hh`in the process. There's currently no command line option to control any of this.

It doesn't really need to be exactly this way (for example, filename patterns like `foo.purs.hh` could be ok, or maybe any/all *.hh or *.cc files present could get copied over). There is some sensitivity to the output paths (and filenames) due to the C/C++ compiler needing to find the appropriate header files, but that's under the control of the C++-specific parts of `pcc` anyway.

**Comment by andyarvanitis** [comment]
Also, these C++ sources residing with the purescript sources are assumed to be FFI related, and there's no parsing of these files going on (no equivalent of `// module X.Y.Z`). Any use of non-FFI C/C++ sources/libraries is handled by the build system (e.g. Make).

**Comment by texastoland** [comment]
Was this implemented?

**Comment by kRITZCREEK** [comment]
Yes, you no longer need to put a module comment at the top of FFI files. Instead the compiler expects to find the ffi file next to the `.purs` source file with the extension changed to `.js` .

**Comment by texastoland** [comment]
But not `*.purs.js`.

**Comment by kRITZCREEK** [comment]
A conscious decision made in `0.9.1` https://github.com/purescript/purescript/releases/tag/v0.9.1 under *Foreign Function Interface Changes*.

**Comment by texastoland** [comment]
Should I create an issue to revisit in `10.0` then? The TL;DR behind the request is for other build tools to be able to treat FFI files differently than intermingled JS.

**Comment by hdgarrood** [comment]
Is there any reason for other build tools to do that now? See https://github.com/purescript/purescript/pull/2118 &mdash; I think the original issue was just that non-FFI files were being picked up and fed to `psc` on the command line, causing warnings and/or errors, and that issue was fixed by https://github.com/purescript/purescript/pull/2118. I'm not aware of any other reason you might want to distinguish FFI files from intermingled JS.

**Comment by texastoland** [comment]
I think that's true for WebPack but I'm moving toward a simpler build. As `psc` moves files to a common `output` directory wouldn't I still need a glob for the remainder of my files?

**Comment by hdgarrood** [comment]
I don't understand what you're getting at, sorry. Is the remainder of your files that you're referring to made up of FFI modules, or intermingled JS?

**Comment by texastoland** [comment]
The latter.

**Comment by hdgarrood** [comment]
It's still not clear to me why it's relevant that `psc` moves files to a common `output` directory, or why you'd need a glob for intermingled JS.

**Comment by texastoland** [comment]
Forget a common directory. Since `psc`/Pulp takes responsibility for FFI how should I pipe everything else through tools like Flow.
