### ISSUE TITLE
Integer dvision by 0 is 0

### ISSUE THREAD

**Issue by aspidites** [purescript/purescript#2089]
```purescript
> import Prelude
> 1 / 0
0
> 1.0 / 0.0
Infinity
```
I'd expect Infinity in both cases. Perhaps we should use `Math.trunc(value)` instead of `value | 0'?

**Comment by garyb** [comment]
Our `Int` type does not have `Infinity` as a value, it sticks to the int32 range, so although the behaviour isn't great, it's not entirely wrong either. Division by zero is undefined... or at least, it will officially be so according to the laws of the numeric classes in the new Prelude.

Using `Math` functions would also make integer operations much more expensive, due to the overhead of many function calls.

**Comment by aspidites** [comment]
First: That was an insanely fast reply! Second: I didn't realize that there was a new prelude in the works, and the new behavior sounds reasonable. Third: I hadn't thought about the performance implications of using Math, and I agree. 

I'll go ahead and close this since it's already being taken care of.
