### ISSUE TITLE
Unable to `npm install -g purescript` on Node 6.1.0

### ISSUE THREAD

**Issue by thunklife** [purescript/purescript#2097]
Recently install Node 6.1.0 and tried to install purescript with npm. However the postinstall script failed with:

```
node: bad option: --harmony_destructuring
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "purescript"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! purescript@0.8.5 postinstall: `node --harmony_destructuring lib/install.js`
npm ERR! Exit status 9
npm ERR!
npm ERR! Failed at the purescript@0.8.5 postinstall script 'node --harmony_destructuring lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_destructuring lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jesse/npm-debug.log
```

I saw a similar issue related to updating documentation, but nothing about installing.

**Comment by AppShipIt** [comment]
Duplicate #2075?

**Comment by thunklife** [comment]
Sure enough. Totally neglected to check the closed issues. Thanks @AppShipIt!

**Comment by AppShipIt** [comment]
Much obliged!

**Comment by hdgarrood** [comment]
Perhaps it's not worth doing now, as I think we're pretty close to releasing 0.9.0, just a suggestion for the future: since we recommend installing via npm pretty much everywhere, I think that if the npm package breaks for whatever reason, we should make a proper patch-level compiler release, where the only change is bumping the version in the cabal file, so that we can publish a new npm release and the versions continue to match up.

Which reminds me the release binary bundle building is broken and that's my fault, haha. I'll try to get that sorted soon. :) Come to think of it, is there anything else that we might be able to streamline or automate re: releases? I was also planning to look at creating OSX binary bundles on Travis at some point.
