### ISSUE TITLE
psc-ide-server becomes not responsive 

### ISSUE THREAD

**Issue by kika** [purescript/purescript#2106]
psc-ide-server accepts multiple connections to the same port, but fails to serve them independently.

Reproduce: 
1. start psc-ide-server `psc-ide-server -p 4242 --debug`
2. `psc-ide-client -p 4242` on terminal 1
3. `psc-ide-client -p 4242` on terminal 2
4. Issue `{"command":"cwd"}` on terminal 2 - no response
5. Issue `{"command":"cwd"}` on terminal 1 - gives response on both 1 and 2

The debug log suggests that the connects are queued and client 2 becomes dependent on what client 1 does. For the application using client 2, the server appears hung, though. 

IMHO, the server should either do not accept the second connect or serve it concurrently.

**Comment by kRITZCREEK** [comment]
What's going on with your pc?? :D I can not reproduce this either...

```
~ 7s
> telnet localhost 4242 
Trying ::1...
Connection failed: Verbindungsaufbau abgelehnt
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

{"result":"Error parsing Command.","resultType":"error"}
Connection closed by foreign host.
                                                                                                                                  
~
> psc-ide-client        
{"command":"cwd"}
{"result":"/home/creek/Documents/pscid","resultType":"success"}
```

**Comment by paf31** [comment]
Is this a buffering issue maybe?

**Comment by paf31** [comment]
Can this be combined with the other issue? I know they're not exactly the same, but they seem related.

**Comment by kRITZCREEK** [comment]
Hmm the socket should be line buffered but both psc-ide-server and psc-ide-client set that. Also when I use telnet on my end it seems to be line buffered.

**Comment by kika** [comment]
I changed the wording of the issue completely after having the coffee.

**Comment by kika** [comment]
So yes, it was hung, but because of the second client connected.

**Comment by kRITZCREEK** [comment]
I do not want to introduce race conditions unless we have a really good reason to do so. I could see us wanting this if we make the pursuit commands more useful since they take some time (latency). 

Right now no command takes a long time and it seems like we are easily responsive enough to provide a fluent editiing experience. So applications talking to psc-ide should make sure to fully assemble their commands before sending it to psc-ide.

Dropping commands will drastically increase the complexity on the editor side and I don't think it's worth it because editing usually is a sequential process.

**Comment by paf31** [comment]
@kRITZCREEK Any thoughts on what to do with this?

**Comment by kRITZCREEK** [comment]
I'm going to say this is "working as intended". `psc-ide-server` serves requests sequentially and blocking, but is able to hold a few connections open and serve them in a FIFO order.
