### ISSUE TITLE
Problem with `Partial` constraints and function composition

### ISSUE THREAD

**Issue by menelaos** [purescript/purescript#2194]
There seems to be an issue when using `unsafePartial` together with `<<<`:

```purescript
module Main where

import Control.Monad.Eff.Console ( log )
import Data.Maybe ( Maybe (..), fromJust )
import Partial.Unsafe ( unsafePartial )
import Prelude

main = do
  let
-- Does not compile
--    hello = unsafePartial <<< fromJust $ (Just "Hello World!")

-- Does compile
    hello = unsafePartial (fromJust (Just "Hello World!"))

  log hello
```

In the first case, the following error is thrown

```
 Could not match constrained type
                   
    (Partial) => t0
                   
  with type
          
    String
```

**Comment by paf31** [comment]
This is by design. I also thought this was a bug when I first saw it, but if you think about it, what is the scope of the `Partial` constraint?

Another way of thinking about this is that you are trying to instantiate the type of `<<<` impredicatively. I suspect giving a type signature for `<<<` would fix the problem.

My workaround is this: `unsafePartial (fromJust (Just "Hello World!"))`
