### ISSUE TITLE
Add position information to types and data constructors

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2216]
This would allow `psc-ide` to jump to the definition site of data constructors, aswell as `psc-docs` to extract docstrings for them. 

We could also improve Errors around mistakes when declaring data constructors. For example:

``` purescript
data List a
  = Nil
  | Cons a List
```

Currently points at the `data` with the error message:

```
  Could not match kind

    * -> *

  with kind

    *

in type constructor List

```

I think it would be a lot better to point the user at the data constructor `Cons` instead of the type constructor `List`, because that suggests he should be changing the LHS of his definition.

**Comment by paf31** [comment]
Note, we don't even have a `PositionedType` right now.

**Comment by garyb** [comment]
*whispers* `Mu` and `Cofree` :smiling_imp: 

In all seriousness, I want to explore that approach on a branch soon (for `CoreFn`, because it's simpler) as our current representations are pretty inelegant, and extremely error prone when traversed directly, and adding more positioned constructors will compound the problems.

**Comment by jdegoes** [comment]
> whispers Mu and Cofree 😈

They are, of course, *noticeably* slower. But far more elegant and robust.

**Comment by paf31** [comment]
I agree they're more elegant. I decided not to use `Cofree` for the first version because that requires every contributor to understand `Cofree`, essentially, since these modules are used by pretty much everything in the system. I would also use `bound` if that wasn't a concern.

**Comment by garyb** [comment]
It's not so much the inelegance that bothers me as the number of times I've been bitten by `Positioned`-related issues - while working on things and it being tricky to track down what the cause is (remembering to re-wrap as well as extract positioned things - there was some point futher along in the compiler that broke when I accidentally erased position info), and there have been bugs that made it into releases that were purely due to cases being missed due to missing position-unwraps.

**Comment by garyb** [comment]
I can only imagine the chaos that will ensue by positioning types in the way we do decls/exprs, as _every_ pattern involving types will need to be updated accordingly too.

**Comment by paf31** [comment]
But how does `Cofree` help there? Presumably we can still forget to deal with position information. I suppose the standard recursion scheme for `Cofree` will tend to push us in the right direction in most cases.

**Comment by jdegoes** [comment]
You can not only ensure annotation of all nodes (if you desire), but you can make the ADTs much more flexible, combining `Coproduct` of individual terms (functors) to allow transformations to add and remove information through the phases of a compiler in a totally type safe way.

The technique has incredible power, however, it makes the code more difficult to contribute to for beginners and does have some performance overhead.

**Comment by paf31** [comment]
I think a good first step would be to parameterize things with some type annotation instead of fixing just position information. That way, we can add a `Comonad` instance later if we find ourselves redecorating trees often, without pulling in the dependencies now and adding the extra cognitive overhead. In the short term, we can derive `Functor` and `Traversable` which will be very useful for some simple traversals.

**Comment by kRITZCREEK** [comment]
I'll close this one, as the error in the issue is now what we'd like it to be.
