### ISSUE TITLE
Punning record updates

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript#2255]
Moved from #2250:

```purs
f baz = g
  { foo = "bar"
  , baz -- punny
  }
{-
  Unable to parse module:
  unexpected {
  expecting no indentation or end of input
-}
```

Does update syntax not support punning to prevent ambiguity with literals when all fields are punned? Would it be sensible to interpret it as un update if there's at least one `=`? I don't feel strongly but it did confuse me for 5 minutes till I realized updates don't mirror literals.

**Comment by garyb** [comment]
Yeah, it's not supported because it's ambiguous. I don't think we should support it even if there is another field with an `=` to disambiguate, as I think it would be strange that the meaning changes entirely when you add or remove a field with an `=`: it would become a type error too, rather than a syntactic one, perhaps further confusing matters.

Updating seems to be in a different category than constructing or pattern matching to me, it's an instruction to explicitly change this thing to be that other thing, whereas in pattern matching and construction you're just carrying a name through - not requiring the `=` part makes it coffescriptesque in its vagueness of intent, IMO.

**Comment by texastoland** [comment]
Makes sense.
