### ISSUE TITLE
Don't export modules that conflict with other packages

### ISSUE THREAD

**Issue by DanBurton** [purescript/purescript#2293]
It would be nice if purescript-the-library didn't export modules like `Control.Monad.Logger`, because these conflict with their counterparts in other packages (e.g. `monad-logger`).

This causes problems like the following: https://github.com/fpco/stackage/issues/1831. While I'd like there to be a fix in doctest for this, it's still poor form for the Haskell ecosystem to have conflicting module names like this.

Possible alternatives are:
* name your modules differently
* use the "canonical" package dependencies for these modules

**Comment by hdgarrood** [comment]
Is it just `Control.Monad.Logger` that's causing problems, or are there others? Also what do you mean by 'a fix in doctest'?

**Comment by bergmark** [comment]
doctest issue: https://github.com/sol/doctest/issues/119

For purescript, why not put everything under `PureScript.*`? Why is it so important that the logger  is a Monad specifically? :-)

**Comment by hdgarrood** [comment]
Ah, I see, thanks. Yeah, I'd personally vote to rename it to `Language.PureScript.Util.Logger`, and likewise perhaps it would be better to rename `Control.Monad.Supply.*` to `Language.PureScript.Util.Supply.*`.

**Comment by paf31** [comment]
I think I would actually like to just have PureScript removed from Stackage. I like using Stack for builds, but I don't see any need for us to be in Stackage. Maybe this is a good time to decide on this.

To answer the immediate question:

> While I'd like there to be a fix in doctest for this, it's still poor form for the Haskell ecosystem to have conflicting module names like this.

Why is this poor form? There is no scheme for agreeing on who gets to claim a module name that I'm aware of, other than who got there first. My understanding is that you would typically use package-qualified imports to solve this sort of thing.

**Comment by DanBurton** [comment]
> There is no scheme for agreeing on who gets to claim a module name that I'm aware of

It's first come first served, for the most part. It's also quite customary for the package name to be somehow included in all of the modules that a package exports.

> My understanding is that you would typically use package-qualified imports to solve this sort of thing.

Yes, but this places the burden on the user to use package imports; it's extremely rare to need this. It's simpler if packages agree not to step on each others' toes.

**Comment by bergmark** [comment]
> I think I would actually like to just have PureScript removed from Stackage. I like using Stack for builds, but I don't see any need for us to be in Stackage. Maybe this is a good time to decide on this.

Having purescript only be part of LTS is another option that should create less less work for you. That has the benefit of `stack install purescript --resolver lts` still working.

**Comment by DanBurton** [comment]
purescript doesn't even have to be part of lts to reap this benefit per se. It can just be treated as an extra-dep.

**Comment by hdgarrood** [comment]
> I think I would actually like to just have PureScript removed from Stackage

It won't surprise anyone who saw the discussion on #2278 that I'm in favour of this, too. :) I went into more detail about why I think that would make sense there (unfortunately it's not very concise though).

Now that #2294 is in, I don't think there's anything preventing us from removing PureScript from Stackage, other than that it might be worth waiting until after we've made a release that contains those changes, so that people who download the latest release don't get out-of-date documentation.

Having PureScript in LTS is still making a commitment to keep it building with everything else in that LTS, essentially, right? Because I don't think it makes sense for us to make that commitment. In particular, we can't just push a new release out after making updates for any upstream library changes, because there are a bunch of other things that need to be coordinated with any PureScript release, such as libraries, documentation, Pursuit, build tools, etc.

Incidentally we're trying to discourage people from doing `stack install purescript` entirely, because it usually gives you an out-of-date version (even with `--resolver nightly`), and also because it will probably pick a set of dependencies that have never been tested together. Recently I've been updating the documentation to use `stack unpack purescript` followed by `stack install`, which doesn't have either of these problems.

**Comment by phadej** [comment]
I might play a devils advocate here, but 

> Incidentally we're trying to discourage people from doing `stack install purescript `entirely, because it usually gives you an out-of-date version (even with `--resolver nightly`), and also because **it will probably pick a set of dependencies that have never been tested together**.

What's the reason to have `purescript` on Hackage then? People will try to `cabal install purescript`. As development of `purescript` is done with `stack` now, it's very likely they will get  a set of dependencies that never been tested together. If they succeed to build `purescript` in the first place (http://matrix.hackage.haskell.org/package/purescript looks quite red atm).

**Comment by kRITZCREEK** [comment]
>  What's the reason to have purescript on Hackage then?

Well there's value in developing against purescript as a library. `psc-ide` started like that and being able to depend on the compiler and develop against it makes for an easy starting point.

The only thing we want to prevent is for anyone to use the binaries produced by installing with a different dependency set.

**Comment by hdgarrood** [comment]
Yeah, exactly. It's not that I think it's very likely that a new set of dependencies will break things, but it is a nonzero risk and there's no reason to expose people who just want to use the compiler to that. For people who want to use `purescript` as a library, then having it available on Hackage with the version bounds not being too tightly locked down seems to me to be best.

**Comment by agrafix** [comment]
Please don't move `purescript` of hackage! Keeping it on stackage is a bonus for me, but future releases to hackage would be awesome :-)

**Comment by phadej** [comment]
@hdgarrood so you want
- keep the `purescript` the **library** for people to build on
- restrict how `psc` the **executable** is installed.

In that case, you should consider splitting the executables into a separate package, say `purescript-executables`. With `stack` multi-package projects are trivial. Then you could have `purescript` the library on Hackage (and Stackage), but if you can have different policy for `purescript-executables`.

**Comment by hdgarrood** [comment]
The idea of putting the executables in a separate package does sound good, apart from that (afaik) the library sees very little direct use, and so I don't think it would be worth the extra effort of having a second package. I don't think we really want to do anything that makes pushing releases out any more fiddly than it is at the moment.

**Comment by paf31** [comment]
Closing, since we're not in Stackage nightly any more anyway. We might deal with the namespace conflict later, but for now I'm not too concerned about it, since `purescript` is rarely (not never) used as a library anyway. 

@phadej makes an interesting point about Hackage. I would also consider removing PureScript from Hackage eventually, but the difference there is that it is harder to install extra dependencies with Cabal than with Stack, so I think it continues to provide some benefit for now.

**Comment by mgsloan** [comment]
Hey all!  Pointed to this issue by hvr.  In the future, `stack install purescript` will likely use the `stack.yaml` packaged in the sdist.  See this issue https://github.com/commercialhaskell/stack/issues/2122

Would this resolve the issue?

**Comment by hdgarrood** [comment]
@mgsloan awesome, thanks for the info! I think it would indeed resolve that issue.

**Comment by tonymorris** [comment]
A beginner, just this morning, was having trouble installing purescript and was "going to use Elm because the documentation is better." Puzzled, and not having used purescript for a while, I wondered what was going on. So I installed purescript `cabal install purescript` which went fine, then I dug deeper, trying to find out why my friend, with very little experience, was having trouble.

The install documentation does not have instructions for cabal. My friend has made the mistake of using stack. This was the second time I've had to pick up the pieces for him, for using stack. I explained to him once again, that stack is terrible for beginners, and that I generally bump into a "beginner who fell for stack" about once per week. I think he needed to fall a second time to know I was serious.

Anyway, please do not purescript from hackage. It installed straight away, into a sandbox, so there is no conflict. And now we are both using purescript.

**Comment by bergmark** [comment]
The first thing listed on the download page is the ready made binaries. Is there a reason those weren't used?

Neither stack nor cabal-install are fool proof ways to install executables, especially not when not used with a freeze file. But as far as I can tell the stack instructions on the website are correct. They use the freeze file distributed with the package. I'm guessing this user tried to `stack install purescript` by itself.
