### ISSUE TITLE
Warn when recursive functions cannot be optimized

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript#2359]
Some collection functions in core lib crash in the case the collections are getting too big. (For example foldM in purescript-arrays). This is of course very unfortunate, because the type system should generally make the generated code safe, so that no runtime crashes should occur.

What I propose is:
1. Make all possible functions tail recursive. 
2. If this is impossible for some functions, warn about usage. This can e.g. be realized as a compiler warning generated for recursive JavaScript functions.

**Comment by garyb** [comment]
:+1:

I think we'll have to use `tailRecM` for some cases, like `foldM` most likely, which sometimes can introduce a slight performance penalty if the monad is already stack safe (/cc @natefaubion), but I'm sure we can figure something out.

**Comment by natefaubion** [comment]
> which sometimes can introduce a slight performance penalty if the monad is already stack safe

`tailRecM` doubles the number of binds and incurs an `Either` allocation for every step for safety. I think this is _slightly_ more than "slight". :)

**Comment by paf31** [comment]
I'm quite torn on this issue. On the one hand, there isn't really a good reason to make something like `foldM` using `MonadRec`.

But consider something like `traverse` - we could change it to use `MonadRec` instead of `Applicative` and make some instances safe, but at the cost of being able to apply it to something like `Const` (thereby rendering all of `profunctor-lenses` essentially useless). But I can't think of any way to keep `Applicative` and have a general, stack-safe `traverse`.

Alternatively, we can just document those functions which are not stack safe in general, and provide helper types like `Trampoline` or `FreeT` which can be used to make things stack safe.

As for warning whenever a function is not tail recursive, that seems fine, although there are probably cases involving self-application where the warning would not fire and we'd still have problems.

**Comment by jdegoes** [comment]
> tailRecM doubles the number of binds and incurs an Either allocation for every step for safety. I think this is slightly more than "slight". :)

Yes. We can workaround the issue in `Free`, if we want, by adding a special case term for `tailRecM`. Alternately, maybe one could implement a `Free` variant on top of a `tailRecM`-type encoding.

**Comment by nwolverson** [comment]
"warning whenever a function is not tail recursive" - if this is a compiler warning this seems undesirable in general, not all calls are or can be tail calls. Thoughts from F# land https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663074-enable-a-compiler-warning-when-a-recursive-algorit

(Though saying that I guess you can just try it and see if it is too irritating.)

**Comment by paf31** [comment]
I think documentation might be enough. The F# post brings up a good point - would you really want to warn on something like `Data.Map.insert` which uses a logarithmic amount of stack compared to the size of the input map? How would you differentiate between that and something like `forever`?

Another interesting option is to use the type system, like we do with `Partial` constraints, by adding a `GeneralRecursion` constraint. The tricky part there is finding a way to insert the constraint before the typechecker runs.

**Comment by hdgarrood** [comment]
I vote to close this: I think the proposal as it stands now would result in too many false positives, such as `Data.Map.insert`, and there's been no movement on this issue in over 2 years.

**Comment by natefaubion** [comment]
I'm more inclined to introduce optimizations for `tailRec` which remove the overhead.
