### ISSUE TITLE
Closed classes

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript#2390]
Sometimes the need to close a class (i.e. prevent other modules from adding instances) arises. In Haskell you can close a type class by giving it an unexported superclass. However PureScript requires that all superclasses and methods are exported. I don't see a way around this so maybe it is a good idea to allow specifying instantiatability in the export list? E.g. `module M ( closed class C ) where`.

**Comment by garyb** [comment]
I can't say I particularly like the idea of closed classes (I wouldn't presume to know that it's never sensible to extend a class again - and with no-orphans it seems even less useful, since people will have to define their own types to be able to make instances, meaning only their projects & dependants will be able to use the extended instances), but if we implement instance chains, this might happen anyway since I'm not sure if there's a reasonable way to define chains in an open setting. I actually hope we can come up with a way of sensibly avoiding that restriction though.

**Comment by kRITZCREEK** [comment]
https://github.com/purescript/purescript-type-equality/blob/master/src/Type/Equality.purs is an example of a "closed" class. I don't think this very special case is enough to warrant an extension of the export mechanism though...

**Comment by paf31** [comment]
👎 from me, we get a natural notion of closedness from the overlap check, as @kRITZCREEK pointed out. Instance chains will let us define locally-closed sets of instances in the longer term too.

**Comment by paf31** [comment]
Any other thoughts on this one?

**Comment by paf31** [comment]
Closing this, at least until we have a good motivating use case.
