### ISSUE TITLE
Functional dependencies can make instances unusable

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2394]
While trying to get `-parallel` into shape I tried to move `ParCont` out of the `Class` module, as it doesn't look like it has any reason to be there - it could depend on the `Class` module. However, when doing so, the tests start failing:

```
Control.Parallel.Class.Parallel t0
                                    (ContT Unit
                                       (Eff
                                          ( http :: HTTP
                                          , console :: CONSOLE
                                          | eff1
                                          )
                                       )
                                    )
```

I found this very surprising, and I'm pretty sure it's not right - instances are supposed to be global, so it shouldn't matter if the `Parallel (ParCont m) (ContT Unit m)` instance is defined alongside the `Parallel` class or not.

**Comment by paf31** [comment]
I'll try to have a look at this later today.

**Comment by paf31** [comment]
What's going on here is that we only check modules which are mentioned in the instance head. So in the example you gave, we will check the modules which define `Parallel`, `ContT`, `Eff`, `Unit`, `HTTP`, and `CONSOLE`. But the instance for `ParCont` is not defined in any of those!

So I think that we need to modify our orphan instance rule so that instances like the one above are considered orphaned if they are not defined in one of those modules.

**Comment by garyb** [comment]
Since there's a bidirectional fundep here that still doesn't seem right to me - I would have thought we could use that to resolve the instance.

Assuming there's some problem with that I'm not seeing, how would we even determine this is an orphan? By which I mean, I'm not sure what the rule would be, since instance head definition doesn't suggest orphan in any way, it only seems to arise during inference from one of its members.

**Comment by paf31** [comment]
How does the bidirectional fundep help though? The problem is that we don't look in the right module, because we have no hints from the type as to where it might be.

The orphan rule has to take into account any minimal covering sets for the instance head. In this case, there are two sets, the one including only the first argument, and the one including only the second. We have to take the intersection of the modules inferred by those minimal sets. The only module used by the first would be the module which `ParCont` is defined in. The modules for the second set are the ones which define `ContT`, `Eff`, `Unit`, `HTTP`, and `CONSOLE`. The intersection is empty, so the only solutions are to put the instance with the class or to move `ParCont` into one of the modules listed above.

**Comment by natefaubion** [comment]
> How does the bidirectional fundep help though?

I think intuitively you could say that in this case you should use the union of modules inferred by those sets, since the variables determine each other.

**Comment by paf31** [comment]
Conversely though, you need less information to commit to the instance. I don't think there's a good way to allow the instance to be moved without a significant slowdown in the compiler, since we'll have to check every module for instances.

**Comment by paf31** [comment]
I think we can probably use @LiamGoodacre's recent work here. The orphan instance check just needs to be modified to only allow instances in types mentioned in the non-determined type arguments of the class.

**Comment by LiamGoodacre** [comment]
@paf31 so the head types of all the non-fully-determined arguments must be defined in the same module for an instance in the same module to not be an orphan (or have the instance defined with the class)?  That makes sense to me.  I can make a start on this if you like?

**Comment by paf31** [comment]
@LiamGoodacre Suppose we have `class Foo a b | a -> b, b -> a`, so that `a` and `b` are in the same strongly-connected component. Then an instance `Foo M.A N.B` is only non-orphaned if either

- `M = N`
- or the instance is defined with the class.

This is because the solver might commit to an instance given only partial information in the presence of functional dependencies.

For example, if the instance is defined in module `M`, and if the solver sees `Foo M.A _`, then it can look in `M` and find the instance, and infer `b`. But if the solver sees `Foo _ N.B`, then it will only look in `N` and not find the instance unless `M = N`.

So when deciding which modules a non-orphan instance can live in, we have to consider which arguments might be inferred. We need to find any covering sets for the set of type arguments (minimal sets of arguments which can be used to infer the remaining arguments) and take the _intersection_ of the modules mentioned in each of those sets.

**Comment by garyb** [comment]
While it would be nice to at least know when this is going to happen, I'm still not entirely clear on why we can't fix it to work "properly". Since we don't allow orphan instances it seems we should be able to have all instances in a global scope when it comes to resolving them?

**Comment by LiamGoodacre** [comment]
@garyb, I consider Phil's explanation to be fixing it "properly" :) - our orphan instance check needs to be updated.  If the instance is in some module other than those Phil described, it would indeed be an orphan.  Non-orphan instances will always be picked up when solving - because once we're solving for a covering set, we will already be looking in the collection of modules that the instance is allowed to be defined in.  (I think).

**Comment by garyb** [comment]
It does fix it for sure, but only by introducing rules that seem a little arbitrary given there's a "simpler" fix. Well, less restrictive anyway.

**Comment by paf31** [comment]
What's the simpler fix?

**Comment by LiamGoodacre** [comment]
@garyb You mean, allow orphans?

**Comment by garyb** [comment]
In answering this I've just talked myself into agreeing that the restrictive fix is the right approach, so, for future reference:

I guess I do see where you're coming from now, in that with an `a -> b, b -> a` it means you can end up with overlaps, much the same as would occur if orphans were allowed. It's not exactly the same as the orphans case, but the consequences are similar, in that two libraries could define an instance with an alternative `b` for an `a` or vice versa, but if the fundeps are taken into account when determining orphan rules then this becomes impossible.

**Comment by LiamGoodacre** [comment]
I have an update nearly ready for this.  Hopefully have a PR open tomorrow.
