### ISSUE TITLE
Module vs Package vs File names

### ISSUE THREAD

**Issue by ivan-kleshnin** [purescript/purescript#2415]
## Haskell-like module system is a problem.

1. You never know which package exposes a module.

### Node

```js
// WHAT I SEE               // WHAT I THINK

import Math from "math"     // npm install math (or system module)
import Global from "global" // npm install global (or system module)
```

### PureScript / Haskell

```purs
-- WHAT I SEE     -- WHAT I THINK

import Math       -- bower install purescript-math (right)
import Global     -- bower install purescript-global (wrong: it's purescript-globals)
import Data.Show  -- ??? (it's a system module)
import Data.List  -- ??? (bower install purescript-lists, -s suffix)
import Control.Plus -- bower install purescript-control (one-to-one again...)   
```

2. Now things get even worse when implicit imports are used

```hs
import Pumpkins

map foo bar -- where map is located? how to find the file?! and the package?!
```

I asked about the same problem in Haskell thread:

http://stackoverflow.com/questions/37960849/find-function-source-in-haskell-workflow

and Haskell, at least, provide a workaround for the second problem:

```
> :i catMaybes
catMaybes :: [Maybe a] -> [a]   -- Defined in ‘Data.Maybe’
```

**Defined in ‘Data.Maybe** – fine

In PureScript it does not work:

```
> :i map
Unrecognized directive. Type :? for help.
```

From the other side, in PureScript only one implicit import is allowed, which is great!

3. As PureScript is split onto tons of micro-modules, the problem amplifies. 

So what do I propose? I have little knowledge of PS and Haskell to really advice something.
My gut instinct wants to unify all three: packages, modules and files / folders like it is in Node. 

If it's not possible or not desirable for some reason - please document at least how modules and packages are supposed to relate. How, by seeing `import Data.List` I should immediately know it comes from `purescript-lists`. It's hard to play this game of guessing.

**Comment by rightfold** [comment]
GHC has the `PackageImports` language extension. They allow you to import modules from specific packages:

    import "base64" Data.ByteString.Base64

**Comment by paf31** [comment]
You can use Pursuit to find modules. We're aware of the issue though, and I'd like to change some of the module names eventually to reflect the package names.

**Comment by paf31** [comment]
Also, there is an open issue already for `:info` support in PSCi.

**Comment by kRITZCREEK** [comment]
If we wanted the compiler tooling to give information about packages, we'd first need to define what a package means to the compiler. Right now we just use globs to grab all the files and pass those to the compiler.

**Comment by ivan-kleshnin** [comment]
@rightfold unfortunately I have no idea what the quoted code is supposed to do 😞 

> You can use Pursuit to find modules

Yes. But it's a solution to a problem which does not even exist in other programming communities. I'm unable to find a single benefit such packaging system brings. 
Drops one level of nesting? 

It's not fine to google every single import line in each file when I exlore other people's repositores. I believe you guys may underestimate the scale of the problem because PS is developed by a small team where everyone basically tracks each other and is perfectly aware what's going on.

To you it's probably like this:
> Data.List? It's easy – just download purescript-lists which @garyb updated yesterday!

But it's almost totally obscure for outsiders especially with different programming cultures.

---

I'm happy to hear you're going to address this eventually.

**Comment by paf31** [comment]
We understand the problem, it's just that fixing it is not an immediate priority, since we have other ways to communicate that information right now.

Also note that `psc-ide` and editor plugins can look up functions by name and show you the possible modules they came from.

**Comment by paf31** [comment]
Closing, since these things are tracked elsewhere.

**Comment by hdgarrood** [comment]
Where else are these things tracked?

Also, I think I may have said this elsewhere already, but I'm really glad to see this raised - I think the current situation is avoidable, and I would really love to see language changes to address this problem, rather than just convention, as I am not convinced that a convention will be enough to really fix it.

I completely agree that we shouldn't have to make the compiler aware of packages, but would it not be enough for a "package", as far as the compiler is concerned, to just be a unique string (its name) together with a collection of modules, whose names only have to be unique within the package?

**Comment by paf31** [comment]
Relevant to `:info`: #1136, #994

Another option for package names is to say that a package is any common prefix of the module name, so `Lists` and `Lists.Lazy` could go in `purescript-lists`. That doesn't give you a single module to look for, but it vastly reduces the search space.

Another option is to handle this using package sets, since module names might not be unique overall, but certainly should be unique in a package set.

Also note, we have some _features_ (not open issues) which document partial solutions:

- Go to definition and completions in `psc-ide`
- Search in Pursuit

I know we've discussed the package/module name issue before, but I can't find the issue. Maybe it was on IRC. In any case, this should be closed and broken down into individual issues IMO.

**Comment by hdgarrood** [comment]
> In any case, this should be closed and broken down into individual issues IMO.

:+1:, then I might submit a new issue concerning only what I said in my previous comment (if nobody beats me to it, that is).

**Comment by joneshf** [comment]
Aside:

> # Node
> 
> ```js
> // WHAT I SEE               // WHAT I THINK
> 
> import Math from "math"     // npm install math (or system module)
> import Global from "global" // npm install global (or system module)
> ```

Is that really true with npm? I want to say in the past I've tried to do exactly that and it didn't work because the module wasn't named how you import it.

**Comment by ivan-kleshnin** [comment]
@joneshf yes it's correct syntax. The only nitpick is that ES module system is not fully standardized yet (but I'm pretty sure this syntax will stay).

**Comment by joneshf** [comment]
I meant, is the mapping from what you type in the source file `"math"` to what you install from npm `npm i math` true? I could've sworn you can have a package importable as `"foo"`, but installable as `npm i bar`.

**Comment by hdgarrood** [comment]
I guess that since there's a multitude of options for transforming your JS before you actually give it to `node`, in general anything could happen. I've worked on a project that used RequireJS, which can remap some modules to different modules, so when you require("foo"), you might actually end up requiring "bar", if "foo" is mapped to "bar" in some config file.

If that isn't happening though, i.e. `import Math from "math"` is being transformed to `var Math = require("math")` (which is the obvious way to transform it, afaik) then yes, `require("math")` will go into `node_modules` and look for a `math/index.js` or similar. As long as you aren't fiddling with `node_modules` manually, I think it's safe to assume that the only stuff that would ever go there would be from the `math` package on npm. Docs: https://nodejs.org/api/modules.html#modules_all_together

**Comment by joneshf** [comment]
Nah, definitely wasn't any of that stuff. Might have just been that the module name doesn't have to match the repo name. I dunno. It's pretty far astray from the topic, so I'll stop.

**Comment by garyb** [comment]
> Might have just been that the module name doesn't have to match the repo name. I dunno. 

I think that's probably it. I know what you're talking about, as I've encountered the same thing for sure.

**Comment by srghma** [comment]
Let's make `PackageImport` required in purescript

```
import "base64" Data.ByteString.Base64
```

**Comment by wclr** [comment]
Not sure why I skipped this one when I prepared [the proposal](https://discourse.purescript.org/t/proposal-on-purescript-package-management/2245), but here are just other pieces of evidence that package/library names and module namespaces are redundant coming together. And a more correct solution would be basically to get rid of one of them, not to try to align or conciliate them in some other way as this would be a palliative, not a resolution, how to make this in the right way I tried to describe in the proposal.
