### ISSUE TITLE
Packaging, Plans and package-sets

### ISSUE THREAD

**Issue by damncabbage** [purescript/purescript#2423]
Hello,

I popped into IRC yesterday to ask some questions about psc-package. They boil down to a few things:
* How does a package end up in a package-set? How does an app (which _uses_ a package-set) get developed vs a library (which almost needs to _already be in_ the package-set)?
* Do packages retain individual dependency constraints, or are they versionless within a particular package-set? If they are versionless, which version is chosen, and if the only check is "they don't error when compiled together", what distinguishes choosing a version that compiles against a compiling-and-correct `foo :: String -> Boolean` from a compiling-but-_broken_ `foo :: String -> Boolean`? And as a library author how do I select which of these end up in a given set?
* `psc-package` is now in `purescript/purescript` master, `package-sets` is part of the purescript org, and people now have the binary alongside the other `psc-*` tools; `psc-package` is arguably the canonical direction packaging is taking, experimental or not. Something new *not* based on the Stackage-alike approach (eg. something using Bower constraints) could split the PureScript community. Could there possibly have been something on the mailing list or elsewhere about switching registries and approaches entirely before this got put into master and pushed out?

The full chat I had with @garyb is here: http://ircbrowse.net/browse/purescript?id=429372&timestamp=1478565982#t1478565982

(On a meta note: I don't know how to discuss this. On one hand, you're all OSS maintainers, and OSS maintainers get a lot of (pardon me) shit from people who don't contribute back. On the other hand, this is changing the direction that a community is going to take; anyone not keeping up with change is going to end up in a pocket universe of only code they personally write, and community network effects make for some powerful inertia to keep going down a path that's been set. I'm worried this is moving a bit quick and will have long-lasting effects. I hope I've come across in my message as worried-but-polite, but I apologise if I haven't.)

**Comment by hdgarrood** [comment]
Just before I respond properly I'd like to check if I am on the same page with others in the following:

I would really prefer to avoid a situation where a library is required to be in any package set. I think it's very important that libraries which aren't in any package sets are easy to depend on (i.e. something like Stack's extra-deps); if I've understood correctly, having a package in a package set implies a responsiveness commitment that many maintainers will not want or be able to make. IMO our packaging solution should allow you to decide where you want to sit on the spectrum with classic dependency solving for all dependencies at one end and relying solely on package sets at the other end. So I think libraries should still specify version bounds and not only depend on package sets (the same way it works currently with Stack+Stackage). This is not how psc-package appears to work currently - reading the code, it seems that psc-package will exit with a failure exit code if you ask for a package which does not exist in the set you've specified. So assuming that people agree with me that we don't want to require that packages exist in package sets, I guess either we will want to build tools which wrap psc-package or build out psc-package to handle cases where you depend on packages that aren't in a set.

**Comment by garyb** [comment]
> @damncabbage: ... vs a library (which almost needs to already be in the package-set)?

@paf31 I would love to know the answer to this too, have you given it any thought? 😛 

> @damncabbage: How does a package end up in a package-set?

At the moment, it's a case of submitting a PR to `package-sets`, updating the `packages.json` file. It's not exactly painless.

> @damncabbage: Do packages retain individual dependency constraints, or are they versionless within a particular package-set?

They are versionless - part of the idea of a package set is you are guaranteed that compiling with it in the future will give you exactly the same result as it does now, meaning every dependency has to be exactly specified. Given that, I'm not exactly sure what you mean by "which version is chosen?" since the version (tag/hash) of a dependency is part of its definition in the package set.

This does mean that any time any library changes, even for a patch, there needs to be an update made to the `package-sets` registry to increment the version - doing so essentially produces a new package set that would then need to be referenced by its commit hash to get the package set with the updated library until a new tagged package set release is made - whether that is weekly or at some other arbitrary point is yet to be determined.

> @hdgarrood: I think it's very important that libraries which aren't in any package sets are easy to depend on (i.e. something like Stack's extra-deps)

Yeah, non-package-set dependencies at an absolute minimum seem like a hard requirement to me before `psc-package` is really usable.

> @hdgarrood: IMO our packaging solution should allow you to decide where you want to sit on the spectrum with classic dependency solving for all dependencies at one end and relying solely on package sets at the other end.

Agreed, that would be the ideal in my book too. I'm not really sure how well the two would mix, but if we could come up with something sensible it'd be great.

**Comment by damncabbage** [comment]
> @garyb: They are versionless (edit: on re-read, we're perhaps referring to two different things here, hopefully the following paragraphs cover it - but to be totally clear, by "versionless" I mean there is no attempt to do any kind of version resolution, "it's just a hash")

I agree we're probably talking about different things. This is little hard to talk about without answering the "how do we add libraries to a package-set" question, but I'll try a different tack; let's think of this scenario:
* A package "version", in the package-setverse, is a chunk of code we can find with a package name and the version of a package set it belongs to. I may be incorrect in this assertion.
* I have a library, `foobar`. It depends on, say, `transformers`.
* Say a new package set doesn't exist yet, or it's in the process of being created. What am I depending on if I just say "transformers"? The version of `transformers` from the last package set (implicitly), unless it's bumped for the new package set? And what if `transformers` itself is bumped in the new package-set? There seems to be an awful lot of shuffling around, and no safety beyond "it compiles together", which is not exactly the strongest of guarantees.  

Separately, my previous open question still applies (as in, not for @garyb specifically): why is this in `master` already?

**Comment by paf31** [comment]
I don't have long, but here is the high-level summary as I see it:

- `extra-deps` should be added to `psc-package.json`. I outlined this in the original PR.
- there is no "the" package set, the whole point is that it should be very simple to create a custom package set if the default one doesn't fit your needs, so that is another solution to the library problem, if you find yourself (as a company for example) requiring many `extra-deps`
- `psc-package` is in `master` and marked as experimental, so that people can try it out and so that we can gather feedback. I tried gathering feedback by suggesting people build from source, but that rarely gets much traction. Note, we've done this with other features before - rank n types and fundeps, and they do tend to get more adoption than experimental features probably should, but I think this one is probably okay, since it's not a feature that will see viral adoption via libraries. The worst case is that some library starts only using `psc-package` for distribution, and then it just won't be adopted by others immediately.

**Comment by paf31** [comment]
Here are some other things I would like to discuss regarding `psc-package`:

- Can it be integrated into Pulp? What work is involved there? (cc @bodil and @hdgarrood)
- Can we consolidate `package-sets` and Pursuit somehow? Specifically, does it make sense to generate documentation for the whole package set on a regular basis, and serve it statically (Pursuit would continue to implement search, and probably much of the rendering code would come from Pursuit). I quite like this idea if `pulp publish` can help developers to easily update the package set repo.

**Comment by hdgarrood** [comment]
What does pulp integration mean? I'm uneasy about encoding into Pulp the idea that publishing a new version of a library always involves updating a package set, because then how do we deal with cases where not everything builds together? For example, suppose packages A and B are developed by separate authors. A is published first and put into a package set. Then, B is created, which depends on A, from that package set. Then, A is updated with a change which means that B no longer builds with the new version of A. What happens if we want to push out a new package set now - do we use the new version of A and drop B from the updated package set?

Also, are package sets mutable? Perhaps I've misunderstood you but your comment about generating documentation for the whole package set on a regular basis kind of makes it sound like they are.

I would certainly like to consolidate `package-sets` and Pursuit; I think it does indeed make sense to generate documentation for specific package sets. Stackage.org has been doing this for a while so there's little doubt in my mind about it.

**Comment by hdgarrood** [comment]
Ok, I've read through https://github.com/purescript/purescript/pull/2424 and it's a bit clearer now. Since packages will be dropped from package sets if they aren't kept up to date quickly enough, and since it's probably going to be more bother for everyone involved (i.e. curators, authors, and people depending on it) for some package to be in a package set for a short time and then dropped again, I would rather have `pulp publish` not do anything w.r.t. package sets. It really needs to be opt-in and separate from normal package publishing given the commitment it represents, I think. In fact, like Stackage, I think we should encourage people to only submit a package into a set if they expect to be able to maintain it.

Have we considered doing something a bit more like Stackage where package authors just say they would like their packages to be included in future versions of Stackage without specifying a particular version, and the curation script works out which versions to use? That would remove the need for `pulp publish` to be aware of package sets, afaict, and selecting which versions go in which package sets is probably best done on the curation side rather than the invidividual package author side anyway.

**Comment by nwolverson** [comment]
@hdgarrood On the consume rather than publish side, I think pulp integration also means using psc-package sources (e.g. calling `psc-package sources` rather than globbing `bower_components`). Maybe triggered by presence of the `psc-package.json`.

**Comment by paf31** [comment]
Sorry for the slow reply.

> What does pulp integration mean?

Mostly just changing some paths to use `.psc-package/` instead of `bower_components/` initially. I think you're right that doing any sort of automatic updates of the package set is a bad idea, and we should concentrate on building tools for curation instead.

> Also, are package sets mutable?

Once a package set is tagged, that tag will be immutable. So we can build docs from each tag at the time we make the tag, and keep docsets for old tags too if we like.

Ideally, we'd just publish them using `gh-pages` during the CI publish step, in addition to building some sort of search index for Pursuit, probably.

**Comment by paf31** [comment]
One more note on this: I would like to see `psc-package` become the standard, supported solution, since I think it can simplify things quite a lot for beginners and simple projects. But Bower is _still available_, and users can continue to use it if they want Bower-style dependency solving. Switching to Bower from `psc-package` should be quite simple, and probably would make a good topic for an article on the website.

Pulp could even support both solutions, depending on which of `bower.json` or `psc-package.json` were present. It would just amount to using a different glob.

**Comment by paf31** [comment]
Again, I'm going to close this, but we should open separate issues on the psc-package repo as necessary.
