### ISSUE TITLE
Add extra-deps section to psc-package.json

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2433]
The idea is that the `update` command should pull any tags listed under `extra-deps`, and include any dependencies of those packages when retrieving things from the package set.

I don't think we should follow `extra-deps` recursively, at least not in the first version. I'm fine with requiring users to list any transitive `extra-deps` instead. Thoughts?

**Comment by hdgarrood** [comment]
If psc-package.json is going to contain more than just information about a particular package set, then I think we should consider whether we want it to eventually become a full-blown package manifest file, i.e. containing the information that bower.json does now, or in comparison to a Haskell project, containing all the information from *both* project.cabal and stack.yaml.

If the answer is yes (which I am expecting that it will be), then I think we should start thinking about how important reproducible builds are to us, i.e. is it acceptable to us that the install plan that psc-package selects for a given manifest file change over time if new versions of dependencies are released? Currently it can if you specify a branch for the package set.

Also, since psc-package is going to take responsibility for installing dependencies outside a given package set, I think it needs to know of version ranges which a particular package is expected to work with, i.e. the dependency information which we currently put in bower.json, because AFAICT at this point actual dependency solving becomes necessary. For example, if you specify a package set and an `extra-dep`, and the extra dep depends on a package A in the set, but the extra dep specifies a version range for A which does not actually include the version of A which is in the set, that should be a dependency solving error, not a compile-time error (or worse, a bug! imagine if the semantics of a function changed without changing its type signature).

So I think psc-package.json needs to potentially contain two types of dependency information:
* Version ranges for all dependencies which are believed to work (i.e. what goes in project.cabal for Haskell). Any package which is going to be used as a library (i.e. depended on) must contain this.
* A specific set of versions which is known to work, which was used the last time someone worked on the project, analogous to a lock file or the information that goes in stack.yaml. This could be specified by a particular package set and/or some specific versions of dependencies (e.g. `extra-deps`, if they're not in the set).

At this point it occurs to me that perhaps not every package needs to contain both. For example, you probably don't want to bother with the first kind if you're creating an application.

**Comment by hdgarrood** [comment]
So to answer the recursive extra-deps question: no, I think only the first kind of dependency information should be used for solving. I think using extra-deps recursively is analogous to publishing a library where the version 'ranges' contain just one specific version, which to me seems like it will almost inevitably cause conflicts.

**Comment by paf31** [comment]
> If psc-package.json is going to contain more than just information about a particular package set, then I think we should consider whether we want it to eventually become a full-blown package manifest file, i.e. containing the information that bower.json does now, or in comparison to a Haskell project, containing all the information from both project.cabal and stack.yaml.

For now, I would like the package file to just contain enough information to pull PureScript dependencies using the information in a package set and build it. Later, I would like to extend it to include data about NPM dependencies, and related things. We can add other metadata later if it is useful.

I am not against the package file turning into a full project manifest if that proves to be useful, but that's why I'd like to be careful not to add unnecessary features now.

> If the answer is yes (which I am expecting that it will be), then I think we should start thinking about how important reproducible builds are to us, i.e. is it acceptable to us that the install plan that psc-package selects for a given manifest file change over time if new versions of dependencies are released? Currently it can if you specify a branch for the package set.

Yes, this is true, but `psc-package init` won't ever use a branch by default, it will use the tag corresponding to the compiler build you have.

I'm not particularly worried about reproducible builds if people choose to use their own package set, but I think we probably should warn if they are pointing at a branch and not a tag.

> Also, since psc-package is going to take responsibility for installing dependencies outside a given package set, I think it needs to know of version ranges which a particular package is expected to work with, i.e. the dependency information which we currently put in bower.json, because AFAICT at this point actual dependency solving becomes necessary. 

I would very much like to avoid constraint solving for now. I don't mind adding constraint _verification_ later, but I think that should go under a separate `constraints` section of the file if we decide to add it.

Generally, I think of `overrides` as an advanced feature, and users should use it at their own risk right now. Users who lean heavily on `overrides` should instead consider hosting their own package set, in my opinion. I'm trying to solve a different problem right now - namely, allowing beginners to get started quickly using a working package set.

> For example, if you specify a package set and an extra-dep, and the extra dep depends on a package A in the set, but the extra dep specifies a version range for A which does not actually include the version of A which is in the set, that should be a dependency solving error, not a compile-time error (or worse, a bug! imagine if the semantics of a function changed without changing its type signature).

That sounds fine to me, but again, I'd implement that using a separate `constraints` section of the file if and when we decide we need it.

> A specific set of versions which is known to work, which was used the last time someone worked on the project, analogous to a lock file or the information that goes in stack.yaml. This could be specified by a particular package set and/or some specific versions of dependencies (e.g. extra-deps, if they're not in the set).

How about this? We could implement a `psc-package freeze` command, which would take any `overrides` and make a new package set JSON file, which could be used to create a custom package set repo.

**Comment by hdgarrood** [comment]
> For now, I would like the package file to just contain enough information to pull PureScript dependencies using the information in a package set and build it. Later, I would like to extend it to include data about NPM dependencies, and related things. We can add other metadata later if it is useful.

This just seems a bit odd to me in light of your other comment in #2458, where you said you think of psc-package as "an interface to the .psc-package directory, via Git". In that case I would expect us to say that npm dependencies are out of scope for the psc-package tool; i.e. that we do want to address npm dependencies but not with the psc-package tool. Is it really the case that dependency solving is not in scope for psc-package but npm dependencies are?

I would prefer that we just have one package manifest file. If psc-package is going to be a lower-level tool then I hope that the eventual goal is to get rid of psc-package.json entirely, and then whatever other tool is calling it would tell it which package set to use, which overrides to fetch, etc. If we are replacing bower then we will need some other file in which we declare packages' authors, descriptions, version constraints, etc. and I'd rather that file also included package set information.

> Yes, this is true, but psc-package init won't ever use a branch by default, it will use the tag corresponding to the compiler build you have.

At the moment, there are no tags corresponding to compiler builds in the package-sets repo, only branches for psc-0.10.1 and psc-0.10.2.

> How about this? We could implement a psc-package freeze command, which would take any overrides and make a new package set JSON file, which could be used to create a custom package set repo.

I don't think we need or want that - to be clear, I think that of those two types of dependency information that I mentioned before, we already have the first in psc-package.json.

---

I'd rather we try to design all this so that custom package sets are not necessary, personally. The way I see it, custom package sets are pretty much exactly the same as what we have now with bower, in that it's up to the user to find a set of packages that build together. If we're going to tell people to use custom package sets in all but the simplest cases, we might as well not bother with all this and keep using bower, surely?

**Comment by paf31** [comment]
> This just seems a bit odd to me in light of your other comment in #2458, where you said you think of psc-package as "an interface to the .psc-package directory, via Git". In that case I would expect us to say that npm dependencies are out of scope for the psc-package tool; i.e. that we do want to address npm dependencies but not with the psc-package tool. Is it really the case that dependency solving is not in scope for psc-package but npm dependencies are?

I don't see why this is a contradiction. NPM dependency information is just metadata which can be attached to packages in a package set. `psc-package` could form the union of the NPM dependencies for all transitive package set dependencies, and check or install them using NPM.

In any case, I'm not thinking about NPM dependencies in very much detail right now.

> If psc-package is going to be a lower-level tool then I hope that the eventual goal is to get rid of psc-package.json entirely, and then whatever other tool is calling it would tell it which package set to use, which overrides to fetch, etc. If we are replacing bower then we will need some other file in which we declare packages' authors, descriptions, version constraints, etc. and I'd rather that file also included package set information.

I suppose that could work, but why not just extend `psc-package.json` to support those fields? We wouldn't necessarily use them for anything other than display in some package list, right?

> At the moment, there are no tags corresponding to compiler builds in the package-sets repo, only branches for psc-0.10.1 and psc-0.10.2.

Okay, well that's a mistake then, but @garyb and I have discussed it already and the goal was to use tags.

> I don't think we need or want that - to be clear, I think that of those two types of dependency information that I mentioned before, we already have the first second in psc-package.json.

I'm fine with implementing fewer features 😄 

> I'd rather we try to design all this so that custom package sets are not necessary, personally. The way I see it, custom package sets are pretty much exactly the same as what we have now with bower, in that it's up to the user to find a set of packages that build together. 

I think custom package sets are a crucial feature for real-world use. And there is an essential difference between using a custom package set and using Bower now, which is that the work of building a package set is broken up over a lot of individual package additions and updates, and only has to be done once by the package set maintainer.

> If we're going to tell people to use custom package sets in all but the simplest cases, we might as well not bother with all this and keep using bower, surely?

No, because a) custom package sets shouldn't be _that_ common, b) it will be possible to make small changes to the cloned package set locally, which should make contributing updates upstream simpler, and c) the package set approach has other benefits over Bower (the ability to build richer, consistent documentation being a big benefit in my opinion, and also the fact that we don't have to worry about terrible error messages from a constraint solver).

Also, we shouldn't underestimate the value of making the simplest cases actually simple. You can build quite a bit with just the core libraries, and quite a lot more with even what's in the package set now.

**Comment by hdgarrood** [comment]
> I don't see why this is a contradiction

Sorry, I didn't mean to imply it was a contradiction, I just am a bit confused about what the scope of the psc-package tool is.

> I suppose that could work, but why not just extend psc-package.json to support those fields? We wouldn't necessarily use them for anything other than display in some package list, right?

Yep, okay, that works.

> I think custom package sets are a crucial feature for real-world use.

Ok, this makes more sense to me now. How are you imagining custom package sets would be used? Also, are we not more or less getting by in the Haskell world without them?

**Comment by paf31** [comment]
> I just am a bit confused about what the scope of the psc-package tool is.

Well, yes, I think we're still figuring that out, so these discussions are very much appreciated. I think I have a good idea of what a minimally-viable `psc-package` should look like, but I'm still not sure if `extra-deps` should be part of that. 

> How are you imagining custom package sets would be used? 

For one-off tests, users could modify the package set definition directly in their project's `.psc-package` directory.

For companies wanting to set up an internal package set, they would create a Git repository and maintain it like we maintain the public `package-sets` repo. Then they'd have their PureScript developers point to their custom package set repo.

> Also, are we not more or less getting by in the Haskell world without them?

For the most part, I think so. But developing an application using Stack with private extra-deps can quickly turn into a mire of SHA hashes in your `stack.yaml` file, right? That's the sort of thing I'd like to simplify by allowing custom package sets.

**Comment by Pauan** [comment]
Another benefit of custom package sets is that you can have different *policies*.

You could have one group of people that maintains a "secure PureScript" package set which has extensive testing, code review, security audits, etc. Naturally that kind of package set would be slow to accept new packages and upgrades to packages (because it needs extensive auditing), but it might be useful for big companies or anybody who wants extra security.

Or you could have a different group of people maintaining a package set which is extremely unstable: pull requests are automatically accepted, new packages/package updates are automatically accepted, there is extremely little oversight, etc. This would be somewhat like the situation with Debian Unstable, where you choose bleeding edge over safety.

I really **really** like the idea of package sets, because they allow a single person (or group) to do the hard work of figuring out which package versions work together, and then everybody else can simply benefit from that work, rather than each application/library needing to figure out its own custom set of package versions (which is how it works in npm).

I think custom package sets give a good amount of freedom/customization while still preserving the good things about package sets.

As for other features, I agree with @paf31, package sets are still new, let's keep it simple and see how far we can go with it.

**Comment by paf31** [comment]
I'm going to move this back to Ideas and close my PR until we can decide if this is a good idea for 1.0.

**Comment by paf31** [comment]
I'm going to close this. We could reopen it on the psc-package repo, but I'm thinking this is probably out of scope now that psc-package is separate with a more clearly defined scope.
