### ISSUE TITLE
Unicode encoding for record keys fails for surrogate pairs

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#2438]
This piece of code type checks:

```haskell
x :: String
x = {"𝌆": "hi"}."𝌆"
```

but generates invalid JS like so:

```javascript
var x = {"\119558": "hi"}["\ud834\udf06"];
```

The issue here is that the key needs to be encoded as a surrogate pair just like the accessor is.

Just something I stumbled upon while trying to work through the String -> Text unicode issues.

**Comment by michaelficarra** [comment]
I would fix this right now, but I think it's best to wait until we change the internal representation in #2434. Then the codegen is simple and obvious (and this will just work).

**Comment by andyarvanitis** [comment]
Even though this ticket is closed, I'm guessing you guys know already that this is not working correctly in 0.10.3? Sorry, a bit hard to tell from all the threads in issues and PRs, so I thought I'd report it, just in case.

For this character and others requiring surrogate pairs, you always get just the replacement code pair `\ufffd\ufffd`. As others have pointed out, invalid code units in `Text` get replaced during most operations. BTW, test `2843.purs` passes due to matching `\ufffd\ufffd` on both key and accessor.

**Comment by paf31** [comment]
Thanks @andyarvanitis, I wasn't aware. Is anyone still working on this? cc @kRITZCREEK @michaelficarra 

Thanks.

**Comment by michaelficarra** [comment]
Yep. As soon as we get Text replaced with our own string representation, this will work. *Speaking of which*, my [branch](https://github.com/michaelficarra/purescript/tree/string-newtypes) is just about ready to go except it's rendering `module."exports"` and `$foreign."warn"(Data_Show."show"(dictShow)(a));` and I can't for the life of me figure out why. If someone can help, I can get that PR submitted right away.

**Comment by paf31** [comment]
Maybe put up a PR and we can try to spot it there?

**Comment by michaelficarra** [comment]
@paf31 Done. See https://github.com/purescript/purescript/pull/2488. :confounded:
