### ISSUE TITLE
IDE: Standardized test runner and test output

### ISSUE THREAD

**Issue by owickstrom** [purescript/purescript#2452]
Hi,

This is not an issue, more of a feature request and hopefully something we can discuss. Maybe it's not the correct forum, if so, please tell me where to bring this up. I talked to @kRITZCREEK a bit about this earlier, and I thought we could bring the discussion here.

So, what I'd like is a standard way to interface test runners to psc-ide, so that editors can easily do stuff like:

* Run all tests in package
* Run test in current file (perhaps tricky, just thinking out loud)
* Run tests after each rebuild
* Get results back to display in IDE/editor

We probably would need a standard format for test results, kind of like XUnit. Haven't thought much about that, to be honest.

This would be lovely for [purescript-spec](https://github.com/owickstrom/purescript-spec). Perhaps @bodil might be interested in this as well for [purescript-test-unit](https://github.com/bodil/purescript-test-unit)? There may be more that I do not know of.

Anyway, if you have ideas and feedback I'd be happy to discuss more. IMO this could raise the developer experience quite a bit, especially for developers that like to use a full IDE, or that want a TDD workflow in their editor.

**Comment by bodil** [comment]
test-unit already supports [TAP](https://testanything.org/tap-version-13-specification.html) output. That's a standard format if anything is?

**Comment by owickstrom** [comment]
@bodi I did not know about it, but it sounds good. And @felixSchl is already working on a TAP reporter for purescript-spec, I believe, so I'm all up for that. :+1:

**Comment by felixSchl** [comment]
I'd love the ability to discover all tests and collapse them by hierarchy, something I was not able to achieve in mocha easily (at all).

Anyway, I find part of the problem lies with the fact that we bundle the executing code and the test code into the same codebase. If we were to take an approach like mocha where you have  a test bed and then run it externally using their cli, I feel we can get more project-independent tooling. I've been thinking about adding a CLI component to purescript-spec, so you can still compile and configure your project at compile time and simply ship with the CLI. It does couple things a bit tighter, though, which might no be a bad thing?

**Comment by bodil** [comment]
@felixSchl Not sure I understand - tests go in the `test` folder and aren't strictly bundled with the main codebase, or do you mean something different?

**Comment by felixSchl** [comment]
@bodil Yes you are right, however, I meant the execution of tests. To go with mocha as an example, I would just create my test files, then start throwing in `describe` and `it` blocks. There would be absolutely no code or any indication of me actually invoking these functions. That's what mocha does, it traverses file system (if told) and looks for tests, then runs them. I don't know if we can do that in purescript, that's why I then took a turn and suggested we could maybe bundle a CLI, so at least all projects using a similar version of the same test runner will have the same interface, which solves half the problem.

**Comment by bodil** [comment]
@felixSchl I'm quite attached to the standard `pulp test` interface whichever testing tool you use (and even if you don't, as with some of the standard libraries) - perhaps that could be extended instead? Assuming we can outline exactly what else would be needed of it.

**Comment by felixSchl** [comment]
@bodil I was thinking of `pulp test` also. But, correct me if I am wrong here, `pulp test` just runs the entrypoint of the `Test` module, so things like discovering tests would not be as easy. If we gave `pulp test` a richer interface to work with, `pulp test` could pull this sort of information out from the underlying test runner.

**Comment by hdgarrood** [comment]
Is it necessary or even desirable for `psc-ide` to be involved in running tests? I would have expected that an editor plugin for purescript would talk directly to any test runner without involving `psc-ide`.

**Comment by owickstrom** [comment]
@hdgarrood might be an external thing, yes. I was thinking about the recompilation part, but an editor plugin could itself trigger test runs after rebuilds. Do you think we should move this discussion elsewhere, like the mailing list? Do we have any other arguments for involving `psc-ide`?

**Comment by kRITZCREEK** [comment]
The one benefit that comes to mind is that we already set up the communication/RPC part for most of the editors with `psc-ide`. But I don't think spawning test processes is within `psc-ide`'s scope. One thing I could see happening *soonish* is that `psc-ide` can provide an annotated AST for a given source file. That could then be used to build test runners that introspect the AST.

**Comment by hdgarrood** [comment]
I think in that case the mailing list might be a better place for this discussion, yeah.

**Comment by owickstrom** [comment]
OK, closing then.

**Comment by owickstrom** [comment]
Please jump over to https://groups.google.com/forum/#!topic/purescript/h0iYpgkeXzc for further discussion. :+1:
