### ISSUE TITLE
`UnusedTypeVar` warning when var is only used in a scoped context

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#2460]
This raises a warning about `a` being unused:

``` purescript
test :: forall a b. b -> b
test = id
  where
  inner :: a -> a
  inner = id
```

**Comment by paf31** [comment]
I think this is a valid warning actually. If the type variable doesn't appear in the original type, how can it meaningfully be used in a way where you couldn't just move it under the `where`?

**Comment by garyb** [comment]
The error message is still wrong: if you remove the "unused" `a` from the quantifiers to fix the warning it becomes an error instead, because `a` is undefined.

**Comment by paf31** [comment]
Oh right, I see. Yes, then we should make this an error, I think?

**Comment by garyb** [comment]
Why's that? I'm just suggesting we use a slightly different message when it arises.

**Comment by paf31** [comment]
Yeah, that's probably fine actually.

**Comment by paf31** [comment]
I think we can just change the wording generally here. There is no way in which code like `test` can be actually useful, since there is no way to indicate what `a` should be instantiated to, and if you try to use it inside the function (e.g. by changing `test = id` to `test = inner`), you rightly get a unification error.

So, while it's not about the type being "unused" (clearly, it is used here), we still ought to warn, since the type argument is _useless_ :)

But I'm not sure how to word it. Maybe something like `Type variable a is ambiguous, since it is not used where it is defined".
