### ISSUE TITLE
Error in language guide

### ISSUE THREAD

**Issue by tbillington** [purescript/purescript#2475]
In the language guide there is some [code](https://github.com/purescript/purescript/wiki/Language-Guide#another-example) 

```purescript
data Person = Person { name :: String, age :: Number }

showPerson :: Person -> String
showPerson (Person o) = o.name <> ", aged " <> show o.age

examplePerson :: Person
examplePerson = Person { name: "Bonnie", age: 26 }
```

Which gives this error when used in try.purescript.org

```
  Could not match type

    Int

  with type

    Number


while checking that type Int
  is at least as general as type Number
while checking that expression 26
  has type Number
in value declaration examplePerson
```

**Comment by joneshf** [comment]
The wiki should be editable by anyone. Please feel free to fix it appropriately!

It seems like `age` should be `Int` rather than `Number`, since most people would say they're "26 years old", rather than "26.0 years old". Does that seem right?

Also, we're kind of transitioning to a separate repo. It'd be great if you could do similar in the `documentation` repo for this example as well: https://github.com/purescript/documentation/tree/master/language#another-example

**Comment by hdgarrood** [comment]
The wiki is only editable by contributors now, to make sure that people don't make edits that accidentally get lost later. I think it's probably time to just replace the entire language guide page with a link to the documentation repo? All the information that was on the wiki page is now in the documentation repo, and it has had a few updates and additions by now.

**Comment by joneshf** [comment]
Oh. :blush:

**Comment by hdgarrood** [comment]
I've fixed this error in the documentation repo and updated the wiki page to point to it. Thanks for the report!
