### ISSUE TITLE
Support `--dump-corefn` with `psc-package build`

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript#2505]
I would like to use package sets for alternative backends which rely on the `--dump-corefn` flag.

I know the `build` command might go away but this seems to be the only way to build a project which uses a package set.

If there are any alternatives or workarounds, I'm interested in hearing about those.

**Comment by paulyoung** [comment]
@paf31 suggested the following workaround, but also thought it would be good to support whatever options the compiler supports.

`psc --dump-corefn '.psc-package/<set-name>/*/*/src/**/*.purs'`

**Comment by paf31** [comment]
I think it could be useful to pass along compiler options, but I would prefer to get rid of the `build` command entirely, and instead have Pulp (or other build tools) support `psc-package` instead of Bower. Really, it's just there right now so that beginners don't immediately dismiss the tool as useless.

You could always alias `psc '.psc-package/<set-name>/*/*/src/**/*.purs'` in your Bash config.

**Comment by paf31** [comment]
I'm going to close this here, but please feel free to reopen on the psc-package repo.
