### ISSUE TITLE
'pulp build' of 'pulp init' generated files has compile error

### ISSUE THREAD

**Issue by vesten** [purescript/purescript#2506]
Performing the following steps,

   stack new foo simple
   cd foo
   stack setup --resolver lts-7.14
   stack install purescript --resolver lts-7.14
   npm init
   npm install pulp bower --save
   npm run bower install
   npm run pulp init
   npm run pulp build

results in,

   > foo@1.0.0 pulp /home/vesten/devel/foo
   > pulp "run"

   * Building project in/home/vesten/devel/foo
   Error found:
   at /home/vesten/devel/foo/bower_components/purescript-eff/src/Control/Monad/Eff/Class.purs line 19, column 33 - line 19, column 33

     Unable to parse module:
     unexpected |
     expecting no indentation or end of input

   See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
   or to contribute content related to this error.

on current Void linux x86_64.

**Comment by hdgarrood** [comment]
This is probably because the version of purescript in stackage LTS releases is usually quite old, my guess is that you've got some versions of libraries that only work with 0.10.x of the compiler but the version of purescript in stackage LTS 7.14 is 0.9.3. Please use one of the options listed on http://www.purescript.org/download/ instead for installing the compiler.

**Comment by vesten** [comment]
That was it. Thanks.
