### ISSUE TITLE
Remove dependency on Bower from the compiler

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2517]
The compile depends on Bower in the following places:

- PSCi
- Test suite
- `psc-publish`

We should be able to sever the tie to Bower by providing generic support for other package managers in the form of command line arguments.

**Comment by paf31** [comment]
@hdgarrood I started looking at this, but it was a lot more work than I expected it would be 😄 

To begin with, can we come up with a list of fields we would need to provide to `psc-publish`? So far I have these:

- Name
- Description
- License
- Author(s)
- Repository URL
- Dependencies with version ranges

Are there any others that you can think of?

**Comment by hdgarrood** [comment]
Yes, I think that would cover it. I was imagining that we might provide this data as JSON on stdin and `psc-publish` could ignore any extraneous fields - that way it should be easy to just pipe bower.json into `psc-publish` / `purs publish` for now and also allow easy switching later.

**Comment by rvion** [comment]
> it should be easy to just pipe bower.json into psc-publish

I would prefer a regular invocation style (windows compat, clearer in scripts, etc.)

**Comment by hdgarrood** [comment]
Windows does support specifying standard input to be read from a file on the command line, though. I'd prefer to use stdin because then if any preprocessing is needed there's no need to write an intermediate file (which could dirty your git working tree). The kind of preprocessing I'm imagining is that e.g. some other package manager might have a manifest file that's not quite compatible with the structure `purs publish` is expecting.

**Comment by rvion** [comment]
> Windows does support specifying standard input to be read from a file on the command line, though

> then if any preprocessing is needed there's no need to write an intermediate file

if any preprocessing is needed, I think windows would need an intermediate file anyway. 
I'm not a windows shell expert though.

http://stackoverflow.com/questions/14574170/how-do-i-use-a-pipe-to-redirect-the-output-of-one-command-to-the-input-of-anothe

-----------

What I wanted to say is that regardless if it is possible to pipe bower.json as stdin to psc-publish, I would prefer to also be able to write

if there is a standard package(s?) definition file:

```
psc publish
```

if there is not:

```
psc publish --from-config=bower.json
```

or :

```
psc publish
 --name foo
 --description="lib to print 'foo' strings"
 --license=bsd3
 --authors=rvion
 --repository=git@github.com:rvion/foo.git
 --deps="..."
```

If you want other reasons why I prefer to avoid piping: 

  - it is harder to document (via available commands and options)
  - it is impossible to add autocomplete in your shell when no commands and flags
  - if you don't want an interactive CLI in case of missing pipe (which could block a script), you need to check the current TTY
  - it is more easilly auditable, log-friendly

**Comment by rvion** [comment]
flags composition also allow basic preprocessing:
we could for instance also say that when both `--config-file` and any other field flag are present, specific flags overwrite the json given by `--config-file`

psc publish
  --from-config=bower.json
  --name foo-optimized

**Comment by hdgarrood** [comment]
I just meant that `purs publish < bower.json` works in cmd.exe just as it works in shells like bash.

Preprocessing inside a program like `pulp` is easy and doesn't need an intermediate file, because it would be using an API like Node's `child_process` API.

I'm not keen on specifying config on the command line; that information should be in a file in the git repository. Allowing specifying it on the command line could easily lead to confusion where a package seems to have two different sets of metadata: one set on pursuit and another on github.

**Comment by rvion** [comment]
> I just meant that purs publish < bower.json works in cmd.exe just as it works in shells like bash.

right, that's true, but piping doesn't work like on unix systems. 

> Preprocessing inside a program like pulp is easy and doesn't need an intermediate file, because it would be using an API like Node's child_process API.

I thought you were speaking about preprocessing with an other tool like `jq`.
Regarding pulp, I really think nothing in this repo should should rely on it.
most pulp commands are only saving a few letters, and small extensions of core psc-* binaries would remove most need of pulp.

> I'm not keen on specifying config on the command line; that information should be in a file in the git repository. Allowing specifying it on the command line could easily lead to confusion where a package seems to have two different sets of metadata: one set on pursuit and another on github.

I agree that a dedicated file would be safer.

That's also a reason why I would prefer a dedicated file for psc-publish. (an other reason would be that I hope we won't end up manually specifying version ranges for deps as it is now)

anyway, I wouldn't mind neither having both high level and low level interface in psc-publish.

----

I know this is not exactly the core topic, but I'm not sure to understand why `psc-publish` and `psc-package` are treated differently. I feel that the existence of `psc-publish` requires the existence of some kind of `psc-package`.

**Comment by hdgarrood** [comment]
> Regarding pulp, I really think nothing in this repo should should rely on it.

I agree. This is currently the case, and I am not proposing we change that. But I think it makes sense to consider tools like pulp in the process of designing APIs which we are intending that tools such as pulp will use.

> most pulp commands are only saving a few letters, and small extensions of core psc-* binaries would remove most need of pulp.

I don't agree with this. Pulp takes care of a lot of JS-specific stuff which we don't want in the `psc-*` binaries, for instance. I also think it's better that `pulp publish` exists outside the compiler. Furthermore, it means that Pulp is free to be much more opinionated than the compiler is, since alternatives to Pulp can and do exist.

**Comment by hdgarrood** [comment]
> I know this is not exactly the core topic, but I'm not sure to understand why psc-publish and psc-package are treated differently. I feel that the existence of psc-publish requires the existence of some kind of psc-package.

I'm not sure I understand where you're coming from here, if you're able to expand on this I'd be interested to hear it. I think this would be a good discussion to have, though; perhaps the mailing list or subreddit would be a better place for it?
