### ISSUE TITLE
Within psc mangle exports to be compatible with valid ES module exports

### ISSUE THREAD

**Issue by wegry** [purescript/purescript#2558]
As part of #2207, the issue of name mangling came up in post-processing conversion to ES modules. Currently, exports like `on'` (the invalid ES character in the identifier) break when converted straight to ES Module export syntax. The name mangler I (and @pauan concurrently) have written gets around `on'` becoming `on$prime`.

This doesn't work well if output object properties (as opposed to exports) have reserved words or apostrophes in them unfortunately. We've had to code around that locally.

As @paf31 has noted, there are [tooling concerns for folks using pulp and psci](https://github.com/purescript/purescript/issues/2207#issuecomment-271357771). Improving name mangling has no effect on these tools, but allows folks using JS based bundling a safer way to output smaller code than what psc-bundle currently offers.

Edit: As @michaelficarra has pointed out, the spec does allow reserved words as export names, and @Pauan was recently responsible for patching acorn (which is used by both rollup and webpack) to allow this.

**Comment by garyb** [comment]
Yeah, using the same name mangling we do for values as we do for exports is definitely the way forward here. Unfortunately it's going to break a not insignifcant number of existing libraries so we'll have to do it right before a major release.

**Comment by hdgarrood** [comment]
What are the tooling concerns? Btw I'm not sure if @wegry can see this since I think he has me blocked.

I realise it's come up before (#1717), but I'd like to alternatively re-suggest disallowing primes in data constructors and identifiers. If I'd appreciated at the time that removing primes would make dealing with the FFI and interfacing with external tools easier, I would have been much more in favour of it.

Since ES2015 explicitly allows using reserved words in module imports/exports, I'm not sure if mangling those is the right way to go. I appreciate that not mangling reserved words makes the implementation more difficult for the Rollup plugin, but since the CommonJS -> ES6 transformation that it's doing is just a temporary solution until we can start emitting ES6 modules from psc anyway, I'm not sure we should be making these kinds of decisions based on it.

**Comment by michaelficarra** [comment]
> Since ES2015 explicitly allows using reserved words in module imports/exports, I'm not sure if mangling those is the right way to go.

I was going to say the same thing. You could easily do

```js
var someGenSym = {};
export { someGenSym as delete };
```

> I'd like to alternatively re-suggest disallowing primes in data constructors and identifiers

I don't think we have to go that far. We can just disallow `foreign import`s of identifiers with primes. I'm even okay disallowing them in exports/imports entirely. But they're really useful for local bindings.

**Comment by garyb** [comment]
I have a problem with primes (in that I probably use them too much) so I'm never really going to vote in favour of a change to remove them :wink:, but aside from that I don't really think it helps given there are other manglings we'd need to perform anyway.

**Comment by hdgarrood** [comment]
Are there any others in addition to mangling variable names which are reserved words in the target language?

**Comment by garyb** [comment]
Well, that's part of why I don't think we should do anything to link our namespace-of-acceptable-names to that of a target language - JS will have different reserved words/syntax from C++, from Lua, from Python, etc. So we either have to bake them all in before the codegen stage, and then update the list whenever someone starts a new backend, or we do it in codegen and then potentially have compatibility issues between even pure-PS libraries and backends.

**Comment by andyarvanitis** [comment]
> We can just disallow foreign imports of identifiers with primes.

+1 for this part. Writing an FFI function with `foo$prime` is kinda crappy and fragile (if the mangling scheme changes). Primes are nice, otherwise.

**Comment by hdgarrood** [comment]
Surely it's equally crappy and fragile to have to call into PS code with `PS.MyModule.foo$prime` in cases where your app's entry point is not PS?

I think it could be annoying to have stricter rules for variable names which you're allowed to export compared to names you're allowed to use within a module. Imagine a case where you have a function which you were previously using only in one module and not exporting, but then you realise you need it in another module and you want to export it, and now you have to rename it. Admittedly not very difficult to deal with if you know how to use your text editor, but surely better to stop the situation from arising entirely?

@garyb: To be clear, I'm not suggesting we start disallowing reserved words in target languages as PS identifiers. The reason I asked if there are any other things we need to mangle is that if there aren't, and if we disallowed primes in PS identifiers, then we wouldn't need to do any mangling of imports/exports at all in JS because reserved words are permitted in ES2015 module imports/exports, and that would be lovely IMO. Can you expand on the compatibility issues you mentioned?

**Comment by andyarvanitis** [comment]
> Surely it's equally crappy and fragile to have to call into PS code with PS.MyModule.foo$prime in cases where your app's entry point is not PS?

Yeah, true. I guess I was just thinking about encountering it when updating package FFIs.

**Comment by natefaubion** [comment]
> Surely it's equally crappy and fragile to have to call into PS code with PS.MyModule.foo$prime in cases where your app's entry point is not PS?

Surely if it's intended to be consumed by JS, you'd just not name it that? I'd posit that instances of having to call a primed PS function (which one has no absolutely no API control over) from JS are extremely rare, and the inconvenience is very minor and predictable. If we are going to disallow primes in values, then you should just disallow it everywhere. It's annoying to have different acceptable character rules for values and types. And since we just recently allowed it _in_ types, I personally don't care to revert it.

**Comment by natefaubion** [comment]
I think we should mangle the prime accordingly, and pose no other restrictions. The only reason its an issue now is because with CommonJS, you have the _opportunity_ to write `exports["foo'"]` so its confusing. If we are going to use ES6 modules, this isn't even possible, so I think it will be a non-issue in practice.

**Comment by garyb** [comment]
@hdgarrood I was thinking we'd still have to mangle other kinds of reserved words like `var`, and globals like `Math`. `exports` too actually.

**Comment by michaelficarra** [comment]
@garyb I don't see why.

**Comment by hdgarrood** [comment]
Right - we certainly have to mangle variable names such as `var` and `Math`, but I don't see why we can't have them exported under their real names as written in PS.

**Comment by garyb** [comment]
Oh, I see - that's true. Maybe primes are the only problematic for exports then... I'll have a think.

**Comment by Pauan** [comment]
My thoughts:

* The only reason primes are a problem right now is because CommonJS allows you to say `exports["foo'"]`

  If PureScript switches to ES6 modules (both in `psc` output and FFI files), then the prime problem solves itself, since it isn't possible to have a prime in a JS identifier.

* I think it would be a good idea for FFI files to stop using primes in their exports, in order to make it easier for them to transition to ES6 modules in the future.

  I just now added in a warning in `rollup-plugin-purs` if you export a variable with a prime in it.

* Reserved words are fine in imports/exports, and `rollup-plugin-purs` doesn't have a problem with them, so I personally consider that to be a non-issue.

  As such, I don't really care much one way or the other: if `psc` mangled imports/exports then it would make it easier to write naive tools, but it doesn't affect me or `rollup-plugin-purs` at all.

**Comment by Pauan** [comment]
Hm, I said that the prime problem "solves itself", but that's not entirely true. If `psc` switches to ES6 modules, then at the very least `psc` will need to mangle `'` to `$prime` in the imports/exports. So I guess it *is* necessary for `psc` to mangle imports/exports, at least if we want to keep `'`

Note: I'm referring to PureScript files which are compiled with `psc`, not FFI files. I don't think `psc` should mangle FFI files.

**Comment by Pauan** [comment]
So I guess my final stance is:

* Continue to allow for `'` in PureScript identifiers

* `psc` should mangle `'` in imports/exports

* FFI files should stop using `'` (and possibly switch to `$prime` instead?)

**Comment by natefaubion** [comment]
Closing in favor of #3613
