### ISSUE TITLE
Make => into a type operator

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#2686]
Here's another breaking change which I'd like to consider for inclusion before 1.0.

This is motivated by adding constraint kinds. Instead of having the current syntax `(X, Y, Z) => t` for multiple constraints, `=>` would only apply to single constraints. We would write things like

```purescript
traverse
  :: forall f t a b
   . Applicative f
  => Traversable t
  => (a -> f b)
  -> t a
  -> f (t b)
```

There are a few benefits:

- `=>` becomes a regular type operator with kind `Constraint -> Type -> Type`. We could even pass it as an argument to a type function.
- Constraints could be represented using `Type`
- The parser becomes simpler and parentheses no longer require backtracking.
- It makes the implementation of constraint kinds simpler, because one of the most difficult parts to implement last time was the parser, because of the ambiguity above.

And some disadvantages:

- Dictionary application becomes curried, which entails a performance hit. Inlining should deal with this, either in the compiler later, or in Rollup by the time we get to 1.0.
- It would break a lot of code. We could address this by deprecating the current syntax in 0.11 and removing it before 1.0.

Thoughts?

**Comment by rvion** [comment]
I really like the idea but don't really like the way it reads.

```
1| traverse
2|  :: forall f t a b
3|   . Applicative f
4|  => Traversable t
5|  => (a -> f b)
6|  -> t a
7|  -> f (t b)
```

I find this example really hard to read:

 - the `=>` operator seems to be an implication
 - when there is two `=>`, it feels like the order is important
 - __the first function argument is line 5__, and it is the second line starting with a "=>"
 - the `.` feels a bit odd, and moving it at the beginning of line 2 is no better because of alignments problem
 - no clear delimitation between the different parts of the signature

When I read C++, I need some extra time to remove some const&<>*() noise and move things around in my head to see what functions takes as an input and return as output

PureScript sure reads quite better IMO but still, I wish it could be better.

In this case, I think that
 - newcomers not really familiar with the syntax will really have trouble understand this
 - it will generally slow us down when we read some code.

If I only take into account how it reads, I think the (Constraint 1, Constraint 2) => is easier.
Regarding constraint classes, I share the same interrogation as @LiamGoodacre

**Comment by fehrenbach** [comment]
Constraint row, cf. effect row?

**Comment by LiamGoodacre** [comment]
@rvion most of your concerns seem to be more about the formatting of the given signature, I think this reads well:
```purescript
traverse :: forall f t a b. Applicative f => Traversable t => (a -> f b) -> t a -> f (t b)
```

I sometimes have the vars and constraints on one line and the rest on the next which I think also improves readability:
```purescript
traverse :: forall f t a b. Applicative f => Traversable t =>
  (a -> f b) -> t a -> f (t b)
traverse ...
```

You said about the ordering feeling important, but couldn't you say the same about `(Applicative f, Traversable t) =>`.

I'm not so sure about the newcomer and speed stuff; I think this is less confusing and won't have any real effect on speed of reading code - at least not in the long term.

**Comment by rightfold** [comment]
There should be a tool to automatically migrate old code to the new syntax.

**Comment by rvion** [comment]
📝  I really like all benefits that come with `=>` becomes a regular type operator.

-----------------------

> @rvion most of your concerns seem to be more about the formatting of the given signature

I don't think so. I also often format code like in the original post, or like you just did this:
```
traverse :: forall f t a b. Applicative f => Traversable t =>
  (a -> f b) -> t a -> f (t b)
traverse ...
```

but still, I'm not quite convinced about how it reads in both forms.

> You said about the ordering feeling important, but couldn't you say the same about (Applicative f, Traversable t) =>.

Sorry, I think I was not really clear: __I think the ordering is not important__, and __that's the reason why I don't liked the `=>` operator__, even in Haskell

**Comment by rvion** [comment]
## notation for for class entailment I would like better

When I look at things like https://www.wikiwand.com/en/List_of_logic_symbols, I really feel there could be some better notations for entailment

in logic, there is [Double_turnstile (⊨) for `entails`](https://www.wikiwand.com/en/Double_turnstile)
and it's [reverse form (⫤) ](http://www.fileformat.info/info/unicode/char/2ae4/index.htm)

💚  I wish class could be

```
instance foo :: C x y ⊨ A x, B y 
instance foo :: C x y |= A x, B y

class C x y ⊨ A x, B y 
class C x y |= A x, B y
```

```
class C x y |= A x, B y
```

feels much more correct than

```
class A x <= B y <= C x y
```

I think entailment after is better, because this way, information are always at the same positions:
I know where to look, and I can read things from general class name to more specific entailment needed.

## If we want an operator.

to get the best of both world (notation and composability) we could have a type operator

```
/\ :: Constraint -> Constraint -> Constraint
∧ :: Constraint -> Constraint -> Constraint
```

so we could write 

```
class C x y |= A x ∧ B y
class C x y |= A x /\ B y
```

💚  Best of both world

**Comment by rvion** [comment]
🔴 🍏 ? 

Using operators for constraints could also bring the possibility for users to decide if they want to place constraints at the left of the declaration or at the right. (unless the operator is a special Primitive Operator we can't flip)

```
foo :: (a -> b) -> f a -> f b |= Functor f
foo :: Functor f =| (a -> b) -> f a -> f b
```

**Comment by rvion** [comment]
if I try to reuse some notation elements from the comment about class above:

```
∧ :: Constraint -> Constraint -> Constraint
⊨ :: Type -> Constraint -> Type
⫤ :: Constraint -> Type -> Type
```

we could have some 

```
traverse
  :: forall f t a b. Applicative f ∧ Traversable t
  =| (a → f b)
  → t a
  → f (t b) 
```
---------------

if we allow for implicit top-level existential quantifications:

```
traverse
  :: Applicative f ∧ Traversable t
  =| (a → f b)
  -> t a
  -> f (t b) 
```

or 

```
traverse
  :: (a → f b)
  -> t a
  -> f (t b) 
  |= Applicative f ∧ Traversable t 
```

I'll stop here as I start to really diverge from the original issue :sweat_smile:

**Comment by natefaubion** [comment]
> Dictionary application becomes curried, which entails a performance hit. Inlining should deal with this, either in the compiler later, or in Rollup by the time we get to 1.0.

Dictionary application is already curried, so you aren't losing anything 😆

**Comment by damncabbage** [comment]
Apologies for additional syntax-stirring.

Taking the initial example (and partly replying to @rvion's first post), maybe this makes the "one `=>` per constraint" thing clearer:
```
traverse ::
  forall f t a b.
  Applicative f =>
  Traversable t =>
  (a -> f b) ->
  t a ->
  f (t b)
```
(This is something I've been mucking around with as a coding style [thanks to a co-worker](https://twitter.com/damncabbage/status/766158839863398400).)

Even with this I'm still fond of the shorter/grouped ()'d list of constraints for short signatures, but I understand if the current version is a pain to keep around.
