### ISSUE TITLE
psc-publish: optional "v" prefix for tag

### ISSUE THREAD

**Issue by ethul** [purescript/purescript#2693]
I am wondering if you would consider making the ["v" prefix](https://github.com/purescript/purescript/blob/c48f74139e94b43c7ecec726d4b280303ae995e0/src/Language/PureScript/Publish.hs#L192) optional in the git tag. It seems to be more of a [convention for npm](https://docs.npmjs.com/misc/config#tag-version-prefix) and is [optional for bower](https://bower.io/docs/creating-packages/#register). I'd be happy to submit a PR at some point for this!

**Comment by hdgarrood** [comment]
It actually was optional originally, but since the majority of published purescript packages do include it, we recently decided to make it non-optional. I'm fairly happy this was the right move; if it were optional but only a tiny fraction of ecosystem packages omitted the 'v', it would be very easy to forget to handle this case in other tooling (such as psc-package).

**Comment by ethul** [comment]
Thanks for the info. I can understand the decision to simplify tooling. Adding the "v" prefix definitely works. Just wanted to bring this up because I ran into this a little while ago.

**Comment by paf31** [comment]
Shall I close this one then?

**Comment by ethul** [comment]
Okay by me to close
