### ISSUE TITLE
Nesting of multi-line comments is broken

### ISSUE THREAD

**Issue by stefanholzmueller** [purescript/purescript#2748]
The [language reference](https://github.com/purescript/documentation/blob/master/language/Syntax.md) mentions that multi-line comments can be nested like this:
```
{-
  Comment
  {- nested comment -}
    continued comment
-}
```
but that snippet does not parse:
```
Unable to parse module:
unexpected "continued"
expecting indentation at column 1 or end of input
```
Tried it with 0.10.7 locally and in Try PureScript. If I remove the spaces before the word 'continue', I get another error: 
```
unexpected }
expecting number
```
Seems like the parser is easily confused with nested comments. And the documentation is incorrect... or possibly outdated?

**Comment by paf31** [comment]
The documentation is out of date, the parser hasn't supported nested comments in a while. Thanks for the report, I'll fix this in the docs repo.

**Comment by paf31** [comment]
https://github.com/purescript/documentation/pull/55

**Comment by gomain** [comment]
Why was _nesting of multi-line comments_ discontinued?

I do have a use case where _nesting of comments_, together with _multi-line comment not require closing `--}`_ makes it very convenient to comment out large sections of code &mdash; potentially to the end of file. Mainly to allow the remaining code to compile together. This very much helps narrow down code space when fixing bugs. And also allows testing/exploring the remaining code whiles the problem code is not yet fixed; in the repl, for instance.

The current semantics of multi-line comments is that the comment section spans from the opening `{--` to the first closing `--}`

```purescript
{--
  these
  lines
  are
  commented
  {--
    these
    lines
    are
    commented
  {--
    these
    lines
    are
    commented
    {--
      these
      lines
      are
      commented
    --}             -- comment stops here
    these
    are
    not
  --}
  neither
  are
  these
```

I'm sure there was good reason to not support nesting of comments. Would someone mind to explain here or point to the argument, please?

If not, can this feature be requested?

**Comment by natefaubion** [comment]
The main reason is that it fairly significantly complicates the parsing rules of comments. As an example edge case, what about your `--` comment in the middle of a nested comment. What happens if that also contains a `-}` delimiter? Should that be ignored? Comment structure becomes it's own mini-language and it's just hard to justify ease of commenting out large blocks of code when editor tooling makes it possible to comment large sections out very easily (with even just single line comments no less).

**Comment by gomain** [comment]
Thanks @natefaubion, but I'm not convinced it's that complicated.
> As an example edge case, what about your -- comment in the middle of a nested comment. What happens if that also contains a -} delimiter? Should that be ignored? 

<i>Multi-line comment</i>s takes precedence over <i>single line comment</i>s. So in this case, the `--` delimiter is ignored. It, together with following text, is just _comment content_. Had there been a `--}` delimiter it would decrease the _nesting count_ by 1. Multi-line comments end when nesting count is decreased to 0.

**Comment by natefaubion** [comment]
If your goal is to comment out large pieces of code, then how `--` is treated in a nested comment matters. If it was a comment in code, should it also be a comment within a `{-`? I'm not saying that there aren't answers to these things, I'm trying to give a reason for it not being supported. It's a fairly uncommon need, so it isn't a priority to support it when the easy (and common) rule serves most use cases.

**Comment by gomain** [comment]
> how -- is treated in a nested comment matters. If it was a comment in code, should it also be a comment within a {-?

Nested _single line comments_ are currently supported; they are regarded as _comment content_.
```purescript
{- this
is
-- a
valid -- comment -}
```
And since nest counting seems trivially simple, even if it were for an uncommon need, shouldn't the benefits out weigh the costs?

I suspect there is more underlying complexity involved making the costs not worth it.

I understand how this would not be a priority as there exists (relatively easy) ways to achieve this. The question is &mdash; is there reason to not support this? would a PR for this feature be accepted?

**Comment by natefaubion** [comment]
Note I was referring to something like
```purescript
example = wat -- this is a -} comment
```

And then inserting
```
{-
example = wat -- this is a -} comment
```

A little silly yes 😆 , but these are the kind of weird cases you get when your goal is to comment out large blocks of code with nested comments.

I'm personally ambivalent, since I don't use block comments to comment out code (I don't really like block comments in general). I can't say whether it would be accepted. My experience has been it's difficult to get language-level things merged that don't have pressing support in the community.

**Comment by milesfrain** [comment]
It seems like most purs syntax highlighters support nested comments, so then it's confusing why seemingly-correct code fails to compile.

If nesting comments was zero-effort to implement and maintain, then I don't think any of us would be against that feature. So then it seems like the question is whether this nice-to-have is worth the effort.

My use case for block comments involves [scriptable resetting](https://github.com/purescript-contrib/purescript-book/blob/671243109bae2a10d5571d92058d75b11ac99873/scripts/resetSolutions.sh) of [tests](https://github.com/purescript-contrib/purescript-book/blob/b75515f4e50a61ee86cd483b50e243c7fff03223/exercises/chapter4/test/Main.purs#L21-L22) and [solutions](https://github.com/purescript-contrib/purescript-book/blob/b75515f4e50a61ee86cd483b50e243c7fff03223/exercises/chapter4/test/Main.purs#L6) for readers of the purescript book. Right now, I can't include any block comments within the tests.
