### ISSUE TITLE
[psc-ide] declaration position is not correct in this case: (data A = X; data B = A A)

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2781]
in this module: https://pursuit.purescript.org/packages/purescript-outwatch/0.6.0/docs/VDomModifier#t:VDom

```purescript
data VNode e = VTree (VTree e)
  | StringNode String

data VDom e = Emitter (Emitter e)
  | Property (Property e)
  | Receiver (Receiver e)
  | VNode (VNo|de e)
--            ^cursor here
```

when I hit `jump to declaration`, vscode takes me to the `data VDom` declaration instead of the `data VNode`declaration

📝  is it because of this configuration?

```purescript
data Aaa = Ccc
data Bbb = Aaa Aaa
--             ^ this one 
```

**Comment by kRITZCREEK** [comment]
The query VSCode makes to psc-ide will return position information for both `data VNode` and `data VDom`, but VSCode likely just picks the first one.

`purs ide` does not know the position of the `VNode` data constructor because of #2216 and so it takes you to the type declaration for `VDom`.

The 100% solution would be to be able to detect the namespace (value, type, kind) the cursor currently resides on by running the full parser on the file, but that will only work when the file is syntactically correct and will be somewhat slow. I'm open for suggestions, but for now the best fix might be for VSCode to display both positions and let the user choose.

**Comment by paf31** [comment]
Close as duplicate then?

**Comment by kRITZCREEK** [comment]
I think so, yes.
