### ISSUE TITLE
Add support for transparently derived lenses, a la purescript-derive-lenses

### ISSUE THREAD

**Issue by andremarianiello** [purescript/purescript#2796]
The functionality of https://github.com/paf31/purescript-derive-lenses is nice, but as written it is difficult to uses the derived lenses in the same source file in which the originating data type is defined. If this functionality was instead, say, a purescript compiler plugin (is that a thing?) or extension, then PDL need not even be relied on at all.

**Comment by paf31** [comment]
I don't think this is the sort of thing we want to build into the language, which is why it's implemented as a preprocessor. Polymorphic labels, which were merged this week, should allow us to derive object property lenses though (and prisms for variants too, with more work).

If we do implement something like this, it's more likely to be implemented as a general feature, like Template Haskell, than a lens-specific thing.
