### ISSUE TITLE
Support for singletons in RowCons solving

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#2809]
```purescript
returnSingleton
  ∷ ∀ s a r
  . RowCons s a () r
  ⇒ Record r
  → Record r
returnSingleton r = r

test ∷ { foo ∷ Int }
test = returnSingleton { foo : 1 }
```
Gives an error 
```

  No type class instance was found for

    Prim.RowCons t0
                 t1
                 ()
                 ( foo :: Int
                 )

  The instance head contains unknown type variables. Consider adding a type annotation.
```
Probably it should unify `t0 == "foo"` and `t1 == Int`

**Comment by paf31** [comment]
The problem is that `s` is undetermined. Yes, in this case, the compiler should be able to realize that `s` can only be `"foo"`, but the fundeps approach doesn't support that right now. We'd have to make a special case for singleton rows, which I think would require overlapping instances.

I'll leave this open, but put it into `Approved`, then we can think about it once we have instance chains. For now, you need to disambiguate `s` somehow.

**Comment by LiamGoodacre** [comment]
This could now be written as:

```purescript
returnSingleton
  ∷ ∀ s a r
  . RowToList r (Cons s a Nil)
  ⇒ Record r
  → Record r
returnSingleton r = r

test ∷ { foo ∷ Int }
test = returnSingleton { foo: 1 }
```

@cryogenian Is this sufficient for your use-case?

**Comment by kRITZCREEK** [comment]
@cryogenian Did you try Liam's suggestion yet?

**Comment by natefaubion** [comment]
I think the RowToList approach works well enough in practice.
