### ISSUE TITLE
constrained type unification jiggery-pokery

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#2862]
Potentially related? https://github.com/purescript/purescript/issues/950

Trying to make a list type with type-level sizing using https://github.com/bodil/purescript-typelevel:

```
data List s a = Nil | Cons a (forall s'. Pred s s' => List s' a)
cons = Cons
```

The above compiles. `purs` issues a warning because `cons`, as a top-level declaration, should get a type annotation. It suggests `forall t16 t17. t16 -> (forall s'. Pred t17 s' => List s' t16) -> List t17 t16`.

That makes sense.

But what happens when I actually add the annotation such that:
```
cons :: forall t16 t17. t16 -> (forall s'. Pred t17 s' => List s' t16) -> List t17 t16
cons = Cons
```

The compiler errors, giving
```
  Could not match constrained type
                                
    Pred t171 t2 => List t2 t160
                                
  with type
                                
    Pred t3 s'4 => List s'4 t160
```

**Comment by matthewleon** [comment]
Also maybe related: https://github.com/purescript/purescript/issues/508

**Comment by matthewleon** [comment]
Weirdly, switching to `cons x xs = Cons x xs` works. Which is, I think, what #950 was about.

So either I have `cons = Cons` with no type signature, and get a successful compile with a warning. Or I add the suggested type signature and compilation fails unless I switch to `cons x xs = Cons x xs`. Rather awkward.

**Comment by paf31** [comment]
The reason is that we don't elaborate terms under function types. If you run with `--verbose-errors`, you'll see that we have to check subsumption of two function types. If we were to elaborate, we would have to elaborate to something like this:

```purescript
cons = \a s -> Cons a \<dict> -> s <dict>
```

Now you might say those two types are _equal_, not just unifiable, so why bother elaborating at all? Well, we could, but in general, types might only be equal up to alpha-renaming and entailment of constraints, so I don't particularly want to make a special case for this. The workaround is to eta expand, as you noticed. It's not ideal, but I think it's a reasonable trade-off.

Of course, we could improve the documentation for the error message, but I think that's best handled in the docs repo.

I'll close this, but we can reopen if someone can come up with a better solution which handles the cases I mentioned above. Thanks!

**Comment by matthewleon** [comment]
Thanks for the explanation.
