### ISSUE TITLE
Instance declarations still use legacy tuple-ish constraint syntax

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#2871]
As of 0.11, we require value declarations with multiple constraints to separate them with `=>` rather the the old tuple style:

```purescript
-- no longer accepted
foo :: forall a. (Eq a, Semiring a) => a -> a

-- ok
foo :: forall a. Eq a => Semiring a => a -> a
```

However, instance declarations with the new syntax fail to parse:

```purescript
-- not accepted
instance semiringPolynomial :: Eq a => Semiring a => Semiring (Polynomial a) where

-- ok
instance semiringPolynomial :: (Eq a, Semiring a) => Semiring (Polynomial a) where
```

Have we considered changing instance syntax to match with the new constraint syntax elsewhere?

**Comment by paf31** [comment]
Constraints in types can be partially applied, but constraints in instances can't. Also, making `=>` as a binary operator is in preparation for when we can make it an actual type operator, after adding constraint kinds. `=>` as an operator on constraints seems to imply more, that we could write implication constraints on the left of an `=>`, for example, when that's not possible. I like the current syntax because it closely resembles what can actually be done with instances.

**Comment by hdgarrood** [comment]
Okay, so I suppose we should close this?

**Comment by paf31** [comment]
I'm happy to leave it open for discussion.

**Comment by kRITZCREEK** [comment]
I've talked about this with @garyb before, and we identified one major source of confusion being that the two `=>` in instance declarations or type declarations are not semantically the same. In Haskell this problem does not arise because the instance arrow points in the other direction, but maybe it would be better to find a proper keyword for it , rather than overloading `=>`.

**Comment by rvion** [comment]
I don't want insist more, but in case it is still relevant, here is some alternative class and instance (not type) declarations symbol proposal (logical entailment `|=` or `=|`) :
https://github.com/purescript/purescript/issues/2688

in logic,  [Double_turnstile (⊨) means `entails`](https://www.wikiwand.com/en/Double_turnstile)
and it's [reverse form is (⫤) ](http://www.fileformat.info/info/unicode/char/2ae4/index.htm) (initially heard about them [here](https://www.wikiwand.com/en/List_of_logic_symbols))

```purescript 
instance foo :: C x y ⊨ A x, B y 
instance foo :: C x y |= A x, B y
-- or alternatives
instance foo :: C x y |= (A x, B y)    -- with parenthesis
instance foo :: C x y |= A x /\ B y    -- with (/\) constraint-and operator
instance foo ::  A x /\ B y =| C x y   -- with reverse entailment

class C x y ⊨ A x, B y 
class C x y |= A x, B y

# instead of 
# class A x <= B y <= C x y
# class (A x, B y) <= C x y
```

**Comment by natefaubion** [comment]
I do not think it is likely that we will significantly change constraint syntax in instances, and this has not had activity in some time. Should this be closed?

**Comment by hdgarrood** [comment]
Sounds good to me!
