### ISSUE TITLE
Generic.Rep doesn't derive inner records

### ISSUE THREAD

**Issue by pkamenarsky** [purescript/purescript#2911]
Is this expected behaviour?

     data A = A { b :: { c :: Array String } }

The `Generic.Rep` representation is:

    (Constructor "A"
       (Rec
          (Field "b"
             { c :: Array String
             }
          )
       )
    )

I would have expected the inner record to result in `Rec (Field "c" ...` and so on.

**Comment by garyb** [comment]
I guess this would also fix `genericShow` working for a nested record?

**Comment by paf31** [comment]
I think so, yes.

**Comment by coot** [comment]
I started working on this issue [here](https://github.com/coot/purescript/tree/generic-rep-for-records).

What I have is this:
```
data A = A { a :: { b :: String, c :: String } }

derive instance genericRepA :: Generic A _
```

The generic rep for A has type:
```
Constructor "A" (Rec (Field "a" (Rec (Product (Field "b" String) (Field "c" String)))))
```

But `genericShow a` fails with
```
> genericShow a
Error found:
in module $PSCI
at  line 1, column 1 - line 1, column 13

  No type class instance was found for
                                                                        
    Data.Show.Show (Rec (Product (Field "b" String) (Field "c" String)))
                                                                        

while applying a function genericShow
  of type Generic t0 t1 => GenericShow t1 => t0 -> String
  to argument a
while inferring the type of genericShow a
in value declaration it

where t1 is an unknown type
      t0 is an unknown type

See https://github.com/purescript/documentation/blob/master/errors/NoInstanceFound.md for more information,
or to contribute content related to this error.
```

I need to look into `Generic.Rep`, maybe it needs some changes.

**Comment by paf31** [comment]
I think we need an instance for `GenericShowFields (Rec fields)`.

**Comment by coot** [comment]
Adding:
```
instance genericShowFieldsRec :: GenericShowFields a => GenericShowFields (Rec a) where
  genericShowFields (Rec a) = ["{ " <> intercalate ", " (genericShowFields a) <> " }"]
```
is not enough, there is still missing a link from a `Rec a` that has an instance of `GenericShowFields` to `Field name (Rec a)`.  There is [genericShowFieldsField](https://github.com/purescript/purescript-generics-rep/blob/master/src/Data/Generic/Rep/Show.purs#L62) but it has a `Show a` constraint.  This is needed to show non nested fields.  I thought that adding a similar instance with a `GenericShow a` contstraint instead of `Show a` would make it work but it does not.

```
rec :: Rec (Product (Field "a" String) (Field "b" String))
rec = Rec (Product (Field "abc") (Field "cde"))

field :: Field "a" (Rec (Product (Field "a" String) (Field "b" String)))
field = Field rec
```

And I can `genericShowFields rec`, but `genericShowFields field` complains about a missing `Show` instance:
```
  No type class instance was found for
                                                                        
    Data.Show.Show (Rec (Product (Field "a" String) (Field "b" String)))
```

Just to check, I put everything in `Generic.Rep` and then I could add `Show (Rec a)` instance (with `GenericShowFields a` constraint) - and it worked :), but that's not an elegant solution.

**Comment by paf31** [comment]
I think the solution is to generate an extra `Argument` or `Rec` in between the `Field` and the type of the value it holds. This would unfortunately mean breaking existing code, but I think it's the only way to handle this without overlapping instances.

**Comment by LiamGoodacre** [comment]
@paf31 Sorry to slightly hijack an issue to rant but I think it's somewhat relevant...

I'd much prefer generics rep to pass arguments without inspecting them in any way.  Having a type constructor for each of these cases.
* For a data type: just inspect constructors into a simplified `Constructor`/`Sum` of `Arg`/`Product`.
* For a closed record, either convert top-level to `Rec`/`Product`/`Field`.
* For primitives keep them as is.
* For newtypes, unwrap.

I haven't fleshed it out yet, but something along the lines of:
```purescript
-- what format of type
kind Rep
  Data :: Data -> Rep
  Prim :: Type -> Rep
  Newtype :: Type -> Rep
  Rec :: # Type -> Rep

-- data is a sum of constructors
kind Data
  NoCtors :: Data
  Ctor :: Symbol -> Arg -> Data
  Sum :: Data -> Data -> Data

-- constructors have a product of arguments
kind Arg
  NoArgs :: Arg
  Arg :: Type -> Arg
  Product :: Arg -> Arg -> Arg

-- Examples:
data These a b = This a | That b | Both a b
newtype Foo = Foo (These Int String)

instance repInt :: Rep Int (Prim Int)
instance repFoo :: Rep Foo (Newtype (These Int String))
instance repThese :: Rep (These a b) (Data
  (Sum (Ctor "This" (Arg a))
  (Sum (Ctor "That" (Arg b))
       (Ctor "Both" (Product (Arg a) (Arg b))))))
instance repRec :: Rep {a :: Int, b :: Boolean} (Rec
  (Product (Field "a" Int)
           (Field "b" Boolean)))
```

If someone wants multiple levels of inspecting then we could have something like `Deep`, or they can manually inspect the levels depending on what they're doing.

I'm also wondering if we could instead of having a runtime representation of a rep, provide optics like `Totally` based on a symbol proxy of the constructor name.  This ties in with generics-rep-optics and @garyb's [ctor name issue](https://github.com/purescript/purescript/issues/2913).  Doing this with optics could mean we don't need to convert back and forth between representations.  Not sure how this would/should play out with foreign/hand-written instances.

Let me know if I should move this to a new issue.

**Comment by paf31** [comment]
Also, how would something like `foreign-generic` work with that API? Or any library which uses the current record behavior? I think `Deep` is too much, since then we have the same problems as old generics, and I'm not seeing how to easily inspect only as far as the first non-record, for example.

**Comment by paf31** [comment]
Closing, since records won't be supported in 0.12.0 now.
