### ISSUE TITLE
Scoped type variables bug

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript#2949]
The following suggests that the name of a type variable in an annotation is important:

```purescript
-- fails, could not match type `a` with type `b`
egA = (([] :: Array a) :: forall b. Array b) :: forall a. Array a

-- works, for some reason
egB = (([] :: Array a) :: forall a. Array a) :: forall a. Array a
```

**Comment by paf31** [comment]
I'm guessing this is a bug in the skolemization code.

**Comment by paf31** [comment]
I think I know what's going on here, and I don't think it's a bug after all.

In the `egA` case, the inner `[] :: Array a` gets skolemized with respect to the outer `forall a. Array a` first. Then it gets checked against the skolemized `Array b` in `forall b. Array b`, which fails, as expected.

In the `egB` case, we don't skolemize the inner `[] :: Array a` the first time round, since the name is shadowed, but we do skolemize it with respect to the inner `forall a. Array a`. It gets checked against that type, which is valid, and then against the outer type, which is also valid.

So I think this is actually fine, and we can close this.

**Comment by paf31** [comment]
Let me know if that doesn't make sense.

Note, both work in GHCi for me, which is slightly surprising.
