### ISSUE TITLE
Flexible instances being detected as orphan instances

### ISSUE THREAD

**Issue by daniel-chambers** [purescript/purescript#2974]
If I try to define a flexible instance for a typeclass in a different module, I am blocked by Purescript's no-orphan-instance restriction, even though a type in the instance is defined in my module. Here's a reproducible example:

```purescript
module Library where

class MyClass a where
  doStuff :: a -> String
```

```purescript
module App where

import Library
import Prelude
import Data.Maybe (Maybe(..))

newtype MyId = MyId Int

instance myIdMyClass :: MyClass (Maybe MyId) where -- Orphan instance :(
  doStuff (Just (MyId a)) = show a
  doStuff Nothing = ""
````

Even though `MyId` is defined in the `App` module, the instance is declared as an orphan, probably because the check is only seeing the `Maybe` type and is ignoring the fact that `MyId` is used in there too.

My practical use case for this is where I have a `Validation` typeclass, and you define instances for the types you want to be able to validate. So if it's an optional field, you define an instance for `Maybe MyId`, since the valid value is a `Maybe`. But I can't define my instances next to `MyId` because of this restriction, and I'm forced to put them in the module where the `Validation` typeclass is defined. If I want to share that typeclass in a library, it would become unusable since I wouldn't be able to make instances in my app. :(

In Haskell (in case it means anything), I am able to define a flexible instance like this without it being considered an orphan.

**Comment by Pauan** [comment]
@daniel-chambers I think the reason PureScript doesn't allow this is because it's actually not safe:

```
instance maybeMyClass :: Show a => MyClass (Maybe a) where
  doStuff (Just a) = show a
  doStuff Nothing = ""
```

If somebody defined an instance like the above, it would be ambiguous whether you wanted a `MyClass (Maybe MyId)` or a `MyClass (Maybe a)`

In this specific case you aren't doing that, so theoretically PureScript *could* be smart enough to realize that it's safe, but that would require it to analyze multiple modules to determine whether it's safe or not.

This also poses problems for libraries:

1. You release your `Library` module as a library

2. An app uses your library and creates a `MyClass (Maybe MyId)` instance

3. You release a new version of your library that adds a `MyClass (Maybe a)` instance

4. The app breaks, and there isn't really anything it can do to fix it

**Comment by Pauan** [comment]
As for a solution to your problem, can't you just flip the `Maybe` and `MyId`?

```
newtype MyId = MyId (Maybe Int)

instance myIdMyClass :: MyClass MyId where
  doStuff (MyId (Just a)) = show a
  doStuff (MyId Nothing) = ""
```

**Comment by daniel-chambers** [comment]
@Pauan I would have expected Purescript to resolve to using the most specific of the instances, ie. `Maybe MyId`. That way if `Maybe a` is introduced in the library later, it isn't used because it is less specific and therefore there is no break in the app.

As for `MyId (Maybe Int)`, unfortunately no, as it's not always an optional ID. Anyway, these are just a contrived examples for reproduction purposes; my reality is a little more complicated. :)

**Comment by Pauan** [comment]
@daniel-chambers That still leaves another problem:

1. Your library defines `MyClass (Maybe a)`

2. Your app defines `MyId`

3. Another app uses `MyId` and relies upon the behavior of `MyClass (Maybe a)`

4. At some point in the future your app defines `MyClass (Maybe MyId)`

5. The other app breaks because it now chooses the more specific `MyClass (Maybe MyId)` rather than `MyClass (Maybe a)`

**Comment by daniel-chambers** [comment]
@Pauan True. However, that same problem exists if the library defines overlapping instances itself, which is allowed. The library can change what instances exist and break downstream parties. Such is the nature of overlapping instances. :) From what I can see, there's a warning when an overlapping instance happens, but it is allowed. 

Example:

```purescript
module Library where

class MyClass a where
  doStuff :: a -> String

newtype Thing a = Thing a

newtype MyId = MyId Int

instance myClassThing :: MyClass (Thing a) where
  doStuff _ = ""

instance myClassThingMyId :: MyClass (Thing MyId) where
  doStuff _ = "Oh Hai"
```

```purescript
module App where

import Library
import Prelude

test = doStuff $ Thing $ MyId 123 -- Warning: Overlapping instances
```

Given overlapping instances are allowed, I'd expect a similar treatment for my orphan (ie. it's allowed with a warning if overlapping instances are detected). If overlapping instances are deemed "bad", then the above should not be allowed at all too.

Either way, I feel like my issue with orphans is separate to the debate about overlapping instances, in that the treatment of orphans should be consistent with overlapping instances. :)

**Comment by LiamGoodacre** [comment]
If you want to read about how orphans are checked, I've written about it here: [orphan-instance-detection](https://liamgoodacre.github.io/purescript/type/class/instance/orphan/functional/dependencies/2017/01/22/purescript-orphan-instance-detection.html).

PureScript looks at only the head of each type argument of an instance.  In your original post, `myIdMyClass` is therefore considered an orphan.

Currently, when multiple overlapping instances are available for selection, you get a warning and it just picks the 'first one'.  I don't advise depending on this behaviour.

**Comment by garyb** [comment]
> From what I can see, there's a warning when an overlapping instance happens, but it is allowed.

Yeah, we probably should have made overlapping instances a hard error rather than just warning. The only reason we didn't is because of the `Inject` class, which behaves as intended, but really needs instance chains or something along those lines to be solved properly. Liam's ^ been on the case for that :wink:.

**Comment by paf31** [comment]
The main reason it needs to stay for now is to support `Eval` in PSCi.

**Comment by paf31** [comment]
Can this be closed then?

**Comment by daniel-chambers** [comment]
Sorry for the slow reply; I was moving house over the weekend. :)

I suppose it's okay to close; it seems like you guys know what you want. I'd prefer that I got a warning than an error for these type of orphan instances, because that'd be consistent with the overlapping warning. But it sounds like longer term, overlapping is going away anyway.

Thanks for the discussion. :)
