### ISSUE TITLE
Reevaluate globs passed on the command line after a :reload

### ISSUE THREAD

**Issue by halcwb** [purescript/purescript#2977]
When I run the repl with the watch flag:`pulp -w repl`, first the repl runs fine, however, when the repl gets reloaded due to a file save, it no longer displays entered characters. Hitting enter runs the command.

Using PSCi v 0.11.5 with node v8.1.3 on macOS Sierra.

**Comment by hdgarrood** [comment]
`pulp -w repl` should be an error, see https://github.com/purescript-contrib/pulp/issues/240. Just use `pulp repl`.

**Comment by halcwb** [comment]
I understand, only, I don't observe any signs that the repl picks up source file changes. When I change a file and save this, I have to `:reload`. When I add a new source file, I even have to quit and restart the repl.

**Comment by hdgarrood** [comment]
I think it's by design - and the right choice - that you have to `:reload` after changing a file; if you accidentally broke your code I think it would be a bit annoying to lose your REPL session and all your bindings. I think it probably should be considered a bug that you have to quit and restart the repl after adding a source file though.

What about re-evaluating the globs passed on the command line after a `:reload`?
