### ISSUE TITLE
[purs ide] consuming way too much memory

### ISSUE THREAD

**Issue by arthur-xavier** [purescript/purescript#3022]
When editing PureScript files on NVIM v0.2.1-359 as of purescript-0.11.6, `purs ide server` is consuming way too much memory. Also it is taking a real long time when opening new files.

With only 4 files open I had `purs ide` consuming 769MB:

![](http://i.imgur.com/xtrkPCK.png)

**Comment by arthur-xavier** [comment]
I tested this further and although Atom takes a little long sometimes to open some files, Spacemacs opens them instantly. This seems to be a problem with https://github.com/FrigoEU/psc-ide-vim maybe. I'll close this and test further.

**Comment by coot** [comment]
This might relate to [this issue](https://github.com/FrigoEU/psc-ide-vim/issues/68). Currently we load all the purs files with the same purs server instance, thus you might end up with a purs server that has way to many things loaded.  You can run `:Pend|:Pload` to restart the purs server and load only current project.  If you'll still have an issue with it, please open an issue for [psc-ide-vim](https://github.com/FrigoEU/psc-ide-vim).

**Comment by kRITZCREEK** [comment]
The memory consumption of `purs ide` doesn't depend on how many files you open in your editor. It always loads all the ExternsFile and all the source files it could find and parse. Your editor shouldn't be slow to open files because of this, unless it's doing calls to collect information about the current files imports, but that call should never be slow.
