### ISSUE TITLE
[purs ide] Editor mode picks up "wrong" source spans

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#3033]
It's a common practice (Emacs, Atom & VSCode definitely do this) to save the currently edited file to a tmp location and run the rebuild command on that file, to not have to save the users file constantly. In editor mode however, this leads to the server picking up the tmp file location for goto definition, which is not good (Leads to lost changes).

Not entirely sure how to handle this. We could try to look up the previous file location from our server state (This will be a little complicated, but not impossible) or allow another parameter to the rebuild command which overrides the filepath in the source spans of the parsed module. The last option is to just save the original file on the editor side and rebuild on top of that.

Any input? \cc @nwolverson @coot

**Comment by nwolverson** [comment]
Right now I think I only call rebuild with the original file, but parse imports and do case-split etc on a temp file. I think that if you're going to do continual rebuilding as you type you need to do this without saving the file, or you break the user's editor experience.

Is it worth considering providing the file contents directly instead of reading them from file? You could avoid the file access entirely. Either way specifying the nominal file location would seem to make sense.

(If you use a temp file do you not break FFI checks anyway?)

**Comment by kRITZCREEK** [comment]
The on-type checker copies the corresponding `.js` file in the

**Comment by coot** [comment]
The vim plugins runs the rebuild command on save, so we don't have this problem. Sending the file to the server together with its file name seems like a really good approach. @kRITZCREEK you're using that to find record fields, in this case you could send a really minimal module to purs server to make the type checking really fast.
