### ISSUE TITLE
shadowing in let binding does not compile

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3046]
[Here](http://try.purescript.org/?gist=706c2885e6b741a2328f38aeaf3cd729&backend=core) is a minimal example:
```
x :: Int
x = 0

y :: Int
y =
  let x = x + 1
  in x
```
Is this a bug or a feature?

**Comment by LiamGoodacre** [comment]
Actually the shadowing has nothing to do with the behaviour you're seeing - you could delete the top-level `x` declaration and still get the same error.

What's going on is that in the expression `x + 1` the `x` would be referring to the local `x` (the one currently being defined).  But in this case it is not allowed because the value of local `x` in the evaluation of `x + 1` would be `undefined`.  The compiler checks for (some of) these situations.

Does that make sense? @coot

**Comment by coot** [comment]
Yes, it does.  It's actually the same way JavaScript is scoping variables too.
