### ISSUE TITLE
Orphan instance error wording reads like a warning

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript#3063]
As discussed on slack, the wording of orphan instance errors reads like a suggestion rather than a requirement. I'm opening this issue to discuss if we want to improve it, and how we can do that.

This is the line in question:
https://github.com/purescript/purescript/blob/ad0c7c04fca8b2dda5a71f558ed943d0b16a2671/src/Language/PureScript/Errors.hs#L776

What if we said something like:

```
There are two ways to fix this error
    1. Move the instance to the same module the class is defined in.
    2. Move the instance to the same module the data type is defined in.
```

Maybe we could make it even easier and mention which module the class and data type are defined in? Do we have that information in the error?

**Comment by AlexMouton** [comment]
+/- 0
;)

**Comment by hdgarrood** [comment]
I think it's slightly difficult because sometimes the answer is to rearrange your code so that you don't need to define any instances at all. For example, suppose you have a type `Foo` from a library with no `Ord` instance, and you want to sort an `Array Foo` according to a total ordering on `Foo` that you have come up with. So, you try to define an `Ord Foo` instance but of course it's an orphan. In that case a good option would be to use `sortBy`. So really there are at least three ways to fix the error: move the instance, use a newtype wrapper, or avoid defining the instance entirely. I don't think we should write "there are n ways to fix this: [...]" unless we are going to have an exhaustive list.

This is also complicated by the fact that saying "an instance must be declared in the same module as either the class or the type" is a simplification which I think  only really works for single parameter type classes. Classes with multiple parameters and functional dependencies are a bit more complex: see https://liamgoodacre.github.io/purescript/type/class/instance/orphan/functional/dependencies/2017/01/22/purescript-orphan-instance-detection.html

**Comment by joneshf** [comment]
For sure, that all makes sense. I'm totally up for different wording. But, every problem can be solved by avoiding type classes. I don't think Kobayashi Maru-ing the error message is helpful.

We currently list only two ways to fix the error in the documentation: https://github.com/purescript/documentation/blob/master/errors/OrphanInstance.md#fix. This reads like the only two options. It doesn't seem crazy to me that we'd just make these explicit in the error message. It's the current state of the world.

Good point about MPTCs. I assume we have all of the information available when we decide to error with an orphan instance.
> I don't think we should write "there are n ways to fix this: [...]" unless we are going to have an exhaustive list.

Then let's do just that! If we give all of that information to `OrphanInstance`, then it should be able to report it properly, yeah? With fundeps, or MPTCs in general, we already know what the covering set is. We should be able to say something like:

```
There are $NUMBER_OF_VALID_INSTANCES ways to solve this:
    1. Move the instance to $VALID_MODULE_1
    2. Create a newtype for $TYPE_1 and define the instance with it
    3. Move the instance to $VALID_MODULE_2
    ...
```

**Comment by hdgarrood** [comment]
> For sure, that all makes sense. I'm totally up for different wording. But, every problem can be solved by avoiding type classes. I don't think Kobayashi Maru-ing the error message is helpful.

Yes ok, good point.

> We should be able to say something like: [...]

That sounds sensible to me, yes.

**Comment by paf31** [comment]
I'm fine with giving a list of the modules where the instance would be valid, but I still think we should have a more detailed explanation in the documentation repo. If the error message gets too long, I'd rather that content be documented there, where it can be searched, indexed, and edited more easily.
