### ISSUE TITLE
purs ide: adding conflicting imports

### ISSUE THREAD

**Issue by coot** [purescript/purescript#3083]
`Data.Tuple.Nested` has both `/\ :: a -> b -> Tuple` and `/\ :: Type -> Type -> Type`.  Now adding import with
```
{"params":{"file":"/home/marcin/repos/gravicus/ospreyui/test/Test/DPIA/Components.purs","importCommand":{"importCommand":"addImport","identifier":"/\\"},"filter
s":[]},"command":"import"}
```
fails with an error
```
["{\"result\":\"Undecidable between type and dataconstructor\",\"resultType\":\"error\"}",""]
```

**Comment by coot** [comment]
ping @kRITZCREEK

**Comment by kRITZCREEK** [comment]
Well that error is "expected" in the sense that we really can't figure out which of the two you want, but now that we have namespace/declaration filters we can ask the editors to let the user decide which declaration they intend to import.

The Declaration filters might be a nicer fit for this, because I think we should prefer
`Did you mean the type class or data constructor Show?` 
over
`Did you mean the type or value level Show`?

**Comment by kRITZCREEK** [comment]
Let's not close this yet. At this point the editors can't figure out the type of declaration they are looking at from the completions: https://github.com/purescript/purescript/blob/71fc308a53bf89678c1e1d4a242cc01561d556d1/src/Language/PureScript/Ide/Types.hs#L193-L201

I'm currently thinking about how to give the protocol more flexibility with respect to the level of detail of the returned information.

**Comment by coot** [comment]
Good.  In vim I can do that by querying syntax highlighting.

**Comment by i-am-the-slime** [comment]
Hey, I think we can close this 😄
