### ISSUE TITLE
Remove ambiguity from TypesDoNotUnify and KindsDoNotUnify errors

### ISSUE THREAD

**Issue by dwhitney** [purescript/purescript#3111]
Every time I get one of the errors mentioned above, I get a little confused about wether I've made an error in the type signature or in the values I'm using, and I often have to open up the repl to write a little sample function to remind myself what the order is. As a reminder here's what a `TypesDoNotUnify` error looks like:

```
  Could not match type

    String

  with type

    Int   
```

I propose this be changed to the following, which makes it more clear about what type is expressed where: 

```
  Found type

    String

  But expected type

    Int
```

Similarly I have the same confusion with the `KindsDoNotUnify` error, and propose it be changed to: 
```
  Found kind

    Type

  But expected kind

    Type -> Type
```

I've created a PR for this here: https://github.com/purescript/purescript/pull/3110
And I've updated the error documentation here: https://github.com/purescript/documentation/pull/127

**Comment by kRITZCREEK** [comment]
This "issue" has come up a couple of times before, I can't find all the discussion around it right now.

The directionality (is that a word?) was taken out in https://github.com/purescript/purescript/pull/1583

Has anything changed since then that lets us avoid the problems described in that PR/issue?

**Comment by dwhitney** [comment]
Should have asked first. Well feel free to kill this if it's a dead topic.

**Comment by kRITZCREEK** [comment]
I'm hoping someone will find the previous discussions and link them here to provide some context. I didn't really participate in them, which is why I can only vaguely hint right now.

**Comment by garyb** [comment]
> Has anything changed since then that lets us avoid the problems described in that PR/issue?

I'm pretty sure no, as it needs that direction hint mechanism Phil mentioned in the other issue.

**Comment by MonoidMusician** [comment]
Here's another issue that talks about it: https://github.com/purescript/purescript/issues/1577

**Comment by dwhitney** [comment]
Alright well I'm not gonna go down that rabbit hole. I'll close this issue and the PRs

**Comment by coot** [comment]
@natefaubion explained it to me that the ambiguity is caused by the type checker alternating between inference and unification, but I couldn't find the quote.

**Comment by natefaubion** [comment]
> @natefaubion explained it to me that the ambiguity is caused by the type checker alternating between inference and unification, but I couldn't find the quote.

What is expected vs given depends on the path the typechecker takes to get to a judgement. It's not a naively local thing where you can say "I'm checking this one, so this one is unexpected", because even though we are checking something, it may be the result of inferring something else, which is a result of checking something else, etc. This varies depending on what's annotated and where. You can then get into cases where just adding a type annotation flips the path around and makes the error flip around and turn into nonsense. So you have to retain some knowledge of how you arrived at a judgement before you can say whether something is expected or not (and even then it's not always great). This is why we retain the typechecker stack in the error, which usually has better information than just the "could not match" part.

Or something. I'm not an expert.
