### ISSUE TITLE
Disallow hiding superclasses of exported classes

### ISSUE THREAD

**Issue by metaleap** [purescript/purescript#3132]
Using the current `master` branch, compiling a purescript project containing these two modules [Mini.TCls3 and Mini.TClsImpl3](https://gist.github.com/metaleap/b7848fb180faaa8e59709679e6d36768) errors not with a description of what's wrong (if anything) in the source but rather:

    * Building project in /home/rox/c/ps/gonad-demos
    Compiling Mini.TCls3
    Compiling Mini.TClsImpl3
    purs: An internal error occurred during compilation: "newDictionaries: type class lookup failed"
    Please report this at https://github.com/purescript/purescript/issues
    CallStack (from HasCallStack):
      error, called at src/Language/PureScript/Crash.hs:24:3 in purescript-0.11.6-8vLqjNaSDrU71uAVwdv7Dy:Language.PureScript.Crash
      internalError, called at src/Language/PureScript/TypeChecker/Entailment.hs:578:40 in purescript-0.11.6-8vLqjNaSDrU71uAVwdv7Dy:Language.PureScript.TypeChecker.Entailment
    purs: thread blocked indefinitely in an MVar operation
    * ERROR: Subcommand terminated with exit code 1

In this case `purs` (built from current `master`) was invoked via this `pulp` command-line:

    pulp build -- --source-maps  --comments

The crash no longer occurs when `class Zero, zilch, class One, ein, uno` are added to the exports of `Mini/TCls3.purs` (equivalently in this case to simply ditching the exports ie. exporting-everything-implicitly). But regardless, `purs` probably wants to error cleanly not crash-ly  =)

**Comment by metaleap** [comment]
The crash no longer occurs when `class One, ein, uno` are added to the exports list. But regardless, `purs` probably wants to error cleanly not crash-ly  =)

**Comment by parsonsmatt** [comment]
So, there's definitely a bug here. I've minimized the test case to #3173. You should be getting an `UnknownClass` error, because the instances for `Uno` and `Zero` aren't in scope because the classes are not exported.

When you provide a fully saturated instance, like `instance Dos Foo`, then it works fine -- the solver is able to find the nullary instance somehow and not error out.

When you provide an instance with a context that depends on an out-of-scope instance, then you get the thread-blocked-on-mvar error. Eg:

```purescript
instance inst3 :: (C2 a) => C3 a B
```

The `C2` instance in the context *also* carries a `C1` instance requirement.

**Comment by parsonsmatt** [comment]
All of the MVar code is located in `Language.PureScript.Make`. I'm having a hard time building with profiling on the test suite so I can get `+RTS -xs -RTS` stack trace information out :\

**Comment by hdgarrood** [comment]
I'm adding the "breaking" label because the way we're addressing this is to produce a `TransitiveExportError` if you try to export a class with a superclass which is not itself exported; we weren't checking for that before so this could break code.
