### ISSUE TITLE
What if we treat recursion like Partiality?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript#3141]
So as we are adding type constraint Partial to expressions which are doing partial pattern match, what if we also add `Recursive` to functions which use recursion and might not terminate?

**Comment by garyb** [comment]
Unbounded recursion is exactly partiality - but without some significantly fancier type system features it can't be determined whether a recursive function is total. Adding `Partial` to every recursive function sounds a bit much to me.

**Comment by paf31** [comment]
👎 from me, the user is free to annotate recursive functions with `Partial` constraints if they want to.

**Comment by joneshf** [comment]
If there won't be official compiler support, you could probably do this in user-land with something like:

```PureScript
module Recursive where

import Data.Function.Uncurried (Fn2, runFn2)

class Recursive

foreign import handleRecursion_ :: forall a. Fn2 a (Recursive => a) a

handleRecursion :: forall a. a -> (Recursive => a) -> a
handleRecursion default value = runFn2 handleRecursion_ default value
```

```JavaScript
'use strict';

exports.handleRecursion_ = function(default, value) {
  try {
    return value();
  } catch (e) {
    if (e.message === "Maximum call stack size exceeded") {
      return default;
    } else {
      throw e;
    }
  }
};
```

Dunno how kludgey you think that is or not. But the idea is, if you don't provide an instance in the `Recursive` module, you can never make one—due to orphans. So the only way to dispatch the constraint is through `handleRecursion` (or some other thing like `unsafeCoerce`). You then force everyone that uses `handleRecursion` to pass in a value that will be used if the stack overflows. Otherwise, the code won't compile.

Probably not the best way to deal with it. And it probably won't get 100% of the cases, but it ought to be a half-way decent jumping off point if you'd like to pursue the idea.

**Comment by natefaubion** [comment]
What if something is monadically recursive, and even asynchronous?

**Comment by safareli** [comment]
Thanks, just wanted to hear what others thought
