### ISSUE TITLE
Core support for unsigned Int

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3146]
This was mentioned back in the day: https://github.com/purescript/purescript/issues/1762#issuecomment-167462204

I think issues like this make it relevant to bring it back up again: https://github.com/purescript-node/purescript-node-buffer/issues/25

I've been doing some work with `TypedArray`s lately, and this kind of thing hurts.

Perhaps the solution is to integrate something like https://github.com/zaquest/purescript-uint in the Prelude? I could raise this issue there.

**Comment by matthewleon** [comment]
One thing that would be very nice about having some kind of lower-level support for unsigned `Int` would be the ability to do, say, `[1, 2, 3] :: Array UInt`. Having to use a function for coercion feels somewhat less ergonomic.

**Comment by hdgarrood** [comment]
I don't have an opinion on whether unsigned integers are important enough to get language support, so I won't weigh in there, but I am against overloaded literals, i.e. I think it's a very nice property that we currently have that a literal like `1` or `1.0` has a single, fixed type, so that you don't need to add annotations to get stuff to compile; I actually much prefer this to Haskell, where the type of `1` is something like `Num a => a` (although perhaps it's more justifiable in Haskell since Haskell has many more numeric types than PureScript).

If we do want unsigned integer literals, could something like a `u` suffix work? For example, `1u :: UInt`?

**Comment by matthewleon** [comment]
> If we do want unsigned integer literals, could something like a u suffix work? For example, 1u :: UInt?

Seems reasonable to me.

**Comment by hdgarrood** [comment]
@parsonsmatt has made a great start on this in #3169 but I probably jumped the gun a little by making a bunch of suggestions in review before we'd really decided whether we want to go ahead with this, so sorry about that!

Anyway, can we make it any clearer as to what the benefit is to having `UInt` built into the compiler instead of as an independent library (as it currently is)? Of course having literals is nice, but on reflection I'm not sure that's enough to swing it on its own.

**Comment by Pauan** [comment]
@hdgarrood Because `Array` indexes are never negative, representing them with `UInt` makes a lot of sense, it gives us tighter compile-time guarantees without runtime cost.

But if the various `Array` functions (like `length`, `index`, `modifyAt`, etc.) use `UInt`, then you really want it to be easy to use `UInt`, so having syntax sugar for `UInt` literals makes sense.

Of course whether the `Array` functions should use `Int` or `UInt` is a separate question, but it is an example of a use-case for built-in `UInt`

**Comment by kRITZCREEK** [comment]
`UInt` is not really a win there. You don't see all the Haskell equivalents take `WordXX` values as their arguments, because an overflow is just as worse as a negative value, but it's easier to detect the negative value and bail with a useful error.

**Comment by matthewleon** [comment]
@kRITZCREEK A bit confused by what you're saying here: If the compiler can guarantee that your index is non-negative through the type system, doesn't that ever-so-slightly simplify your bounds check? It seems to me like, at a minimum, a very slight performance win.

**Comment by kRITZCREEK** [comment]
@matthewleon Do you want to not define `(-)` for `UInt`? You can do these kind of things in a dependently typed programming language where the compiler is able to prove things at compile time, but it's not practical in a language like PS (it's not really all that "fun" in dependently typed languages at this point either).

If I can't index into an Array after performing a subtraction and need to use a function like `toUInt :: Int -> Maybe UInt` I didn't actually win anything, since I'm doing the `> 0` check at every callsite to account for the `Nothing` case.

**Comment by garyb** [comment]
All the examples above should be `Nat` rather than `UInt` really, but... /waves hands, leaves thread with no useful contribution

**Comment by parsonsmatt** [comment]
`Nat` would probably be a more useful type, with a different implementation of `-` that bottoms out at `0` instead of underflowing.

I've heard Haskellers say that functions accepting an `Int` when a `Nat` would do are unfortunate, and I tend to agree.

Having `UInt` in the compiler gives us a few benefits:

- `UInt` literals
- Warning when accidentally writing a negative `UInt` literal
- Optimizer and inliner support
- A built-in type to express "numbers that can't be negative"

And has a few downsides:

- Another datatype to support for every backend
- The optimizer has essentially duplicate cases for `Int` and `UInt`
- Underflow is possibly more confusing than mere negative numbers, and is harder to check for (eg, in a negative `Int`, you can report `"You provided a negative number to index into an array, that's an error"`, but with a negative `UInt`, you only have `"You provided a number out of bounds of the array"`)

**Comment by michaelficarra** [comment]
I'm 👎 on this proposal. 32-bit unsigned ints, as proposed here, aren't that useful for the array use-case, as JavaScript array indexes are bounded at [0, 2<sup>53</sup>).

**Comment by hdgarrood** [comment]
On the topic of optimizer and inliner support: assuming we want a `Ring UInt` instance which wraps around e.g. `0 - 1 == top`, since 32-bit `Int` and `UInt` are both isomorphic to (as rings), you might be able to obtain inlining without compiler support by defining `newtype UInt = UInt Int` and `derive newtype instance {Semiring,Ring,...} UInt`. You could then define a `toNumber :: UInt -> Number` which internally does `>>> 0` for display and communication with external libraries/over the network.

**Comment by hdgarrood** [comment]
@parsonsmatt when you say `Nat`, are you imagining an arbitrary large nonnegative integer type?

**Comment by parsonsmatt** [comment]
Possibly? `Nat` and `UInt` are conceptually different enough that I think it's a bit off topic.

Sad to discover that GHC's `Numeric.Natural.Natural` just throws an exception on underflow :frowning_face:

**Comment by Pauan** [comment]
@michaelficarra That's not true, JavaScript Arrays are bounded at 32-bit uints:

```javascript
new Array(Math.pow(2, 32))      // RangeError: Invalid array length
new Array(Math.pow(2, 32) - 1)  // Works
```

This is [specified in the ECMAScript spec](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-arraycreate), and has been true for a long time (even before ECMAScript 3!).

**Comment by Pauan** [comment]
@kRITZCREEK That's a good point about underflow. I agree that makes this proposal less attractive.

**Comment by Pauan** [comment]
Speaking of JavaScript arrays, because JavaScript indexes can go all the way up to 32-bit uints, it's currently not possible (in PureScript) to access array elements which are between indexes `2147483648` and `4294967294`. This is a very niche case, but it is a reason for using `UInt` (or `Nat`) instead.

I would personally be in favor of a `Nat` type that raises an exception when underflowing/overflowing (or alternatively saturates to `bottom`/`top`)

**Comment by michaelficarra** [comment]
@Pauan See the [`ToLength`](https://tc39.github.io/ecma262/#sec-tolength) abstract operation and its references. This abstract operation was defined specifically for use in all of the Array prototype methods. So while arrays created with the Array constructor have this 32-bit limitation, array-likes are allowed indexes anywhere within the non-negative safe integer range of doubles, and all of the Array methods will just work on them.

**Comment by Pauan** [comment]
@michaelficarra There's a big difference between `Array` and array-like.

The PureScript `Array` type is always a JavaScript `Array`, not an array-like.

The ECMAScript spec is quite clear that `Array` indexes are always 32-bit uints under all circumstances, not just the `Array` constructor:

https://tc39.github.io/ecma262/#sec-array-exotic-objects
https://tc39.github.io/ecma262/#array-index

As an example, trying to call `array.push` or `array.splice` when `array` has a length of `4294967295` will trigger a `RangeError`
