### ISSUE TITLE
Prim docs: Inaccurate type for RowCons

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3155]
Pursuit has `RowCons` from `Prim` typed as:

`class RowCons (l :: Symbol) (a :: # Type) (i :: Type) (o :: Type) | l a i -> o, l o -> a i`

See: https://pursuit.purescript.org/builtins/docs/Prim

I think this should be `class RowCons (l :: Symbol) (a :: Type) (i :: # Type) (o :: # Type) | l a i -> o, l o -> a i`

From looking at the Pursuit code, it seems the pretty printing for the type comes from within the PS code.

**Comment by hdgarrood** [comment]
IIRC this is fixed as of 0.11.7, we just need to update Pursuit to use the most recent version of the compiler library.

I can't check right now but if you use `purs docs --html` with some set of modules it should produce an HTML page for Prim as well, and you could check there to see if it is fixed in 0.11.7.

**Comment by hdgarrood** [comment]
Confirmed that this is fixed in 0.11.7. Thanks anyway for the report!
