### ISSUE TITLE
Proxy syntax / plans for 0.12

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3178]
Currently I think it's not entirely clear what the plans are for 0.12, and what the difference between the `0.12.0-dev` and `master` branches is. I'm opening this issue to try to resolve this. There's been a bit of discussion on Slack already but issues are easier to refer back to in the future, which is why I'm creating one here.

The new proxy syntax presents issues because of the kind unification bug/bugs mentioned in #3075 and #3077 (note: #3077 exists in 0.11.7 too, but the issue is much harder to run into accidentally without proxy syntax). Additionally, it sounds like fixing this kind unification bug might take us some (most?) of the way towards polykinds, but of course if we have polykinds there's less of a reason to have special proxy syntax, since we can define a polykinded Proxy type; the only benefit of the proxy syntax is then that you can use proxies with less noise (`@"foo"` vs `Proxy :: Proxy "foo"`).

Setting the kind unification bug aside for a moment, I think it's probably also worth resolving the original issue in #3075 one way or another before we make a release which includes the proxy syntax, so that we don't later need to make a possibly-breaking change to make proxies comfortable to use.

I think the effort/value ratio of resolving these issues is probably quite high, so I think it might be worth considering reverting the proxy-related PRs for now to avoid blocking a 0.12.0 release, namely:

* #2846
* #3095
* #3124
* #3144

We could then delete the `0.12.0-dev` branch and continue working towards a 0.12 release on the `master` branch.

What do people think about this? /cc @rightfold

**Comment by joneshf** [comment]
I'm much more of a user than a contributor to the compiler these days, so take these comments from that perspective.

I have a concern with not having a separation between future work and current work. We haven't had a clean separation in the past and sometimes it takes quite a while to get fixes.

For instance, https://github.com/purescript/purescript/issues/2958 was fixed in four days, but it took four months for users to get a fix. That bug in particular might seem trivial or unimportant or whatever. But depending on what the operator is, it can cause you to change your entire program around just to get around it.

Even now, we're sitting on some bug fixes that could make 0.11 life better:
* https://github.com/purescript/purescript/pull/2967
* https://github.com/purescript/purescript/pull/3106
* https://github.com/purescript/purescript/pull/3126
* https://github.com/purescript/purescript/pull/3128

The point I'm trying to make is that having some way to get bug fixes and non-breaking changes is incredibly beneficial for users of PS (more beneficial than it sounds). Whether that requires a separate branch or not is up to contributors.

If making releases is too much of a burden, I can totally understand why it's less appealing to make a new release that just has bug fixes. I also don't really know what goes into releases, so I can't even begin to help.

> and what the difference between the 0.12.0-dev and master branches is.

I think this commit merged the two branches together: https://github.com/purescript/purescript/commit/c19a79285c5697b59c46803483b41ffeaa5cd7b0. I'm not sure if that was intentional though. I didn't really review it, just made the comment about cherry picking vs. merge.

**Comment by hdgarrood** [comment]
Yeah, I hear you, definitely. This has occurred to me before too. We do keep breaking releases fairly infrequent, though; 0.11.0 was released in March and we've had 7 non-breaking releases since then.

At this point, I'm not super keen on trying to backport the non-breaking changes and bug fixes which have not yet made it into a release and make an 0.11.8 release including them, though; the way I see it, that would involve quite a lot of effort for maintainers which would probably be better spent working on issues, and a non-negligible risk of accidentally introducing new bugs as well.

> If making releases is too much of a burden, I can totally understand why it's less appealing to make a new release that just has bug fixes.

I think this is pretty much it unfortunately. I haven't been particularly deeply involved in making releases before but there is a surprisingly large amount of stuff that needs doing, and I expect that's why there can sometimes be longer periods of time between releases.

Anyway, I think the issue of release frequency and frequency of breaking changes is slightly off-topic for this issue; obviously it's good to discuss but can we avoid doing so further on this issue, please? I think Slack or the mailing list might be better options.

**Comment by paf31** [comment]
> Currently I think it's not entirely clear what the plans are for 0.12, and what the difference between the 0.12.0-dev and master branches is

I made 0.12.0-dev because there was no work happening on 0.12 but we had bug fixes that should have been backported to 0.11.*. If you merge, you might have a hard time making any patch releases if 0.12 gets delayed again.

**Comment by hdgarrood** [comment]
That merge has already happened (possibly accidentally) - proxy syntax and instance chains are both in `master` now as well as in `0.12.0-dev`. Do you think we should do an 0.11.8 with all of those bug fixes? Maybe I'm being pessimistic and overestimating how much work that would be.

**Comment by kRITZCREEK** [comment]
I'd like to remove Proxy syntax for now and have a breaking release with instance chains and removed Generics as the next release.

**Comment by hdgarrood** [comment]
Ok great, shall we say we're doing that and delete the `0.12.0-dev` branch then?

**Comment by matthewleon** [comment]
> I'd like to remove Proxy syntax for now and have a breaking release with instance chains and removed Generics as the next release.

Does this mean delaying the `Eff` changes? I feel like I'm not alone in being very keen on getting this sooner rather than later.

**Comment by hdgarrood** [comment]
I wouldn't think so, I imagine that wasn't meant to be an exhaustive list.

**Comment by parsonsmatt** [comment]
I'm going to be working on getting `Eff` changes incorporated into 0.12 and would definitely like to see them be packaged along :)
