### ISSUE TITLE
Make Releases Easier

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript#3185]
One of the questions raised in https://github.com/purescript/purescript/issues/3178 was: why does the `0.12-dev` branch exists? The long and short is that bug fixes for 0.11.6 were on `master`, but a release couldn't be made that would only include bug fixes (instead of both bug fixes and breaking changes). In answering that question, it surfaced that making releases is currently hard.

I'd like to make releases not hard. Then bug fixes can be released without a bunch of ceremony and wouldn't require a breaking change for lack of people-power.

I don't know the pain points that go into a release, and won't speculate what they are. I will speculate that the less a person has to do, the easier releases become. So, I think the way forward is to automate as much as possible and fix problems in the process as they arrive.

Some searching hasn't yielded a definitive list of release steps. Is there a list of steps written down somewhere that explains what it takes to make a release? If not, let's start that list here.

**Comment by hdgarrood** [comment]
I think the closest thing we have to a list of release steps is previous "release checklist" issues: #2745, #2151. Those issues are for breaking releases, and of course non-breaking releases are a fair bit simpler.

I would like to have a list of release steps in a markdown file in this repo; we can base it off those issues.

**Comment by seanwestfall** [comment]
Was there ever a roadmap written to explain where future PureScript work was headed? Elm has one, just to think of an example, https://github.com/elm-lang/projects/blob/master/roadmap.md, but it doesn't look like there's anything in https://github.com/purescript/documentation, is that on purpose?

**Comment by hdgarrood** [comment]
No, there isn't, and I think this is because it would be quite a bit of effort to make sure it was kept up to date and accurate. If you want to get a feel for where future work is headed, the best thing to do is to look at the issue tracker, and specifically the milestones which mention an actual version, like 0.12.0 and 1.0 (note that the 1.0 milestone just means "any time before 1.0", and so things tagged as 1.0 may well happen in an 0.x release).

**Comment by garyb** [comment]
We could also just be sure to provide better messages when we merge things, since you can rewrite them in the GH UI - if we always rewrote them to be "Fix: something meaningful", etc. then using `make_release_notes` would give us a pretty good list that just needs sorting also.

**Comment by hdgarrood** [comment]
Presumably there will be quite a few commits which shouldn't correspond to entries in the changelog, though? I think it's probably easier to require changelog updates than to try provide better commit messages as well. Totally up to you though since you seem to be doing most of that work at the moment!

**Comment by garyb** [comment]
At the moment just about everything that gets merged goes in the changelog, I think the only thing we dropped from the last release was adding tags to the gitignore - the "Other" section of the changelog is where anything like internal code reorganisation goes, which we do out of a desire to credit anyone who has done any kind of work on it I guess (I didn't start the tradition 🙂).

Our CI setup at SlamData makes a release for every commit, and builds a changelog based on the commit messages which does work pretty nicely. I'm not suggesting we go that far, just since you brought it up I thought of the similarities there.

One thing that is kinda nice about the current release notes/changelog is the links to the issues or PRs related to the change - it means you can go and read up any discussion that happened around the change also. We could definitely require adding issue numbers in the changelog, but I think having the PR numbers like we've been doing lately is perhaps even better, since there's often further discussion in there. I guess that still works if we require changelog updates, it's just that change would have to be committed after the PR is created.

One other con is we'll sometimes get conflicts in the changelog if merging a few things at once.

Sorry, that's a bit of a confusing message as it's a mixture of arguing against and musing about how we might do a manual changelog, just thinking aloud really.

**Comment by hdgarrood** [comment]
That all makes a lot of sense, thanks for writing it up :)

**Comment by hdgarrood** [comment]
I'm going to close this since no more concrete proposals for making releases easier seem to be coming up, and since releases don't seem to be too difficult now, especially since our new 6-week release schedule seems to be working nicely.
