### ISSUE TITLE
Allow ansi-terminal version 0.8

### ISSUE THREAD

**Issue by mekeor** [purescript/purescript#3189]
[Purescript currently uses `ansi-terminal >=0.6.2 && <0.7`](https://github.com/purescript/purescript/blob/master/package.yaml#L37). It would be nice to use the most recent version 0.8 instead. [This would also make it build on Nix again, I think.](https://github.com/NixOS/nixpkgs/issues/33355) As [its changelog](https://hackage.haskell.org/package/ansi-terminal-0.8/changelog) suggests, it shouldn't be a problem to use ansi-terminal version 0.8.

**Comment by mekeor** [comment]
Sorry. More precisely, I'd suggest to use `ansi-terminal >=0.6.2 && <1.0`.

**Comment by hdgarrood** [comment]
I'd much prefer that Nix find a way to use the same install plan as the one we use, i.e. what gets printed when you run `stack list-dependencies`. Since purescript is not (really) a library, it doesn't make sense for us to be chasing the latest versions of things all the time; this is why we removed it from Stackage, for instance.

**Comment by mekeor** [comment]
I made this PR to make it easy for you 😉

**Comment by hdgarrood** [comment]
The hard bit is not making the change to package.yaml though, it's thinking through the implications of the change, reading the changelog of the relevant package to check whether I agree with your assessment that the changes aren't important for us, thinking about whether the new bounds are appropriate, thinking about how much of the package we are using here and, based on that, how likely we are to be affected by future changes... it's much more subtle than it might first appear, and this is why it's much easier to pin down dependencies as much as possible. This is why stack's behaviour of pinning dependencies down is perfect for us and why I recommend that other distributions of the compiler use the same install plan that we are using.

**Comment by peti** [comment]
Distributions don't work that way. Nixpkgs cannot include every Hackage package in every single version just so that every install plan out there on the Internet can satisfied. Most Linux distributions carry a handful of packages in precisely *one version* each. Nix is already an exception there, but the maintenance overhead of distribution multiple version of the same package (without any apparent technical reasoning behind it) is too great to be feasible.

Apart from that, I also believe that you greatly overestimate the dangers of performing minor updates in dependencies.

**Comment by hdgarrood** [comment]
> Nixpkgs cannot include all Hackage packages in every single version just so that any random install plan out there on the Internet can be satisfied.

The way I see it, this is a problem with Nix/Nixpkgs. It's not hard to build the compiler from source using the same install plan as the one specified by our stack.yaml on platforms which haven't imposed the constraints that Nix does.

> Most Linux distributions carry a handful of packages in precisely one version each.

Indeed, and I think this is a large part of the reason almost all programming languages end up rejecting distributions' package managers and use their own instead; `gem`, `virtualenv` plus `pip`, `cargo`, etc. I really don't think this is a reasonable constraint to impose.

> (without any apparent technical reasoning behind it)

The technical reasoning (which I would also have happily given if you had asked nicely) is that the compiler is likely to behave differently with a different install plan, and since almost everyone who uses the compiler is using the exact same install plan, namely the one given by `stack.yaml`, it's likely that installs with a different set of dependencies haven't been tested *at all*. I'm trying to avoid situations where people report bugs which arise from having selected a different install plan, leading to lost time (both on the user's and the maintainer's ends).

The way I see it, the bounds information in `purescript.cabal` is not really part of the public API, rather a necessary part of uploading to Hackage. I don't think we should support compiler installs which use a different install plan.

> Apart from that, I also believe that you greatly overestimate the dangers of performing minor updates in dependencies.

Perhaps, but 0.7 -> 0.8 is a major update which may include breaking changes, according to Haskell's PVP. Of course, breaking changes often reflected in type signatures, but not always.

**Comment by hdgarrood** [comment]
I'll close this since Nix seems to have found a solution, and we have updated to ansi-terminal 0.7.x. We will update to ansi-terminal 0.8 at some point in the future, probably once it's in a Stackage LTS snapshot.
