### ISSUE TITLE
Use `<=` instead of `=>` for function signatures

### ISSUE THREAD

**Issue by adius** [purescript/purescript#3201]
It makes sense to me, that you use `<=` for superclasses.

```purescript
class (Apply f) <= Applicative f where
```
The Applicative class implies that the Apply class is implemented.

But shouldn't it then be the same for function signatures:

```purescript
void :: forall f a. Functor f <= f a -> f Unit
```
The implementation of `void` implies that `f` is a Functor.

It's confusing that the `=>` can mean "implies" or "constraints"

**Comment by hdgarrood** [comment]
:-1:, mainly because this would be a severe breaking change.

I can offer an explanation for the way it is now, though: the type of `void` says, *if* you can give me a `Functor f` instance, *then* I can give you a function whose type is `f a -> f Unit`. The way I see it, this is where the analogy with logical implication comes in.
