### ISSUE TITLE
Add Result data type

### ISSUE THREAD

**Issue by adius** [purescript/purescript#3202]
It's really awful that we misuse `Either` as a Success/Error type.
Why is `Left` the error and `Right` the success?
Not intuitive at all and not intuitive for Developers new to Haskell.

The elm community recognized the problem and introduced the Result data type (http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Result)

How about we introduce it too, in order to have dedicated type for computations that can fail?

```purescript
data Result error value = Error error | Success value

fromEither :: forall error value. Either error value -> Result error value
fromEither either = case either of
  Left error -> Error error
  Right value -> Success value
```

**Comment by Pauan** [comment]
:+1: Rust, OCaml, and F# also use a `Result` type.

**Comment by garyb** [comment]
> Not intuitive at all and not intuitive for Developers new to Haskell.

I assume you mean PureScript in this case? :wink:

Feel free to make a library for it, there's nothing to stop people using a `Result` rather than `Either` if that's what they prefer. The core libraries don't really have any situations (aside from maybe `ExceptT`) where there's any kind of error `Either`-based error handling that I can think of.

I'll close this here as it's not an issue specific to the language / compiler.

**Comment by adius** [comment]
Ok, thanks for the feedback. This would have been my next step anyways, just wanted to make sure that's the best way.

**Comment by garyb** [comment]
Just a note on "why left or right" though - using `Left` as the failure case means that the `Functor` instance will map over the intended result type, which is generally more useful than mapping over the error. Also the joke/mnemonic is "`Right` is right" (used in the sense of not-wrong in the second case).

**Comment by adius** [comment]
> using Left as the failure case means that the Functor instance will map over the intended result type

But it could just as well have been implemented the other way round, right?

**Comment by natefaubion** [comment]
The instance depends on the right-most type variable. It would be very obscure to have `Left` use the right variable, and `Right` use the left variable.

**Comment by adius** [comment]
I mean
```purescript
instance functorEither :: Functor (Either a) where
  map f (Left x) = Left (f x)
  map _ (Right y) = Right y
```

**Comment by natefaubion** [comment]
No, that would not compile. You would have to redefine the data type as

```purescript
data Either a b = Left b | Right a
```

Where the right variable `b` points to the `Left` constructor, and vice-versa, which would be very confusing.

**Comment by adius** [comment]
Ok, this would be confusing indeed . But why would it not compile? 🤔

**Comment by natefaubion** [comment]
I would encourage you to try writing it :)

The instances for `Either` are not arbitrary (only a single, lawful implementation exists), and it has a single objectively intuitive representation, which you can't really say for `Result` (is the error the left or the right type variable?).

**Comment by adius** [comment]
Mh, I tried to implement it and couldn't make any sense of the error messages 😅.
Maybe you can enlighten me? 😇

```purescript
data Either a b = Right b | Left a
```
This works 😛

Actually I think `Right` and `Left` are bad names.

```purescript
data Direction = Left | Right

date Either a b = OptionA a | OptionB b
```
would make much more sense.

**Comment by natefaubion** [comment]
Maybe try using different variable names. Since everyone is using `a` the error is awkward.

Given:
```purescript
map :: forall f a b. Functor f => (a -> b) -> f a -> f b

data Either x y = Left x | Right y

instance functorEither :: Functor (Either x) where
  map f (Left x) = Left (f x)
  map _ (Right y) = Right y
```
```
  Could not match type

    x2

  with type

    a0


while checking that type t1
  is at least as general as type a0
while checking that expression x
  has type a0
in value declaration functorEither

where x2 is a rigid type variable
      a0 is a rigid type variable
      t1 is an unknown type
```

So let's specialize the function `map` to the Functor `Either x`.

```purescript
map :: forall a b. (a -> b) -> Either x a -> Either x b
```

The `Left` constructor contains a value of type `x`, not of type `a`. Therefore you cannot apply the provided function to whatever is in `Left`. You would have to redefine the data type.

```purescript
data Either x y = Right x | Left y
```

But this is a very confusing representation.

The languages you mention have opted for a data-type like `Result` because they lack the same kind of abstraction PureScript and Haskell support. You end up doing a lot of pattern matching, so it is helpful. Either is just a very general data type that happens to have clearly defined (unambiguous, given the typeclasses we use) short-circuiting behavior, but if you wanted to program against actual semantics, you could use `MonadError e m`, which supports `throwError` and `catchError`, and would be clearer than both, _and more reusable_ since you could use it for Either, Result, ExceptT, etc.

**Comment by Pauan** [comment]
> @natefaubion The languages you mention have opted for a data-type like `Result` because they lack the same kind of abstraction PureScript and Haskell support.

That's not *quite* true: Rust has *excellent* abstraction capabilities, and using `Result` in Rust is even easier (and more concise) than using `Either` in Haskell / PureScript.

The reason Rust chose to use `Result` is because the names are intuitive and hard to mess up, even for people new to the language.

Your point might be more correct when applied to OCaml, F#, and Elm: their abstraction powers aren't as good. But even in those languages the choice was mostly about *making the name obvious and intuitive* and less about abstraction per se.

Of course there's nothing stopping a highly abstract language like Haskell / PureScript from using `Result`, gaining the benefits of both intuitive names *and* abstraction.

**Comment by adius** [comment]
First version is coming up in a few minutes 😁

**Comment by kRITZCREEK** [comment]
@Pauan The abstraction Nate is talking about here is Functor (which requires Higher kinded types), which can't be expressed in Rust. `.map` is a monomorphic method of the Result type. An example of what this enables in PureScript is that I can use the `void` function, which is defined as `void :: forall a f. Functor f => f a -> f Unit`, on `Either` as well as `Maybe`, while I have to redefine it for both types in Rust or Elm.

**Comment by natefaubion** [comment]
> Of course there's nothing stopping a highly abstract language like Haskell / PureScript from using Result, gaining the benefits of both intuitive names and abstraction.

No, not at all. And I'm not trying to make a value judgement about abstraction capabilities in other languages, only that Haskell and PureScript are pretty unique and it influences the behavior of the data type. `Either a b` is very general (it's the canonical sum type) which has all sorts of applications beyond error handling. It just so happens that when combined with the abstractions we use, you get something that has the short-circuiting behavior you'd expect for error handling. Since the data type already exists, many APIs just reuse it (keep it DRY).

**Comment by Pauan** [comment]
@natefaubion Ah, I understand now what you're saying, I agree with you that `Either` is a natural type to define in Haskell / PureScript (for non-error handling) and it naturally extends to error handling, so they never had much need for `Result`

**Comment by adius** [comment]
Here we go: https://github.com/adius/purescript-result 😁
Would be happy to hear your feedback, then I can publish it on Pursuit.
