### ISSUE TITLE
0.11.8

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript#3225]
I am curious to float the idea of another 0.11 release containing bugfixes and instance chains, but (of course) no breaking changes – overlapping instances would remain a warning.

I tried to see if there has been discussion of this possibility elsewhere, but I don't see it.

It seems to me that there are quite a number of bug fixes being made that could make for a final 0.11 release, and it would be nice for people to begin being able to use instance chains sooner.

Thoughts?

**Comment by matthewleon** [comment]
I see there has been some discussion of this idea here: https://github.com/purescript/purescript/issues/3178

But things have evolved since then, with Proxy syntax, for example, being dropped.

**Comment by garyb** [comment]
I'm not crazy about the idea personally. We'd have to make another branch of master and revert a bunch of breaking changes, which would just further delay 0.12. That's just my 2p though :).

**Comment by hdgarrood** [comment]
I don’t think things have evolved since the discussion in #3178 really; one of the main reasons I created that issue was to propose reverting the new proxy syntax in order to clarify how we were going to get to a state where we could release 0.12.

I’m not really keen either, for the same reason as @garyb gave. Since @kritzcreek also previously said his preference was to have the next release be 0.12 I’ll close this.
