### ISSUE TITLE
Request: Add purescript to stackage 

### ISSUE THREAD

**Issue by Profpatsch** [purescript/purescript#3402]
In [nixpkgs](https://github.com/NixOS/nixpkgs) we have serious problems building purescript consistently, it’s broken more often than not.

Each week, we generate a new version of the package set which contains the current stackage snapshot and on top of that every package that is not on stackage (along with their minimal dependencies if need be).

This means that big non-stackage projects like purescript tend to break regularly, because nobody in our package set can afford to keep it building from week to week. If upstream could handle stackage integration with only the latest snapshots, that would help downstream projects considerably.

**Comment by hdgarrood** [comment]
PureScript used to be in Stackage, but we removed it. It doesn’t really make sense for us to commit to building with the latest versions of everything, since the compiler is, in the vast majority of cases, used as an app, not a library. Also, I don’t think we have the resources to keep up with Stackage even if we wanted to. I’d prefer not to re-add it.

I think the ideal solution would be that nixpkgs finds a way to use the build plan specified by our stack.yaml.

**Comment by justinwoo** [comment]
Related, I'm a bit confused why PureScript on nixpkgs doesn't just use the binary, since I have never wanted to compile the compiler other than when I do development on the compiler itself

**Comment by Profpatsch** [comment]
> Related, I'm a bit confused why PureScript on nixpkgs doesn't just use the binary, since I have never wanted to compile the compiler other than when I do development on the compiler itself

If it’s possible to build from source, we like to do so. With binaries it’s never quite clear where they come from or how they’ve been built. Additionally, they might contain stuff like paths that point out of the nix store.

**Comment by Profpatsch** [comment]
> I think the ideal solution would be that nixpkgs finds a way to use the build plan specified by our stack.yaml

Okay, then we should use the [stack2nix](https://github.com/input-output-hk/stack2nix) tool for purescript.
