### ISSUE TITLE
Add `kind Row` to Prim's Docs

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3459]
The best reference we have to a definition of `Row` is `Record` which is inaccurate because Rows are used in so many other places besides Records (e.g. Variant, type-level programming). I'd like to submit a PR that adds docs for it, but before I do, I want to discuss the best rendering for it. Here's my current rendering for `Row`:

> `Row` is a kind for 0 or more label-type associations where the total number of these associations is known at compile time. A label can be used to refer to an instance of the associated type.
>
> First, a row can be empty (there are no associations) or non-empty (there is at least one association). Second, it can be closed (the row contains only the label-type associations defined here) or open (the row contains at least, though it may contain more than, the label-type associations defined here). Third, it can contain duplicate 'labels'.
>
> Examples:
> Empty closed Row: `()`
> Empty open Row: `( | otherLabelTypeAssociations)`
> Non-empty closed Row: `(label1 :: TypeName1, ... , labelN :: TypeNameN)`
> Non-empty open Row: `(label1 :: TypeName1, ... , labelN :: TypeNameN | otherLabelTypeAssociations)`
> Duplicate Labels: `(someLabel :: String, someLabel :: Int)`

One open question I have. While rows can contain duplicate labels, can those labels associate different types? I'm assuming yes, but I'd like it clarified.

**Comment by thomashoneyman** [comment]
👍  to this. It may still be worth noting some of the uses of row types, including that they can represent a product (`Record`), sum (`Variant`), or list, to give something concrete to map the idea to.

**Comment by hdgarrood** [comment]
I think this is a good idea. Note that the documentation repo does already discuss rows; see https://github.com/purescript/documentation/blob/master/language/Types.md#rows. I think what we have there is good, although it could be expanded a bit; it doesn't mention the syntax for a closed row, for instance.

**Comment by hdgarrood** [comment]
Actually, come to think of it, rows and row kinds aren't actually defined in `Prim`, they're part of the language; see https://github.com/purescript/purescript/blob/dcdd70d50194e723be22c7964f47c2458cc9a706/src/Language/PureScript/Kinds.hs#L18-L28

Given this, arguably it makes more sense to leave things as they are currently. In the same vein, we don't include the kind `->` (that's `FunKind` in the above code snippet) in the `Prim` documentation.

**Comment by JordanMartinez** [comment]
@hdgarrood Mm... That reveals things I didn't know about. 

Let me restate what you are saying to confirm I'm understanding you.

> While the `Prim` module defines a number of primitive types (e.g. `Int`, `String`, etc.) and primitive kinds (e.g. `Type`, `Symbol`) and this module is imported automatically, one can import it as a qualified import to hide some of its types. However, this same idea does not apply when it comes to the kind `Row`, or the kind, `someKind -> someKind` (i.e. `FunKind`s). Rather, these kinds are just "part of the language:" they are always imported; one cannot hide them no matter what they do. If one were to add these kinds to the `Prim` module, it would incorrectly imply that these kinds can also be hidden.

I initially raised this issue because I couldn't find the documentation for `Row`s. So, at the very least, could there be additional information added to the `Prim` module that links back to the documentation repo, with a comment like "additional types and kinds that are a part of the language which cannot be hidden by using a qualified import and which do not appear below are explained in the following link"?

**Comment by hdgarrood** [comment]
Yes, I think what you've written there is accurate. Adding a note to `Prim` along those lines sounds sensible to me. I'd suggest adding a few examples, perhaps: "There are some additional built-in types and kinds, such as row types and kinds (`(name :: String, age :: Int) :: # Type`, type wildcards (`_`), quantified types (`forall`), which are not listed here. This is because they are not defined in Prim, but deeper inside the compiler. These types and kinds are documented in the language reference <link>."

**Comment by hdgarrood** [comment]
We can indeed use markdown for links there. I would prefer something like

```markdown
Instead, these are documented in [the PureScript language reference](https://github.com/purescript/documentation/blob/master/language/Types.md).
```

(see e.g. https://medium.com/@heyoka/dont-use-click-here-f32f445d1021 for why I think descriptive link text is important.)

Also, since we're talking about row kinds I think it would be a bit clearer to put an example of a kind containing `#` first, before an example of a type which has that kind; something like

> ... for example, row kinds (e.g. `# Type`, which is the kind of types such as `(name :: String, age :: Int)`)

I'd avoid using a capital R for row in 'Row kinds' because I think it risks implying that `Row` is the name of something in the language.

I also think that `functionTypeSignature` is a slightly strange name for a function. Would `f` do there?

A final note: you can check how the Prim docs are going to come out locally by putting the `purs` binary you've just built on the front of your PATH and running `pulp docs -- --format html` inside a purescript project; the Prim module will be included amongst the generated html docs.

**Comment by JordanMartinez** [comment]
> We can indeed use markdown for links there
> A final note: you can check how the Prim docs are going to come out locally...

Ok, thanks for the clarification on those two points

> I think it would be a bit clearer to put an example of a kind containing `#` first
> I'd avoid using a capital R for row in 'Row kinds'

Good points.

> I also think that functionTypeSignature is a slightly strange name for a function. Would f do there?

That was my attempt at using meta-language to emphasize that the `_` goes in a type signature of a function as opposed to it appearing at the value-level (e.g. `f _`). Looking at it again, `f` as a name is all that's needed since the type signature is already there.

I'll update my PR to account for these changes.

**Comment by JordanMartinez** [comment]
Done.
