### ISSUE TITLE
Make html output the default in `purs docs`

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3489]
Currently `purs docs` can produce output in markdown, html, ctags, or etags. I think that the html output not only looks nicer but is also more useful, as it also includes links. (The markdown output probably could also include links now, come to think of it). I'd quite like to make html the default in the next breaking release.

**Comment by garyb** [comment]
I thought we already had this issue somewhere, but I must have imagined it. :smile:

Another option might be to make the format argument required, rather than having a default? I don't really have a particular preference about anything we do here though, as I tend to browse the source directly if I'm offline, and rely on Pursuit otherwise.

**Comment by hdgarrood** [comment]
I think making it required would be a bit awkward for tooling which wraps `purs docs` already, like `pulp`. Currently you can do `pulp docs -- --format <whatever>`; if we just changed the default, this would continue to work, whereas if we made the format a required argument, `pulp` (and any other tool which wraps `purs docs`) would have to build in specific support for this.

**Comment by garyb** [comment]
Hmm, that's true, I didn't think about the other tooling. I was thinking making it breaking might be desirable, since `docs` is not going to do what it used to do, so breaking it "silently" might be more surprising.
