### ISSUE TITLE
Require existence of externs files when producing docs

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#3503]
This originally arose in my mind as a way of fixing #3264, but it would be a breaking change to the CLI so I think a dedicated issue is probably warranted.

At the moment, we invoke the type checker during generation of docs in order to fill in any type signatures for declarations where the type signatures have not already been provided. However, we can't perform all of the desugaring steps which would normally have been run by this point, because some of them modify the AST in such a way that we wouldn't be able to produce sensible docs from them (e.g. desugaring of type classes and type synonyms). Often this is not a problem, but occasionally we see errors in docs generation which only occur when type signatures are left off (e.g. #3264).

To address this, I am proposing that we instead modify `purs docs` to accept an `--output` option, like `purs compile` does, and have `purs docs` first check that up-to-date externs files exist for all of the provided source files, and fail if not. Then, `purs docs` could obtain any missing types from the externs files. As with `purs compile`, the `--output` option would have a default of "output". However, it would only be used for locating externs files.

A nice side effect of doing this would be that it would prevent situations where the docs have incorrect types. For instance, if I write

```purescript
foo :: String
foo = 3
```

in a module and run `purs docs` on it, provided that all value declarations in that module have type signatures, it will succeed and the resulting docs will say that `foo` has the type `String`.

This would also pave the way for using the re-exports information contained in externs files (see #2191) to replace most of the code in `Docs.Convert.ReExports`. I would be very happy about this, because not only is that code quite frankly horrible (I'm allowed to say that because I wrote it), but also I suspect it's one of the main causes of the awful performance and memory consumption of `purs docs`. However, to do that, I think we'd need to add the module a re-export is being re-exported from to the externs format (currently, we only include the module a re-export originally came from, see https://github.com/purescript/purescript/pull/2191#issuecomment-225186677).

**Comment by garyb** [comment]
Seems reasonable to me. I think when I did #2191, one of the various motivations behind it was to remove the need for `Docs.Convert.ReExports`. I probably didn't realise that just dropping it in wasn't going to work, until I tried it out (I'm not so familiar with a lot of the docs code).

**Comment by hdgarrood** [comment]
Thinking about this a little more, perhaps it would be good to instead/also add a `docs` target to the `--codegen` option of `purs compile`, which generates a `Language.PureScript.Docs.Module` for each module passed to the compiler, serializes them as json, and saves it alongside the compiled js and externs files and everything else. That way, you avoid having to exit with a failure if the relevant externs files aren't there, or aren't up to date, and it also will be more convenient if you want to do something with the documentation data which is slightly different from what `purs publish` does (e.g. #3528).

**Comment by f-f** [comment]
I started looking into adding `purs compile --codegen docs`, and I think I can put something together for this, but I have some questions (after all it's the first time I look into the compiler 😊)

Some context first:
- I guess we want to write a `docs.json` file for every module (containing a `Docs.Module` object), and we can do it around [where it happens for the `CoreFn` representation](https://github.com/purescript/purescript/blob/b09144bc68637bf6657e4147567a3e9185221594/src/Language/PureScript/Make/Actions.hs#L155)
- However, we cannot use the `CoreFn` representation that we get in `Make.Actions.MakeActions.codegen` (where the `CoreFn` codegen happens) to produce docs, because at that point some important information is lost - e.g. typeclass desugaring and type synonyms expansion already happened (source: @hdgarrood)
- On the other hand the Docs module (e.g. `Docs.Conver.convertModules`) takes `AST.Module`s, which come straight from the parsing phase (while the `CoreFn` representation is generated after typechecking)
- Moreover, when generating docs (i.e. `Docs.Module` objects) we need to collect and convert _all_ the modules together, because there might not be enough typing information so we need to typecheck all the modules together. This means that it's a problem to fit it in `MakeAction` as it is now, because the `codegen` works on single modules

So I think a workable approach could be to:
- have a pre-step that processes `AST.Module`s into `Docs.Module`s
- actually output the relevant module in the `Make.Actions.codegen` phase

Questions:
1. Does this make sense?
2. How about the `Prim` modules? We call the `codegen` on actual source paths only, but if we're generating docs then we should include the `Prim` modules somewhere too IMO

**Comment by hdgarrood** [comment]
That all sounds sensible, but:

> Moreover, when generating docs (i.e. Docs.Module objects) we need to collect and convert all the modules together, because there might not be enough typing information so we need to typecheck all the modules together.

At the moment, we type check during docs generation for the sole purpose of inserting inferred types for declarations which have not been given type annotations. However, this is slow and error prone (eg #3264), so the idea behind this issue is to make type checking just for docs unnecessary. If we're in a `purs compile` invocation we're going to be type checking later on anyway, so there shouldn't be a need to do it again. I'm imagining something a bit more like:

* Have a pre-step which processes `AST.Module`s into `Docs.Module`s, leaving any missing types as they are (i.e. _without_ the type checking step which `Docs.Convert` currently includes)
* Fill in the gaps from any missing types during the `codegen` phase just before outputting them; by this point, the relevant information should be available (since type checking has already happened). Preferably we'd be able to keep it in memory, but if that proves awkward, rereading the externs files should be fine, I think.

Also, I don't think we need to write `docs.json` files for the `Prim` modules. Of course, when we come to actually generate documentation in a format like html or markdown, we'll want to include output files for those modules, but in that case there's no reason to write the json-serialized `Docs.Module` to the disk, because that information is immediately available from the compiler library already.

**Comment by hdgarrood** [comment]
@f-f did you manage to make some progress on this?

**Comment by f-f** [comment]
@hdgarrood unfortunately not, I didn't manage yet to book myself a chunk of time big enough to acquaint myself properly with how this is all wired together. So if you want to make some progress on this feel free 😊

**Comment by hdgarrood** [comment]
No worries! In that case I will start looking into it.
