### ISSUE TITLE
CommonJS module generation in psc-make

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#352]
At least investigate whether it's workable for PureScript. I'm pretty sure it is, and would potentially be a much better default than the current export method. It would mean having to using Browserify or something to package up the result for client-side js though.

It would also help with `psc-make` as the individual generated js files aren't really usable in Node at the moment, due to how `_ps` is resolved.

**Comment by bstro** [comment]
How is one supposed to use this functionality within an environment like Browserify? There are no relative paths, so it seems the environment must be made aware of the Prelude… its unclear to me how to make this happen. I have psc-make half-way working, but its building a directory full of CommonJS modules that don't know how to find each other.

**Comment by joneshf** [comment]
The way I've found to make this work is to use the env variable `NODE_PATH`. `node` will search for modules on these paths. Some documentation is here: http://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

So if you are just using the defaults you'll get modules in `output`, something like `output/Prelude/index.js` or so. If you set `process.env.NODE_PATH = path.resolve('output')` it will look for modules in `output` and resolve things properly.

Since we have modules as folders: http://nodejs.org/api/modules.html#modules_folders_as_modules it suffices to `require('Prelude')` and things will load properly.

N.B. modifying `process.env` is a hack. I can't remember where I read it, but apparently you're not supposed to go willy nilly messing with `process.env`. Given the situation, I just do it as there isn't much other option. Though, maybe someone has node module that does it properly.

**Comment by bstro** [comment]
That worked! Seems fine for now…hope someone figures out how to do this properly.

**Comment by garyb** [comment]
One option is to move/rename the `output` as `node_modules`. @paf31 took that approach here: https://github.com/purescript-contrib/grunt-init-purescript/blob/master/root/Gruntfile.js
