### ISSUE TITLE
Add `!` operator from idris

### ISSUE THREAD

**Issue by kevinbarabash** [purescript/purescript#3529]
It turns:
```
let y = 42 in f !(g !(print y) !x)
```
into
```
let y = 42 in do y' <- print y
                 x' <- x
                 g' <- g y' x'
                 f g'
```
Source: http://docs.idris-lang.org/en/latest/tutorial/interfaces.html#notation.

**Comment by kevinbarabash** [comment]
It doesn't have to be a `!`, but I think be able to unwrap things inline like this would be useful.

**Comment by hdgarrood** [comment]
When I mentioned this on Slack I didn't mean to suggest that I think purescript should add this feature. Adding syntax is a breaking change for any tooling which concerns itself with syntax (e.g. `purty` or editor highlighters), and so I think we need to have a pretty compelling reason whenever we add syntax. For me personally, this doesn't quite reach the bar; in fact, I think in general I'd prefer explicit binds, even, since it's clearer what order the effects are going to happen in.

**Comment by natefaubion** [comment]
FWIW, I agree with @hdgarrood. Generally, it's very difficult to reserve anything additional that's just a symbol, which means you'll probably end up with keyword variations that will be equally noisy. In some ways I like this, but mostly because I'd want to use it as an alternative to `ado` syntax. But we already have `ado` syntax, and this proposal doesn't offer it as such.

Personally, I feel like we have enough syntax sugar. I think that any new syntax sugar needs a _very_ high bar to clear and address specifically painful points. In my day-to-day PS, I don't feel this pain point around binds, and it's arguable that this is a clear win.

**Comment by kevinbarabash** [comment]
These are good points, thanks for the feedback.

The current project I'm working on adds unique ids to nodes in a tree while the tree is being created, but I could add the ids after creation of the tree or something.

**Comment by natefaubion** [comment]
@kevinbarabash I don't believe this proposal helps you in that case, since it's just syntactic sugar for monadic binds. Therefore there's nothing you could do with this proposal that you can't already do right now.

**Comment by aij** [comment]
I just came across the ! notation in Idris and I thought thought the idea was pretty exciting. It seems roughly analogous to support for sub-expressions -- which I quite like. 

Of course you can always write the same code in "single operation per line", regardless of whether it's monadic or not, but not having to do so frees the programmer from repeatedly having to solve one of the hardest problems in computer science.

> There are only two hard things in Computer Science: cache invalidation and naming things.
>  -- Phil Karlton

Without subexpressions, instead of `a + b + c` one would have to write something like
```
aPlusB = a + b
aPlusB + c
```

Without monadic subexpressions, instead of `!a + !b + !c` one would have to write something like
```
do
  outputOfA <- a
  outputOfB <- b
  outputOfC <- c
  outputOfA + outputOfB + outputOfC
```

(assume for the sake of argument that `a`, `b`, and `c` are general expressions rather than simple variables with existing names)

**Comment by MonoidMusician** [comment]
Doesn't `lift2` and friends solve this problem already? For example, `lift2 (+) a $ lift2 (+) b $ c`. I think this even will work:
```
a `lift2 (+)` b `lift2 (+)` c
```

Or you could name `add3 x y z = x + y + z` and then call `lift3 add3 a b c`.

To my eyes it is much clearer what that does than the notation in Idris.
