### ISSUE TITLE
incremental builds are slow

### ISSUE THREAD

**Issue by kevinbarabash** [purescript/purescript#3557]
I have a test project that implements a React based calculator web app.  It has two .purs source files and a number of dependency for a total of 456 folders in the output/ directory after compilation completes.  I did some tests and incremental builds take long that I would expect them to.  Here's the data:
```
full build: 10.47s
rebuild (no changes): 2.93s
rebuild (trivial change to src/Calculator.purs): 3.18s
```
I assume that rebuilds require parsing and traversing dependencies to make sure that everything still makes sense in Calculator.purs after my change.  If that is indeed the case, is there anyway that that data can be cached between runs?  I tried `pulp --watch build` and it also takes about 3 seconds after making a change to Calculator.purs.

**Comment by hdgarrood** [comment]
I don't think everything is necessarily parsed every single time; the compiler currently uses file modification times in order to skip recompiling source files when it can (although we might want to change this; see #3145). #2477 and #3555 would go a long way towards addressing this, I think. Unless you have specific suggestions separate from those two, though, I'd like to close this, as we prefer to keep the compiler issue tracker clean for tracking actual specific work we want to do on the compiler, rather than vaguer ideas and discussions.

**Comment by natefaubion** [comment]
> I don't think everything is necessarily parsed every single time;

It is parsing everything because it's the only way it knows which modification time to check (it has to lookup the output module, which is parsed in the module header declaration).

**Comment by kevinbarabash** [comment]
@hdgarrood would slack be a better place to discuss this kind of thing?

**Comment by natefaubion** [comment]
@kevinbarabash Probably https://discourse.purescript.org/

**Comment by hdgarrood** [comment]
Oh yes, of course, thanks. I think there was an intention of writing a parser which only parses the module header and/or imports to start with, and then only parses the rest if necessary but I guess we didn’t quite get around to that.

**Comment by joneshf** [comment]
Can someone put the link to the discourssion here once it's created?

**Comment by kevinbarabash** [comment]
@joneshf https://discourse.purescript.org/t/incremental-builds-are-slow/685.
