### ISSUE TITLE
Remove DuplicateSelectiveImport Warning

### ISSUE THREAD

**Issue by friedbrice** [purescript/purescript#3569]
Remove the warning for duplicate selective imports.

Here's a minimal example:

```purs
module Lib where

data Foo = Foo
data Bar = Bar

```

```purs
module Main where

import Lib (Foo)
import Lib (Bar)

app :: Foo -> Bar -> String
app _ _ = "Hello sailor!"
```

Compiling produces the following:

```console
$ pulp build
* Building project in /home/daniel/friedbrice/warning-example
Compiling Main
Warning found:
in module Main
at src/Main.purs:4:1 - 4:17 (line 4, column 1 - line 4, column 17)

  There is an existing import of Lib, consider merging the import lists


See https://github.com/purescript/documentation/blob/master/errors/DuplicateSelectiveImport.md for more information,
or to contribute content related to this warning.


* Build successful.
```

The above import style should not induce a warning:

  * Warnings are intended to warn the user of practices that can cause future compilation failures (such as non-selective imports breaking when a new symbol is added in the imported module). To my knowledge, there is not a scenario in which the above style would cause a future compilation failure (though I'm open to hearing otherwise).

  * The above style drastically reduces the occurences of merge conflicts.

**Comment by friedbrice** [comment]
I'm happy to work on this and submit a PR, if you think it's a good fit.

**Comment by hdgarrood** [comment]
Sorry, but I'm not in favour of this.

> Warnings are intended to warn the user of practices that can cause future compilation failures (such as non-selective imports breaking when a new symbol is added in the imported module).

Some warnings (most notably, most of the import ones) are indeed intended to achieve this, but this is not the only valid reason for producing a warning. For example, any top level declaration which does not have a type signature generates a warning, but this doesn't have anything to do with future compilation failures.

In the case of the DuplicateSelectiveImport warning, I do think it deserves to remain a warning, because it's useful to be able to see a single import and assume that a given module is using a certain set of values from that module _and no others_ (and in my experience this is almost always a safe assumption; all of the projects I've worked on do try to avoid warnings at least).

The merge conflict issue is, in my opinion, better addressed by using the style
```purescript
import Lib
  ( Foo
  , Bar
  )
```

If I haven't convinced you, it's also worth noting that you can silence a particular warning or set of warnings with [`psa`](https://www.npmjs.com/package/purescript-psa).

**Comment by friedbrice** [comment]
> it's useful to be able to see a single import and assume that a given module is using a certain set of values from that module and no others

I had not considered that, and it's very compelling. Closing this.
