### ISSUE TITLE
Failing to Build on NixOS

### ISSUE THREAD

**Issue by Jumblemuddle** [purescript/purescript#3571]
This appears to be caused by outdated dependencies which aren't available in Nix.
http://packdeps.haskellers.com/feed?needle=exact:purescript
https://github.com/NixOS/nixpkgs/issues/53597

**Comment by justinwoo** [comment]
In that issue is linked my easy-purescript-nix repo, so you might choose to just use the derivation for PureScript in it instead https://github.com/justinwoo/easy-purescript-nix/blob/master/purs.nix

**Comment by hdgarrood** [comment]
Sorry, but I’m going to close this as wontfix. It doesn’t really make sense for purescript to be chasing the latest versions of its dependencies, since there are other more important factors to take into account when planning release schedules, and since 99.9% of the time, purescript is being used as a binary, not as a library, so it shouldn’t matter what versions of dependencies are being used. At one point PureScript was in Stackage, but we removed it for the same reason.

**Comment by Jumblemuddle** [comment]
Thanks, @justinwoo, I'll take a look at that.
It kinda seems like nixpkgs should package the binary itself.
