### ISSUE TITLE
Composing with (.)

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#358]
It is possible to make `.` a valid operator and make it so `f . g` parses correctly while still allowing `obj .prop` (or indented `.prop`s) - `.` only being treated as compose when followed with a space.

This is obviously slightly ambiguous the same way that `2-3` was, but allowing `.` is possibly worth it? `<<<` is kinda ugly when you need to use it multiple times in one expression, or when you have things like `ask >>= return <<< f`.

Just a thought.

**Comment by felixSchl** [comment]
I would give my somewhat uninformed vote to having `.` for readability alone. @paf31 why might the whitespace approach not be a good thing? Could you elaborate?

**Comment by 5outh** [comment]
I think the main problem is that it's something that would have to be mentioned explicitly to newcomers. Error messages could also get confusing unless carefully put together (a warning that `submarine . engine` is performing composition instead of access, and vice-versa for `f.g` would be helpful).

**Comment by Fresheyeball** [comment]
After spending more time in other functional languages, I personally just don't like dot accessors, they feel... unnatural. I find myself wanting to reverse the order, and going out of my way to do so. PureScript also does not auto generate accessor functions, so they have to be manually written in order to compose with them. I've been working some with Elm which has an idiom with functions that start with a dot. So `.foo` de-sugars to `(\x -> x.foo)`, its nice because you don't have to worry about generating accessors, but again it uses the dot so `f . g` can be ambiguous. That said I see no reason the automatic de-sugar to `(\x -> x.foo)` can't work for another character like `-`. Consider the following:

```haskell
type Foo = { foo :: String }
f = { foo : "hi" }
main = trace . -foo $ f 
main = trace $ -foo f --or
```

**Comment by garyb** [comment]
You should know by now that `_.foo` works in PureScript :grin:

**Comment by jdegoes** [comment]
After PureScript supports Unicode, we can just use 	&#8728; and call it a day. :smile:

**Comment by joneshf** [comment]
If you've used a language that overloads `.` to mean composition if it has whitespace around it and property access if it doesn't, you know it pretty much means you should choose only one overloading once the codebase gets large enough. In large LiveScript programs it becomes very confusing to have to mentally disambiguate it all the time.

**Comment by andyarvanitis** [comment]
We could squint and sort of consider `.` an identifier character, and thus allow ``` f `.` g ```

**Comment by felixSchl** [comment]
> In large LiveScript programs it becomes very confusing to have to mentally disambiguate it all the time.

Don't forget we have the type system on our side. I hear you in regards to LiveScript. I left LiveScript behind me fairly quickly for just using normal javascript for exactly that reason. A space between a variable and an open parenthesis would also mean sth else than if there was none, e.g.: `foo ()` /= `foo()`. It's just painful. But in purescript, the type system comes to the rescue.

Also, writing property access with white spaces on either side would just look weird, wouldn't it? The javascript guys would put it right next to the accessed object or the access property (if desugaring), and the haskell guys would want `.` with whitespaces around either side, or as a operator section `(. x)`, `(x .)` or `(.)`.

Maybe this could be considered for the next major release? For reference, TypeScript do not remain 100% compatible with their upgrades from version to version - for example our project's code was written against 1.4 but needed a small upgrade to run fine on 1.5. As long as things don't change on us and we can fix the version for a project, it should be OK to make these changes going forward.

> We could squint and sort of consider . an identifier character, and thus allow ```f `.` g```

Well, that looks sort of better, but it's still 3 characters down the drain, instead of just one.

**Comment by jdegoes** [comment]
`f  ∘ g`. Looks much prettier and is totally unambiguous. Just requires unicode support which is even on the roadmap. Case closed? :smiling_imp:

**Comment by garyb** [comment]
PureScript 0.9: APL's revenge

**Comment by joneshf** [comment]
> Don't forget we have the type system on our side.

That's what I mean, you become the type checker just when parsing the words in the file. Not even when attempting to assign semantics to them.

> I hear you in regards to LiveScript. I left LiveScript behind me fairly quickly for just using normal javascript for exactly that reason. A space between a variable and an open parenthesis would also mean sth else than if there was none, e.g.: foo () /= foo(). It's just painful. But in purescript, the type system comes to the rescue.

I'm glad I'm not the only person that feels that way. :) Most people I talk to seem to like these things.

> and the haskell guys would want `.` with whitespaces around either side, or as a operator section `(. x)`, `(x .)` or `(.)`.

To me, the only advantage of having `(.)` available is being able to use it in things like SECs or lenses. So forcing the whitespace doesn't appeal to me. But everyone has different aesthetics they care about. In any other situation I prefer having both `(<<<)` and `(>>>)` as some things read easier one way than the other.

**Comment by felixSchl** [comment]
So to summarise the issue as I understand it, please correct me if this is incorrect:

It is *technically feasible* to allow function composition a la `f . g`, even given the white-space and property access ambiguity, however it is a matter of aesthetics and a potential pitfall for newcomers?

Personally, I would not consider the pitfall for newcomers an issue. There's so much to learn coming straight from oop to any functional language that this is really just a minor bump in the road, if any. After all, to fall into this pit, one would need to do property access like this: `foo . bar`, which I have never seen in any larger codebase - or any codebase at all for that matter. What I do see a lot and I do that myself is to do chaining, e.g.:

```javascript
Promise.resolve('qux')
    .delay(100)
    .tap(console.log.bind(console, 'Hello,'))
```

...but even then the dot is still anchored to the accessed property and how relevant is this style to purescript anyway?

Are there any other implications to consider? I do understand that this could be a potentially disastrous decision because once it's in it'll have to stay, so I would really like to discover all the follow-ons of it before rooting for `f . g`.

**Comment by LiamGoodacre** [comment]
Think I'd like `..` for composition and `.` for property access: `foo = map _.bar .. baz`

**Comment by garyb** [comment]
> Think I'd like `..` for composition

Lens provides that alias actually: https://github.com/purescript-contrib/purescript-lens/blob/366636c8233478e091dde191147ac00bcb1d6e98/src/Optic/Core.purs#L9-L10

Which is great until you import `Data.Array` and forget about it :wink: (`(..)` is an operator for `range` also).

**Comment by freebroccolo** [comment]
I also felt that `(<<<)` is a bit verbose but I've gotten used to it. I wouldn't mind a single dot character, whether it's `.` or `∘` (ideally I'd prefer the unicode but whatever). However, if it's more than a single character, I think `(<<<)` and `(>>>)` are superior because of the directionality, which I often make use of in pointfree code. So I agree with @joneshf there. I suppose one could have something like `<.` but to me that feels kind of like the worst of both worlds.

**Comment by Fresheyeball** [comment]
Just to throw more mess in. You can do `>>` and `<<` since composition is more common than monad next thingy, and we have `*>` anyway for haskell's `>>`. Its one less character.

**Comment by andyarvanitis** [comment]
I don't feel strongly about this one, but I also favor Haskell-like `.` for composition. As far as ambiguities go, I think the points are valid, but there are other similar cases already, and they're accepted. For example, `a'a'` vs `a 'a'`, `-- |` vs `--|`, etc..

**Comment by Fresheyeball** [comment]
Or we could make prince happy `f Ƭ̵̬̊ g`
I feel it looks pretty swanky.

**Comment by paf31** [comment]
Moving to Discussion. Let's try to come to a decision on this one.

:-1: from me. Vote for unicode operators once we have operator aliases.

**Comment by jdegoes** [comment]
:+1: to unicode operators, in which case, :-1: to this one.

**Comment by kRITZCREEK** [comment]
:-1:

**Comment by cryogenian** [comment]
:+1: for unicode operators 
Is it possible to override current `.` behaviour to make `foo.bar` aliases like `foo#bar` or `bar@foo` and so forth?

**Comment by AppShipIt** [comment]
👎 for `(.)`; 👍 for Unicode aliases. `(<<<)` conveys direction, correlates to Kleisli `(<=<)`, discourages point free abuse, and looks pretty in ligature fonts ([Hasklig](https://github.com/i-tu/Hasklig), [Fira Code](https://github.com/tonsky/FiraCode), but not [Monoid](https://github.com/larsenwork/monoid)).

**Comment by jdegoes** [comment]
:+1: Yes, please close!
