### ISSUE TITLE
`Unexpected {` when installing 0.13

### ISSUE THREAD

**Issue by danbroooks** [purescript/purescript#3677]
I am trying to install purescript to a machine, but coming up against this error:

```
$ npm install -g purescript
/home/dan/.nvm/versions/node/v8.15.1/bin/purs -> /home/dan/.nvm/versions/node/v8.15.1/lib/node_modules/purescript/purs.bin
> purescript@0.13.0 postinstall /home/dan/.nvm/versions/node/v8.15.1/lib/node_modules/purescript
> install-purescript --purs-ver=0.13.0

/home/dan/.nvm/versions/node/v8.15.1/lib/node_modules/purescript/node_modules/install-purescript-cli/index.js:97
	} catch {
	        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

I realised that it is trying to install `0.13` which was released 15 days ago, and I don't need this version at this time, so I have worked around this by installing `0.12` instead. 

Though I thought I would make an issue here to flag it, in case it hasn't been flagged already.

**Comment by natefaubion** [comment]
See https://github.com/purescript/npm-installer/issues/2. The npm installer currently only works with v10+.

**Comment by danbroooks** [comment]
Is it worth adding something to https://github.com/purescript/npm-installer/blob/master/install-purescript/index.js ? to make this clearer in the error message? Something that checks the version is at least 10? I'd be willing to submit a PR if it was straightforward enough and a change that was wanted

**Comment by natefaubion** [comment]
AFAIK a correct `engines` constraint was already added.

**Comment by hdgarrood** [comment]
Perhaps we should make an 0.13.1 release with the correct engines constraint. This seems to be tripping quite a few people up.

**Comment by garyb** [comment]
I think it already is correct, if I `npm install purescript` currently, the `node_modules/purescript/package.json` does have:
``` json
  "engines": {
    "node": ">=10.16.0",
    "npm": ">=6.9.0"
  },
```

**Comment by felixSchl** [comment]
If these "incompatibilities" are due to install scripts using later language features only supported by newer node versions I remain on my position that this is a problem with the install scripts. They should run on any node version because what user actually cares what language an install script is written in? Perhaps we should write it in purescript.

**Comment by cruhl** [comment]
👋 

This is the first thing I ran into when following the getting started guide. For folks on older versions of node this is going to be a big turn off.

**Comment by hdgarrood** [comment]
Thanks all for letting us know. I'm working on restoring node 8 support now.

I would also like to port the installer to PureScript, but that's a slightly bigger job.

**Comment by berdario** [comment]
FYI, npm used to ignore the engines constraints (unlike Yarn, which enforces them), I don't think that the behavior changed recently.

I think we should consider dropping npm from the instructions for installing purescript tooling, since that can trip up a lot of people.

That said, 10.16 is a bit too bleeding edge for a Node version, since the last currently stable Nix channel for darwin (394dfe911291ea5833147cdbf6da6449856c2dbd) ships v10.15.3 for node 10 

(it also ships node11, luckily... but yarn is only shipped with node8 builtin)

**Comment by hdgarrood** [comment]
The npm installation method is really convenient and is the most widely used one, as far as I'm aware. I think it would be a lot better to just restore node 8 support.

**Comment by berdario** [comment]
I agree with restoring node 8 support, but that doesn't exclude gently suggesting people to use yarn instead of npm

(yarn is just a different cli tool, it uses the same npm registry:

`yarn add purescript` instead of `npm install purescript`
`yarn global add purescript` instead of `npm install -g purescript`
)

**Comment by natefaubion** [comment]
I'm think yarn users know they can use yarn, and I don't think that PureScript is the place to evangelize yarn when npm is still the default node tooling.
