### ISSUE TITLE
Chinese character crashes psci 0.13

### ISSUE THREAD

**Issue by rnons** [purescript/purescript#3693]
To reproduce, start `pulp repl` somewhere, paste in `"世界"`, then psci crashes.

```
PSCi, version 0.13.0
Type :? for help

> import Prelude
> "??????"
purs: fd:35: hGetContents: invalid argument (invalid byte sequence)
```

It works fine on psci 0.12.5.

```
PSCi, version 0.12.5
Type :? for help

> import Prelude
> "世界"
"世界"
```

**Comment by rnons** [comment]
This only happens on nix installed purs 0.13. I downloaded another from the release page on github and it works fine.

**Comment by klntsky** [comment]
This is a well known problem with nix and haskell (haskell runtime incorrectly assumes that locale encoding is ascii when built with nix).

Usually can be fixed by this:

```
GHC.IO.Encoding.setLocaleEncoding System.IO.utf8
```

For example, dhall [follows this approach](https://github.com/dhall-lang/dhall-haskell/search?q=utf8&unscoped_q=utf8).

Obviously, this line disables encoding autodetection and breaks things for non-utf8.

**Comment by rnons** [comment]
I'm not building purescript from source in nix. 

From reading https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/purescript/purescript/default.nix#L39, I think it downloads the same tarball from github release page, the difference is ncurses is linked to the nix built version. I'm not sure if the problem can be fixed in this nix expression, or is there some local nixpkg config I can use. @justinwoo  do you have any idea?
