### ISSUE TITLE
Rebinding 'apply' in a let binding in 'ado notation' does not produce an error

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3702]
See https://gist.github.com/JordanMartinez/6494136e3acebc80113401fe39dd515b

This produces an error in 'do notation:'
```purescript
normalBind_let_only :: Box Int
normalBind_let_only = do
  let
    bind = NormalBind.bind

    discard = NormalBind.discard

  three <- Box 3
  Box unit
  two <- Box 2
  pure (three + two)
```

The corresponding situation in 'ado notation' does not even though it should:
```purescript
normalApply_let_only :: Box Int
normalApply_let_only = ado
  let
    apply = NormalApply.apply
    map = NormalMap.map

  three <- Box 3
  two <- Box 2
  in three + two
```

**Comment by LiamGoodacre** [comment]
`let` declarations with an `ado` block are only in scope for the body (after the `in`).
It's effectively the same as writing:
```purescript
normalApply_let_only :: Box Int
normalApply_let_only = ado
  three <- Box 3
  two <- Box 2
  in
    let
      apply = NormalApply.apply
      map = NormalMap.map
    in three + two
```

On the right of a `<-` it's impossible to reference the `let` bound variables.

So I don't think this should warn :thinking:

**Comment by JordanMartinez** [comment]
@hdgarrood Your thoughts? I originally opened this due to your response on FP Slack.

While the above code works for `ado`, perhaps the issue is that it's not consistent, such that it doesn't also work for `do`?

**Comment by hdgarrood** [comment]
Oops, yes, @LiamGoodacre is absolutely right. The fact that `let` in `ado` works this way means there's no risk of switching to a different `apply` halfway through an `ado` block, so on second thoughts I agree that no warning or error is necessary. It's intentional that `let` in `ado` works this way, because it's necessary if we want to be able to define `let` bindings based on the results of previous actions, i.e. if we want to refer to anything on the left-hand-side of a `<-`.

We should probably document how `ado` desugaring works, if we haven't already.

**Comment by JordanMartinez** [comment]
I have [something documented in my learning repo](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/11-Syntax/05-Prelude-Syntax/src/04-Ado-Notation.purs), which is based on [the original PR that added support for it (see the 'Desugaring Procedure' section)](https://github.com/purescript/purescript/pull/2889#issuecomment-301260299)

**Comment by LiamGoodacre** [comment]
Closing as I don't think there's any further action to take.  But please do reopen if you disagree.
