### ISSUE TITLE
Bundling issue after upgrading to v0.13.3

### ISSUE THREAD

**Issue by alexpeits** [purescript/purescript#3727]
After upgrading from v0.13.2 to v0.13.3 at work we started seeing some weird behaviour with dead code elimination when bundling was turned on. The gist is: if an exported value in a js file depends on another exported value that doesn't end up being used when `foreign import`ed, it ends up being `undefined`. This happens if the initial value is assigned directly (`exports.foo = <value>`), not if assigned first as a variable and then this variable is assigned to the exported value. In more detail, here's a minimal environment to reproduce this behaviour (repo with the relevant files: https://github.com/alexpeits/purs-bundle-issue-reproduction)

Main.js
```js
'use strict';

exports.foo = 1;
exports.bar = exports.foo;
```

Main.purs
```purescript
module Main (main) where

import Prelude
import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = log (show bar)

foreign import bar :: Int
```

Run the following:
```bash
purs compile bower_components/**/*.purs src/Main.purs
purs bundle output/**/*.js -o bundle.js -m Main --main Main
```

The relevant block for `Main.js` in `bundle.js` ends up being:
```js
'use strict';
exports.bar = exports.foo;
```

which means that `bar` is then `undefined` in my purs file.

This behaviour persists if I add `foreign import foo :: Int` in the purescript file, but it disappears if I:
- Use `foo` somewhere in the module (e.g. `log (show foo)`)
- `foreign import foo` and export it (or not specify an export list)
- Instead of doing: `exports.foo = 1;` doing:
```
var foo = 1; 
exports.foo = foo;
exports.bar = foo;
```

**Comment by hdgarrood** [comment]
cc @rhendric, do you have any thoughts?

I'm not sure this is necessarily a bug, since `purs bundle` doesn't have a spec. I'm not sure it's worth the effort of coming up with one now, though. I am becoming more keen getting ES modules out (preferably at the next breaking release) and just removing `purs bundle` entirely then, or soon after.

**Comment by rhendric** [comment]
IMO this is indeed a bug, and it's my fault. The `bundle --debug` output (thanks for forcing me to add that!) shows that the bundler believes `exports.bar` depends on an internal symbol `foo`, and thus that the public `exports.foo` has no dependents and can be dropped. I don't yet know how I goofed but there'll be a PR once I figure it out.

**Comment by hdgarrood** [comment]
Ah fantastic, thanks!

**Comment by rhendric** [comment]
Three issues came to light during my investigation of this bug:
1. The expression `exports.foo` didn't register as a dependency on `(module, "foo", Public)`.
2. The expression `exports.foo` (and, more generally, `anything.foo`) *did* register as a dependency on `(module, "foo", Internal)` if such a dependency was possible.
3. The existence of `exports.foo = ...` was causing `"foo"` to be considered as a bound name, making dependencies on `(module, "foo", Internal)` possible.

#3731 contains fixes for 1 and 3, and the fix for 3 ameliorates 2 somewhat. However, the issue remains that a module-private `var toString`, for example, won't be dropped if `x.toString()` is present anywhere in the module. The design of `language-javascript` would make a fix for that rather involved (the issue is that the `toString` in `x.toString` is a `JSIdentifier`, and so any SYB-style traversals looking for `JSIdentifier`s need to be made much more complicated to detect which `JSIdentifier`s are in value position versus other random places in the AST). I'm okay with leaving 2 unfixed since the fix would add a lot of code, this specific sub-issue is not a regression from 0.13.2, the error is in the direction of leaving too much code in, I don't think (?) it can be triggered by compiler-generated code, and it sounds like the ultimate fate of the whole bundler is in question.

**Comment by hdgarrood** [comment]
Yeah, I agree with your analysis and conclusions.
