### ISSUE TITLE
compiler loop: cycle in type synonyms, v. 0.13.3

### ISSUE THREAD

**Issue by brubar** [purescript/purescript#3735]
With purs 0.13.3, the compiler may loop until there is no more memory.
I'm expecting it to report a CycleInTypeSynonym error instead.

Here is a small (meaningless) example to reproduce:

```PureScript
    import Prelude(unit, Unit)
    
    data D   = D S
    type S   = T D
    type T x = S
    
    f :: D -> Unit
    f (D _) = unit
```

**Comment by garyb** [comment]
Thanks for the report!

**Comment by hdgarrood** [comment]
I looked into this a little today. I think the problem is in `Language.PureScript.Sugar.BindingGroups.toDataBindingGroup`:

```haskell
toDataBindingGroup
  :: MonadError MultipleErrors m
  => SCC Declaration
  -> m Declaration
toDataBindingGroup (AcyclicSCC d) = return d
toDataBindingGroup (CyclicSCC [d]) = case isTypeSynonym d of
  Just pn -> throwError . errorMessage' (declSourceSpan d) $ CycleInTypeSynonym (Just pn)
  _ -> return d
toDataBindingGroup (CyclicSCC ds')
  | all (isJust . isTypeSynonym) ds' = throwError . errorMessage' (declSourceSpan (head ds')) $ CycleInTypeSynonym Nothing
  | otherwise = return . DataBindingGroupDeclaration $ NEL.fromList ds'
```

For each module, we construct a graph where the vertices are the data type and type synonym declarations, and where there is an edge from T to U if the type T mentions U in its definition (or perhaps the other way around, I can't remember). Then we split the graph up into strongly-connected components (SCC), and apply the `toDataBindingGroup` function to each SCC.

At the moment, we only produce an error if every type declaration in an SCC is a type synonym, so the given example slips through because it also has a `data` declaration in it. I think changing the logic so that any data binding group with at least two type synonyms is disallowed would catch this error, but that's probably excessive; I think it would also disallow a lot of currently-allowed cases which don't cause problems, such as:

```purescript
data A = A B
type B = C
data C = C D
type D = A
```

which is legal (if a bit useless since you can't construct any values of these types without cheating). 

My understanding is that cycles are only a problem if they only involve synonyms; if you have a type synonym `T` but the only way to construct a cycle starting at `T` is to go through at least one `data` declaration, then you're fine.

Therefore, I think the proper fix is to construct a graph of just type _synonyms_, and throw an error for each SCC in that graph; if there are no SCCs, then we can construct the `DataBindingGroup` declarations separately afterwards.
