### ISSUE TITLE
Error when using Rank-N types with sum types but not with records

### ISSUE THREAD

**Issue by frabbit** [purescript/purescript#3849]
I wonder if this is expected behaviour or a bug:

```purescript
type F = (forall y . y -> y)

data Dat x = Dat x

type Syn x = { x :: x }

t0 :: F -> Syn F
t0 f = { x : f } -- works fine

t1 :: F -> Dat F
t1 f = Dat f -- The type variable y, bound at has escaped its scope, appearing in the type (y18 -> y18) -> Dat (y18 -> y18)
```

i'm using the compiler version 0.13.6.

**Comment by garyb** [comment]
:smile:

I think this might be the "record's don't play well with higher rank types" in reverse (in that it's beneficial this time), but there's perhaps something not quite with how the constructor is being handled too since this works:

``` purescript
t1 :: forall a. a -> Dat a
t1 = Dat

t2 :: F -> Dat F
t2 = t1
```

However I think this is impredicative, so it could just be down to that - impredicative types are kinda usable but don't play too well with typechecking sometimes.

I thought it might have been an interaction with synonym usage also, but then reducing it even further, there's this oddity:

``` purescript
data Dat x = Dat x

t1 :: (forall y. y -> y) -> Dat (forall y. y -> y)
t1 = Dat -- fine
```

``` purescript
data Dat x = Dat x

t1 :: (forall y. y -> y) -> Dat (forall y. y -> y)
t1 f = Dat f -- error
```

As for the record case, it's a little weird that both of these work, but is probably relevant:

``` purescript
type F = (forall y . y -> y)

type Syn x = { x :: x }

t0 :: forall a. F -> { x :: a -> a }
t0 f = { x : f }

t1 :: F -> { x :: forall a. a -> a }
t1 f = { x : f }
```

**Comment by natefaubion** [comment]
This particular case is due to an ad hoc typechecker rule that was used to keep Halogen compiling after some refactoring. https://github.com/purescript/purescript/blob/a4f35ac878f0428a0b1beb51e34c0a9f5150df4b/src/Language/PureScript/TypeChecker/Types.hs#L357-L359
https://github.com/purescript/purescript/pull/2625

I personally think we should remove this rule. @kritzcreek and I have talked about it some in the past. It does mean fewer things will type check, but I don't think the rule makes much sense as is.

**Comment by natefaubion** [comment]
@garyb Without that record case I linked to, the record example would behave like the constructor example.

**Comment by garyb** [comment]
By which you mean it wouldn't allow this?

``` purescript
t0 :: forall a. F -> { x :: a -> a }
t0 f = { x : f }
```

It's interesting that the rule allows that if so, as that's not the case that Halogen required - it relied upon the reverse.

**Comment by natefaubion** [comment]
Oh yes, I've got that wrong. The case I linked to is only for inference, and this would be checking.

**Comment by garyb** [comment]
It might be that #2625 made the two behaviours possible? Since I assume that without it, it would only allow the `t1` version, and that was the whole problem in the first place (since `{ x: mempty }` would be `{ x :: Monoid a => a }`).

**Comment by natefaubion** [comment]
```purescript
t0 :: forall a. F -> { x :: a -> a }
t0 f = { x : f }
```
This works fine because in check mode it knows that `x :: a1 -> a1` where `a1` is a skolem, and it instantiates `forall y. y -> y` with `a1`.

**Comment by garyb** [comment]
I don't think Halogen relies on the workaround anymore FWIW anyway, so we could investigate taking it out and seeing how much it breaks. I remember a bit more now - what I said up there about `query` and `DriverIO` isn't strictly true either. It was putting something in a record and then reading it back out to avoid a skolem escape error that couldn't be worked around by any other concoction I could formulate.

**Comment by natefaubion** [comment]
Yes, it's off topic now. I don't think that rule is involved here. I see a variable in a record with polymorphic types and see this rule 😆.

```purescript
t0 :: F -> Syn F
t0 f = { x : f } -- works fine
```
This works because in check mode it knows `x :: F`, and it will do a subsumes check that works out fine. the annotation on `Syn F` instantiates `F` with a skolems `y1 -> y1`, and the subsumption check instantiates `f` with unknowns `u1 -> u1`.

```purescript
t1 :: F -> Dat F
t1 f = Dat f
```
This does not work because the application judgement instantiates `f :: forall y. y -> y` with unknowns `f :: u1 -> u2`, making `Dat :: (u1 -> u2) -> Dat (u1 -> u2)`, which will end up triggering the skolem escape error.

**Comment by natefaubion** [comment]
I think something to consider is that while `Dat F` and `Syn F` seem like they would be comparable, I don't think that's a fair assessment. With `Syn F`, the compiler knows structurally and fully what to `check` against. I think `Syn F` would be more comparable to:
```purescript
t1 :: F -> Dat F
t1 f = (Dat :: F -> Dat F) f
```
or
```purescript
data Dat = Dat F
```
Which both work. There is no polymorphic `Syn` constructor with an application; the record just "is". When you have a polymorphic `Dat` constructor, the compiler has to do inference to figure out how the application should instantiate the type parameter _first_, which is _then_ checked against the `t1` signature. The paper I linked is a way of using more information from the signature as a whole to do more checking and less inference during the application judgement.

**Comment by garyb** [comment]
Ah, there it is:
``` purescript
t1 :: F -> Dat F
t1 f = (Dat :: F -> Dat F) f
```

I knew there would be a way to convince the constructor to instantiate the right way for this impredicative situation without eta reduction, but I couldn't think what it was off the top of my head.

**Comment by natefaubion** [comment]
This behavior makes sense to me even if it isn't immediately obvious, so I don't think there's anything in particular to address here. I'm going to close for now.
