### ISSUE TITLE
Incorrect code generated matching on imported constructor where other non-exported constructors exist

### ISSUE THREAD

**Issue by fsoikin** [purescript/purescript#3869]
## Description

When only one constructor of a type is exported from its module, it appears that PureScripts tries to optimize pattern-matches as if other constructors did not exist at all, rather than just being hidden. This leads to generating unsound JS code.

## To Reproduce

```
-- Note: only constructor `A` is exported. Constructor `B` is hidden.
module M(T(A), mkB) where
data T = A | B
mkB = B :: T


module Main where
import M(T(..), mkB)

f :: T -> Int
f = case _ of
  A -> 0
  _ -> 1

main = Console.log $ show $ f mkB
```

The above program prints "0", and the following JS code is generated for function `f`:

```
var f = function (v) {
    return 0;
};
```

## Expected behavior

Generated JS code should look the same as if both `A` and `B` were exported from `M`:

```
var f = function (v) {
    if (v instanceof M.A) {
        return 0;
    };
    return 1;
};
```

## Additional context

The example above is silly for the sake of being minimal, but it can easily be made to actually crash at runtime, for example:

```
module M(T(A), mkB) where

data T
  = A { foo :: String }
  | B

mkB = B :: T


module Main where
import M(T(..), mkB)

f :: T -> String
f = case _ of
  A x -> x.foo
  _ -> "ain't gonna happen"

main = Console.log $ f mkB
```

results in:

```
TypeError: Cannot read property 'foo' of undefined
```

## PureScript version

0.13.6

**Comment by hdgarrood** [comment]
Yikes! Thanks for the report.

**Comment by kl0tl** [comment]
This happens because the only constructor is inferred to be for a product type here: https://github.com/purescript/purescript/blob/df3170f5bb0ba21517e2ca72db6aee5c479c99df/src/Language/PureScript/CoreFn/Desugar.hs#L181

If we want to keep optimizing matches on product types perhaps we could store a `ConstructorType` under the `Data` constructor of `DataDeclType` so we just have to lookup in the environment instead of trying to guess from the number of exported constructors.

**Comment by hdgarrood** [comment]
Seems reasonable, yeah. I think we could potentially also consider removing the ability to export some but not all constructors of a data type, since it appears pattern matching is completely broken on data types where not all constructors are exported now. I don't think only exporting some constructors of a data type makes a huge amount of sense in the first place: if it worked properly, you'd be forced to add a catch-all pattern every time you matched on that type, because we treat non-exhaustive pattern matches as an error.

**Comment by natefaubion** [comment]
I'm inclined to agree with @hdgarrood. I don't think this this is something I've ever wanted to do for this reason.

**Comment by fsoikin** [comment]
> I don't think only exporting some constructors of a data type makes a huge amount of sense in the first place

We do this all the time for passing messages between parent/child components in our Elm-style UIs, kind of like:

```
module Child( Message(StuffHappened), State, update, view ) where

data Message 
    = ButtonClick 
    | TextChange String 
    | StuffHappened  -- intended to be handled by the parent

...


module Parent where

import Child as Child

data Message
    = OneMsg
    | AnotherMsg
    | ChildMsg Child.Message

update :: ...
update state message = case message of
    ChildMsg Child.StuffHappened -> 
        -- the child raised this for us to handle
        ...
    ChildMsg m ->
        -- child's internal message, just pass it through
        Child.update state.child m

    OneMsg -> ...
    AnotherMsg -> ...
```

Here I'd like to be able to only export `SutffHappened` from `Child`, ensuring that the only thing the parent can do with all other messages is pass them through to the child. Right now we're forced to export all constructors and rely on discipline.

I agree, it's not _that_ big of a deal. I just wanted to illustrate how it may make sense to allow such exports.

**Comment by hdgarrood** [comment]
In that case, could you do something like this?

```
module Child (InternalMessage(), PublicMessage(..), Message) where
data InternalMessage
  = ButtonClick
  | TextChange String

data PublicMessage
  = StuffHappened

type Message = Either InternalMessage PublicMessage
```

**Comment by fsoikin** [comment]
Yes, that's what we also do in some places. Like I said: not that big of a deal, but definitely far from "doesn't make sense".

**Comment by natefaubion** [comment]
I think it poses an awkward question though. If you only export explicit constructors, should it never be possible to have an exhaustive match?

Given:
```purescript
module A (Foo(X, Y)) where
data Foo = X | Y | Z
```

If I import this and case on it, I will need to:
```purescript
example = case _ of
  X -> ...
  Y -> ...
  _ -> ...
```

But then remove the `Z` constructor (non-breaking interface change), should the `_` warn for redundancy?

**Comment by fsoikin** [comment]
I would see removing `Z` as a _breaking_ interface change. 

Exporting `Foo(X, Y)` in presence of `Z` really creates a public contact that reads like: "_Foo has constructors X, Y, and some others that you're not allowed to see_", while exporting `Foo(X, Y)` in the absence of `Z` creates a contact that reads: "_Foo has constructors X and Y_"

**Comment by hdgarrood** [comment]
I'm struggling to see this as breaking. Can you give an example of how that could break downstream code, other than perhaps that it might issue warnings where it didn't previously?

**Comment by natefaubion** [comment]
The inverse applies:
```
module (Foo(X, Y))

data Foo = X | Y
```
If I add a constructor `Z`, but do not change exports. This will raise something that only matched on X and Y as an error. The public interface has not changed, but it potentially breaks downstream code.

**Comment by fsoikin** [comment]
That depends on what you see as "public interface". What I'm saying is that, if exporting partial set of constructors is allowed, the definition of "public interface" must include the presence of absence of non-exported constructors.

**Comment by natefaubion** [comment]
@fsoikin The written module interface has not changed. I would not expect an internal change that does not result in a change to the module signature to break downstream code. I'm suggesting that if we want to support partial exports robustly at all, explicitly listed constructors must always be treated as partial. The only way to export a complete set of constructors according to the exhaustivity checker would be to use `(..)`.

**Comment by hdgarrood** [comment]
Right - I understand that, I just am not sure if I'm convinced; if you were able to come up with a concrete example of why this kind of change should be considered as breaking, I might find it more compelling. With the example you gave before, the downstream code probably doesn't need to care if you remove all unexported constructors: the path where it would send internal messages straight to the child would just no longer be hit.

I would definitely regard @natefaubion's example as breaking though: if downstream code which previously compiled no longer compiles, that's breaking for our purposes, because the downstream code needs to change in order to work with the new version.

**Comment by fsoikin** [comment]
> The written module interface has not changed. I would not expect an internal change that does not result in a change to the module signature to break downstream code.

But that's exactly what happens when you export all constructors with `(..)`!

So clearly, there is precedent for this sort of thing.

**Comment by natefaubion** [comment]
`(..)` is an opt-in for everything (including breaking changes), vs an explicit list.

**Comment by hdgarrood** [comment]
Not really, the constructors are still part of the module signature when you use `(..)`.

**Comment by fsoikin** [comment]
That's only because we choose to define it that way.

So we can similarly choose to define "presence of more constructors" to be part of the signature.

**Comment by hdgarrood** [comment]
When we say "module signature" we mean "information about what the module exports which is visible to downstream modules". That's not something we can really choose to define however we want to, we have to look and see what the implementation does. Right now, I am fairly certain that downstream modules cannot see whether or not the exported list of constructors is the complete list of constructors, so this information would not be part of the signature.

**Comment by hdgarrood** [comment]
(We can change the implementation to add this information to the signature if we decide that's what we want to do, sure.)

**Comment by fsoikin** [comment]
Yes, "change the implementation to add this info to the signature" is exactly what I mean.

The bug has to be fixed, which means changing the compiler code one way or another. So the change could be either to ban partial exports or to change how module signature is defined.

**Comment by garyb** [comment]
I'd lean towards banning partial exports personally, as I think it would be a little odd to get a partial pattern match error that can't be solved by explicitly matching anything, and I think it would be simpler to fix this way also.

There is some precedence for this in PS also, in that we require whole classes to be exported.

**Comment by hdgarrood** [comment]
I'd quite like to do this in v0.14.0 since it's a breaking change, it's pretty easy, and it seems like we agree on requiring all data constructors to be exported if any are - the fact that we already require whole classes to be exported seals the deal for me. I don't think it will delay the release of v0.14.0 because there are still a number of Coercible issues being worked on alongside, which are probably going to take a bit longer to fix.
