### ISSUE TITLE
dependent types as an extension

### ISSUE THREAD

**Issue by raptazure** [purescript/purescript#3963]
Currently, the JavaScript backend for Idris2 and Agda seems still experimental and the compiled code isn't that readable while PureScript's compiler is production ready and efficient. Maybe It would be great to add dependent type (even quantitative type) support as an extension of the current type system so that it can be more powerful and bring dependent types to the industrial world.

**Comment by hdgarrood** [comment]
I’m sorry to disappoint you, but real dependent types in PureScript are extremely unlikely to happen. Firstly, adding big type system extensions like this one is likely to be a really big engineering effort, to the extent that it’s really quite difficult to justify compared to other things we could be doing. Secondly, adding more features is not always a good thing: it creates more work for people working on the implementation, on docs, and even on learning the language itself, and it increases the risk that different language features will interact in a way that is awkward or that introduces bugs in the compiler; it’s not clear that the benefit provided by the feature would outweigh these concerns. In general we have tried to follow the principle that fewer features which work well together is better than many features (even if those many features do end up covering more use cases). I wrote a bit about this at https://discourse.purescript.org/t/thoughts-on-future-additions-of-type-level-features/707. Finally, there’s an argument against dependent types specifically, which is that so much of the design of the language, standard library, and general patterns you use when writing code in the language are influenced by the type system, that adding dependent types would essentially create a new language (or, at least, I would argue that it should be seen as doing this). It would be absurd to provide dependent types but not to make use of them in the standard library; if you poke around in Idris’ standard library you’ll see quite a few things which look very different to how they look in PureScript and Haskell. PureScript has now reached a level of maturity that I would find it unacceptable to make such far-reaching changes to the standard library to make the best use of DT.

Having dependent types opt-in as a language extension doesn’t solve these issues either: in fact it exacerbates the maintenance cost because now you have two languages to maintain at the same time (and every time you add a new extension, that number doubles). We’ve previously made a conscious decision not to support language extensions for this reason.

If you want a strict, purely functional, general purpose programming language with dependent types and a JS backend, you can already get that with Idris, so I don’t think it makes a whole lot of sense for us to try to fill that niche - especially since there are considerable costs to attempting it.

**Comment by hdgarrood** [comment]
Ah, I see you already addressed Idris in your initial comment. I would suggest that working towards making Idris’ or Agda’s JS backends production ready (whatever that means in this case) is probably a better use of effort than trying to add dependent types to PureScript.

**Comment by rhendric** [comment]
See also the [project values](https://github.com/purescript/governance#project-values) section in the governance repo (which basically says the same thing, just in the form of a formal mission for participants to rally around).

At the risk of inspiring hope where there ought to be none, though, I for one would be interested in revisiting the question of DTs in PureScript if/when Dependent Haskell is a thing, as that would provide some interesting evidence about (among other things) what actually happens when a language with an existing prelude adds dependent types, should it ever come to pass. I don't know if it's necessarily the case that Idris's example proves that any Idris-like language would need to have such an invasively-dependent standard lib.

**Comment by raptazure** [comment]
Oh, I see. Thanks for responding. 👍
