### ISSUE TITLE
Core, Web, Node, and Contrib Library - Write release notes for v0.14.0-compatible releases

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#3985]
I'm opening this up for now, but we'll need to fill this issue with a list of repos, so we can track which we've done and which we haven't. 

Related to #3942

**Comment by thomashoneyman** [comment]
When we do go through and release these libraries, we should:

1. Set the correct date in the CHANGELOG and commit directly to `master` / `main`.
2. Create a new GitHub release & tag for that commit, copying the CHANGELOG contents into the release notes.

**Comment by hdgarrood** [comment]
I think a PR that just tags and updates dependencies probably doesn’t need to be noted in the changelog, as it’s part of adding support for v0.14.0, which is probably already noted in the changelog anyway?

**Comment by thomashoneyman** [comment]
I’ve only been noting syntax changes / addition and removal of dependencies for 0.14, waiting for the commit which actually sets the new dependency versions to note that we’ve updated dependencies for 0.14. That’s because all dependency changes so far have been to “master” or “main” branches.

I don’t have a strong preference — we could just go ahead and note that dependencies bumped for 0.14 and not worry about updating the changelog again when it comes release time. But we should agree on which approach we’d like to take. @JordanMartinez, have an opinion on this?

**Comment by JordanMartinez** [comment]
I think the PR should be added to the [list of PRs](https://github.com/JordanMartinez/purescript-prelude/blame/c35562b73e2043a91dbb38ea10cdcda577e82933/CHANGELOG.md#L18) for the "added support for v0.14.0" line, but I don't think we need to explicitly say "bumped dependency X to `vX.Y.Z`" in that line.

**Comment by hdgarrood** [comment]
Agreed - dropping a dependency entirely is something that is worth noting in the changelog, but just updating a dependency usually isn't, I think.

**Comment by thomashoneyman** [comment]
I was more thinking that it would be nice to refer to the or which sets the actual dependency versions rather than to the pr which sets them all to “master”. But perhaps we could just add both pr numbers to the “update to 0.14” line.

**Comment by JordanMartinez** [comment]
These have been done.
