### ISSUE TITLE
Build with GHC-LTS (Currently 8.8.4)

### ISSUE THREAD

**Issue by waynevanson** [purescript/purescript#3990]
Purescript should be able to be built from source using the GHC 8.8.4, which offers long term support.

This would make compiling from source a breeze when using package managers such as `nix` and `xbps`, which use the LTS version of GHC only. I'm trying to add this to `void-linux/void-packages` but they don't accept prebuilt binaries like they've done in `nix`. I'm also trying to do the same for `spago`.

Upon snooping, I've been able to summarize the following list in order to complete. Is there anything else missing?

- [ ] Release purescript-0.14.x - https://github.com/purescript/purescript/pull/3943#issuecomment-706728352
- [ ] Remove `hpack` by merging #3933 - https://github.com/purescript/purescript/pull/3943#issuecomment-706728352
- [ ] Update to 8.8.4 by merging https://github.com/purescript/purescript/pull/3943

**Comment by hdgarrood** [comment]
Sorry, this is explicitly a non-goal for us, it's just too much effort. We already have quite a bit of difficulty trying to coordinate releases as is, we definitely don't need the additional pressure of "we need to make another release because some upstream dependency was updated and it no longer builds". I am sure that compiling from source using nix is already possible, you just need to use the install plan that we've provided via the stack.yaml file in this repository. If you ignore that and try to build with the latest versions of everything in your distro package manager, it's definitely not going to work.

Note that using the install plan we've provided is not only important for getting the compiler to build in the first place, it's actually critical to follow the install plan to end up with a compiler that functions correctly. At least one of our dependencies (language-javascript) is pinned to a specific version because that dependency forms part of the compiler's public API, and so it's very much not an option to update whenever it updates, because updates for that library are often semver-major updates for the compiler.

**Comment by waynevanson** [comment]
> At least one of our dependencies (language-javascript) is pinned to a specific version because that dependency forms part of the compiler's public API, and so it's very much not an option to update whenever it updates, because updates for that library are often semver-major updates for the compiler.

@hdgarrood That's okay, thank you for the explanation. This section is very useful to keep in the back of my mind.

I was on the fence about create patches but now it's clear that I must.

**Comment by waynevanson** [comment]
For those interested, here is the git diff between `language-javascript/current` and `language-javascript/7.0.0`

https://github.com/erikd/language-javascript/compare/b493492306895be48955aaf0454314694f2e8db9...new-ast

**Comment by andys8** [comment]
https://github.com/erikd/language-javascript/compare/b493492306895be48955aaf0454314694f2e8db9...new-ast this looks like the only change is adding `async` / `await`
