### ISSUE TITLE
Role protections not applying with empty data declaration

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/purescript#4031]
## Description

Empty data declarations can be freely coerced to one another. This occurs even though foreign imported data types (such as those used to provide types for a kind implemented via an empty data declaration), even though they should be defaulted to a `nominal` role. It also occurs even when the type being coerced is given an explicit `nominal` role for the parameter corresponding with the empty data declaration.

## To Reproduce

Initialize a Spago project using the 0.14.0 compiler and install the `safe-coerce` library -- for example:

```sh
mkdir role-test && cd role-test
spago init --tag psc-0.14.0-20210313
spago install safe-coerce
```

Then, replace `src/Main.purs` with these contents:

```purs
module Main where

import Safe.Coerce as Safe.Coerce

data OpaqueType

newtype UsingOpaque :: OpaqueType -> Type -> Type
newtype UsingOpaque o a = UsingOpaque a

type role UsingOpaque nominal representational

coerceOpaque :: forall o o' a. UsingOpaque o' a -> UsingOpaque o a
coerceOpaque = Safe.Coerce.coerce

-- To make things concrete...

foreign import data X :: OpaqueType
foreign import data Y :: OpaqueType

coerceXY :: forall a. UsingOpaque X a -> UsingOpaque Y a
coerceXY = coerceOpaque
```

You should be able to successfully build the project with `spago build`.

## Expected behavior

I would expect for `coerceOpaque` to produce a compiler error stating that these types cannot be coerced, perhaps with an explanation that the first parameter to `UsingOpaque` has a nominal role and can't be coerced except to itself.

## PureScript version

0.14.0

**Comment by hdgarrood** [comment]
I think this is working as intended. Because the `UsingOpaque` constructor is in scope, you're allowed to coerce from `UsingOpaque o a` to `a`, and from `a` to `UsingOpaque o' a`. If you move the definition of `UsingOpaque` to a different module and don't import the constructor, you get the error I think you were expecting:

```
  Could not match type

    o'0

  with type

    o2


while solving type class constraint

  Prim.Coerce.Coercible (UsingOpaque o'0 a1)
                        (UsingOpaque o2 a1)
```
```

**Comment by hdgarrood** [comment]
GHC works the same way:
```
-- src/UsingOpaque.hs
{-# LANGUAGE RoleAnnotations #-}
module UsingOpaque where

newtype UsingOpaque o a = UsingOpaque a

type role UsingOpaque nominal representational
```
```
-- app/Main.hs
module Main where

import UsingOpaque
import Data.Coerce

coerceOpaque :: UsingOpaque o' a -> UsingOpaque o a
coerceOpaque = coerce

main = return ()
```
The above compiles successfully, but if I stop importing the UsingOpaque constructor:
```patch
-import UsingOpaque
+import UsingOpaque (UsingOpaque)
```
then I get an error:
```
app\Main.hs:7:16: error:
    * Couldn't match type o' with `o' arising from a use of `coerce'
```
```

**Comment by thomashoneyman** [comment]
Would you mind sharing the full example you're using to produce that error? Even if I separate this implementation into three files as demonstrated below I can't trigger the error.

First, the coerce implementation:

```purs
module Main where

import Opaque (Opaque)
import Safe.Coerce (coerce)

coerceOpaque :: forall o o' a. Opaque o' a -> Opaque o a
coerceOpaque = coerce
```

Second, the newtype (without constructors exported):

```purs
module Opaque (Opaque) where

import OpaqueType (OpaqueType)

newtype Opaque :: OpaqueType -> Type -> Type
newtype Opaque o a = Opaque a
```

Finally, the data declaration:

```purs
module OpaqueType (OpaqueType) where

data OpaqueType
```

**Comment by hdgarrood** [comment]
I don’t have my example to hand any more but I think the difference might be that you’re missing a role declaration in that example. In the absence of a role declaration the first parameter will be inferred as `phantom`.

**Comment by kl0tl** [comment]
Your second example fails to compile as expected with a `type role Opaque nominal representational` declaration. As Harry said, your first example compiles because the `UsingOpaque` constructor is in scope. The compiler unwraps newtypes when their constructor is in scope before trying to decompose them, because this let us solve more coercions. For example, given `newtype App f a = App (f a)` and `newtype Age = Age Int`, we are not able to solve `Coercible (App Maybe Int) (App Maybe Age)` if we decompose to `Coercible Maybe Maybe` and `Coercible Int Age`, because `App` is nominal in its second parameter, but unwrapping the newtype yields `Coercible (Maybe Int) (Maybe Age)` which is indeed solvable, because `Maybe` is representational.

**Comment by thomashoneyman** [comment]
🤦‍♀️ I blame daylight savings for forgetting the annotation! Let me check locally one more time and then I can close this.

**Comment by thomashoneyman** [comment]
Yes, I can confirm that adding:

```purs
type role Opaque nominal representational
```

works as expected.
