### ISSUE TITLE
Issue involving type-aliases, polykinds, and externs

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript#4035]
## Description

A certain type leads to a compilation error when imported from a different file but not if it appears in the same file. The error is 
```
  Type synonym Other.Id is partially applied.
  Type synonyms must be applied to all of their type arguments.
```

## To Reproduce

Try to compile [this project](https://github.com/i-am-the-slime/psbug/blob/master/src/Main.purs) and then either inline the type alias of `Alias` to make it compile or use the commented out local definition of `Id`.

Note that everything works without the kind (?) annotations.

## Expected behavior

It's possible to import the `Id` type instead of having to define it locally.

## Additional context

This is the repro main file:

```purescript
module Main where

import Other (Id)

-- type Id :: forall k. k -> k
-- type Id a = a

type Alias = Int

type Wrapped :: forall k. (Type -> k) -> Row k -> Row k
type Wrapped f r = (key :: f Alias | r)

type Unwrapped :: Row Type -> Row Type
type Unwrapped r = Wrapped Id r
```

## PureScript version

0.14.0

**Comment by rhendric** [comment]
@natefaubion, could I get your thoughts on this? The issue seems to hinge on how `createBindingGroups` topsorts type synonyms with and without kind signatures—if the declaration of `Wrapped` precedes the declaration of `Unwrapped` in the final ordering of declarations, then the module compiles; but otherwise, when the definition of `Unwrapped` is type checked, `Wrapped` isn't expanded, and so `Id` is treated as a partial application. In `createBindingGroups`, you commented:

    -- If a dependency has a kind signature, than that's all we need to depend on, except
    -- in the case that we are defining a kind signature and using a type synonym. In order
    -- to expand the type synonym, we must depend on the synonym declaration itself.

I don't understand the rationale for this distinction, though. This issue makes me think that depending on a type synonym needs to mean pointing at the definition vertex regardless of whether the depending vertex is a kind signature, but what do you think?

**Comment by natefaubion** [comment]
> I don't understand the rationale for this distinction, though. This issue makes me think that depending on a type synonym needs to mean pointing at the definition vertex regardless of whether the depending vertex is a kind signature, but what do you think?

It's been a while, and I don't remember exactly, but you are probably correct. I was likely just making a short-sighted correction to get tests to pass. 😆

**Comment by rhendric** [comment]
Ha, okay thanks!
