### ISSUE TITLE
Purs bundle drops `var` but keeps `const` and `let`

### ISSUE THREAD

**Issue by vapaj** [purescript/purescript#4039]
## Description

When bundling a foreign module, the bundler drops global variables if they are not directly used in an exported function. Interestingly, it seems to depend on how the variable is defined.

Let's say we have a simple program:
```purescript
foreign import foo :: Effect Int

main :: Effect Unit
main = do
  x <- foo
  log $ show x
```

And a foreign module:
```javascript
var a = 1;
exports.foo = function() {
  return a + 1;
}
```
Everything works as expected. However, if instead of exporting an anonymous function, we would use a named function which we set the value of `foo` to:

```javascript
var a = 1;
function foo_() {
  return a + 1;
}
exports.foo = foo_;
```

When bundling the app and running it with node, the following error occurs:
```
$ spago build
$ purs bundle "output/*/*.js" -m Main --main Main -o index.js
$ node .

index.js:47
    return a + 1;
    ^

ReferenceError: a is not defined
```

However, if we declare `a` with `const` or `let`, we still seem to have `a` in place:
```javascript
const a = 1;
function foo_() {
  return a + 1;
}
exports.foo = foo_;

```
```
$ spago build
$ purs bundle "output/*/*.js" -m Main --main Main -o index.js
$ node .

2
```

## To Reproduce

Test with code provided, then `spago build`, `purs bundle "output/*/*.js" -m Main --main Main -o index.js` (which is basically `spago bundle-app`) and run with `node .`

## Expected behavior

Global variable should not be dropped.

## PureScript version

0.13.8

**Comment by kl0tl** [comment]
The actual issue is that `purs bundle` only considers variable declarations: function declarations are ignored so the dependency on `a` is never discovered. Replacing the function declaration by a variable declaration works as expected:

```diff
 var a = 1;
-function foo_() {
+var foo_ = function () {
   return a + 1;
 };
 exports.foo = foo_;
```

Let and const declarations are preserved because they aren’t considered as bindings at all.

**Comment by JordanMartinez** [comment]
Should this issue be closed?

**Comment by rhendric** [comment]
It's not clear (to me) whether DCE in foreign modules is an officially-supported feature (as opposed to merely a side effect of DCE in PureScript-generated code); if so, then I'd say keep this open.

**Comment by f-f** [comment]
@rhendric this seems to be a bug rather than a missing feature - the foreign module needs to be carefully designed to please the DCE transform and surely this is not desirable? I mean, if we're doing DCE then it should just work for all JS?

**Comment by rhendric** [comment]
Ah, I seem to have misread this the first time. Yeah, whether dead code in foreign modules is eliminated is a feature, but certainly the DCE transform shouldn't break foreign modules.

**Comment by hdgarrood** [comment]
I don’t think our DCE was ever supposed to work for _all_ JS - as I recall, previously we’ve taken the view that it’s ok to impose some constraints on how you write your FFI modules so that purs bundle can understand them without having to handle the whole set of possibilities of what people can do in JS - but in this case I’d definitely view this as a bug.

**Comment by hdgarrood** [comment]
The boundaries of what `purs bundle` can understand have never been well defined and there are a number of bugs in this repo surrounding it, so we probably ought to either tighten that up a bit more so that what `purs bundle` can handle is documented or at least defined somewhere, or decide that we aren’t going to keep supporting it.

**Comment by kl0tl** [comment]
Things would have been so much simpler regarding ES modules if we didn’t have to support our own bundler 😅 

On the other hand I think there’s space for a tool such as `purs bundle` between the bundler-less experience enabled by ES modules and the overwhelming nightmare JavaScript bundlers can be, so that people without sophisticated needs can still ship decently sized applications without having to know about `zephyr` or yet another tool.

I opened https://github.com/purescript/purescript/pull/4044 to fix this issue. While we’re at it (and while I’m still familiar enough with the bundler code), what do you think of adding support for more declarations? Classes, generators, lets and consts would be easy to support, and declarations introducing multiple bindings (`var x = …, y = …, z = …;` and `var { x, y, z } = …`, plus their variations with `let` and `const`) shouldn’t be much harder.

**Comment by rhendric** [comment]
On the topic of dropping `purs bundle`, the browser-backed REPL does depend on it; but if we switched to ES modules, and we were okay with only supporting browsers that support same, we could conceivably change that!

**Comment by garyb** [comment]
> Things would have been so much simpler regarding ES modules if we didn’t have to support our own bundler 😅

For the longest time I've argued `purs bundle` needs to continue to exist because all the JS bundlers are painfully slow compared to `purs bundle`, despite that also being pretty slow itself. I hear good things about `esbuild`, but I've not had a chance to try it out, and I don't know if it does DCE and stuff. It's fast because it's also not implemented in JS. :wink:

> I opened #4044 to fix this issue. While we’re at it (and while I’m still familiar enough with the bundler code), what do you think of adding support for more declarations? Classes, generators, lets and consts would be easy to support, and declarations introducing multiple bindings (`var x = …, y = …, z = …;` and `var { x, y, z } = …`, plus their variations with `let` and `const`) shouldn’t be much harder.

One argument against supporting more of that stuff in the bundler, is that the less things are supported, the less people will be tempted to do in the FFI files. I feel like they should be as-simple-as-possible implementing a layer between the PS file and code elsewhere, so allowing classes and all sorts in there doesn't really go with that. 

Also it will add some complexity to the bundler, and we already mostly don't want to touch it :smile:.

**Comment by hdgarrood** [comment]
> For the longest time I've argued purs bundle needs to continue to exist because all the JS bundlers are painfully slow compared to purs bundle

Ah right yes, I'd forgotten about this. However, where speed is the primary concern I think not bundling at all is the ideal approach - this is enabled by ES modules. So once ES modules are shipped I'd like to try to nudge more people towards just serving the output directory in dev by default and only bundling in production. If that workflow works as well as I hope it will, I think there will be a stronger case for deprecating `purs bundle`, but I'd like to validate that in practice before we start making steps to actually deprecate it, especially since on the other hand I think @kl0tl may indeed have a point in that there's a space for `purs bundle` in between no bundling at all and full-on JS bundling with webpack or similar.

> I feel like they should be as-simple-as-possible implementing a layer between the PS file and code elsewhere, so allowing classes and all sorts in there doesn't really go with that.

I agree with this view but I'm no longer sure if it's an appropriate position for a compiler to take (as opposed to, say, a style guide).

**Comment by garyb** [comment]
I took a quick look into `esbuild` after commenting yesterday, I think once we support ES modules it probably will be a suitable replacement for `purs bundle`. It is a lot faster already, but the bundle size is larger right now, as if I understand correctly it needs ES modules for its DCE to work correctly.

**Comment by rhendric** [comment]
If we were to take the stance that the bundler rejects foreign JS that doesn't conform to some standard, then fine. If we could dump the bundler, also fine. The status quo, that we ship a bundler and that it will accept some foreign JS but can silently cause it not to work, doesn't seem acceptable. On top of that, for the specific case of function declarations, they are an extremely vanilla JS feature and the engineering cost of supporting them as demonstrated in #4044 is negligible.

Can we agree that #4044 as written is worth doing, regardless of what we decide about other JS features? The only thing stopping me from approving it right now is the question of whether we want it.

**Comment by hdgarrood** [comment]
I agree that the status quo doesn't seem acceptable, and I think #4044 is fine as a short term solution. My only concern is that it's probably only a partial fix, and that a complete fix along the same path probably would represent an unacceptable engineering cost. But if we're planning to deprecate `purs bundle` eventually anyway, which I think we most likely are, then it seems like a good tradeoff.

**Comment by f-f** [comment]
I think #4044 is a good fix for this bug, so I approved it.

**Comment by kl0tl** [comment]
I tried `esbuild` on this module and forks of `purescript-prelude`, `purescript-effect` and `purescript-console` with ES foreign modules:

```purescript
module Example where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = log "Hello world"
```

but the result is disappointing 🙁 

<details>

```javascript
(() => {
  // output/Effect.Console/foreign.js
  "use strict";
  var log = function(s) {
    return function() {
      console.log(s);
    };
  };

  // output/Data.Show/foreign.js
  "use strict";
  var showIntImpl = function(n) {
    return n.toString();
  };
  var showNumberImpl = function(n) {
    var str = n.toString();
    return isNaN(str + ".0") ? str : str + ".0";
  };
  var showCharImpl = function(c) {
    var code = c.charCodeAt(0);
    if (code < 32 || code === 127) {
      switch (c) {
        case "\x07":
          return "'\\a'";
        case "\b":
          return "'\\b'";
        case "\f":
          return "'\\f'";
        case "\n":
          return "'\\n'";
        case "\r":
          return "'\\r'";
        case "  ":
          return "'\\t'";
        case "\v":
          return "'\\v'";
      }
      return "'\\" + code.toString(10) + "'";
    }
    return c === "'" || c === "\\" ? "'\\" + c + "'" : "'" + c + "'";
  };
  var showStringImpl = function(s) {
    var l = s.length;
    return '"' + s.replace(/[\0-\x1F\x7F"\\]/g, function(c, i) {
      switch (c) {
        case '"':
        case "\\":
          return "\\" + c;
        case "\x07":
          return "\\a";
        case "\b":
          return "\\b";
        case "\f":
          return "\\f";
        case "\n":
          return "\\n";
        case "\r":
          return "\\r";
        case "  ":
          return "\\t";
        case "\v":
          return "\\v";
      }
      var k = i + 1;
      var empty = k < l && s[k] >= "0" && s[k] <= "9" ? "\\&" : "";
      return "\\" + c.charCodeAt(0).toString(10) + empty;
    }) + '"';
  };

  // output/Data.Symbol/foreign.js
  "use strict";

  // output/Type.Proxy/index.js
  var Proxy3 = function() {
    function Proxy32() {
    }
    ;
    Proxy32.value = new Proxy32();
    return Proxy32;
  }();
  var Proxy2 = function() {
    function Proxy22() {
    }
    ;
    Proxy22.value = new Proxy22();
    return Proxy22;
  }();
  var $$Proxy = function() {
    function $$Proxy2() {
    }
    ;
    $$Proxy2.value = new $$Proxy2();
    return $$Proxy2;
  }();

  // output/Data.Symbol/index.js
  var SProxy = function() {
    function SProxy2() {
    }
    ;
    SProxy2.value = new SProxy2();
    return SProxy2;
  }();

  // output/Record.Unsafe/foreign.js
  "use strict";

  // output/Data.Show/index.js
  var ShowRecordFields = function(showRecordFields) {
    this.showRecordFields = showRecordFields;
  };
  var Show = function(show2) {
    this.show = show2;
  };
  var showString = new Show(showStringImpl);
  var showRecordFieldsNil = new ShowRecordFields(function(v) {
    return function(v1) {
      return [];
    };
  });
  var showProxy3 = new Show(function(v) {
    return "Proxy3";
  });
  var showProxy2 = new Show(function(v) {
    return "Proxy2";
  });
  var showProxy = new Show(function(v) {
    return "Proxy";
  });
  var showNumber = new Show(showNumberImpl);
  var showInt = new Show(showIntImpl);
  var showChar = new Show(showCharImpl);
  var showBoolean = new Show(function(v) {
    if (v) {
      return "true";
    }
    ;
    if (!v) {
      return "false";
    }
    ;
    throw new Error("Failed pattern match at Data.Show (line 20, column 1 - line 22, column 23): " + [v.constructor.name]);
  });

  // output/Example/index.js
  var main = log("Hello world");

  // main.js
  main();
})();
```

</details>

Here’s what `purs bundle` yields for comparison:

```javascript
// Generated by purs bundle 0.14.2
var PS = {};
(function(exports) {
  "use strict"; var log = function (s) {
    return function () {
      console.log(s);
    };
  };
  exports["log"] = log;
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign["log"];
})(PS);
(function($PS) {
  
  $PS["Example"] = $PS["Example"] || {};
  var exports = $PS["Example"];
  var Effect_Console = $PS["Effect.Console"];                  
  var main = Effect_Console.log("Hello world");
  exports["main"] = main;
})(PS);
PS["Example"].main();
```

ESBuild does not manage to remove unused instances and type declarations by fear of side effects. We can help by providing `/* @__PURE__ */` annotations though!

```javascript
(() => {
  // output/Effect.Console/foreign.js
  "use strict";
  var log = function(s) {
    return function() {
      console.log(s);
    };
  };

  // output/Data.Show/foreign.js
  "use strict";

  // output/Data.Symbol/foreign.js
  "use strict";

  // output/Record.Unsafe/foreign.js
  "use strict";

  // output/Example/index.js
  var main = log("Hello world");

  // main.js
  main();
})();
```

Much better :relieved:

I’ll bundle https://github.com/f-f/purescript-react-basic-todomvc to compare against the various bundlers I tested with ES modules (see https://github.com/purescript/purescript/pull/3791#issuecomment-618048488). Would results comparable to, or even better than thanks to scope hoisting, our bundler be enough to drop `purs bundle` in v0.15.0? Some work is needed to preserve comments and code formatting without destroying source maps but I’d rather not sink more time in our bundler :grimacing:

**Comment by rhendric** [comment]
#4125 may also help with removing unused instances.

**Comment by kl0tl** [comment]
It does indeed! We could also avoid having to annotate data types by revisiting their representation as discussed in https://github.com/purescript/purescript/issues/4020.
