### ISSUE TITLE
`purs repl` fails with "no input files"?

### ISSUE THREAD

**Issue by osa1** [purescript/purescript#4049]
I just installed pre-compiled binary for 0.14.0:

```
~ $ purs --version
0.14.0
```

If I run `purs` it shows a "repl" command for the interactive mode, but running it fails with this error:

```
purs 0.14.0
~ $ purs repl
purs repl: No input files; try running `pulp psci` instead.
For help getting started, visit https://github.com/purescript/documentation/blob/master/guides/PSCi.md
Usage: For basic information, try the `--help' option.
```

I'd expect repl to just work without any input files. Secondly, it tells me to run `pulp psci`, but I don't think `pulp` is coming with the tarball. The tarball only has one executable which is `purs`.

**Comment by kritzcreek** [comment]
`purs` doesn't have a runtime, but we need a minimal set of definitions for the repl to run, which are usually provided through https://github.com/purescript/purescript-psci-support. (which in turn depends on the `prelude`, `effect` and `console`)

The easiest way to set this up these days is to use [spago](https://github.com/purescript/spago) (maybe we should update the error to mention that).

If you'd prefer to do this by hand you'd have to do the equivalent of:

```
$ git clone https://github.com/purescript/purescript-prelude.git
$ git clone https://github.com/purescript/purescript-effect.git
$ git clone https://github.com/purescript/purescript-console.git
$ git clone https://github.com/purescript/purescript-psci-support.git
$ purs repl "purescript-psci-support/src/**/*.purs" "purescript-prelude/src/**/*.purs" "purescript-effect/src/**/*.purs" "purescript-console/src/**/*.purs"
```

**Comment by osa1** [comment]
Interesting, thanks. It's not great from UX point of view, but maybe that's OK. 

I also just realized that the link in the error message does not mention `pulp`. Perhaps it might worth mentioning pulp in the PSCi docs so that users coming from this error message won't have to google it.

**Comment by kritzcreek** [comment]
> Interesting, thanks. It's not great from UX point of view, but maybe that's OK.

It's rare for people to directly interact with `purs`, unless they're setting up a custom build.

If you're just getting started I'd suggest following the instructions in https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md to get a working environment up and running.

I'll close this issue, because we use the issue tracker for tracking compiler bugs, but feel free to ask more questions. We usually prefer to use https://discourse.purescript.org/  for general discussion/support.

**Comment by wolfsprite** [comment]
> It's rare for people to directly interact with `purs`, unless they're setting up a custom build.

I just ran into the same error that this issue mentions by grabbing the binary for my system first, and then following the documentation here after:
https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md

The first two sentences specifically mention `purs repl`, which I tried and then ran into the "no input files" error. I notice that further down the page `spago repl` is shown as a way to interact with the repl, but as someone starting out with PureScript, this was pretty confusing to me.

**Comment by twome** [comment]
Same here. This is terrible UX. If the `repl` command isn't meant for ordinary users to see, then it shouldn't be listed to everyone exploring the CLI. The only reasonable assumption would be that a command named "REPL" opens a functioning REPL. Referring to something named `pulp`, which isn't otherwise described, is also maximally confusing.

**Comment by JordanMartinez** [comment]
Feel free to open a PR.
