### ISSUE TITLE
purs compile rebuilds modules if output is touched

### ISSUE THREAD

**Issue by wclr** [purescript/purescript#4066]
## Description

`spago build` (that calls `purs compile` under the hood) rebuilds modules if compiled output files of one module ( `index.js` and `externs.cbor` together) were touched.

## To Reproduce

- spago init
- spago build
- spago build - see no rebuild
- execute: `touch output/Data.Show/index.js` and `touch output/Data.Show/externs.cbor`
- spago build - see rebuild

Demo:
![purs-touch-rebuild-issue-cmd](https://user-images.githubusercontent.com/736697/115125531-3117ca00-9fe2-11eb-8541-a8dc5ab5c176.gif)

## Expected behavior

I would expect no rebuild if the content of files has not been modified, and it is not clear why touching only one file (index or externs) doesn't cause the rebuild.

## Additional context
Registred on Windows 10.

Probably this this issue is responsible for unessesary rebuilds caused in the environments where the editor (for example vscode) thouches files for watching.

## PureScript version

0.14

**Comment by hdgarrood** [comment]
This is expected: we need to use the output timestamps to ensure that downstream modules are recompiled when upstream modules change. If you don’t want unnecessary rebuilds to happen, don’t touch those files. I don’t think any tool other than `purs` should be touching or writing to those files anyway?

**Comment by hdgarrood** [comment]
It seems weird to me that your editor touches those files for watching - I can’t think of a good reason for it to do that. It’s actually quite important that only `purs` is writing to or touching files in the `output` directory, because otherwise it’s easy for the compiler to consider compiled outputs to be up to date when they aren’t. For example, if index.js is out of date for a particular module as a result of the module having been compiled most recently without the `js` codegen target, and you touch it and then compile with the `js` codegen target, the compiler will (by design) think that no compilation is necessary.

**Comment by wclr** [comment]
> It seems weird to me that your editor touches those files for watching

Ok, I looked at the code, and it adds a module in the build plan if its output modified date more than dates of dependency modules date.

So I think I know that is going on here, it is not vscode watching touching the files, but the language server, which sends a rebuild command on a document being opened in the editor and shows the diagnostics. This feature was added because without it if you open in the editor a file with an error it didn't show anything until you change and save it.

Actually, it was me who added [this feature to the language server](https://github.com/nwolverson/purescript-language-server/pull/125) recently, I didn't realize that the compiler behaves this way, that it will overwrite existing output even if the source didn't change.

Sometimes I happen to open source purs lib files (from .spago dir) in the editor, and it rebuilds them and this causes output to be overwritten though even the purs source didn't change from the last build, this is quite strange.

**Comment by hdgarrood** [comment]
Ah ok, so it sounds like what might be happening is that the ide fast-rebuild path doesn't account for the case where a module is already up to date, and compiles and overwrites the output files anyway.

**Comment by wclr** [comment]
Though I think this feature of building opened files in the editor could be replaced with just executing the full build on purs ide start, which will too make the diagnostics show up.

**Comment by hdgarrood** [comment]
I think that’s not a bad option - iirc pscid does the same.

**Comment by wclr** [comment]
I'm checking this option now, but it may take quite a long time on a big project to make the full build and get the diagnostics, and also if multiple editors at once this can very resource consuming, so probably for a better user experience, those approaches could be combined to make things more smooth.

So, on the issue with the fast rebuild, I believe it still should not rebuild if it is not actually needed? Is there a need to create a new issue?

**Comment by hdgarrood** [comment]
I think it’s reasonable to argue that ide rebuilds should probably use the same mechanism as normal builds to decide whether rebuilds are needed, or at least that they should not trigger rebuilds for other downstream modules when recompiling a module which hasn’t changed. I think it’s potentially a bit early to be able to say exactly how we would achieve this. It might be worth forgetting about this particular issue and continuing to work towards cutoff (#3724), because once that is implemented I think it would also address the issue you are seeing.

**Comment by wclr** [comment]
So, I'll close it.
