### ISSUE TITLE
Make typeclass and deriving desugaring part of type checking

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4086]
## Summary

Make certain kind information available sooner in the compilation pipeline, such that other desirable features become unblocked or easier to do.

## Motivation

See [kl0tl's comment and natefaubion's following comment in #3426](https://github.com/purescript/purescript/issues/3426#issuecomment-651082718). Fixing this would unblock a few things:
- #3426
- #4084 
- potentially other things I'm not aware of

Since this is far outside my expertise, I'm not able to provide a concrete proposal or example. However, this at least provides a place to discuss this further.

**Comment by rhendric** [comment]
I did some digging into #4101 and #4105 and I believe they both boil down to this. #4105 can be narrowly fixed without this, but I'm not sure it's worth it—we should probably just roll up our sleeves and do it right.

**Comment by kl0tl** [comment]
This would also fix #3510 and #3453. I’m focusing on ES modules when I find time for PureScript these days but I believe I’ve done a good chunk of the work in https://github.com/kl0tl/purescript/commit/9e94eddc2f7ccf5ce89ba7b932034432ff44eae7. If I recall I stopped at the desugaring of binding groups: since type class instances are not desugared before binding groups anymore their declarations now depends on the bindings appearing in their members, so we may need another type of binding group declaration which can weave together both types and terms.
