### ISSUE TITLE
Allow partial application in operator definition

### ISSUE THREAD

**Issue by Swordlash** [purescript/purescript#4089]
## Summary & Motivation

Hi, I'm writing a helper library to make HTML DOM creation less painful. I implement some layout combinators like `>|<`, `<|>`, `<<|>>` etc., all meaning the same thing, but with different padding between components. So I have a general function like

```purescript
horiz :: forall w i a b. IsLayout w i a => IsLayout w i b => Padding -> a -> b -> Layout w i
horiz padding a b = ...
```
and in order to create operator synonyms I have to write a bunch of helper functions like
```purescript
horiz0 :: forall w i a b. IsLayout w i a => IsLayout w i b => a -> b -> Layout w i
horiz0 = horiz (Padding 0)

infixl 6 horiz0 as >|<

horiz5 :: forall w i a b. IsLayout w i a => IsLayout w i b => a -> b -> Layout w i
horiz5 = horiz (Padding 5)

infixl 6 horiz5 as <|>
```

## Proposal

I think it would be nice to allow operators to be defined as not only "whole" functions as they are defined, but also as partially applied ones.

## Examples

In this example, I could simply type
```purescript
infixl 6 (horiz (Padding 0)) as >|<
infixl 6 (horiz (Padding 5)) as <|>
infixl 6 (horiz (Padding 10)) as <<|>>
```
without a need to define a whole family of almost-identical functions. Currently attempting to do so results in parse error (unexpected parentheses).

**Comment by Swordlash** [comment]
Actually, what is the reason for having to define operator as an alias to function, not as a function itself as in Haskell?

**Comment by garyb** [comment]
There are a few reasons for the current choice:

1. To make fixity and precedence for all operators explicit
2. To give operators a name that can be used by humans when describing them to other people
3. To ensure the generated code also has a name that can be used rather than having to generate something meaningless

**Comment by Swordlash** [comment]
1. We always have to give fixity and precedence explicitly anyway: `infixl 6 <|>` in Haskell
2. Has some virtues, but I imagine half of names are still being made dummy only to satisfy compiler (like horiz0, horiz5, horiz10 in my examples)
3. Can't argue with that, can be useful perhaps

**Comment by garyb** [comment]
1. Well, you don't have to provide a fixity declaration at all in Haskell, is what I meant. You can just define a named operator and leave it "unspecified" (I realise that it's not really unspecified, it'd be `infixl 9` if I remember right, but I like that it's required in PS to make it explicit to someone reading the code if they don't have that piece of information stored away in their head).
2. I don't disagree, some of the names we came up with after this was introduced are dubiously useful (`voidRight`, `applyFlipped`)... but I think it's still better than "everted double fishy thing" and the like that might otherwise arise :smile:.
3. This was probably actually the main motivation when we did it, as generating mostly human readable code was a strong goal for the language. I personally don't put as much weight on that as I once did, as it's very uncommon that I actually have to look at the generated code these days.

**Comment by JordanMartinez** [comment]
> infixl 6 (horiz (Padding 0)) as >|<
> infixl 6 (horiz (Padding 5)) as <|>
> infixl 6 (horiz (Padding 10)) as <<|>>

I don't find such a change as something that adds a lot of value. I think the resulting docs would be harder to notice. To me, using `horiz0`, `horiz5`, and `horiz10` would be more readable at the end of the day. Perhaps a different example would be more appealing to me.

A few thoughts to consider:
- assuming annotations are added so that we can properly notify users of deprecation warnings on things other than functions, would we support annotations on operators as well in case `>|<` was being changed to something else (e.g. `horiz0` to `horiz5`)?
- how complex could these functions get before the current approach of defining a function with an infix is needed (e.g. `infixl 6 (Heterogenous.hmap Record1ToRecord2 <<< (_ { foo = 42 }) ) as <$$>`) and would that complicate type checking?

**Comment by rhendric** [comment]
I don't know, I think this is a pretty reasonable proposal. Operators are already basically little macros; they expand to a double application of a different expression during desugaring. Currently, that expression is restricted to being an identifier or constructor. I don't think lifting that restriction to encompass arbitrary `exprAtom`s would cause any engineering problems, or even really add much complexity to the compiler to speak of. (The one piece of real new work I can think of is that operator definitions would need to be topsorted and cycles prohibited.) Docgen would largely not need to change; operators are still aliases for things, just possibly more complex things.

AFAICT the arguments against are all of the ‘we know what's good for you’ variety. And maybe we do? But how much rope (with which our users might hang themselves) would this be really? If we say that explicitly declaring identifiers corresponding to operators is still what we consider to be best practice, for the various above reasons, but it's possible to buck the convention if you weigh the pros and cons differently, is the harm done to the ecosystem by the authors who choose to do so unwisely large enough to justify tying everyone's hands preemptively and requiring extra boilerplate in cases like the OP's? I could be convinced that it is, but I have not yet been.

> would we support annotations on operators

This is a question regardless of whether operators can possibly represent non-atomic expressions. You could make a case that they're not needed in the status quo, because annotations on value declarations should also apply to any operators that alias those declarations, but I don't think it's a good case; since operators can be defined independently of what they alias, you might want to deprecate an operator specifically, perhaps because you've deployed a new operator with the same alias.

> how complex could these functions get

I think we should advise the simpler the better (with the status quo of a simple identifier being the best), but ultimately it's up to the author.

> and would that complicate type checking?

Operators are completely desugared before type checking, so not from an engineering perspective. From a human perspective, I think we can just tell people that whatever is in the ‘body’ of an operator declaration gets inlined wherever that operator is used, which is another good reason to keep those bodies simple if one thinks that type checking the resulting expressions might create difficult-to-understand situations.

**Comment by f-f** [comment]
> is the harm done to the ecosystem by the authors who choose to do so unwisely large enough to justify tying everyone's hands preemptively and requiring extra boilerplate in cases like the OP's?

I'm firmly in the camp of "yes" when it comes to this question. When I first came to PureScript I was so glad that operators had to have a readable identifier! Other than aiding memorization, it allows to talk about them with others, as Gary already mentioned.
If you are looking for places where lifting this requirement could do harm to an ecosystem, I think [Haskell's lens](https://hackage.haskell.org/package/lens) is a good example. Note that I don't absolutely mean to reprimand lens' authors, it's just to demonstrate that if the language doesn't force you to assign names to things then you might not do that, and this might turn into a long list of symbols that it's hard to penetrate and make yours - I'll never forget the frustration that I encountered when trying to make sense of all of these, remember them, and trying to ask for help. (fortunately the most common ones have names so I still managed)

I think it's an entirely acceptable tradeoff to impose a small amount of boilerplate on package authors if that means improving the UX for users.

**Comment by garyb** [comment]
> From a human perspective, I think we can just tell people that whatever is in the ‘body’ of an operator declaration gets inlined wherever that operator is used, which is another good reason to keep those bodies simple if one thinks that type checking the resulting expressions might create difficult-to-understand situations.

I'd be against implementing a version of this that inlines the expressions directly as there is one footgun and one actual problem with it that I see.

The footgun: if you put some complicated/expensive expression as the operator expression and it inlines that as-is everywhere, you're going to be paying for the cost of evaulating the expression every time the operator is used.

The actual problem: scope capture issues. If the expression references identifiers that are rebound locally in the scope the operator is used, then it's either going to mean the operator behaviour can change (or become an error) at each use site, or we're going to have to figure out how to keep the reference stable somehow.

So I'd say that if we are to do this, then we'd need to generate a named value for the operator, so we can substitute the way we do now without these additional concerns.

**Comment by JordanMartinez** [comment]
> the arguments against are all of the ‘we know what's good for you’ variety.

I'll admit it. I'm in that camp.

I'll respond to some of the more recent discussion. To address some of the readability/findability concerns, what if this syntax included a name part that "desugared" to what we would write today? In other words,
```
-- what if we took what is currently being proposed
infixl 6 (horiz (Padding 0)) as >|<

-- and added a "name" to this somewhere into the proposed syntax
-- in the below case, the name is "horiz0"
infix6 (horiz (Padding 0)) as >|< "horiz0"
```
... which would be understood by the compiler as the same as writing the following in the source code...
```
horiz0 :: _ -- InferredByCompiler
horiz0 = horiz (Padding 0)

infixl 6 horiz0 as >|<
```
This would satisfy all three points Gary made in his original response and the readability/findability concern Fabrizio mentioned. I'm not sure how it would affect source span issues.

**Comment by rhendric** [comment]
Would scope capture really be a problem? The name resolution desugaring step happens before operators are desugared, and since operators can only be declared at the module level, all of the names used in an operator declaration would be desugared to module-qualified names. Local variables at sites where the operators are used, if they shadow module-level names, would still be represented with unqualified names. I don't know if all of the downstream parts of the compiler handle that distinction cleanly, but if not, would fixing that be too hard?

To my mind, the biggest advantage of doing a direct inlining is that it preserves the ability to use the same operators in both expressions and patterns without too much fuss, in a case like `inlinel 6 (Horiz (Padding 5)) as <|>`, where `Horiz` is a three-argument data constructor. I have no idea how you'd accomplish this with a compiler-generated intermediate binding—I expect it could be done but I think it'd be messy.

I can't deny that there are footguns here, though. :shrug:

**Comment by natefaubion** [comment]
I personally don't like the idea of having what is semantically a binding, but no way to add a type signature, with potentially unexpected evaluation semantics. Could you come up with some way around all these problems? Probably. But at that point, it's snowballing, and the far simpler solution would be to just allow operator definitions directly and require that they have a matching fixity declaration. This proposal is a 👎 for me for that reason.

**Comment by natefaubion** [comment]
> To my mind, the biggest advantage of doing a direct inlining is that it preserves the ability to use the same operators in both expressions and patterns without too much fuss, in a case like inlinel 6 (Horiz (Padding 5)) as <|>

I think that this conflates fixity and pattern synonyms. There are lots of cases where you'd want pattern synonyms without fixities, and I don't think there's a reason why a pattern synonym couldn't have an operator fixity.

**Comment by JordanMartinez** [comment]
What is the final decision on this issue? Based on Nate's above comments, it sounds like there's a few reasons against implementing this that are stronger than the original "we know what's good for you" reasons.

**Comment by rhendric** [comment]
I've been convinced that it doesn't make sense to do this without revisiting the broader operators-aren't-identifiers design choice (which I agree doesn't make sense to do absent a more compelling use case than presented here). I don't see any other dissenting maintainers so I think we can close this.
