### ISSUE TITLE
Questions on making a release

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4102]
Reading through the [RELEASE_GUIDE.md](https://github.com/purescript/purescript/blob/master/RELEASE_GUIDE.md), could I get answers to these questions?

Overall questions...

1. Can we produce a step-by-step "run these commands" checklist to ensure releases are done correctly?

1. How much of this guide needs to be updated? It seems like things are somewhat out of order. Moreover, the instructions never say to update the CHANGELOG.md file to include a new "Unreleased" section.

Regarding ["Before making a release"](https://github.com/purescript/purescript/blob/master/RELEASE_GUIDE.md#before-making-a-release)...

1. I'm supposed to compile the latest package set with (I imagine) a locally built binary using the `master` branch. Is there a script we can write that does this automatically?

1. What is there to check in INSTALL.md?

1. For the release notes, aren't we just copying and pasting the CHANGELOG.md entry and (possibly) editing it slightly?

Regarding ["Making a release"](https://github.com/purescript/purescript/blob/master/RELEASE_GUIDE.md#making-a-release)...

1. Let's say the GitHub-release-triggered CI build fails. How do I manually upload the prebuilt binaries? Are these instructions still relevant?

1. For the `stack upload` parts, do I need an account or some token to prove authorization?

1. What's a quick and easy way to see whether `purescript`/`purescript-cst` can be installed from Hackage?

1. For the `npm publish` parts, do I need an account or some token to prove authorization?

Regarding ["After making a release"](https://github.com/purescript/purescript/blob/master/RELEASE_GUIDE.md#after-making-a-release)...

1. Instructions say to announce the release on Twitter. Is that necessary (I don't have a Twitter account)? Do we have a `purescript` Twitter account that I'm supposed to use?

**Comment by hdgarrood** [comment]
These are great questions, thanks for writing them up!

> Can we produce a step-by-step "run these commands" checklist to ensure releases are done correctly?

I’m sure there is scope for automating more of these steps, and that would be great, but I doubt we will be able to automate the entire process; I think some steps necessarily require human judgement, such as checking INSTALL.md is up to date (I’ll come back to that).

> How much of this guide needs to be updated? It seems like things are somewhat out of order. Moreover, the instructions never say to update the CHANGELOG.md file to include a new "Unreleased" section.

This question is difficult to answer as posed, because I’m not sure what you’re referring to exactly. What things seems like they are out of date or out of order? We probably should say to update the changelog to include a new unreleased section at least.

> I'm supposed to compile the latest package set with (I imagine) a locally built binary using the master branch. Is there a script we can write that does this automatically?

Yes, this seems like a good candidate for automation.

> What is there to check in INSTALL.md?

Ideally the entire thing. The parts that are most likely to go out of date are the GHC version we are on and the corresponding set of supported OSes (you can check this on the GHC website), the set of unofficial installation methods that are listed there (eg unmaintained ones should be dropped), and the instructions for building from source (these are currently broken as it happens, and we should fix them, but this doesn’t need to hold up 0.14.2).

> For the release notes, aren't we just copying and pasting the CHANGELOG.md entry and (possibly) editing it slightly?

Pretty much, yes. I think it’s probably a good idea to read over the whole set of release notes to check for errors at this stage too.

> Let's say the GitHub-release-triggered CI build fails. How do I manually upload the prebuilt binaries? Are these instructions still relevant?

I think so: this hasn’t failed for a while but CI is often unreliable so I don’t think we can necessarily count on it always working. You would want to create the binaries the same way CI does, there’s a script in this repo iirc, and then on the release page on GitHub it should let you upload the files.

> For the stack upload parts, do I need an account or some token to prove authorization?

Yes, you’ll need a Hackage account and you’ll need to be invited to become a maintainer of the purescript package on Hackage. I think `stack upload` asks you for a username and password where necessary.

> What's a quick and easy way to see whether purescript/purescript-cst can be installed from Hackage?

I think the building from source instructions in INSTALL.md would usually be best, although as I say they are broken right now. `cabal install purescript` might do it.

> For the npm publish parts, do I need an account or some token to prove authorization?

Yes, you’ll need an npm account and you’ll need to be invited to become a maintainer of the purescript package on npm.

> Instructions say to announce the release on Twitter. Is that necessary (I don't have a Twitter account)? Do we have a purescript Twitter account that I'm supposed to use?

I don’t think a Twitter announcement is necessary. I think the only one that is necessary is Discourse, and then people can link to that wherever else they feel like it. I personally like to tweet about compiler releases but I don’t think we should expect everyone to. There is https://twitter.com/purescript but I think only Phil has access to it, and it might even pick up a release announcement by itself anyway because it automatically pulls stuff in from a few places.

**Comment by JordanMartinez** [comment]
> This question is difficult to answer as posed, because I’m not sure what you’re referring to exactly. What things seems like they are out of date or out of order? We probably should say to update the changelog to include a new unreleased section at least.

I think I'll submit a PR that highlights things. That seems to be a better way to further discuss this.

**Comment by JordanMartinez** [comment]
> I think I'll submit a PR that highlights things. 

See #4104.

**Comment by JordanMartinez** [comment]
And thanks for the answers provided so far!

**Comment by JordanMartinez** [comment]
I think this issue has been addressed by the answers above and the discussion that followed in #4104.
