### ISSUE TITLE
Type class instances that aren't given names don't show up in generated documentation

### ISSUE THREAD

**Issue by ursi** [purescript/purescript#4109]
## Description

When generating docs with `purs docs`, only the documentation for type class instances with names get generated.

## To Reproduce

```purescript
module Main where

import Prelude

newtype Foo = Foo Int
derive newtype instance Eq Foo

newtype Bar = Bar Int
derive newtype instance eqBar :: Eq Bar
```
- generate documentation

![image](https://user-images.githubusercontent.com/17836748/121412073-4b12c080-c932-11eb-918b-74ac3703aa9e.png)

## PureScript version

0.14.2

**Comment by JordanMartinez** [comment]
Fortunately, this bug is easy to fix. The doc generation process has its [own desguaring pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Docs/Convert.hs#L82-L101) that is different from the [main desugaring pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar.hs#L64-L93)

The fix would be to add the `desugarTypeClassInstanceNames` pass into the docs version. I guess this is a valid reason to not implement #4099

**Comment by rhendric** [comment]
That's one possible fix; another would be to change `getDeclarationTitle` to return `Just "<anonymous>"` or something instead of `Nothing`, for `TypeInstanceDeclaration`s with no name.

(I was going to start down that road, but I started with trying to add a unit test, and I think changing the documentation unit test infrastructure to support verifying that unnamed instances are documented is going to be a substantially larger change than the fix itself! Those tests seem generally to assume that anything that can be documented has a name, which is no longer true.)

**Comment by JordanMartinez** [comment]
> another would be to change getDeclarationTitle to return Just "<anonymous>" or something instead of Nothing, for TypeInstanceDeclarations with no name.

Yeah, that would be a faster fix.

**Comment by JordanMartinez** [comment]
I realize it doesn't guarantee that this bug won't reappear, but should we at least get something merged to fix this and then do a hotfix release?
