### ISSUE TITLE
Include inferred kind signatures in HTML docs when no kind signature declaration is provided explicitly

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4117]
## Summary

Related to #3973. Once #4100 gets merged, explicit kind signatures will be displayed in the HTML docs. [First proposed in #4100](https://github.com/purescript/purescript/pull/4100#issuecomment-864039666), we should also include implicit (i.e. inferred) kind signatures in docs.

## Proposal

#4100 did not include inferred kinds in its PR because it seemed best to add them in a separate PR. 

To add the inferred kind signatures, we can adjust the [`insertValueType` function](https://github.com/purescript/purescript/pull/4100#issuecomment-864416670) to look up the corresponding kind in the `Environment` using the declaration's name. This idea already proved to work in #4100 when I started to implement it there around the same time the below guidelines were proposed.

However, there are a few guidelines on how this should be done:
1. The final kind signature inferred by the compiler may need to be adjusted in some circumstances. For example, a declaration of `data Foo a = Foo` will have the inferred kind signature of `forall (k :: Type). k -> Type` rather than the simpler and expected `forall k. k -> Type` (edited. Original was <del>`Type -> Type`</del>). We would need to rewrite such cases to their expected version. We could call this "kind signature docs desugaring" or something.
2. Inferred kind signatures where all type parameters have kind `Type` should not be displayed ([proposal](https://github.com/purescript/purescript/pull/4100#issuecomment-864427332) and [clarification](https://github.com/purescript/purescript/pull/4100#issuecomment-864491464)). This should occur after the "kind signature docs desugaring" step as we may not find some signatures that satisfy this condition until after they are desugared.

Unanswered questions:
- Let's say a user adds an explicit kind signature declaration where all type parameters have kind `Type`. Should we remove that  kind signature from that declaration's documentation? Or continue to let users override this behavior if they so desire?
- Since I'm unfamiliar with the `P.Type` type, is there pre-existing code that shows what each data constructor represents? (Maybe I just need to look around a bit more)
- The questions/comments raised in [Harry's comment about the 'sort annotation'](https://github.com/purescript/purescript/pull/4100#issuecomment-864546458)

**Comment by rhendric** [comment]
>   1. The final kind signature inferred by the compiler may need to be adjusted in some circumstances. For example, a declaration of `data Foo a = Foo` will have the inferred kind signature of `forall (k :: Type). k -> Type` rather than the simpler and expected `Type -> Type`. We would need to rewrite such cases to their expected version. We could call this "kind signature docs desugaring" or something.

Why would we do this? If someone finds a `foo :: Foo "some-symbol"` in the wild and, looking up `Foo`, reads in the documentation that the kind of `Foo` is `Type -> Type`... that seems bad.

**Comment by rhendric** [comment]
>   * Let's say a user adds an explicit kind signature declaration where all type parameters have kind `Type`. Should we remove that  kind signature from that declaration's documentation? Or continue to let users override this behavior if they so desire?

It's a weak opinion, but my lean is towards removing it. Precisely because of kind inference, sometimes users need to add an explicit but uninteresting kind signature to prevent a more polymorphic signature from being inferred. In such cases, it'd be incorrect to read the signature as a signal of the user's intent to emphasize that kind. It makes sense that we require authors to be explicit if they're tying their hands, but I don't think that means the compiler has to be equally explicit when describing the type to readers of documentation.

**Comment by hdgarrood** [comment]
> The final kind signature inferred by the compiler may need to be adjusted in some circumstances. For example, a declaration of data Foo a = Foo will have the inferred kind signature of forall (k :: Type). k -> Type rather than the simpler and expected Type -> Type. We would need to rewrite such cases to their expected version. We could call this "kind signature docs desugaring" or something.

I don’t think we should do this, because it would be incorrect. If we claim that the kind is Foo is `Type -> Type`, we are saying that you are not allowed to write things like `Foo Array` or `Foo "hi"`, because that would not be kind-correct - but in fact you are allowed to write both of those. My proposal was that we should simplify `forall (k :: Type). k -> Type` to `forall k. k -> Type`.

I think always including explicit kind signatures makes sense - if the author has provided a kind signature, it probably means one of two things:
1. the author thinks it helps people understand what is going on, or
2. Without a kind signature, the data type has an inferred kind which contains kind variables, which would produce a warning, so the author has provided a kind signature in order to avoid the warning. In this case I think providing the kind signature in the docs is preferable even if all of the parameters do have kind `Type`, because you wouldn’t be able to figure that out from the rest of the data type declaration.

**Comment by rhendric** [comment]
>   because you wouldn’t be able to figure that out from the rest of the data type declaration.

I defer to your judgement, but this bit is just a matter of convention, isn't it? If the convention when reading documentation is ‘assume all type parameters have kind `Type` unless otherwise stated’, there's no ambiguity. Admittedly, this is a different convention then when reading code, which is ‘understand what the compiler would infer’. I think the former convention is simpler and possibly therefore more appropriate for docs? But possibly the cost of the context shift isn't worth the benefit.

**Comment by hdgarrood** [comment]
My opinion here is also weakly held. I’m imagining a case where the reader knows what kinds are, and is looking at the docs for a data type declaration like, say,
```
data Foo :: Type -> Type
data Foo a = Foo
```
and wants to know if you can write `Foo "hi"`, but doesn’t know the rule for which kinds are shown in HTML docs and is therefore unable to obtain the information they want (specifically, that Foo is monokinded). This is not a problem if the rule for choosing which kinds are displayed in HTML docs is well known by people; maybe it’s reasonable to expect people who care that much about kinds to understand the rule, in which case applying the rule to explicit kind signatures would make sense.

**Comment by garyb** [comment]
One minor advantage of displaying "uninteresting" kinds is that it would make the kinds of partially applied type synonyms explicit in the docs if they were also annotated in the code for documentation purposes.

**Comment by JordanMartinez** [comment]
> My proposal was that we should simplify `forall (k :: Type). k -> Type` to `forall k. k -> Type`.

Sorry all. This is what I meant to write, but accidentally wrote the wrong thing. So, the "desugaring" (or resugaring?) idea still exists, but it just cleans up this one case. I'll edit my opening thread to clarify that.

**Comment by JordanMartinez** [comment]
> One minor advantage of displaying "uninteresting" kinds is that it would make the kinds of partially applied type synonyms explicit in the docs if they were also annotated in the code for documentation purposes.

Couldn't we still get this advantage without including all "uninteresting" kind signatures? AFAIK, that should only occur with type synonyms, right?

**Comment by JordanMartinez** [comment]
Also, could some of these decisions be delayed until feedback from the community is received? We could show all kind signatures regardless until the community and us both agree that it shouldn't be done. Or we could do vice versa until we come across situations where the community and us both agree that it should be done in X circumstance.

**Comment by hdgarrood** [comment]
Yeah, I think we should just pick an approach and see how it works in practice rather than getting too mired in discussions about what we should do, because we can always change it later. I think I have changed my mind - I would be tempted to start off by saying that uninteresting kinds should always be hidden, even if they are explicitly declared, because displaying too much kind information to beginners seems like it could be a worse outcome than slightly inconveniencing power users who don’t yet know the rule for when kinds are hidden. I think it would also be good to update https://pursuit.purescript.org/help/users to explain when kinds are displayed.

**Comment by JordanMartinez** [comment]
I think hiding them would be a good first step because no one is used to seeing kind signatures in docs yet. So, that should become "normal" before this decision is reevaluated.
