### ISSUE TITLE
Using Weeder; or, what is our public API as a library?

### ISSUE THREAD

**Issue by rhendric** [purescript/purescript#4146]
I'd like to add [Weeder](https://hackage.haskell.org/package/weeder) to our CI workflow, to help us clean up functions that are exported from a module but never used anywhere in the project.

The problem is, anything exported from any module in either `purescript` or `purescript-cst` technically is part of our public API, right? So deleting these definitions would be a breaking change. But I imagine there's a line we could draw around some of our modules and call those our actual public API, and everything else internal. Where would we draw it?

Aside from that question, there's the smaller question of whether we'd want to keep some internal unused functions around anyway, because they complete a set or might be expected to be useful in the future. I'm inclined towards no in most cases, but, for example, maybe we want to keep `runSupply` alongside `runSupplyT`, even though we only ever use the latter.

For reference, after defining `Main.main` and a handful of tool-generated functions as entry points, [here](https://gist.github.com/rhendric/feaa460453459bf524e341d7ebb4b753) are the 187 unused definitions Weeder found. This wouldn't include any functions that would become unused if these are deleted, of course, and also I haven't verified that there are no false positives in there.

**Comment by hdgarrood** [comment]
We generally don’t consider the API of the purescript package to be “public,” in the sense that it is allowed to change in any way at any time without incurring a major version bump. This means that depending on the compiler as a library is kind of awkward, and you often need to add stricter upper bounds than you normally would, but this doesn’t seem to have caused too much trouble so far; I think the proportion of people who just use the compiler normally is so much higher than the proportion who use the library that it would be mad to allow the library to dictate compiler version numbers. At some point we might want to start publishing a compiler library which is separate from the compiler so that it can have its own version numbers and follow the PVP, but that would add a lot of hassle to releases and so I don’t think it would be a good tradeoff right now.

I also haven’t inspected that list in much depth but right now I’d probably be happy to remove the majority of those definitions and set up CI so that unused definitions cause the build to fail unless we’ve explicitly made an exception for them.

**Comment by hdgarrood** [comment]
Oh also, a lot of the functions which are identified as unused there probably ought to stay as they are expected to be used in other projects which are using the compiler API. I think CST.Flatten and the CoreFn FromJSON modules fit into this category, for example.

**Comment by rhendric** [comment]
`FromJSON` only exports two functions! It looks like Weeder does actually report the transitively unused declarations after all; there's really only one function there that needs to be added as an entry point.

Similarly, I think all the `CST.Flatten` stuff is just in support of `CST.Print.printModule`.

My hope is that there'll just be a handful more functions like those, or maybe some namespaces that we want to blanket support, and the rest we can junk? Or is that too naive?

**Comment by hdgarrood** [comment]
That sounds plausible to me!
