### ISSUE TITLE
Drop Type sort annotations in all kind signatures for docs, not just inferred kind signatures

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4160]
## Description

As reported [here](https://github.com/purescript/purescript/pull/4137#issuecomment-881575727), sort annotations for kind `Type` are only removed in inferred kind signatures, not explicit ones.

The below code

```
data Foo a = Foo
```
would be inferred to have a kind signature of
```
data Foo :: forall (k :: Type). k -> Type
data Foo a = Foo
```
but we want it rendered as

```
data Foo :: forall k. k -> Type
data Foo a = Foo
```
since the `(k :: Type)` is a sort annotation for kind `Type`.

However, if one declares the kind signature explicitly using that, it will be rendered like that.
```
-- explicit kind sig declaration with type sort annotation
data Foo :: forall (k :: Type). k -> Type
data Foo a = Foo

-- will get rendered as is without dropping the sort annotation
data Foo :: forall (k :: Type). k -> Type
data Foo a = Foo
```

**Comment by hdgarrood** [comment]
I disagree: I think if a kind signature has been explicitly given with sort annotations, they should stay in. If the author has indicated that this is how they would like the declaration to look, then I think we should respect that.

**Comment by JordanMartinez** [comment]
What is the difference between `forall (k :: Type). k -> ...` and `forall k. k -> ...`? If the answer is nothing, then why should we display information in this situation but hide "uninteresting" kind signatures? AFAICT, the reasons for hiding "uninteresting" kind signatures are just as applicable to this situation if the code above with and without the sort annotation are the same.

**Comment by hdgarrood** [comment]
The difference is that people are often encouraged to provide uninteresting kind signatures for data types which would otherwise be inferred to have a polymorphic kind, because of the warning which is emitted when a polymorphic kind is inferred; there’s no similar warning in this case.

**Comment by hdgarrood** [comment]
Sorry, to clarify, there’s no difference between `forall k. k -> Type` and `forall (k :: Type). k -> Type`, but I think the polymorphic kind warning is arguably a reason to treat these cases differently.

**Comment by kl0tl** [comment]
Type is the only sort though, the following:

```purescript
module Example where

data K

data Foo :: forall (k :: K). k -> Type
data Foo a = Foo
```

fails to compile with:

```
Error found:
in module Example
at Example.purs:5:32 - 5:34 (line 5, column 32 - line 5, column 34)

  Could not match kind
     
    K
     
  with kind
        
    Type
        

while checking that type k
  has kind Type
while inferring the kind of k -> Type
while inferring the kind of forall (k :: K). k -> Type
in kind declaration for Foo

See https://github.com/purescript/documentation/blob/master/errors/KindsDoNotUnify.md for more information,
or to contribute content related to this error.
```

So sort annotations are entirely redundants.

**Comment by hdgarrood** [comment]
Not quite. For example:

```
data A :: forall (k :: Type -> Type). k Type -> Type
data A x = A
```

In your case, the kind `k` only has to have sort `Type` because it is being used as a parameter to `->`.

**Comment by hdgarrood** [comment]
Maybe it's best to avoid talking about "sorts" and we should just talk about types having kinds, because sorts are really just the kinds of kinds (which are really just types).

**Comment by JordanMartinez** [comment]
`forall k. k -> Type` and `forall (k :: Type). k -> Type` are the same.

Is `forall k. k Type -> Type` and `forall (k :: Type -> Type). k Type -> Type` the same? I assume not because in the former the kind of `k` could be `Type -> CustomKind` or `Type -> Type` whereas in the latter the kind of `k` must be `Type -> Type`. Is that right?

If so, I still see the `(k :: Type)` sort annotation (or kind signature for `k`) as being redundant. I wouldn't see the `(k :: Type -> Type)` as being redundant. This issue proposes dropping the first because it's "uninteresting" / redundant whereas keeping the latter because it actually matters.

**Comment by cyrilfretlink** [comment]
I think I understand what Harry said about the lack of warning on inferred polymorphism in the types of kinds.

Generating documentation for the following module:

```purescript
module Example where

data Example :: forall f k. f k -> Type
data Example a = Example

example = Example :: Example _
```

yields this type for `example`:

```purescript
example :: forall (t5 :: Type) (t6 :: t5 -> Type) (t7 :: t5) (t10 :: t6 t7). Example @t5 @t6 @t7 t10
```

but annotating `k`:

```diff
 module Example where

-data Example :: forall f k. f k -> Type
+data Example :: forall f (k :: Type). f k -> Type
 data Example a = Example

 example = Example :: Example _
```

yields:

```purescript
example :: forall (t4 :: Type -> Type) (t5 :: Type) (t8 :: t4 t5). Example @t4 @t5 t8
```

We can erase monomorphic kinds because types with inferred polymorphic kinds raise the MissingKindDeclaration warning but we cannot erase type annotations on kinds themselves because a kind without annotation might be polymorphic, and annotating it is the only way to monomorphize it.

**Comment by kl0tl** [comment]
I think I understand what Harry said about the lack of warning on inferred polymorphism in the types of kinds. Generating documentation from the following:

```purescript
module Example where

data Example :: forall f k. f k -> Type
data Example a = Example

example = Example :: Example _
```

yields this type for `example`:

```purescript
example :: forall (t5 :: Type) (t6 :: t5 -> Type) (t7 :: t5) (t10 :: t6 t7). Example @t5 @t6 @t7 t10
```

but annotating `k`:

```diff
 module Example where

-data Example :: forall f k. f k -> Type
+data Example :: forall f (k :: Type). f k -> Type
 data Example a = Example

 example = Example :: Example _
```

yields:

```purescript
example :: forall (t4 :: Type -> Type) (t5 :: Type) (t8 :: t4 t5). Example @t4 @t5 t8
```

We can erase monomorphic kinds because types with inferred polymorphic kinds raise the MissingKindDeclaration warning but we cannot erase type annotations on kinds themselves because a kind without annotation might be polymorphic, and annotating it is the only way to monomorphize it.

**Comment by hdgarrood** [comment]
> Is forall k. k Type -> Type and forall (k :: Type -> Type). k Type -> Type the same? I assume not because in the former the kind of k could be Type -> CustomKind or Type -> Type whereas in the latter the kind of k must be Type -> Type. Is that right?

No, they are still the same. If I write `forall k. k Type -> Type`, then we can infer that:
- `k` has to have kind `_ -> _`, because it is applied to something,
- the thing it is applied to is `Type`, and `Type :: Type`, so `k` has to have kind `Type -> _`,
- the result of `k Type` is the first argument to an arrow `->`, which means that `k` has to have kind `_ -> Type`

so putting all of these together we see that, whether the annotation was provided or not, `k` has to have the kind `Type -> Type`.

While these things are the same from the compiler's point of view with respect to type checking, that doesn't mean we should leave redundant information out of docs. The point of docs is to make it easy for people to understand things; often that means we should include redundant information. For example: it's technically possible to figure out what the kinds of all of the parameters to `HalogenM` are by inspecting the definition and/or the functions which make use of it, but that's annoying to do (and unnecessary) because the compiler can just tell us what they are.

**Comment by JordanMartinez** [comment]
Ok, then it sounds like we should not drop `(k :: Type)` sort annotations for explicit kind signatures. 

If so, then can this issue be closed?

**Comment by hdgarrood** [comment]
I’m still open to being persuaded otherwise, but yes, I think it can be closed for now.

**Comment by JordanMartinez** [comment]
Since kind signatures won't appear in Pursuit docs across most packages until a new breaking change is made, we don't have much feedback to go off of besides our own opinions/thoughts. So, how about we close this for the time being and reconsider after more time has passed (by opening a new issue)?

**Comment by kl0tl** [comment]
I think we can close this, and I don’t think we should reconsider:

+ `forall k. k -> Type` and `forall (k :: Type). k -> Type` are the same,
+ `forall f. f Type -> Type` and `forall (f :: Type -> Type). f Type -> Type` are the same, but
+ `forall f k. f k -> Type` and `forall f (k :: Type). f k -> Type` are not the same.

**Comment by JordanMartinez** [comment]
> `forall f k. f k -> Type` and `forall f (k :: Type). f k -> Type` are not the same.

Sounds good to me!

Closing.
