### ISSUE TITLE
Discord invite invalid?

### ISSUE THREAD

**Issue by pmiddend** [purescript/purescript#4203]
## Description

The Discord invite link in the README seems to be invalid.

**Comment by thomashoneyman** [comment]
I just tried it and it appears to be working for me; would you mind letting me know a little bit about your environment?\

1. Do you have Discord open in the browser, or on your desktop, or on your mobile device?
2. If so, do you have an existing account?
3. Either way, what exactly happens when you visit the https://www.purescript.org/chat link (the Discord invite link)?

**Comment by pmiddend** [comment]
Oh, very weird. Now it's working. I got a message literally saying the invite link is invalid.
