### ISSUE TITLE
Let Generalization

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#423]
In the Haskell version of `skolemEscapeCheck` we have an untyped definition like this in the `where`:
``` haskell
def s _ = (s, [])
```
and is used in `everythingWithContextOnValues [] [] (++) def go def def def`, but this fails in PureScript as the type is being inferred as something like:
``` haskell
def :: X -> Declaration -> (Tuple X Y)
```
Because that's the type for the first usage in `everythingWithContextOnValues`, but ideally we'd want:
``` haskell
def :: forall a. X -> a -> (Tuple X Y)
```
as it is also used for `Binder`, `CaseAlternative`, etc.

I assume this would happen when inferring a similar definition in a binding group too.

**Comment by paf31** [comment]
Now that we do constraint generalization, it's natural to ask whether we should do that as part of let generalization too. It's not obvious whether it's a good thing, because it results in more dictionary passing for cases where the type is only ever instantiated with a single type. But then, the dictionary hoisting which has been mentioned elsewhere should address that.

**Comment by paf31** [comment]
Closing, since evidence suggests this is more trouble than it's worth from a type system point of view.
