### ISSUE TITLE
Proposal: Remove the Browser REPL backend

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#4252]
## Summary

Remove support for the Browser REPL backend in 0.15.

## Motivation

The browser REPL backend currently relies on `purs bundle` to serve bundled code to the browser. `purs bundle` is slated to be removed in 0.15. Retaining support for the browser REPL entails reworking it's internals to serve unbundled code. Discussion with other contributors has lead me to believe this feature is essentially unknown, lacks maintainer interest, and is a roadblock for shipping a highly requested feature.

## Proposal

Remove the browser REPL backend code, and direct users to Try PureScript, which offers a much better experience for trying code. It also supports the full current package set and even supports things like Halogen and React bindings.

**Comment by JordanMartinez** [comment]
This proposal was opened only 3 days ago, which doesn't provide a lot of time for discussion or feedback. By fixing #4225 in #4255, I will also need to remove the browser backend from the REPL because removing `purs bundle` will necessarily break `purs repl --port 1234`. 

There's 11 likes on the opening thread and no other reactions, so I assume this is fine to do. However, please speak up if you feel otherwise.

**Comment by hdgarrood** [comment]
I’m a bit hesitant about this; the browser REPL backend feels like the sort of thing ES modules ought to make easier, not harder, and as far as I’m aware we haven’t raised this in places that more of the community are likely to see such as Discourse or Discord. Are people using the browser REPL backend? I’d argue Try PureScript isn’t much of a replacement because it’s much harder to load your own projects into there.

**Comment by natefaubion** [comment]
I don’t think I said it was harder. I mentioned it was a blocker, what needed change, and that there’s no maintainer interest in this feature.

**Comment by natefaubion** [comment]
Also note that you can get essentially the same behavior through any bundler with a dev server.

**Comment by hdgarrood** [comment]
You didn’t say it was harder, correct. I just think it might seem a bit odd from the point of view of a user for maintainers to say the browser REPL backend has been removed as a result of us moving from a module format that browsers don’t understand to one that browsers do.

If it is the case that either nobody knows about this feature so it’s not being used at all, or if there’s a perfectly acceptable substitute, then I’ll withdraw my objection. How can you get the same behaviour now with a dev server?

**Comment by natefaubion** [comment]
> If it is the case that nobody knows about this feature so it’s not being used at all

Could you clarify what would convince you that this is the case? AFAIK, this proposal has support from all the core team members.

**Comment by garyb** [comment]
I didn't even know there was a browser REPL until I saw this issue FWIW.

**Comment by natefaubion** [comment]
> If someone posted in Discourse about removing it and few or no people responded to say “yes I use this, please don’t remove it” I would consider that sufficient.

That's fair, I will cross post. FWIW, my experience is that the compiler repo garners far more responses than Discourse. I've noted this in the past wrt language proposals.

**Comment by natefaubion** [comment]
Crosspost: https://discourse.purescript.org/t/removing-the-browser-repl-backend/2938

**Comment by hdgarrood** [comment]
Thanks! Now that you mention it I do remember you saying that the compiler repo tends to get more interaction, I’d forgotten about that.
