### ISSUE TITLE
Wildcard is inferred for partial function

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4268]
## Description

See https://github.com/purescript/purescript-lists/pull/203#issuecomment-1067431674

## To Reproduce

```purescript
module Main where

import Prelude

data List a = Nil | Cons a (List a)

last :: forall a. Partial => List a -> a
last (Cons a Nil) = a
last (Cons _ xs) = last xs
```

Compiling the above produces this warning:
```
[1/1 WildcardInferredType] src/Main.purs:10:1

  10  last :: forall a. Partial => List a -> a
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Wildcard type definition has the inferred type
  
    a0
  
  in binding group last
  
  where a0 is a rigid type variable
          bound at (line 0, column 0 - line 0, column 0)
```

## Expected behavior

The warning should not be produced.

## PureScript version

This doesn't occur on `v0.14.5` but does on `v0.14.7`.

**Comment by rhendric** [comment]
Sure looks like it.

**Comment by JordanMartinez** [comment]
Looks like this warning was emitted in CI for that PR, too. See https://github.com/purescript/purescript/runs/4601156598?check_suite_focus=true#step:8:5016

However, we missed it because there's so many other warnings in the package set.

**Comment by rhendric** [comment]
@natefaubion, quick (?) question for you:

I'm looking at [this change](https://github.com/purescript/purescript/pull/3500/files#diff-face7661808c8804ee47e10a0fd05d5ffc7ddebbef1acccffb5463633e08ae7fR277) in #3500, and I notice that there isn't a corresponding censor in the `BindingGroupDeclaration` case. Is that intentional?

The regression I introduced seems to be prevented by the `censorUnnamedLocalWildcards` in the `ValueDecl` case, which is why out of the four `Partial` declarations in [`Data.List.Partial`](https://github.com/purescript/purescript-lists/blob/master/src/Data/List/Partial.purs), only the two recursive ones get the warning. I'm wondering if I should attempt to adapt `censorUnnamedLocalWildcards` to also work on binding groups or if I should take an entirely different approach.

**Comment by natefaubion** [comment]
I can't think of an obvious reason.

Does the approach of using typeWildcard mean that if you have a partial function, and did not provide a type signature, you would see the wildcard warning?

**Comment by rhendric** [comment]
Not in any cases I've tested; I'm under the impression that in general no warnings are ever emitted if any errors are.

**Comment by rhendric** [comment]
I'm having trouble wrapping my head around the rules of wildcard warnings. Could you look at [these examples](https://try.purescript.org/?gist=44f637ba0c1ca91f48506ca25a47dc9a) and tell me which of them ought to be issuing warnings? None of them involve `Partial`.

**Comment by natefaubion** [comment]
I think your expectations are correct. If there's a top-level signature, then there should be no wildcard warnings ever. If there _isn't_ a top-level signature, all bets are off. I don't remember the exact reason why that made sense at the time, but I'm sure I could be convinced it's nonsense.
