### ISSUE TITLE
`purs docs` crash IncorrectAnonymousArgument

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/purescript#4274]
## Description

```
purs: An internal error occurred during compilation: Failed to produce docs for Data.List.Types; details:
Error 1 of 2:

  at bower_components/purescript-lists/src/Data/List/Types.purs:111:17 - 111:18 (line 111, column 17 - line 111, column 18)

    An anonymous function argument appears in an invalid context.


  See https://github.com/purescript/documentation/blob/master/errors/IncorrectAnonymousArgument.md for more information,
  or to contribute content related to this error.

Error 2 of 2:

  at bower_components/purescript-lists/src/Data/List/Types.purs:263:16 - 263:17 (line 263, column 16 - line 263, column 17)

    An anonymous function argument appears in an invalid context.


  See https://github.com/purescript/documentation/blob/master/errors/IncorrectAnonymousArgument.md for more information,
  or to contribute content related to this error.


Please report this at https://github.com/purescript/purescript/issues
CallStack (from HasCallStack):
  error, called at src/Language/PureScript/Crash.hs:23:3 in purescript-cst-0.5.0.0-LBvXtFLJUAtErBtpMXcn5X:Language.PureScript.Crash
  internalError, called at src/Language/PureScript/Make.hs:127:29 in purescript-0.15.0-HWpzlVMP5sp7RvXZ32b1sR:Language.PureScript.Make
```

I'm not sure if this is a bug or part of the churn for v0.15. The __purescript-lists__ package has a v0.15 upgrade, so I think maybe this shouldn't be happening, and it's a bug? 

## To Reproduce

```
cd purescript-lists
bower install
purs docs "src/**/*.purs" "bower_components/*/src/**/*.purs"
```

## PureScript version

__purs__ version 0.15.0-alpha-02
__purescript-lists__ https://github.com/purescript/purescript-lists/tree/7498594b8a32aa2ab545a7bf67ed6746dcd4646c

**Comment by JordanMartinez** [comment]
The specific line for the first error is here: https://github.com/purescript/purescript-lists/blob/master/src/Data/List/Types.purs#L263=

Which has the following line:
```
<#> case _ of NonEmptyList (x :| xs) → foldl (flip nelCons) (pure x) xs
--       ^
```

Perhaps #4033 didn't propagate to docs?

**Comment by JordanMartinez** [comment]
Here's what I've found so far. 

First, this failure only occurs when a `case _ of` is used within an instance. For example, running `purs docs` works on `foldl'` but fails on `foldl` in the below smaller reproducible example:
```purs
module OperatorSection where

data List a = Nil | Cons a (List a)

infixr 6 Cons as :

class Foldable f where
  foldl :: forall a b. (b -> a -> b) -> b -> f a -> b

instance Foldable List where
  foldl f b = case _ of
    Nil -> b
    a : _as -> f b a

foldl' :: forall a b. (b -> a -> b) -> b -> List a -> b
foldl' f b = case _ of
  Nil -> b
  a : _as -> f b a
```

Second, the [AST's `desugar` pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Make.hs#L94=) refers to [the full pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar.hs#L69-L89=) whereas the [Doc `desugar` pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Docs/Convert.hs#L45=) only does a [partial pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Docs/Convert.hs#L254-L273=). There's a few important differences:
- The AST desguar pass [includes the `desugarObjectConstructors` pass](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar.hs#L71) whereas the Docs one [does not](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Docs/Convert.hs#L266-L267=)
- Similarly, the AST desugar pass calls [`rebracket`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar.hs#L78=), which is an alias for [`rebracketFiltered (const True)`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/Operators.hs#L75-L76=). The Docs pass calls [`rebracketFiltered isInstanceDecl`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Docs/Convert.hs#L273=). `rebracketFiltered` eventually calls [`rebracketModule`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/Operators.hs#L107=).

Third, #4033 changed where/when the compiler checks for whether an anonymous argument is used incorrectly (i.e. bad `_` usage) and fails if it used incorrectly. Before #4033, this check would not be run during the Docs desugar pass whereas now it is: #4033 moved that check from the [`desugarObjectConstructors` pass](https://github.com/purescript/purescript/pull/4033/files#diff-7b0784140ed46f56deb1225301820d35d26f53c0bbdf205949a73034c711f402L34-L43) into [`rebracketModule`](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/Operators.hs#L217-L229=)

I think the fix is to only run the [`isAnonymousArg` failure check](https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Sugar/Operators.hs#L219=) when the pass is from the `compile` caller and to ignore it when the pass is from the `docs` caller.
