### ISSUE TITLE
Variable names clashing across guard clauses

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript#4357]
## Description

This is a regression apparently introduced in #4293.

A case statement containing guard clauses with pattern guards which bind the same variable result in an error when building with 0.15.3 but not 1887bcf2ebb3f15f8410f1d353e344e42f7d3b9c (just before that PR was merged).

## To Reproduce

```purescript
data Foo = Foo Int | Bar Int

g :: Foo -> Int
g  =
  case _ of
    a
        | Bar z <- a
        -> z
        | Foo z <- a
        -> z
        | otherwise
        -> 42
```

Results in the following error:

```
Error found:
in module Main
at src/Main.purs:15:12 - 15:13 (line 15, column 12 - line 15, column 13)

  Value z is undefined.

while inferring the type of z
in value declaration g
```

After renaming the `z` in the 1st guard clause, the error disappears.

## Expected behavior

No error - as in previous compiler versions.

Variables bound in guard clauses are only in scope in the corresponding expression, and there is no conflict between different guard clauses. 

## PureScript version

0.15.3

**Comment by PureFunctor** [comment]
Good catch! From what I can tell this happens because of how guarded case alternatives are represented in the AST and as a consequence, how they're traversed.

What I think happens here is that the renamer isn't scope-aware; the first `z` binding gets overridden by the second guard before the renamer recurses into the first expression, hence the type-checker's inability to find it.

I'm on a break this week though, but I'll see what I can do today or tomorrow.

**Comment by JordanMartinez** [comment]
Looking at [this line](https://github.com/purescript/purescript/pull/4293/files#diff-21ed76a39c9c01daabfc33ac2cfb9625a9999ddf54bffd135e2173b2a2c8d375R309) in the PR, is this issue caused because we were previously using `[Ident]`, which would allow the same identifier to appear multiple times in the list, whereas now we use `Map Ident`, where the same identifier can overwrite a previous one?

**Comment by PureFunctor** [comment]
Sort of, but if it was an `[Ident]` or similar there's no way to disambiguate between which one to choose. For what it's worth, though, the scope-aware traversal that I had before 3d48d013764706284d0f494ee7e1b723d58b4603 handles this case just fine. I think a refactor of `renameInModule` would be fine to account for this bug. I also think it'd better accommodate #3897 in the future.

**Comment by JordanMartinez** [comment]
I did a trace of `updateGuard`:
```haskell
updateGuard :: [GuardedExpr] -> M.Map Ident SourcePos
updateGuard [] = M.empty
updateGuard (GuardedExpr g _ : xs) =
   (traceWith "updateGuard (left):" $ updateGuard xs `M.union` (traceWith "updateGuard (right):" $ rUnionMap updatePatGuard g)
```
which outputted:
```
updateGuard (right): fromList [(Ident "z",SourcePos {sourcePosLine = 13, sourcePosColumn = 11})]
updateGuard (right): fromList []
updateGuard (left): fromList []
updateGuard (left): fromList []
updateGuard (left): fromList [(Ident "z",SourcePos {sourcePosLine = 13, sourcePosColumn = 11})]
```
So, it's not that.

**Comment by rhendric** [comment]
`everywhereWithContextOnValuesM` needs to give `Guard`s their own handler. Without that, `updateGuard` has to collect all the identifiers in every `GuardedExpr` in that particular case into a single map, even though identifiers in different `GuardedExpr`s can collide.

This is an exacerbation of a pre-existing issue, where if you shadow a name that should be imported, the compiler loses sight of the import in adjacent guarded expressions:

```purs
import Data.Foldable (fold)
import Data.Maybe (Maybe(..))
import Data.Monoid.Additive (Additive(..))

test :: Maybe Int -> Int
test = case _ of
  m | Just fold <- m -> fold
    | otherwise -> case fold [Additive 0] of Additive x -> x  -- Value fold is undefined.
```
