### ISSUE TITLE
`freeTypeVariables` returns incorrectly ordered set of free variables?

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript#4368]
## Description

In https://github.com/purescript/purescript/blob/master/src/Language/PureScript/Types.hs#L514, the function `freeTypeVariables` is defined in a more step-by-step fashion below. Shouldn't `sortByKindLevelsOnly` be used rather than `sortByKindLevelsANDVarText`?:
```hs
-- | Collect all free type variables appearing in a type,
-- tracking kind levels so that variables appearing in kind annotations are listed first.
freeTypeVariables :: Type a -> [Text]
freeTypeVariables =
  -- This is what the code currently is...
  removeDuplicates . dropKindLevels . sortByKindLevelsANDVarText . getVarsWithKindLevels
  -- Isn't this what it should be?
  removeDuplicates . dropKindLevels . sortByKindLevelsOnly       . getVarsWithKindLevels
  where
  getVarsWithKindLevels :: Type a -> [(Int, Text)]
  getVarsWithKindLevels = go 0 []

  sortByKindLevelsANDVarText :: [(Int, Text)] -> [(Int, Text)]
  sortByKindLevelsANDVarText = sort

  sortByKindLevelsOnly :: [(Int, Text)] -> [(Int, Text)]
  sortByKindLevelsOnly = sortBy fst

  dropKindLevels :: [(Int, Text)] -> [Text]
  dropKindLevels = fmap snd

  removeDuplicates :: [Text] -> [Text]
  removeDuplicates = ordNub

  go :: Int -> [Text] -> Type a -> [(Int, Text)]
  go lvl bound (TypeVar _ v) | v `notElem` bound = [(lvl, v)]
  go lvl bound (TypeApp _ t1 t2) = go lvl bound t1 ++ go lvl bound t2
  go lvl bound (KindApp _ t1 t2) = go lvl bound t1 ++ go (lvl - 1) bound t2
  go lvl bound (ForAll _ v mbK t _) = foldMap (go (lvl - 1) bound) mbK ++ go lvl (v : bound) t
  go lvl bound (ConstrainedType _ c t) = foldMap (go (lvl - 1) bound) (constraintKindArgs c) ++ foldMap (go lvl bound) (constraintArgs c) ++ go lvl bound t
  go lvl bound (RCons _ _ t r) = go lvl bound t ++ go lvl bound r
  go lvl bound (KindedType _ t k) = go lvl bound t ++ go (lvl - 1) bound k
  go lvl bound (BinaryNoParensType _ t1 t2 t3) = go lvl bound t1 ++ go lvl bound t2 ++ go lvl bound t3
  go lvl bound (ParensInType _ t) = go lvl bound t
  go _ _ _ = []
```

I'm not sure what implications this change would have, nor what bugs it might also fix.

## PureScript version

0.15.4

**Comment by JordanMartinez** [comment]
Doing a search for [`freeTypeVariables` in this repo](https://github.com/purescript/purescript/search?q=freeTypeVariables), all usages except for one are doing a membership test. [`checkMemberIsUsable`](https://github.com/purescript/purescript/blob/acc5ad0e02538c20f53bf4f08e84842771a67705/src/Language/PureScript/TypeChecker.hs#L195-L205) seems to be the only one that is doing a bit more than that. However, the logic there does not depend on the order of the value returned by `freeTypeVariables`.

So, AFAICT, there is a potential for a bug here, but it's not currently being used in such a way so as to cause a real bug.

**Comment by rhendric** [comment]
Why is there a ‘should’ here in either direction, as long as the invariant described in the comment holds?

**Comment by MonoidMusician** [comment]
Semantically speaking, the names should not matter so we shouldn’t be sorting on them. Also if there’s some existing order it’s usually nicer to preserve that, even if it doesn’t affect typechecking.

**Comment by MonoidMusician** [comment]
It took me a bit to identify where exactly it comes up, but I have done so.

There's one usage of `freeTypeVariables` that Jordan didn't mention above (probably since GH search truncates to two results per file!): in [`quantify`](https://github.com/purescript/purescript/blob/94343bc4613a0cbf8507943809fa2d49b81bb0bf/src/Language/PureScript/Types.hs#L539).

This function quantifies a type by adding quantifiers for types not already quantified. Of course it needs to do it in the right kind-level order (to get dependencies right), but it would also be nice to preserve the order that variables appear.

In fact it might also be important to preserve the order with [Visible type applications](#4235). I haven't checked thoroughly enough to know …

It's basically only used with typeclass stuff in this one file: https://github.com/purescript/purescript/blob/78786130e3c595b3084d57e0b46581477d741cfb/src/Language/PureScript/Sugar/TypeClasses.hs#L307
(And with reexports in a different file.)

Here's a two-parameter class where its variables are used in reverse alphabetical order (in both the class declaration and the member type):
```purescript
class Reflectable :: forall k. k -> Type -> Constraint
class Reflectable v t | v -> t where
  reflectType :: Proxy v -> t
```

And sure enough, if you query for the type of it in the REPL you see the variables swapped:
```purescript
> import Data.Reflectable
> :t reflectType
forall (t71 :: Type) (t :: Type) (v :: t71). Reflectable @t71 v t => Proxy @t71 v -> t
```

And with Jordan's PR it's as I would expect:
```purescript
> import Data.Reflectable
> :t reflectType
forall (t71 :: Type) (v :: t71) (t :: Type). Reflectable @t71 v t => Proxy @t71 v -> t
```

**Comment by JordanMartinez** [comment]
Hey, good catch!
