### ISSUE TITLE
`npm install purescript@0.15.8` on Linux gets a 404

### ISSUE THREAD

**Issue by eikooc** [purescript/purescript#4447]
## Description

I get a 404 when trying to run `npm install purescript`

## To Reproduce

Run `npm install purescript`

## Expected behavior

That it finds the latest version

## Additional context

I think it is because NPM points to `0.15.8-0` as the latest which has no binary. It should probably point to `0.15.8`

**Comment by JordanMartinez** [comment]
This is a temporary issue. I accidentally published the update to the NPM package before the Linux binary finished building. Mac and Windows binaries will install fine.

The binary is built in CI, but it got an [`ECONNRESET` issue initially](https://github.com/purescript/purescript/actions/runs/4342828583/jobs/7584118063#step:15:13). I restarted it, but it failed due to the [`linx64.sha` already existing](https://github.com/purescript/purescript/actions/runs/4342828583/jobs/7584899179#step:15:12). I removed that file and restarted it. Hopefully, this next CI run (should finish in 30 min or so) will build and upload the binary to the release page. `npm install` should work after that.

**Comment by eikooc** [comment]
Thanks for the quick reply @JordanMartinez :clap:. We'll just leave this open until the CI finishes if anyone else stumbles upon this :+1:

**Comment by JordanMartinez** [comment]
Binaries have been built. I can install it now.

**Comment by JordanMartinez** [comment]
FWIW, this is why it's generally better to wait until the Discourse announcement is made before updating PureScript. Sometimes, we run into issues like this. So, we delay the announcement until such issues are resolved.
