### ISSUE TITLE
Remove CoreFn "closed record update" optimization

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript#4473]
## Summary

Remove (or defer to JS codegen) the "closed record update" optimization, which turns a record update over a closed record type into a record literal.

## Motivation

Both the `es` and `erl` backends have no need for this optimization. This optimization mainly exists for the purpose of the existing `js` backend, which generates a for/in loop with `hasOwnProperty` checks at each update. The optimization can be a big performance win in that case. However, in the `es` backend, we just use object spread syntax for updates, which essentially has no performance impact and results in less code. Additionally, there was a user in the `#compiler` channel on the PS discord that noted this optimization resulted in a significant code size increase for the project (20-25%, though I'm not aware of the specifics). It's not obvious to me that this is in fact an optimization at all for any backends other than the existing JS backend.

## Proposal

I think we should remove this optimization from the CoreFn pipeline and defer it to JS codegen for now. This optimization relies on type information, however, which is unsupported in the CoreFn JSON interface, so this will only be available when going through the built-in code generation pipeline.

Alternatives could be:
* Add an annotation to CoreFn that identifies these concrete updates with their known field names (in lieu of typed CoreFn) thus making this optimization available to all backends if it's advantageous.
* Add an annotation on record literals that shows it was derived from an update so that backends could "undo" the transformation.

**Comment by nwolverson** [comment]
More than not having a need for the optimisation, for `purerl` this has a negative outcome, as there is in fact a native update operation on maps (the representation chosen for records). I previously attempted to reverse this transformation but as it turns out, it is not possible to determine what is a record update operation after deserialising CoreFN from JSON (https://github.com/purerl/purerl/issues/19).

I would be in support of initially moving the optimisation in the compiler downstream past the point where CoreFN JSON is emitted; longer-term it may be an idea to annotate CoreFn such that a backend could perform similar transformations. It seems that for this transformation to be advantageous it probably is tied to the particular object size - I think I recall discussion before of having a cut-off - which would anyway seem to be a backend-specific decision.

**Comment by rhendric** [comment]
Sounds good to defer it—I agree it seems like it should be a backend detail—and I'm strongly in favor of doing it by modifying the CoreFn `ObjectUpdate` constructor to contain a `Maybe [PSString]` of known fields to preserve in the update. (So either you have `ObjectUpdate ... Nothing ...`, which must be a dynamic update, or you have `ObjectUpdate ... (Just [keep]) [(change, newVal)]`, which could compile to `{ keep: x.keep, change: newVal }` or `{ ...x, change: newVal }` at the backend's discretion.)

I'll also note that this is, to my knowledge, the one and only use of type information in CoreFn annotations, so in doing this refactoring we could drop the type member from the `Ann` tuple.

**Comment by avi892nash** [comment]
I made a PR with minimal changes to move the optimization at JS CodeGen level. But, @rhendric is suggesting a good approach. I am not sure I can do those changes (New to compiler`s code). So, If anyone else want to work on this, they can take it, It will be helpful for me also.
