### ISSUE TITLE
Syntactic support for specifying FFI dependencies

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript#616]
I've found it is not convenient to follow good FFI practices. Say I have this simple function:

```hs
foreign import f """
  function f(x) {
    return x == null ? Nothing : Just(x);
  }
  """ :: forall a. a -> Maybe a
```

We're aware at this point that `Nothing` and `Just` cannot be relied upon, so must be passed in. So we arrive at

```hs
foreign import fP """
  function fP(Nothing) {
    return function(Just) {
      return function f(x) {
        return x == null ? Nothing : Just(x);
      };
    };
  }
  """ :: forall a. Maybe a -> (a -> Maybe a) -> a -> Maybe a

f = fP Nothing Just
```

But now we can't rely upon implicit exports and must explicitly export every other entity in the module (see #460). And `f` should really be using `runFn2` here for efficiency. I propose we add a syntactic form that encapsulates this pattern in its most idiomatic form. Something like this:

```hs
foreign import f """
  function f(Nothing, Just) {
    return function(x) {
      return x == null ? Nothing : Just(x);
    };
  }
  """ Nothing Just :: forall a. a -> Maybe a
```

`Nothing` and `Just` can be arbitrary values in the above example. For instance, we could pass in a curried function of 2 arguments in its uncurried form using `mkFn2`:

```hs
p a b = true

foreign import f """
  function f(Nothing, Just, p) {
    return function(x) {
      return function(y) {
        return p(x, y) ? Nothing : Just(x);
      };
    };
  }
  """ Nothing Just (mkFn2 p) :: forall a b. a -> b -> Maybe a
```

**Comment by hdgarrood** [comment]
I think @joneshf is absolutely right that the correct answer is to create types that accurately describe the real types of things, so that all you need to write in the FFI files in most cases is `exports.whatever = whatever`. The more we can move into PureScript, the more we can leverage the type checker.

[purescript-nullable](https://github.com/paf31/purescript-nullable) was created since this issue was raised, and I think it's the best solution to the original problem. Yes, someone still has to create libraries like `nullable`, and it's still a bit awkward for creators of those libraries. But such libraries only need to be created once, and then everyone else can benefit from them. And hopefully we only need a few.

In a similar vein, I've just created [purescript-eff-functions](https://pursuit.purescript.org/packages/purescript-eff-functions/0.1.1/docs/Data.Function.Eff) to solve another related issue: being unable to give a PureScript type to standard effectful javascript functions (because they're usually curried and don't have the `Eff` thing with the nullary function).

**Comment by paf31** [comment]
Closing since this is out-of-date, and partially solved by some libraries.
