### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#703]
Let's make a list of bad error messages and try to systematically improve them.

Generally, I think good error messages should be goal of the project, and it's something which I've neglected so far. Hugs would be a good reference.

**Comment by rtrvrtg** [comment]
Not sure if this is the right place for it, but:

`Cannot unify * with # !.`

I know that this is a conflict between a foreign data type and a foreign data type with side effects, but the line number indicated places the error on a type signature. There's very little information on which sections of the type signature are conflicting, and no comparison of the data types involved that might help resolve it.

**Comment by michaelficarra** [comment]
That's because the kinds do not match, not types. Anyone who has had a cursory overview of the [language guide on kinds](https://github.com/purescript/purescript/wiki/Language-Guide:-Kinds) would recognise these symbols. Did the error point to the erroneous signature? If so, I'd say that's a pretty good error: you have used a type (or type variable) in a position where a row of effects is expected (probably the first parameter of Eff).

**Comment by garyb** [comment]
We could still clarify that message by specifically saying it's a kind unification error specifically, and printing the types involved perhaps.

**Comment by paf31** [comment]
I've been working on #745, and since there are a lot of problems reported here, I've come up with the following plan: the new ADT for errors will provide a way to associate a wiki link with each error, which will be displayed alongside the existing error message. The user will be encouraged to look at the wiki for more information, or to add information if it is missing. This way we can distribute the work of improving the error messages, by dispersing info from e.g. IRC chats.

**Comment by garyb** [comment]
I like it :+1:

**Comment by joneshf** [comment]
Great stuff!

**Comment by paf31** [comment]
When #906 is merged, I'll close this and split out those errors that can't be addressed on the wiki.
