### ISSUE TITLE
Run test-everything and core-tests during travis builds

### ISSUE THREAD

**Issue by garyb** [purescript/purescript#737]

**Comment by paf31** [comment]
For the resolutions, one thing which works is to set all the versions in `bower.json` to `latest`, and then run update with `-F`. The problem is that we can't guarantee that the latest versions of non-core libraries all work with the latest versions of the core libraries, even though any core libraries should work together.

Maybe for now we can just build the core libraries. We don't even need `test-everything` to do it - we can just run one big `bower install` command.
