### ISSUE TITLE
Question marks in variable names

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#751]
Super minor thing. But I'd like the ability to have the `?` as a symbol that can be in variable names. Naming booleans as `ready?` vs `isReady` the former is my preference, if there is a way to make this possible it would be coooool...

**Comment by jasonkuhrt** [comment]
I recently had a discussion about this feature in Haskell IRC with a lot of enthusiasm for it. The barriers to entry in Haskell for it are obvious (too much code would break) but I can't understand why something so helpful would be rejected in a greenfield context. I guess what's obvious to one person is obscure to another.

I would take allowed `?` character in ident suffix position over `<$>` `<*>` etc. and any other fancy idents a hundred times over. This thread has discussion at length over operator UX https://github.com/purescript/purescript/issues/806 yet herein this issue is a tractable win for everyone (and even moreso camelCase convention communities where the ability to avoid isFoo capital adds another benefit).

Boolean-returning functions are used in programming a lot and they play a fundamental role in just about any program you can write I think. Optimizing for them is actually a significant language feature.

**Comment by puffnfresh** [comment]
```purescript
import Prelude
import Data.List

(?) = ($)

uno = id? 1

isSorted :: forall a. (Ord a) => List a -> Boolean
isSorted xs = sort xs == xs

haha = isSorted? (1 : 2 : 3 : Nil)
```

**Comment by garyb** [comment]
> `(?) = ($)`

:+1: :smile:

**Comment by jasonkuhrt** [comment]
Cute.

But fails to facilitate better library APIs and such. Design is not the consumers job.

**Comment by Fresheyeball** [comment]
Ok, this may be time for a mini-rant. @jasonkuhrt you are right, and PureScript in general does not seem to be interested in design. Or rather, PS community seems to be only interested in design in a singular regard, and its types. The **typeclass structures are angelic**, and fancier and fancier types are on the way. But I've yet to see any clear or careful reasoning on why, what, or how language features are selected or moved over from other fp languages. Look at the piece of code @puffnfresh wrote, beyond being dismissive, it contains numerous other barriers to entry and reasoning from a design perspective.

```haskell
import Prelude (($))
import Data.List (sort, (::))

(?) = ($)

uno = id ? 1

isSorted : Ord a => List a -> Boolean
isSorted xs = sort xs == xs

haha = isSorted ? (1 :: 2 :: 3 :: Nil)
```

- `import` imports exposing everything **by default**
- `:` is cons instead of typeof, regardless of usage frequency
- infix operators are allowed without whitespace
- `forall` is required for all top level declarations

ect. Facilitating better api design, lowering barriers to entry, good ecosystem UX, and pragmatically deciding what features are **needed** for productivity vs **desirable** from a type theory perspective seem to be off the radar. PureScript has many nice things that I love, but this mentality is not one of them.

**Comment by jasonkuhrt** [comment]
Yep. This mentality is why Elm is the front runner for a lot of people coming from JavaScript despite PureScript being ostensibly the superior technical project in many (most?) ways.

I've noticed this "problem" before. I felt it in the discussion about packaging a while back. It's definitely an issue for adoption of PS in my eyes. Elm will get better and being specialized for apps with a design oriented philosophy be a top pick there. Haskell will get better with ghcjs and and build/workflow. It will leave little reason to use PS. Maybe getting popular isn't he goal like Simon said years

**Comment by jasonkuhrt** [comment]
... ago about Haskell. I respect that every community and core members have necessarily different priorities, tastes, and so on, of course. I'm still groking what PS is concerned about which doesn't help orient my input so sorry if it is out of scope.

**Comment by paf31** [comment]
The "avoid (success at all costs)" mentality resonates with me. I can't speak for all contributors, but I'm not trying to build a language for mainstream adoption by JS devs. I'm always happy when JS devs come to PS, but there is a trade-off between language appeal and being able to add the advanced features you want. I'm just trying to build the language I want to use.

To answer points specifically:

> import imports exposing everything by default

Yes, this is unfortunate, we're working on it. It might turn into a warning with an option to elaborate to a minimal set of imports.

> : is cons instead of typeof, regardless of usage frequency

I see this as a matter of taste for the most part. Maybe it would be good to change it if we had a do-over, but this would break literally every piece of code we have. Not worth it in my opinion.

> infix operators are allowed without whitespace

Again, a matter of taste. I don't personally use operators without space, but in some case, it can be useful.

> forall is required for all top level declarations

I still think this is the best option in the presence of scoped type variables.

> $ vs # idioms that do not express directionality

Yes, this is handy for Haskellers, not so much for JS developers. But something like `purescript-preface` is the solution possibly, since users can always define their own operator aliases.

> Question marks in variable names

`?` is not a valid character in JS identifiers, so this directly contradicts one of the original design goals: clean generated JS. Now, you might say "but you allow tick characters", and yes, those need to go too, in my opinion.

**Comment by Fresheyeball** [comment]
> The "avoid (success at all costs)" mentality resonates with me.

The sentiment is literally a synonym for "I wish to fail". It usually means 'I want to do a good job, and succeeding in some other sense is not important'. The problem is its a false dichotomy, if you do a good job on all fronts, success can be a side effect (while not being the goal). There is no need to deliberately avoid success, to have quality. 

The concerns raised are not a matter of appeal or subjective. These are design *principles* not tastes. Ensuring that more common cases are catered to over less common cases, (like `:` vs `::` being type of vs cons, or demanding explicit `forall`) fall into the 80:20 rule, which has measurable impact on usability. Infix operators with whitespace vs allowing special characters in variable names should be informed by **gestalt principles** of symmetry and proximity. `$` and `#` are not more handy than `<|` and `|>`, they are more *familiar* for haskell developers, which is legitimate, as a secondary concern. `|>` is objectively more understandable than `#` as even most haskellers are unfamiliar with `#` as a symbol. Putting it on consumers of the language to alias less usable operator symbols to more usable operator symbols, in the name of familiarity, is bad design. 

PureScript developers doing it in libraries is cool, but it does also mean that the understandability of PureScript is potentially damaged, as looking at any given project the symbols can have different meanings. This is a legitimate usability concern for anyone who wants to use the language in a serious way. Consistency is a better for reasoning and reading code, and a system that promotes inconsistent code throughout the ecosystem, ostensibly because of design decisions made in the standard libs is not a good thing.

Point is, its not about popularity for popularity's sake, or about being appealing to JS developers or anyone else. Its about ignoring design principles, and the usability of the system. 

As for a strong argument for `?` its been made, `?` can help facilitate better APIs through design. Perhaps its not a strong enough argument, or maybe its just an argument from a perspective you don't accept.

**Comment by paf31** [comment]
> The sentiment is literally a synonym for "I wish to fail". 

No, it's the opposite. First of all, if this isn't clear, it is avoid (success at all costs), not (avoid success) at all costs. In my case, I want to avoid success at the cost of compromising on the core principles of the project - in this case, clean codegen and minimalism.

> PureScript developers doing it in libraries is cool, but it does also mean that the understandability of PureScript is potentially damaged

Actually, it's crucial if you believe minimalism is important in a language. Let's be clear - PureScript the language is independent from PureScript's core libraries. Complaints about things like `$` should be directed at the core library repositories, but extracting the core libraries allows users to redefine their Prelude as they see fit.

> Point is, its not about popularity for popularity's sake, or about being appealing to JS developers or anyone else. Its about ignoring design principles, and the usability of the system.

Please don't confuse "ignoring design principles" with ignoring the specific set of design principles you might have in mind. Every decision in the compiler has been carefully considered.

Of course, the compiler and core libraries _are_ open source, and could be forked if someone felt motivated to redesign with a different set of principles in mind.

> ? can help facilitate better APIs through design

The claim is that `isSorted?` is better than `isSorted` because it looks like a predicate. My claim is that the type of `isSorted` is `forall a. (Ord a) => [a] -> Bool`, which also looks like a predicate. The price you pay is ambiguous syntax and ugly JS identifiers.

**Comment by garyb** [comment]
I think the suggestion is it means you don't need the `is` at all: `sorted?`, and would also be usable for things like `eq?`. It's nice in Scheme, but I can't say it's something I've particularly missed in Haskell or PureScript, primarily for this reason: your public API shouldn't be using booleans anyway, and with lightweight ADTs there is no excuse to do so.

**Comment by Fresheyeball** [comment]
I don't missing `?` in PureScript, and I accept the counter argument based on ambiguity as valid. I simply disagree with mentality behind it. There is nothing that does not come with a price, and while I know that every decision has been carefully considered, design principles are being ignored (not all principles many are respected). 

I've spent most of my career studying how human beings develop understanding and use systems, and my mentality is based on research into these areas. Its tradeoffs all the way down. 

Some of the things that bother me in PureScript are a matter of taste (not many), some are differences of philosophy (I don't find it reasonable to expect more than one code ecosystem to spring from one compiler just because its *possible* to have competing different standard lib, for example), but most are objective violations of usability principles. Maybe I should take the time to split my concerns into chunks and levy them at the specific part of the system where that concern is valid. 

But I'd rather have a conversation.  One from the wide angle perspective. The design decisions made in PureScript are all reasonable isolated to their problem space, its the wider picture of teams human beings working on distributed projects, forming a broad ecosystem of code that is where I get concerned.

**Comment by jasonkuhrt** [comment]
Thanks for everyone sharing there thoughts on an old issue. There is a transparency here that I didn't see communicated on the official website etc. which I am glad to have seen. I now know that the approach of PS is actually very much distinct (opposed even) to Elm. For me j now can make an informed choice about which community I personally want to invest in if any ever. PS is an awesome project and I still look forward to watching to evolve! Cheers.

**Comment by paf31** [comment]
@Fresheyeball Splitting out the core libraries is not just about minimalism for its own sake. It's actually useful. I have put code into production which makes use of a specialized Prelude. Sometimes you don't want to import a whole bunch of standard libraries just to write a few data types and combinators for example.

Also, which design principles do you think are being ignored?

**Comment by garyb** [comment]
@Fresheyeball it would be good if you did open specific issues about those things, as like the list you enumerated earlier, most of the points potentially warrant further discussion or explanation but in these kind of freeform discussion lots of threads are left open ended (you brought `forall` back in, for example, after Phil tried to explain the rationale for keeping it).

Regarding the wider point about PureScript's supposed lack of design or UX hostility - I'd like to point out that **we're not at 1.0 yet**. There is indeed much work to be done, having a solid foundation is currently a higher priority than maximising convenience. Spending a lot of energy on the type system and related features at this stage of the project seems like obviously the right thing to do, since essentially that's why it exists at all.

I write PureScript full time, believe me, I know there are usability issues, I just don't think they're all necessarily the most important things to address when I work on the compiler right now. Bugs are the current priority, I'd argue that things not breaking is a pretty big win for usability over, say, the ability to omit `forall` sometimes.

**Comment by andyarvanitis** [comment]
While very true that PS at not at 1.0 yet, it's probably good that @Fresheyeball and others bring up usability issues as early as possible -- some things will be very difficult to change later, due to too much breakage of existing code. Indeed, we're probably already there with a lot of things.

**Comment by jdegoes** [comment]
> These are design principles not tastes. Ensuring that more common cases are catered to over less common cases, (like : vs :: being type of vs cons, or demanding explicit forall) fall into the 80:20 rule, which has measurable impact on usability. 

These are all very subjective. Case in point:

1. Omitting `forall` actually obfuscates code, because it treats type parameters as being totally and incompletely inferred by the compiler, which makes it harder to reason about; and you cannot omit them in the general case, because the location of the `forall` dictates the semantics of the function, so at best you can make the language inconsistent (and thus harder to predict and reason about) by introducing rules to magically insert them at arbitrary places.
2. Favoring `:` over `::` is not an improvement in usability, unless you consider minimizing keystrokes to maximize usability — which I consider false in general. Programmers spend about 1% of time writing code, and 99% reading it and reasoning about it, so extra characters here and there have unmeasurable impact on productivity. Beyond that, `::` is used for type annotations in Haskell, arguably the most successful functional programming language of all time, so `::` is almost an affordance for type annotations at this point; that is, breaking with that established pattern could be considered hostile to the community that PureScript targets.

I say these things not to pick a fight, I'm actually quite unconcerned about them, only to emphasize that *what you find as most usable* does not have an objective basis. Some things you favor would make the language easier for you to understand and / or use, but might introduce inconsistencies and magic that would make it harder for someone with no prior programming experience to pick up. In programming language design, there is no linear scale between "unusable" and "usable", rather there are may dimensions that have complex effects on usability with different audiences.

Ultimately, I believe that a very few things will affect PureScript's success:

1. **The community.** Do they go out of their way to welcome new people and help them learn what is necessary? Are they friendly? What is the attitude toward people who don't come from FP or the front-end but still want to learn PureScript? Etc.
2. **Documentation.** Both standalone, and the kind you get from the compiler in response to error and warning states. It must be very easy for people to learn whatever they need to become productive PureScript programmers, solving complex real-world scenarios without having to first master the language or functional programming.
3. **Killer libraries and / or use cases.** If PureScript is a good language for front-end design, it must have use cases that offer compelling alternatives to the Javascript status quo.
4. **Simple, unsurprising, consistent design.** Community-driven programming languages can sometimes acquire numerous surprising, complex, and inconsistent features that appeal to particular niches (usually of advanced skill level), but these are all detrimental to the long-term success of the language. Simple, unsurprising, and consistent design — *even one with a higher learning curve for programmers coming from certain backgrounds* — will always have more staying power than the converse.

In particular, the names of operators, the names of type classes, the number of characters that programmers have to type, whether or not question marks are allowed in identifier names, and *infinite many other concerns* will have no affect on success of the language. Not because such things have *no effect* on individuals, but because the amount of impact they can have relative to the above considerations is vanishingly small (`O(1)` versus `O(n)`).

That's just my opinion, of course. I think for a pre-1.0 language, PureScript is doing quite well, but we do have more work to do on all the above concerns.

**Comment by robotlolita** [comment]
> * infix operators are allowed without whitespace

This is a somewhat unfortunate decision, because [it leads to some awkward ambiguities](https://medium.com/cool-code-pal/the-hassle-of-haskell-a74862541dfb). It's not as bad in PureScript because, while there's some amount of special syntax, we don't have arbitrary post-fix/prefix/mixfix operators, and it can be solved somewhat by better error messages (being ambiguous for humans is cool if you can guide them to writing the correct code without getting them even more frustrated).

```purs
1+-5
-- "Unknown value (+-)

-- Could've been:
-- In `1+-5`, `+-` is not a known operator.
-- (since `+` is in scope, and `-5` is valid:)
-- Maybe you meant `1 + -5`. Note that PS considers any sequence
-- of symbols not separated by whitespace a single operator.
```

But while requiring whitespace would get rid of that problem, it would also (possibly) break existing code. And the benefits aren't that great, since it can be solved by better error messages (which I'd argue would have a much larger impact in PS's adoption). From a cost/benefit perspective, this change doesn't make much sense at this point.

Adding arbitrary postfix operators would make the problem worse, and also break existing code. I don't think the difference between `isSorted` and `sorted?` is that significant for PureScript to make this tradeoff. Also, imho, `isSorted a` reads better than `sorted? a`.

Furthermore, @garyb's point:

> It's nice in Scheme, but I can't say it's something I've particularly missed in Haskell or PureScript, primarily for this reason: your public API shouldn't be using booleans anyway, and with lightweight ADTs there is no excuse to do so.

Is pretty important. Booleans aren't something we should be encouraging people to use, because we lose [data coherence](https://www.youtube.com/watch?v=gVXt1RG_yN0), and PureScript, unlike Flow/TypedRacket/Core.Typed/etc, does not support occurrence typing, which means we can't really *reason* about control flow branching over predicates in the type system. However, ADTs do allow us to constraint the branches in ways that are provably correct, which is a clear win considering the type system, and aligns better with PureScript's goals.

Perhaps we need to guide people better to design better libraries by using good data structures. Though this one is a documentation/community problem.

**Comment by Fresheyeball** [comment]
Ok, so ranting here turned out to spawn way more productive and interesting conversation than I anticipated. If there is a willingness to break code before 1.0 and address usability concerns from a design perspective; than I will break my concerns up into smaller units. Personally, I'd like to see PS dominate. Right now Elm is giving me the things I *need* but nothing I *want*, while PS is just the opposite. *frustration reigns.
