### ISSUE TITLE
Implicit forall

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#766]
requesting that both syntaxes be supported (at least for top level declarations)

```
foo :: forall a e. a -> e
foo :: a -> e
```

**Comment by paf31** [comment]
This is another one which is discussed frequently enough that I think it merits immortality on the Discussion list.

Please cast your :+1: s and :+1: s below.

:-1: from me. My reason is that in the presence of rank N types and scoped type variables, I think it becomes very important to name type variables. Even when you're in the rank 1 case, it doesn't hurt, doesn't take long, and becomes a form of documentation.

**Comment by puffnfresh** [comment]
:+1:

Because convenience and consistency.

**Comment by phadej** [comment]
I'd support unicode `∀ a e. a -> e` or even `∀ a e. a → e`, then it will be as short as value-level abstraction ( `\x y -> x :: y`).

**Comment by jdegoes** [comment]
:-1: Due to ambiguity, `forall` will always be required; you can "infer" what the user wants in only common cases. Therefore, for consistency, I think it should always be required.

But, a big :+1: for unicode ∀. :smile:

**Comment by joneshf** [comment]
Why is `forall` only required in function type signatures and foreign type signatures?
It isn't required in data type definitions.
It isn't required in newtype definitions.
It isn't required in type aliases definitions.
It isn't required in typeclass definitions.
It isn't required in instance definitions.

How does haskell get away with not requiring it?

If you use ghc and turn on `RankNTypes` can't you still write stuff like:

```haskell
id :: a -> a
```

> Even when you're in the rank 1 case, it doesn't hurt, doesn't take long, and becomes a form of documentation.

Similar things have been said about java :wink:

**Comment by garyb** [comment]
It's `ScopedTypeVariables` more than `RankNTypes` that makes the requirement more solid - scoped type vars only apply in Haskell if you use the `forall`.

I'm abstaining from voting on this one because I really don't mind either way. I'll probably keep writing `forall` out of habit, as that happens when I write Haskell now too :laughing:

**Comment by natefaubion** [comment]
> It isn't required in data type definitions.
> It isn't required in newtype definitions.
> It isn't required in type aliases definitions.

I think because these aren't type signatures. They are more analogous to function declarations for types. They are declared by being on the lhs of the `=`. Classes/Instances are inconsistent, though.

**Comment by joneshf** [comment]
> I'm abstaining from voting on this one because I really don't mind either way.

I feel similarly. I wasn't intending to support one way or the other, though I can see how it might look like it.

**Comment by phadej** [comment]
Yes. The `ScopedTypeVariables` and `RankNTypes` makes story complicated. E.g.

```hs
id :: a -> a
id = f <<< g
  where f :: a -> a
             f x = x
             g :: b -> b
             g x = x
```

Now where we should add that implicit `forall`? Everywhere, only at top-level? IMHO the implicitness will just add confusion here.

What's about:

```hs
id :: a -> a
id = f f
  where f :: a -> a
             f x = x
```

That is valid Haskell, and compiles (because of let-generalisation).

**Comment by paf31** [comment]
One could argue that instances and classes are not inconsistent, because they neither bind type variables, nor are they rank n > 1.

**Comment by natefaubion** [comment]
> One could argue that instances and classes are not inconsistent, because they neither bind type variables, nor are they rank n > 1.

I think they "feel" inconsistent. Partially because of the syntax `identifier :: Typeclass`. It feels as though you are writing a type signature, and you are creating variables out of nothing.

**Comment by phadej** [comment]
> One could argue that instances and classes are not inconsistent, because they neither bind type variables, nor are they rank n > 1.

True, one could write
``` purescript
instance listMonoid :: forall a. Monoid (List a)
``` 

Classes on other hand are ~ type declarations
```hs
class (Eq a) <= Ord a where
  compare :: a -> a -> Ordering
```
is about as writing
```hs
data Ord a = Ord
  { ordEq :: Eq a
  , compare :: a -> a -> Ordering
  }
```

**Comment by garyb** [comment]
@phadej agreed

**Comment by joneshf** [comment]
> Now where we should add that implicit forall? Everywhere, only at top-level? IMHO the implicitness will just add confusion here.

Can you explain this part?

**Comment by garyb** [comment]
I think the question is which of these should it desugar to without an explicit `forall`:

``` purescript
id :: forall a. a -> a
id = f <<< g
  where
    f :: forall a. a -> a
    f x = x
    g :: forall b. b -> b
    g x = x
```

vs

``` purescript
id :: forall a. a -> a
id = f <<< g
  where
    f :: a -> a
    f x = x
    g :: forall b. b -> b
    g x = x
```

**Comment by phadej** [comment]
@garyb The second one is IMHO confusing. What's about:
 ```hs
id :: a -> a -> 
id = f <<< g <<< h
  where
    f :: a -> a
    f x = x
    g :: b -> b
    g x = x
    h :: b -> b
    h x = x
```

**Comment by paf31** [comment]
Surely it has to desugar to the second one though, it's the only one which defines `b` and still allows us to use scoped type variables if we want them.

**Comment by jdegoes** [comment]
> I think they "feel" inconsistent.

Indeed, I'd like to see the `forall` syntax supported here, as I would definitely use the feature. Type variables are variables, too.

> I think the question is which of these should it desugar to without an explicit forall:

That's just the simple ambiguities introduced in a trivial case. When you start passing around polymorphic functions, the number of options multiplies! It's nice to have the compiler write code for us, but in the case where there are many semantics, then it's best to force the user to choose the desired semantic, rather than magically trying to guess, and being right sometimes and wrong other times.

**Comment by joneshf** [comment]
I don't understand why if a line of syntax contains `::` the `forall` is necessary, whereas if a line of syntax does not contain `::` the `forall` is unnecessary. But, I'm willing to learn why.

From someone not familiar with the compiler, a type synonym has no problem with type variables being on the left side of an `=` without `forall` in front of it, but if the type variables are on the right side the story changes.

**Comment by garyb** [comment]
> Surely it has to desugar to the second one though, it's the only one which defines `b` and still allows us to use scoped type variables if we want them.

Good point!

**Comment by garyb** [comment]
For the cases that don't require `forall` and don't have a `::` the reason it works currently is that they declare the type variables by other means (we don't have to extract the set of type variables by scanning the type before checking/inferring).

The semantics is the real problem though, it's not hard to make the change so that we extract type variables from a type first instead of relying on the `forall`.

**Comment by paf31** [comment]
@joneshf Type variables on the left hand side of `type` or `data` declaration are not quantified. Such things define functions on types, but `forall a. ...` is a type in its own right.

Just so it's clear, there is no "magic" involved with `forall` - `forall a. ...` parses as `Forall "a" ... :: Type`. That's what it always is, there are no special cases (alright, apart from `instance`..). On the other hand, there is magic involved with Haskell's `forall`, it implicitly binds type variables at the top level, which can lead people to thing that `forall` is some special instruction, but it's not, it's just another type-former! Haskell's `forall` story is further confused by things like `ScopedTypeVariables` and `RankNTypes`, and I think the current approach in `psc` is the best option, and it can be specified succinctly - always make type variable binding explicit, and always scope outermost bound variables.

**Comment by jdegoes** [comment]
`forall` is how you pass a type variable to a function. In a function such as `id :: forall a. a -> a`, there are actually 2 parameters passed to the function: a type parameter, and a value of the specified type. The use of `forall` makes it explicit: this is a type variable that you are passing to this function.

This explicitness is often required, and not just with scoped type variables. For example:

```purescript
foo :: a -> (b -> c) -> d
```

Here, the naive insertion of `forall` may not be what we want:

```purescript
foo :: forall a b c d. a -> (b -> c) -> d
```

This indicates we pass the type parameters `a`, `b`, `c`, and `d`, together with an `a` and a function `b -> c` to `foo` to get back a `c`. 

But here's another interpretation:

```purescript
foo :: forall a c d. a -> (forall b. b -> c) -> d
```

This indicates you pass the type variables `a`, `c`, `d`, a value of type `a`, and a function which itself accepts a type variable `b`, and a value of type `b`, and returns a `c`, in order to get back a `d`. 

The meaning of these two functions is completely different. Being explicit about where you are passing type variables is a good thing and helps people think in terms of "everything is a function".

**Comment by paf31** [comment]
@jdegoes I like that way of thinking about the problem a lot. It also makes it clear why type variable scoping acts the way it does - because they're just (implicitly passed) function arguments! Lots of things become clearer when you think in System F it seems :smile:

**Comment by jdegoes** [comment]
Indeed, System F is much clearer than the languages built on top of it. :laughing:

**Comment by joneshf** [comment]
> @joneshf Type variables on the left hand side of type or data declaration are not quantified. Such things define functions on types, but forall a. ... is a type in its own right.

Why are they not quantified?
Is it that they cannot be, or that they do not need to be?
How does it being a function on types change the idea of type variables enough to allow the variables to not be quantified?

**Comment by paf31** [comment]
`type Pair a = Tuple a a` is like the type function `Λa. Tuple a a`. You can think of this as having "type" `Pair :: Type -> Type`.

`forall` as a type former acts like `(Type -> Type) -> Type`, so it makes sense to form the type `forall a. Pair a`, for example.

It sounds like you're asking, why can't the type variables appearing on the left hand side of `type` be universally quantified. Well, they can, in the sense that `forall a. Pair a`, is a valid type, but you can't introduce a type function and quantify its argument at the same time. What would you want such a type to mean? How would you write it? What would its terms be and how would you eliminate them?

> How does it being a function on types change the idea of type variables enough to allow the variables to not be quantified?

The idea of type variables isn't being changed. A type variable is just a name for a type which has been brought into scope somewhere, but there might be different ways of bringing it into scope.

**Comment by joneshf** [comment]
> ...but, you can't introduce a type function and quantify its argument at the same time.

Why is that?

**Comment by paf31** [comment]
I should rephrase - _I don't know what it means to_ introduce a type function and quantify its argument at the same time.

**Comment by Fresheyeball** [comment]
Just out of curiosity, why are rank-n types a requirement for PureScript? Is there a problem that really can't be solved another way?

**Comment by jdegoes** [comment]
> Just out of curiosity, why are rank-n types a requirement for PureScript? Is there a problem that really can't be solved another way?

An uncountably many of them! Rank-ns let you encode all the families of existential types, which PureScript would not be able to encode in any other way.

**Comment by garyb** [comment]
Halogen in it's current form wouldn't be possible either, as no rank-n types means no natural transformations (`forall a. f a -> g a`).

**Comment by phadej** [comment]
My 5¢:

Between `FunctionalDependencies` and `TypeFamilies`, I'd pick `TypeFamilies` and type equality constraint `~`. Even the later is a slippery slope into dependent types like programming (or maybe because of that?)

I'll explain why.

Conceptually `TypeFamilies` are (open or closed) type level functions. We need equality constraint to make possible to postpone unification of function results. For example:

`F a ~ F b` may hold when `a` and `b` are instantiated, even `a` and `b` are different. Pick `type instance F a = ()`.

Taking the previous example by @cdepillabout (examples are Haskell, I tested them):

```hs
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FunctionalDependencies #-}

class AdderFunDeps a b c | a b -> c where
    myPlusFunDeps :: a -> b -> c  

class AdderTypeFam a b where
    type ResultType a b

    myPlusTypeFam :: a -> b -> ResultType a b
```

we can simulate `FunDeps` with `TypeFam`:

```hs
class (AdderTypeFam a b, c ~ ResultType a b) <= AdderFunDeps' a b c where
    myPlusFunDeps' :: a -> b -> c
    myPlusFunDeps' = myPlusTypeFam
``

Other way around is impossible (?), at least I don't know how to write `ResultType` without `TypeFamilies`.

---

Another (a bit more) complicated example:

```hs
class Strict strict lazy | strict -> lazy, lazy -> strict where
    -- In `lens` there's just strict :: Iso strict lazy
    strict :: lazy -> strict
    lazy :: strict -> lazy

class StrictTF strict where
    type Lazy strict

    strictTF :: Lazy strict -> strict
    lazyTF :: strict -> Lazy strict

class (StrictTF strict, lazy ~ Lazy strict) => Strict' strict lazy where
    strict' :: lazy -> strict
    strict' = strictTF

    lazy' :: strict -> lazy
    lazy' = lazyTF
```

---

Why this examples? To motivate that `FunctionalDependencies` could be desugared into `TypeFamilies`.

In `Strict` example inference is better with original *both ways* functional dependency. There other parameter could be inferred from other one. In `TypeFamilies` example that is not possible, as `Lazy strict` is ambigious. **Except** if we have [`InjectiveTypeFamilies`](https://ghc.haskell.org/trac/ghc/wiki/InjectiveTypeFamilies) which introduces the same `| -> ` syntax :)

OTOH as `TypeFamilies`, especially `InjectiveTypeFamilies` are very expressive, you will eventually (probably sooner than later) run into situations like in this [haskell cafe post](https://mail.haskell.org/pipermail/haskell-cafe/2015-November/122322.html). In other words, you'd like to be able to guide type checker, and it's not clear where actually.

**Comment by FranklinChen** [comment]
:-1: I believe explicit scoping right off the bat helps confusion when moving to higher-rank types and such. Hiding System F for a special (if common) case hides a key fact about how types really work.

**Comment by Fresheyeball** [comment]
middle road:

```purescript
foo :: forall a e. a -> e
foo :: a e. a -> e
foo :: a -> e
```

with ranks:

```purescript
bar :: a. (b. b -> b -> a) -> a
```

**Comment by husnoo** [comment]
Hi,

I don't understand enough of the esoteric terms above to fully appreciate the situation - but is there anything that Purescript does with the "forall" that Haskell can't do?

**Comment by garyb** [comment]
@husnoo yeah, we don't do anything with `forall` that Haskell can't do (if you include GHC extensions), but [`RankNTypes`](https://prime.haskell.org/wiki/RankNTypes) and [`ScopedTypeVariables`](https://prime.haskell.org/wiki/ScopedTypeVariables) both require it in Haskell too.

**Comment by husnoo** [comment]
@garyb It would be great though if this were an opt-in for people who know what it means, rather than force the extra verbiage on everyone - it makes it harder for newbies like me to get to grips with the language!

**Comment by jdegoes** [comment]
> It would be great though if this were an opt-in for people who know what it means, rather than force the extra verbiage on everyone - it makes it harder for newbies like me to get to grips with the language!

This can't be an opt-in feature because RankNTypes and ScopedTypeVariables are baked into PureScript, and that means you need to be explicit if you want to use type variables.

I'd also suggest that many beginning-to-intermediate Haskell programmers have an inaccurate understanding of what something like `id :: a -> a` means. I'm not sure exactly how to describe it, but it's like they picture the preceding `id` function as being a function from *some* unknown type `a` to that same type.

When they encounter PureScript, and they are forced to introduce the type variable (`forall a. a -> a`) via universal quantification, they can't reconcile this with their previous (wrong) mental model of polymorphism. So they want to change the way PureScript works, but what really needs updating is their mental model. 

PureScript is not pointlessly confusing them because of mere syntactic differences, but rather strongly suggesting they need to dig in to understand type variables a bit more.

I think the correct response is, "how can we better explain these concepts to PureScript beginners," rather than, "let's let PureScript beginners make it a little further on their existing, faulty mental model of polymorphism."

**Comment by natefaubion** [comment]
> I'd also suggest that many beginning-to-intermediate Haskell programmers have an inaccurate understanding of what something like id :: a -> a means. I'm not sure exactly how to describe it, but it's like they picture the preceding id function as being a function from some unknown type a to that same type.

I strongly agree with this statement as I went through this exact unlearning in Haskell when trying to understand rank-n types. I find the `forall` a little tedious sometimes, but being explicit about introducing type variables and their scope really helps later on.

I think @Fresheyeball's example of explicit quantification without the keyword is cute. I know @paf31 has had `exists` on his wishlist for a while though, in which case it might be better to keep it explicit.

**Comment by jdegoes** [comment]
> middle road:

There are really two separate issues: (a) whether PureScript's explicit introduction of type variables is really good and necessary (I have argued that it is); (b) what the syntax for that feature looks like.

I would regard (b) as not massively important to the success of the language. Currently, it's 8 characters which can be typed in less than a second, and shares compatibility with Haskell. I do understand that many (including myself) enjoy clean and compact syntax, which is motivating some of these discussions.

I personally like `∀a. a -> a`, because there's the symmetrical `∃a. a -> a` for existential quantification, and these symbols have well-defined histories dating hundreds of years. But I regard this as a personal preference that's irrelevant to the success of the language, and really a secondary issue to the main one being discussed here, which is whether the explicitness is good and necessary.

**Comment by husnoo** [comment]
@jdegoes Thanks for explaining this :-) I will try again at grokking it.

**Comment by joneshf** [comment]
> I'm not sure exactly how to describe it, but it's like they picture the preceding id function as being a function from some unknown type a to that same type.

Opposed to what?

**Comment by natefaubion** [comment]
Referencing type variables without quantifying them first is kind of like referencing a free variable in a function and having it implicitly added to the argument list. The intuition that type variables are just type level arguments parallels the value level and extends to ranked types just like higher order functions do at the value level. For me at least, implicit quantification just obscured this.

**Comment by LiamGoodacre** [comment]
:-1: from me.
I find it useful when purescript tells me I've forgotten to introduce a type variable - I can more quickly catch scoping mistakes.

**Comment by Lokathor** [comment]
New to Purescript, but :+1: to this. The fact that sometimes you want the extra power of precisely declaring where the forall goes doesn't stop it from putting extra line noise on the page in the many cases where you don't need it.

Seems like something that could be a compiler flag or other optional setting to activate an implicit forall at the start of a polymorphic type signature that otherwise lacks one entirely.

**Comment by AppShipIt** [comment]
> I'd support unicode `∀ a e. a → e`, then it will be as short as value-level abstraction ( \x y -> x :: y).

For documentation purposes @phadej's proposal was implemented in #1847.

**Comment by jdegoes** [comment]
> For documentation purposes @phadej's proposal was implemented in #1847.

Cool, & thanks! It's too easy for stuff like this to slip through the cracks!

**Comment by AppShipIt** [comment]
Much obliged it was news to me 🎉

**Comment by paf31** [comment]
Can this be closed/frozen now?

**Comment by garyb** [comment]
I think so, we've probably exhausted the arguments on it, and I don't think you are I are in favour at least, for the rank-n / scoped type variable reasons in particular.

**Comment by paf31** [comment]
Agreed, and I think the unicode alternative provides a decent compromise for those who are concerned about number of characters.
