### ISSUE TITLE
Warn on name shadowing

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#837]
I'm working on #822 and can't decide if the right fix is to disallow shadowing of names generally, which will break lots of existing code, but seems like a win overall.

Thoughts?

**Comment by michaelficarra** [comment]
I like shadowing. I avoid it when I can, but it would be surprising if it worked any other way (or was disallowed).

**Comment by paf31** [comment]
Makes sense. Maybe it can be a warning instead, when we have warnings :)

**Comment by michaelficarra** [comment]
Yes, that would be a great candidate for a warning.

**Comment by garyb** [comment]
Agreed, I'd also rather allow it but warn.

**Comment by jdegoes** [comment]
I like shadowing. It can eliminate lots of bugs -- for example, in pattern matching in recursive data structures, it can allow you to eliminate the option of accidentally referencing a value of the same type in the outer scope. In fact, most of my bugs in deep pattern matching are because I use `a'` naming convention instead of shadowing (and then refer to `a` instead of `a'`, accidentally).

That said, I think a variable that is never referenced should be an error.

**Comment by garyb** [comment]
This is done now, isn't it?
