### ISSUE TITLE
true and false instead of True and False

### ISSUE THREAD

**Issue by aspidites** [purescript/purescript#842]
Perhaps I'm just inferring this from my Haskell knowledge, but I was under the impression that data constructors had to begin with capital letters? If so, is there a particular reason true and false were made the exception to the rule?

**Comment by garyb** [comment]
You're right, data constructors are captialised, but `true` and `false` refer to Javascript values of the `Prim.Boolean` type. The compiler has special cases for parsing them and allowing them to be used as values in patterns.

**Comment by aspidites** [comment]
Could the special casing not be done to transform `False` to `false` and `True` to `true`. I suspect  doing so would be easier and cleaner than having special cases to handle treating the lower case forms as a valid pattern match. Please correct me if I'm wrong. 

This isn't really a big deal, but it does stick out like a sore thumb to me (and I've been bitten more than once by trying to pattern match on True/False).

**Comment by michaelficarra** [comment]
@aspidites: Instead of pattern matching on `true`/`false`, why don't you use the `if`/`else` sugar?

**Comment by aspidites** [comment]
That  makes sense. Hell, I already do that in Haskell. I guess I'm just so early in the purescript book that I didn't think of that! Thanks. I still think my point about desugaring during compilation instead of having a special case for booleans in pattern matching is valid though

**Comment by paf31** [comment]
It probably does make sense to desugar `true` and `false` into constructors and constructor patterns.

**Comment by aspidites** [comment]
Ah, ok

**Comment by aspidites** [comment]
@paf31: How non-trivial would it be to try and take something like that on? As a sort of measuring stick, if I were to finish watching that video where you walk through purescript's source, would I have a good idea of where to dig in to experiment whether or not this would be a worth-while thing to do? 

I ask because I know that there are more important things to focus on, but have a hunch that this would be a great way to practice Haskell and learn more about Purescript at the same time. Feel free to discourage me from trying if you think its only a quest for the mad man.

**Comment by paf31** [comment]
I would say go for it, but honestly I think there might be better things to spend time on, if you are interested in learning more Haskell or about the compiler. Also, it might just complicate things - the code might be a little redundant right now, but it's simple.

Check out the issues with the 'easy' tag if you want to find some things to get started.  IRC is also a good place to ask questions if you'd like to start working on the compiler, and we always need more compiler developers :)

**Comment by jasonkuhrt** [comment]
As someone who knows JavaScript very well and is learning Haskell I was surprised by the `true/false` rather than `True/False`. If I invest more into PS maybe that will feel rational but indeed my initial reaction was surprise. If I didn't know about Haskell maybe I would have had a different reaction.

**Comment by zudov** [comment]
I also was initially surprised with `true`/`false`, but now I think it makes sense. `Boolean` isn't ADT, it's a foreign data type with two predefined values `true` and `false`. Foreign data types don't have constructors at the moment.

**Comment by aspidites** [comment]
Purescript's String type has a simple runtime representation of String in JavaScript. I don't see why that couldn't also be the case for Boolean.

**Comment by paf31** [comment]
But `String` is also not an algebraic data type.

**Comment by zudov** [comment]
@aspidites All primitive types look as if they defined in this way:
```purescript
foreign import data String :: *
foreign import data Number :: *
foreign import data Array :: * -> *
foreign import data Boolean :: *
foreign import true :: Boolean
foreign import false :: Boolean
...
```
`String`, `Array`, `Char`, `Number`, `Int` have a special literal syntax because it would be cumbersome to define them with FFI every time when you need one like:
```purescript
exports.helloStr = "hello"
foreign import helloStr :: String
```
and those literals don't confusing look as some other syntax elements. But `True`/`False` literals would make it look as if the `Boolean` defined with `data Boolean = True | False` which isn't true.

**Comment by jprider63** [comment]
I'm just starting with PureScript, and I just wanted to say that this is one thing that is confusing initially (especially in patterns since `true` and `false` look like they could be variable names). I personally favor `True` and `False`.

**Comment by hdgarrood** [comment]
:-1: from me; keep `true` and `false`, for the same reasons as @zudov already explained. Additionally, now that we have generics, I think it's particularly important not to imply that `Boolean` is defined as `data Boolean = True | False`.

**Comment by paf31** [comment]
Closing, for the reasons given above.

**Comment by ivan-kleshnin** [comment]
I imagine Boolean as FFI have limitations 

1. `Boolean` not being part of the`Ord` or something like that.
2. Even basic code (app / lib code) becomes not portable between compilation targets.

I agree that non-ADT `Boolean` should be as it is, but
couldn't we make `Boolean` an `ADT` and **conversely** 
provide some kind of "foreign export" *"from PS Boolean to JS Boolean"*.

Please correct me if I'm wrong. 
I ask for learning purposes but as answer may be useful to others I do it here.

**Comment by LiamGoodacre** [comment]
@ivan-kleshnin Boolean has an Ord instance.  Both primitives and foreign data types can have type class instances.
Not sure what you mean with respect to compilation targets - what compilation targets don't have booleans?
If you really wanted to you could write an ADT boolean library, but I find its worth questionable.

**Comment by ivan-kleshnin** [comment]
> Not sure what you mean with respect to compilation targets - what compilation targets don't have booleans?

Imagine we have a language with `yes` and `no` instead of `true` and `false`.

If we *import* this stuff to PS through FFI I must have two different codebases 
to implement basically any program:
1. for YesNo language 
2. for JS language

If we *export* booleans from PS, this difference is kept inside (imaginary) `purescript-to-js` and `purescript-to-yesno` layers and is removed from MY code. So it becomes portable (until I start to use platform-specific libraries).

**Comment by hdgarrood** [comment]
If I've understood you, booleans are already 'portable' in the way you're hoping. If we had a compilation target in which `true` and `false` were written `yes` and `no` respectively, we'd write the compiler backend so that `true` in PS automatically comes out as `yes` in your target language. There is no 'PS boolean'; if you have a `Boolean` in PS, it's going to be compiled down to the boolean type from whatever language you're targeting.

If you start writing FFI code, then yes, you'd have to write the same FFI code once for each backend you want to support, but that's always going to be the case, regardless of whether we have a boolean ADT.

**Comment by ivan-kleshnin** [comment]
@hdgarrood yes, but that would undermine the explanation: "`true` is lowercase because it's imported from JS" as JS is no longer *referential* in that situation. My point is - if PureScript targets one platform it's fine. If PureScript targets multiple platforms - it's strange to model core datastructures after one of them.

**Comment by hdgarrood** [comment]
I think the explanation is really "`true` is not uppercase because it's not an ADT". The only constraint we really have on the name is that it shouldn't start with a capital letter because of course that would imply that it's an ADT. Given that, `true` and `false` are the most obvious names, as every language I know of calls the two boolean values by those names (up to lower/uppercase). But also, PureScript does intend to match the semantics of JavaScript more closely than e.g. Haskell does; that's one big part of its selling point over GHCJS, so I think a limited amount JavaScript influence in the language design does make sense.

**Comment by ivan-kleshnin** [comment]
Ok, fair enough, thanks for answering @hdgarrood

**Comment by hdgarrood** [comment]
You're welcome :)
