### ISSUE TITLE
duplicated names of imported module and adt 

### ISSUE THREAD

**Issue by cryogenian** [purescript/purescript#867]
suppose I have 

    import Foo
    data Bar = Foo Number | Baz Number 

then it will be compiled to

    var Foo = require("Foo");
    var Foo = (function() {
      function Foo(value0) {this.value0 = value0}; 
      Foo.create = function(value0) {return new Foo(value0)}; 
      return Foo; 
    })();

I think this is bug

**Comment by garyb** [comment]
Definitely a bug, thanks for the report.

**Comment by paf31** [comment]
Do we want to catch this in `Names` and throw an error?

**Comment by garyb** [comment]
I've been thinking about it, but I'm not really sure how best to deal with it yet... restricting the name of data constructors based on the name of imported modules seems like a slightly odd restriction to impose. I guess ideally the module `Foo` should be imported as `Foo1` in the JS or something like that.

**Comment by paf31** [comment]
Underscored names to the rescue yet again :)

**Comment by jdegoes** [comment]
I would not make this an error in the compiler. This is an implementation detail in the way modules are imported and should not be visible to programmers. The imported module could be called anything and it would not affect the semantics of the code. As @garyb suggests, using numbers or underscores or dollar signs to make the imported module unique where conflicts would otherwise occur is probably the right solution.

**Comment by paf31** [comment]
Yes, I agree. If we can find a nice way to solve this in codegen, that would be great.

**Comment by paf31** [comment]
Seems like we don't need the reserved ProperNames list any more then. We could just prefix all module names with `__import_` or something similar, like we do for dictionaries.

**Comment by garyb** [comment]
The reserved `ProperName`s list also protects us from hiding global JS things by declaring data constructors with those names too.

**Comment by paf31** [comment]
Makes sense.
