### ISSUE TITLE
Semirings and monoids are related no?

### ISSUE THREAD

**Issue by Fresheyeball** [purescript/purescript#900]
I'm probably way off, but this seems right to me. It would also mean more emergence for functions that depend on semigroup and monoid now work with more types.

![screen shot 2015-02-21 at 11 59 59 am](https://cloud.githubusercontent.com/assets/609279/6315507/7ee5a45e-b9c1-11e4-8d0b-648d93c551f9.png)

**Comment by paf31** [comment]
Which `Monoid` does the `Semiring` use? There are two and neither is canonical.

**Comment by Fresheyeball** [comment]
I was thinking (+) because it would share identity in `Ring`.

**Comment by Fresheyeball** [comment]
Also kind of following the haskell thought where other monoids are defined in terms of `(+)` like `(<+>)` and `mplus`

**Comment by paf31** [comment]
But `*` is an equally valid `Monoid`. The reason we don't do this is that neither `+` nor `*` is preferable to the other.

**Comment by Fresheyeball** [comment]
I guess I feel that `(+)` is preferable, and the having even if they are equally preferable, I'd rather have one than none.

**Comment by Fresheyeball** [comment]
So I observe that of Num 

- `(+)` monoid 0
- `(*)` monoid 1
- `(-)` loop 0
- `(/)` loop 1
- `mod` ? 1

`ModuloSemiring` is uglier and more restrictive than `Ring` (2 definitions instead of 1 definition), in a choice between `(*)` and `(+)` I feel that `(+)` is more useful for programming.

**Comment by Fresheyeball** [comment]
Also there is the `Semiring => BoolLike => Bits` thing.

**Comment by garyb** [comment]
Haskell doesn't define a monoid for numbers either, you choose (0, +) or (1, *) with the `Sum` or `Product` newtypes, just as we did up until recently, and now have the more general `Additive` and `Multiplicative`.

**Comment by Fresheyeball** [comment]
So... ok. You take a `Number` and convert it to a `Multiplicative `, then you could use `mconcat` with a `[Multiplicative]`? If so, then it makes sense to span the gap with `newtype` as you can convert and de-convert between `Multiplicative`,`Additive` and `Number`. 

So if you want to link with `Semiring`, what do you do?  Do you require that an element that is a `Semiring` have two `Monoid` instanced `newtypes`?  Or is something like this possible:

```
newtype Additive :: forall a. (Semiring a) => a -> Additive
```

so that the only way to make a `newtype` is with an argument of that is an instance of specific typeclass?

**Comment by Fresheyeball** [comment]
Btw, thank you for explaining this.

**Comment by garyb** [comment]
Ah, so `Additive` and `Multiplicative` accept a parameter already: `Additive a` and `Multiplicative a`, and yep, you can use `mconcat` with, say, a `Multiplicative Number` or `Additive Number`.

We don't allow class constraints on the constructor like you have there (it was possible in Haskell via extension at one point but found to be a Bad Idea in the end), but the `Monoid` instance for `Additive a` (etc) is defined like this:

``` purescript
instance monoidAdditive :: (Semiring a) => Monoid (Additive a) ...
```
([see here](https://github.com/purescript/purescript-monoid/blob/7613b59cb5a180767c08cc405124fda4b9603d72/src/Data/Monoid/Additive.purs#L48-L52))

This means that *any* type that implements `Semiring` can be used as a `Monoid` with (zero, +) by lifting it into `Additive`.

It is true you can make nonsensical `Additive`s also, like `Additive Unit`, but since there is no `Semiring Unit` instance, there is also no `Monoid (Additive Unit)` instance, so `mconcat` and friends will not work for those types.

**Comment by Fresheyeball** [comment]
![](http://i1.kym-cdn.com/photos/images/original/000/288/643/6c6.jpg)

**Comment by garyb** [comment]
Haha, it is pretty nice ;)

Does it all make sense?

**Comment by Fresheyeball** [comment]
Yes. That was monumentally helpful. I can see how `newtypes` can be used as channels between typeclasses. 

There is more I'd like to understand though. How does `Semiring` and `BoolLike` relate? Because it seems that `BoolLike` is like a dual `Semigroup` with `compliment`.

**Comment by garyb** [comment]
Actually, you're right, there's perhaps an opportunity here to make the `Any` and `All` newtypes in `purescript-monoid` polymorphic and define the monoid and semigroup instances with a `BoolLike` constraint rather than specializing them on `Boolean`.

`BoolLike` is basically a Boolean algebra structure, which is a type of lattice, which does have some connections to group-like structures: https://en.wikipedia.org/wiki/Lattice_%28order%29#Connection_to_other_algebraic_structures

You have to be careful throwing the word "dual" around when talking about this stuff by the way, I thought you meant something [entirely different](https://en.wikipedia.org/wiki/Duality_%28mathematics%29) at first ;)

**Comment by garyb** [comment]
Actually there's a `Semigroup` definition for `BoolLike` but no `Monoid` as there are no identities for conjunction and disjunction in `BoolLike` (the `true` and `false` equivalents of `zero` and `one` in `Semiring`).

**Comment by garyb** [comment]
Check out @joneshf's `purescript-algebra` for a more nuanced version of this stuff: https://github.com/joneshf/purescript-algebra

**Comment by joneshf** [comment]
> It is true you can make nonsensical Additives also, like Additive Unit, but since there is no Semiring Unit instance, there is also no Monoid (Additive Unit) instance, so mconcat and friends will not work for those types.

What's nonsensical about `Additive Unit`? It seems like it would be the trivial `Additive`.

In fact, why don't we have more `Unit` instances?

**Comment by Fresheyeball** [comment]
Ok, so I don't understand why conjunction and disjunction down't have identities in `BoolLike` since they do have identities with `Boolean`.  `BoolLike` seems like it could just be a `Semiring` with `not`.

**Comment by Fresheyeball** [comment]
Made this for myself incase anyone wants it:
![screen shot 2015-02-21 at 9 16 27 pm](https://cloud.githubusercontent.com/assets/609279/6317426/ff5ee544-ba0e-11e4-9273-de2f5cc6fe67.png)

**Comment by joneshf** [comment]
Well, `BoolLike` just doesn't have a `⊥` or `⊤`. That's all there is to it. There's nothing stopping it being extended to that, but we might want to think about reformulating that part of the hierarchy. Dunno that there's much need to change, or if it's even worth it, but `LVars` at least could definitely benefit from that, among some other data structures.

**Comment by garyb** [comment]
> @joneshf: What's nonsensical about Additive Unit? It seems like it would be the trivial Additive.

Yeah that was a bad example, I was just thinking of a type that we don't have a `Semiring` instance for.

> @Fresheyeball: Ok, so I don't understand why conjunction and disjunction down't have identities in `BoolLike` since they do have identities with `Boolean`.  `BoolLike` seems like it could just be a `Semiring` with `not`.

`Semiring` also has `(*)`, so that doesn't really work, what's `true * false`? And yeah, conjunction and disjunction *do* have identities in a Boolean algebra, but we don't have them in our current definition of `BoolLike` is what I meant.

@joneshf: What would we need to do to reform `BoolLike`? Would adding 
``` purescript
class (BoolLike a) <= BooleanAlgebra a where
  bottom :: a
  top :: a
```
be enough for what you have in mind?

**Comment by joneshf** [comment]
Well, I'm all about some granularity, so I'd think `Bits` and `BoolLike` would both be split up to share as much as possible. Also, I've not really explored the poset side of `Lattice` stuff, so maybe there's a better formulation that uses `Ord` in there somewhere.

**Comment by jdegoes** [comment]
`BoolLike` should extend `Semiring`, because `(+)` is disjunction and `zero` is `false`, while `(*)` is conjunction and `one` is `true` (under this definition, anything plus `zero` is that thing; and anything times `one` is that thing). The unique operation in `BoolLike` is `not`, which presumably asserts the cardinality of the boolean type is two (but that can surely be loosened).

Note that if `BoolLike` extends `Semiring`, you get `Disjunction` and `Conjunction` monoids for "free", albeit, they are called `Additive` and `Multiplicative` (which some would say is an argument for separate `Disjunction` and `Conjunction` newtypes).

**Comment by jdegoes** [comment]
> In fact, why don't we have more Unit instances?

:+1:  to this. It's hugely helpful to have as many unit instances as possible, because this enables you to express "not caring about the information" more precisely.

**Comment by Fresheyeball** [comment]
Ok, so I was onto something. `BoolLike` is just a `Semiring` with `not`. 

For that matter then, why not have `Semiring => BoolLike => Bits`? Bits seem like they should be able to absorb all the `BoolLike` functions with Identities of a pure false bit and a pure true bit. With this Bits get all `BoolLike` accepting functions as well as `Semiring` and `Additive` and `Multiplicative` Monoids.

**Comment by Fresheyeball** [comment]
I've considered before writing a color library that would potentially benefit from `BoolLike` as a `Semiring` with `not`. Where Hues go around the color wheel clockwise or counter-clockwise using Modular Arithmetic (Semiring) but can also flip to the other side of the wheel using `not` for `complimentary`. This should hold for anything with Modular Arithmetic like transforms on an N dimensional context (2d 3d stuff).

**Comment by joneshf** [comment]
> For that matter then, why not have Semiring => BoolLike => Bits? Bits seem like they should be able to absorb all the BoolLike functions with Identities of a pure false bit and a pure true bit. With this Bits get all BoolLike accepting functions as well as Semiring and Additive and Multiplicative Monoids.

That would make the `Number` instance of `Bits` unlawful. So we'd need specific bounded types after that point.

**Comment by jdegoes** [comment]
I wonder if it's sufficient to define the following law(s) for `not`: 

* `not <<< not = id`
* `a || not a = a`

This allows complimentary negations, bitwise negations, etc. (`negate` also satisfies these laws, albeit for `negate`, we have the additional law `negate zero = zero`, which does not hold for `not` &mdash; in fact for booleans, `not zero = one`, which is sort of the defining property for booleans!).

**Comment by joneshf** [comment]
> I wonder if it's sufficient to define the following law(s) for not:
> 
> not <<< not = id
> a || not a = a
> This allows complimentary negations, bitwise negations, etc. (negate also satisfies these laws, albeit for negate, we have the additional law negate zero = zero, which does not hold for not — in fact for booleans, not zero = one, which is sort of the defining property for booleans!).

You need a bit (hah!) more than that. Say you had three values.

```purescript
data Tri = A | B | C

(||) :: Tri -> Tri -> Tri
(||) A t = t
(||) t A = t
(||) B B = B
(||) C _ = C
(||) _ C = C

(&&) :: Tri -> Tri -> Tri
(&&) A _ = A
(&&) _ A = A
(&&) B B = B
(&&) C t = t
(&&) t C = t

not A = C
not B = B
not C = A
```

Then `a || not a /= a`

```purescript
A || not A 
    = not A
    = C
```

What you need is that `a || not a == ⊤` and also `a && not a == ⊥` along with the double negation.

**Comment by jdegoes** [comment]
So collecting these:

```
a || not a = true
a && not a = false
not (not a) = a
```

With `(||)` as `(+)` and `(&&)` as `(*)` in `Semiring`, these would be:

```
a + not a = one
a * not a = zero
not (not a) = a
```

which makes it clear that bools diverge from numbers at some place in between `Ring` and `Semiring`, i.e. where you have a unary operation `n` for which `n <<< n = id` but not much else.

**Comment by garyb** [comment]
> @Fresheyeball: Ok, so I was onto something. `BoolLike` is just a `Semiring` with `not`. 

It also has additional laws:

- both operators are commutative in a boolean algebra, whereas only `+` is in a semiring
- `+` and `*` should be connected by the absorption law, meaning `a + (a * b) = a` and `a * (a + b) = a`

**Comment by Fresheyeball** [comment]
So with `Booleans` it still holds with either binding:

```haskell
a * (a + b) = a
True  && (True  || False) = True
False && (False || True)  = False

a * (a + b) = a
True  || (True   && False) = True
False || (False && True)   = False
```

So it could be said that `BoolLike` is a `Semiring` with `not` in which `(+)` and `(*)` must be commutative.

**Comment by paf31** [comment]
The concept of a distributive lattice should probably show up somewhere with distributivity (both ways) as laws.

**Comment by Fresheyeball** [comment]
Thats crazy talk @paf31, you crazy.

**Comment by Fresheyeball** [comment]
^^^ sarcasm. Anyway, do you mind if I take a stab at this?

**Comment by jdegoes** [comment]
A new ticket should be opened for revising the `BoolLike` hierarchy (of which Lattice & friends will form some role).

**Comment by Fresheyeball** [comment]
Ok, so if this needs to be bundled with Lattice stuff, then I'm not ready. I will need to spend some time figuring out what a Lattice is.
