### ISSUE TITLE
"Meltdown" Release Issues

### ISSUE THREAD

**Issue by paf31** [purescript/purescript#937]
The 0.8 ("Meltdown") release might become the release in which we fix a bunch of major things which break lots of libraries. Let's figure out what we want those things to be.

Ideally, these should be things that we can implement relatively painlessly, and then support while we work through the transition, without too many bug fixes, so huge typechecker changes are probably not appropriate.

That said, if we commit to making breaking changes, we have a rare opportunity to break things, so I think we should be pretty bold about it.

Some of my own preferences:

- Operator aliases
- No more string literals in the FFI
- Remove special support for arrays (matching and construction)
- Replace `show` with `showsPrec`
- Remove the `Prelude` (requires rewrites to be done in 0.7)

_Note_: To avoid this turning into another giant thread, I'm going to delete comments which are just suggestions and move them into the list above.

**Comment by garyb** [comment]
- Remove the `Prelude` if possible

**Comment by paf31** [comment]
^^ :+1:

**Comment by paf31** [comment]
To avoid this turning into another giant thread, I'm going to move suggestions into the issue body.

**Comment by michaelficarra** [comment]
* Disallow imports without explicit import list so that additive changes to libraries are not breaking changes.
* Use `[]` syntax for linked lists, and require users to explicitly use a data structure that is compatible with JavaScript Array if they want to expose it to JS land through FFI.

**Comment by garyb** [comment]
re: non-explicit imports. I was thinking about this lately also, but read elsewhere that this style was dropped in GHC as it can result in many changes unnecessarily becoming conflicts: https://wiki.haskell.org/Import_modules_properly#Counter-arguments_to_explicit_import_lists

**Comment by paf31** [comment]
@michaelficarra Would `[]` become polymorphic then? It would basically have to, or else the compiler would depend on a particular implementation, which is incompatible with removing the Prelude.

**Comment by jdegoes** [comment]
Related, I suggest we make the core libraries use `npm` to install a compatible version of psc, so that all libraries can always compile regardless of changes to the compiler.

**Comment by Fresheyeball** [comment]
why not use bower to install a compatible version of psc?

**Comment by paf31** [comment]
Bower doesn't really have a story for installing binaries as far as I know.

**Comment by Fresheyeball** [comment]
`npm` does via hooks into `npm install` so if you run `npm install` a package that gets installed can run a script that might build a binary. But `psc` has prebuilt binaries already, and the script to detect which one to use just needs to live somewhere, so it should be doable on bower. If you take the `npm` approach, then each library could have conflicting compiler versions required, so I don't see what it really gets you as everything needs to compile together anyway. A bower package with `psc` in it would be nice anyway.

**Comment by michaelficarra** [comment]
@garyb: That seems like a very minor (and entirely theoretical) downside for a pretty significant gain.

@paf31: I hadn't considered that we were removing the prelude. How would that work with other primitives like numbers and Booleans?

**Comment by joneshf** [comment]
Might be worthwhile to revisit ghcjs compilation, if we're looking to ship precompiled things. Let ghcjs make a js file, and just push that to bower or whatever.

**Comment by garyb** [comment]
@michaelficarra: perhaps, but GHC developers did run into the problem... I definitely think we should move to explicit imports within all core libraries as they certainly should be settling down over time, but I'm not sure it's a restriction we should impose on everyone. Making it a warning would be the way to go perhaps.

**Comment by hdgarrood** [comment]
:+1: to what's on that list already. 

Re explicit import lists: I don't think I've ever had a case in Haskell or PureScript where I updated a library in an existing project and things broke because of newly exported symbols from that library clashing with existing ones in scope. (@michaelficarra that is what you mean by breaking changes right?)

Being forced to use explicit imports could become really tiresome, especially for imports from the same package. I'd much rather opt in to being protected against additive changes, by choosing to use an explicit import list.

How would a polymorphic `[]` type constructor work?

**Comment by jdegoes** [comment]
Explicit import lists make it easy to find where functions are used. They also have a tendency to clean up the code due to less use of qualified imports. That said, I understand why people hate having to be explicit with their imports. At SlamData, I'm trying to make it a code review policy: always import only and exactly what you need to make it easier for developers to understand where things are coming from.

**Comment by paf31** [comment]
How do qualified imports fit into the picture?

Also, I think we should move these discussions into their own issues if they become controversial.

**Comment by jdegoes** [comment]
I'm not voting one way or the other on imports. :) Just relating my own personal experience (it's so much easier to find what you're looking for with explicitly qualified imports). That said, since the explicitly qualified import lists are usually single-line lists, I can see where this style would lead to spurious Git conflicts, and developers having to constantly fix tedious imports. Which is the lesser evil is a matter of taste.
