### ISSUE TITLE
Make instance naming optional

### ISSUE THREAD

**Issue by dvdsgl** [purescript/purescript#952]
I apologize if this issue has already been discussed *ad nauseum*, and I'm sure the reasoning behind instance naming is robust, but I need to share my experience:

After adding 50 instance declarations to my app over the past few days, none of which I plan to reference from JavaScript, I felt like I was doing work that the compiler should be doing for me when writing down typeclass instance names. I'd really appreciate it if instance names were optional, so if I omit the name like:

```purescript
instance Show Foo where
  show (Foo x) = x
```

Then the compiler comes up with some unique name for this that I never need to worry about. If I want to provide a name for any reason, I can continue to do so with the current syntax.

**Comment by paf31** [comment]
The compiler used to do this, but the names were so ugly that they made the code practically unreadable at times. Making them optional is an interesting option.

**Comment by jdegoes** [comment]
:-1: Will lead to bad code generation and error messages. For me personally, I can type 50 names in less than a minute -- typing has never been a bottleneck for me, it's more thinking about how to design the code and also debugging it. Names interfere with the latter.

**Comment by andyarvanitis** [comment]
In the context of the C++11 backend, the instance names aren't used, so I've also been thinking optional names would be nice. I can't speak to what effect it would have in JS, or on the error messages. Would a simple hash (if optional and not provided) work without negatively affecting much? It seems that as long as the error messages include line numbers it would be ok, but I'm not an expert on it.

**Comment by joneshf** [comment]
I'd say it depends on what you're wanting out of the backend. If you want to generate code that others will still use, then optional names is a bad idea. If you don't care what people do with the generated code, then enforcing names is a good thing. Since the current js backend still wants people to read the output, keeping names mandatory is a good idea. If a different backend (could still be js, could be C++11) didn't care about readable output, then names wouldn't even be necessary.

**Comment by andyarvanitis** [comment]
Not another argument for or against, but just to clarify: in the C++11 backend, the instance names do not appear at all in the generated code.

**Comment by user471** [comment]
I also would like this feature. Compiler can just generate guid. If someone needs a instance name he can simply add it. Why to force people to do something if they don't need it.

**Comment by puffnfresh** [comment]
I'm of course a :+1:

**Comment by michaelficarra** [comment]
Why was this closed?

**Comment by paf31** [comment]
I closed it because this is one of a few issues which seem to crop up every few months. The only reason for it seems to be that it's a mild inconvenience to choose and type a name, and I can think of three reasons against:

- Choosing a naming scheme which guarantees global uniqueness and is pleasant to read is difficult. I don't want hashes or GUIDs in generated code.
- Renaming a class or type has the possibility to break working FFI code. 
- As @jdegoes mentioned, poor error messages.

I generally like to leave these things open for discussion, but we don't seem to be able to reach a consensus, and at some point, a decision has to be made. I don't think it's worth it, sorry.

**Comment by jdegoes** [comment]
I think this is the best decision. Seriously, we probably spent more time on this ticket than any of us will spend writing instance names in a whole lifetime. :wink: :laughing:

**Comment by user471** [comment]
>we probably spent more time on this ticket than any of us will spend writing instance names in a whole lifetime

What if ps will become popular? Then thousands programmers will write this useless names.

**Comment by paf31** [comment]
Locking this, discuss it on IRC if you like.
