### ISSUE TITLE
Purescript default operator precedence

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript#990]
So there are a lot of default operators in PureScript, some at the value level, some at the type level.
```purescript
->
<<<
>>>
$ # :
<$> <#>
<*>
>>=
+ * / -
== /=
< > <= >=
& | ^
&& ||
<> ++
`some_function` `mod` `shr` `shl`
= <-
```
From the documentation it's not immediately obvious what the priorities of the operators are. For example, I would expect something like this for the familiar binary operators:
```rust
* / `mod`
+ -
`shr` `shl`
&
^
|
== \= < > <= >=
&&
||
=
```
but that has two issues: it assigns multiple priorities to certain, special backtick functions (which makes no sense), and it leaves out half the operators (`-> <<< >>> $ # : <$> <#> <*> >>= <> ++ <-`). And in the mix is also the precedence of plain-old function invocation: `const "a" 1`.

What exactly are the operator precedences? And the associativities, when it's significant?

**Comment by alexchandel** [comment]
Oh and **completely undocumented** is the modulus operator `%`. Where does it fit in?

**Comment by alexchandel** [comment]
As well several syntactic tokens `@ . ... : , ::` and `\x ->` that can appear in expressions.

**Comment by garyb** [comment]
That's a good point, this stuff isn't output in the documentation at the moment, although at least it's not too hard to look it up in the source.

Backticked functions all share the same precedence and fixity at the moment, which I think works out as `infixl 9`. I couldn't find that documented anywhere so we should probably add it to the wiki, but need to check that I got that right first!

`->` and `<-` aren't really operators, they're syntax. `:` is usually an operator, except when it appears in patterns, at which point it is syntax. That's something we've not fully figured out yet, native array patterns are possibly going to be removed due to their poor performance when treated like a cons list.

The `(->)` type is a special case and is the only operator that can appear at the type level (currently) so fixity is irrelevant there for now.

No operator can have a higher precedence than function application.

`(%)` should probably also go away when `Int` from `purescript-integers` is as efficient to use as `Number`. That hopefully won't be too long from now, when we add rewrite rules. It's a leftover from before we reformed the `Num` hierarchy, it's now monomorphic on `Number` and does whatever `%` does in JS, whereas the laws for `DivisionRing` mean that `mod` for `Number` always returns 0.

**Comment by brainrape** [comment]
+1 for including the fixity declaration in the doc

**Comment by alexchandel** [comment]
For `(%)`, perhaps it would be appropriate to introduce a `EuclideanDomain` type class and have `(%)` be the remainder operator, since that's effectively what it does in `4.5 % 4 == 0.5`.

From the syntax of records, it seems like `|` acts like a type level operator too, in that it kind of takes a partially applied type synonym and a `# *` and returns a `*`.

It actually seems like there are three arrows, the lambda `\x -> x`, the value constructor  `a -> b`, and the type constructor `k1 -> k2`.

I like the idea of a `:` that can be optimized out. And maybe a `:` for datakind natural numbers.

It'd be nice to draw up a PureScript "Reference" with a terse list of operators and their precedence, among other things.

**Comment by alexchandel** [comment]
Presenting,
```purs
infixr 9 >>>
infixr 9 <<<

infixl 7 *
infixl 7 /

infixl 6 +
infixl 6 -

infixr 5 <>
infixr 5 ++

infix 4 ==
infix 4 /=
infixl 4 <
infixl 4 >
infixl 4 <=
infixl 4 >=

infixl 4 <$>
infixl 4 <*>

infixr 3 &&
infixr 2 ||

infixl 1 <#>
infixl 1 >>=
infixl 1 #

infixr 0 $
```

Does anyone else find it bizarre that `<$>` and `<*>` have the same precedence as the comparison operators? Or that the lattice operators are between map, apply, and the reversed map `<#>`? This seems wrong to me.

**Comment by alexchandel** [comment]
Adding the array operators makes it even stranger, since they intermix with the ring ops:
```purs
infixr 9 >>>
infixr 9 <<<

infix 8 ..
infixl 8 !!

infixl 7 *
infixl 7 /

infixl 6 +
infixl 6 -
infixr 6 :

infix 5 \\
infixr 5 <>
infixr 5 ++

infix 4 ==
infix 4 /=
infixl 4 <
infixl 4 >
infixl 4 <=
infixl 4 >=

infixl 4 <$>
infixl 4 <*>

infixr 3 &&
infixr 2 ||

infixl 1 <#>
infixl 1 >>=
infixl 1 #

infixr 0 $
```

Wouldn't it be better to group related ops together (necessarily with a few precedences higher than 9)?

**Comment by paf31** [comment]
Giving a total ordering to operators using integers in this way is a workaround for the fact that you have a quadratic number of relationships to define between pairs of operators. We often don't care about the total order, just the relationships between certain pairs. Really, I would like for the the relationships to form a lattice, and incomparable things should probably not even be allowed in the same infix expression without some form of disambiguation. The issue is - how do you capture that information? You could start with something like

```
infixl <*> below <$>
infixr $ below *
```

and take the antisymmetric, transitive closure of whatever relation that determines, but how do you know if you even got something consistent?

I'm open to other ideas, since operators will get an overhaul in 0.8 anyway.

**Comment by jdegoes** [comment]
> Really, I would like for the the relationships to form a lattice, and incomparable things should probably not even be allowed in the same infix expression without some form of disambiguation. 

Ooh, that's an interesting idea.

**Comment by brainrape** [comment]
Related research:
http://www.cse.chalmers.se/~nad/publications/danielsson-norell-mixfix.pdf
Secions 2 and 5.2 describe an approach to operator precedence graphs.

**Comment by garyb** [comment]
Mixfix has been mentioned before, #139, perhaps now is the time to look at it again.

**Comment by brainrape** [comment]
The operator precedence graph approach described above should work with regular infix operators as well. That's the interesting part of the paper for the idea mentioned above.

**Comment by garyb** [comment]
Oh sure, I just meant in the general "looking at operators again" thing we'll be doing soon it might be worth considering the whole paper.

**Comment by alexchandel** [comment]
I find the total ordering very useful for writing long expressions *without* disambiguating parentheses, e.g. when combining ring, order, and lattice ops, when all three are defined for a type.

**Comment by hdgarrood** [comment]
Pursuit and psc-docs now include fixity information, and there's now [a wiki page](https://github.com/purescript/purescript/wiki/Understanding-fixity-declarations) documenting fixity declarations, so I think the original issue can be considered resolved.
